// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHART_SELECTION_MODES = exports.chartPlainText = exports.chartSummary = exports.chartKindName = exports.labelWithUnit = exports.binLabel = exports.chartTargetKinds = exports.RANGE_TARGET_KINDS = exports.CHART_TARGET_KINDS = void 0;
exports.chartTargets = chartTargets;
exports.chartDataTable = chartDataTable;
exports.isContiguousRun = isContiguousRun;
exports.nextChartSelection = nextChartSelection;
exports.CHART_TARGET_KINDS = Object.freeze(["category", "series", "datum", "point", "bin"]);
const TARGETS_BY_KIND = Object.freeze({
    bar: ["category", "series", "datum"], line: ["category", "series", "datum"], area: ["category", "series", "datum"], combo: ["category", "series", "datum"],
    pie: ["category"], scatter: ["point", "series"], histogram: ["bin"], radar: ["series"], boxplot: ["category"], heatmap: []
});
exports.RANGE_TARGET_KINDS = Object.freeze(["category", "bin"]);
const chartTargetKinds = (spec) => TARGETS_BY_KIND[spec.kind];
exports.chartTargetKinds = chartTargetKinds;
function chartTargets(spec, kind) {
    if (!(0, exports.chartTargetKinds)(spec).includes(kind))
        return [];
    switch (spec.kind) {
        case "bar":
        case "line":
        case "area":
        case "combo": {
            const single = spec.series.length === 1;
            if (kind === "category")
                return spec.categories.map(c => ({ key: c.id, label: c.label, kind, categoryId: c.id }));
            if (kind === "series")
                return spec.series.map(s => ({ key: s.id, label: s.label, kind, seriesId: s.id }));
            const out = [];
            for (const s of spec.series)
                spec.categories.forEach((c, i) => {
                    const v = s.values[i];
                    if (v !== null)
                        out.push({ key: s.id + "/" + c.id, label: single ? c.label : s.label + " — " + c.label, kind, seriesId: s.id, categoryId: c.id, value: v });
                });
            return out;
        }
        case "pie": return spec.slices.map(s => ({ key: s.id, label: s.label, kind: "category", categoryId: s.id, value: s.value }));
        case "boxplot": return spec.boxes.map(b => ({ key: b.id, label: b.label, kind: "category", categoryId: b.id, value: b.median }));
        case "histogram": return spec.bins.map(b => ({ key: b.id, label: (0, exports.binLabel)(b.start, b.end), kind: "bin", value: b.count }));
        case "radar": return spec.series.map(s => ({ key: s.id, label: s.label, kind: "series", seriesId: s.id }));
        case "scatter":
            if (kind === "series")
                return spec.series.map(s => ({ key: s.id, label: s.label, kind, seriesId: s.id }));
            return spec.series.flatMap(s => s.points.map(p => ({ key: p.id, label: pointName(p) + (spec.series.length > 1 ? " — " + s.label : ""), kind: "point", seriesId: s.id })));
        case "heatmap": return [];
    }
}
const binLabel = (start, end) => "[" + start + " – " + end + ")";
exports.binLabel = binLabel;
const pointName = (p) => p.label ?? "(" + p.x + "، " + p.y + ")";
const labelWithUnit = (label, unit) => (unit ? label + " (\u2068" + unit + "\u2069)" : label);
exports.labelWithUnit = labelWithUnit;
function chartDataTable(spec) {
    switch (spec.kind) {
        case "bar":
        case "line":
        case "area":
        case "combo": {
            const horizontal = spec.kind === "bar" && spec.orientation === "horizontal";
            const valueAxis = horizontal ? spec.xAxis : spec.yAxis, categoryAxis = horizontal ? spec.yAxis : spec.xAxis;
            const unit = (s) => (spec.kind === "combo" && s.axis === "secondary" ? spec.y2Axis?.unit : valueAxis?.unit);
            return { columns: [categoryAxis?.label ?? "الفئة", ...spec.series.map(s => (0, exports.labelWithUnit)(s.label, unit(s)))], rows: spec.categories.map((c, i) => ({ header: c.label, cells: spec.series.map(s => s.values[i]) })) };
        }
        case "pie": return { columns: ["الفئة", (0, exports.labelWithUnit)("القيمة", spec.unit)], rows: spec.slices.map(s => ({ header: s.label, cells: [s.value] })) };
        case "scatter": return { columns: ["النقطة", "السلسلة", (0, exports.labelWithUnit)(spec.xAxis?.label ?? "x", spec.xAxis?.unit), (0, exports.labelWithUnit)(spec.yAxis?.label ?? "y", spec.yAxis?.unit)], rows: spec.series.flatMap(s => s.points.map(p => ({ header: pointName(p), cells: [s.label, p.x, p.y] }))) };
        case "histogram": return { columns: [(0, exports.labelWithUnit)(spec.xAxis?.label ?? "الفئة", spec.xAxis?.unit), (0, exports.labelWithUnit)(spec.yAxis?.label ?? "التكرار", spec.yAxis?.unit)], rows: spec.bins.map(b => ({ header: (0, exports.binLabel)(b.start, b.end), cells: [b.count] })) };
        case "radar": return { columns: ["المحور", ...spec.series.map(s => s.label), "الحد الأعلى"], rows: spec.axes.map((a, i) => ({ header: a.label, cells: [...spec.series.map(s => s.values[i]), a.max] })) };
        case "boxplot": return { columns: [spec.xAxis?.label ?? "المجموعة", ...["الأدنى", "الربيع الأول", "الوسيط", "الربيع الثالث", "الأعلى"].map(h => (0, exports.labelWithUnit)(h, spec.yAxis?.unit))], rows: spec.boxes.map(b => ({ header: b.label, cells: [b.min, b.q1, b.median, b.q3, b.max] })) };
        case "heatmap": return { columns: [spec.yAxis?.label ?? "الصف", ...spec.columns.map(c => (0, exports.labelWithUnit)(c.label, spec.unit))], rows: spec.rows.map((r, i) => ({ header: r.label, cells: spec.values[i] })) };
    }
}
var chartSpec_1 = require("./chartSpec");
Object.defineProperty(exports, "chartKindName", { enumerable: true, get: function () { return chartSpec_1.chartKindName; } });
Object.defineProperty(exports, "chartSummary", { enumerable: true, get: function () { return chartSpec_1.chartSummary; } });
Object.defineProperty(exports, "chartPlainText", { enumerable: true, get: function () { return chartSpec_1.chartPlainText; } });
exports.CHART_SELECTION_MODES = Object.freeze(["single", "multiple", "range"]);
function isContiguousRun(order, keys) {
    if (keys.length === 0)
        return false;
    const idx = keys.map(k => order.indexOf(k));
    if (idx.some(i => i < 0) || new Set(idx).size !== idx.length)
        return false;
    const lo = Math.min(...idx), hi = Math.max(...idx);
    return hi - lo + 1 === keys.length;
}
function nextChartSelection(mode, order, current, key, max) {
    if (!order.includes(key))
        return order.filter(k => current.includes(k));
    const cur = order.filter(k => current.includes(k));
    if (mode === "single")
        return cur.length === 1 && cur[0] === key ? [] : [key];
    if (mode === "multiple") {
        if (cur.includes(key))
            return cur.filter(k => k !== key);
        return cur.length >= max ? cur : order.filter(k => k === key || cur.includes(k));
    }
    if (cur.length === 1 && cur[0] === key)
        return [];
    if (cur.length === 0)
        return [key];
    const anchor = order.indexOf(cur[0]), at = order.indexOf(key), m = Math.max(1, max);
    return anchor <= at ? order.slice(anchor, Math.min(at, anchor + m - 1) + 1) : order.slice(Math.max(at, anchor - m + 1), anchor + 1);
}
