import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SURFACE_PLOTS_ACCEPTANCE_PATH, buildSurfacePlotsAcceptanceExam, serializeExam } from "./surfacePlotsExam.js";

// Phase 21D-A.4 — the committed acceptance exam is generated byte-for-byte from its source. Regenerate with WRITE_21DA4_FIXTURES=1.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
describe("21D-A.4 generated fixture drift", () => {
  it("the committed JSON is byte-for-byte generated from the source", () => {
    const file = path.join(root, SURFACE_PLOTS_ACCEPTANCE_PATH), text = serializeExam(buildSurfacePlotsAcceptanceExam());
    if (process.env.WRITE_21DA4_FIXTURES) fs.writeFileSync(file, text);
    expect(fs.readFileSync(file, "utf8")).toBe(text);
  });
});
