// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.composerSectionId = exports.composerQuestionId = exports.isComposerNonce = exports.buildSectionDraftSchema = void 0;
exports.buildItemSchema = buildItemSchema;
exports.normalizeComposerItem = normalizeComposerItem;
exports.normalizeSectionDraft = normalizeSectionDraft;
const aiQuestionDraft_1 = require("../aiQuestionDraft");
const examQuality_1 = require("../examQuality");
const composerLimits_1 = require("./composerLimits");
const composerCatalog_1 = require("./composerCatalog");
const composerPlan_1 = require("./composerPlan");
const composerRich_1 = require("./composerRich");
const composerSim_1 = require("./composerSim");
const composerSchemaKit_1 = require("./composerSchemaKit");
const L = composerLimits_1.COMPOSER_LIMITS;
const PART_KINDS = Object.freeze([...composerCatalog_1.COMPOSER_DRAFT_TYPES, "smartSim"]);
const POLICIES = ["all", "firstNAnswered"];
const LETTERS = ["أ", "ب", "ج", "د", "هـ", "و", "ز", "ح", "ط", "ي", "ك", "ل"];
function buildItemSchema() {
    const q = (0, aiQuestionDraft_1.buildAiAuthorSchema)();
    const part = (0, composerSchemaKit_1.sObj)({ group: (0, composerSchemaKit_1.sInt)(1, L.compositeGroups), kind: (0, composerSchemaKit_1.sEnum)(PART_KINDS), linked: (0, composerSchemaKit_1.sBool)(), marks: (0, composerSchemaKit_1.sInt)(1, L.itemMarksMax), label: (0, composerSchemaKit_1.sStr)(), simChecks: (0, composerSchemaKit_1.sArr)((0, composerSchemaKit_1.sStr)(), 40), simText: (0, composerSchemaKit_1.sStr)(), question: (0, composerSchemaKit_1.sNull)(q) });
    const group = (0, composerSchemaKit_1.sObj)({ title: (0, composerSchemaKit_1.sStr)(), policy: (0, composerSchemaKit_1.sEnum)(POLICIES), requiredAnswers: (0, composerSchemaKit_1.sNull)((0, composerSchemaKit_1.sInt)(1, L.compositeParts)) });
    const context = (0, composerSchemaKit_1.sObj)({ kind: (0, composerSchemaKit_1.sEnum)(["smartSim", "source"]), sim: (0, composerSchemaKit_1.sNull)((0, composerSim_1.buildSimSpecSchema)()), sourceTitle: (0, composerSchemaKit_1.sStr)(), sourceBlocks: (0, composerRich_1.buildRichBlocksSchema)() });
    return (0, composerSchemaKit_1.sObj)({
        kind: (0, composerSchemaKit_1.sEnum)(composerCatalog_1.COMPOSER_ITEM_KINDS), topic: (0, composerSchemaKit_1.sStr)(), difficulty: (0, composerSchemaKit_1.sEnum)(composerPlan_1.PLAN_DIFFICULTIES), rationale: (0, composerSchemaKit_1.sStr)(), stem: (0, composerRich_1.buildRichBlocksSchema)(),
        question: (0, composerSchemaKit_1.sNull)(q), smartSim: (0, composerSchemaKit_1.sNull)((0, composerSchemaKit_1.sObj)({ text: (0, composerSchemaKit_1.sStr)(), sim: (0, composerSim_1.buildSimSpecSchema)() })),
        compositeText: (0, composerSchemaKit_1.sStr)(), compositeContext: (0, composerSchemaKit_1.sNull)(context), compositeGroups: (0, composerSchemaKit_1.sArr)(group, L.compositeGroups), compositeParts: (0, composerSchemaKit_1.sArr)(part, L.compositeParts),
        assetRequest: (0, composerSchemaKit_1.sNull)((0, composerSchemaKit_1.sObj)({ description: (0, composerSchemaKit_1.sStr)() }))
    });
}
const buildSectionDraftSchema = () => (0, composerSchemaKit_1.sObj)({ items: (0, composerSchemaKit_1.sArr)(buildItemSchema(), L.itemsPerSection) });
exports.buildSectionDraftSchema = buildSectionDraftSchema;
const ITEM_KEYS = ["kind", "topic", "difficulty", "rationale", "stem", "question", "smartSim", "compositeText", "compositeContext", "compositeGroups", "compositeParts", "assetRequest"];
const FLAT_GROUP_KEYS = ["title", "policy", "requiredAnswers"];
const PART_KEYS = ["kind", "linked", "marks", "label", "simChecks", "simText", "question"];
const GROUP_KEYS = ["title", "policy", "requiredAnswers", "parts"];
const CTX_KEYS = ["kind", "sim", "sourceTitle", "sourceBlocks"];
const isComposerNonce = (v) => typeof v === "string" && /^[a-z0-9]{6,16}$/.test(v);
exports.isComposerNonce = isComposerNonce;
const composerQuestionId = (ids, sectionIndex, itemIndex) => "ai" + ids.nonce + "-" + (sectionIndex + 1) + "-" + (itemIndex + 1);
exports.composerQuestionId = composerQuestionId;
const composerSectionId = (ids, sectionIndex) => "ai" + ids.nonce + "-s" + (sectionIndex + 1);
exports.composerSectionId = composerSectionId;
const issue = (code, message, path, questionId) => ({ code, message, path, ...(questionId ? { questionId } : {}) });
function mapDraftQuestion(raw, kind, qid, marks, request, path) {
    if (!(0, composerSchemaKit_1.hasExactKeys)(raw, Object.keys((0, aiQuestionDraft_1.buildAiAuthorSchema)().properties)))
        return { ok: false, issues: [issue("AI_DRAFT_MALFORMED", "مسودة السؤال غير صالحة البنية.", path, qid)] };
    if (raw.intent !== kind)
        return { ok: false, issues: [issue("AI_ITEM_KIND_MISMATCH", "نوع السؤال المكتوب (" + String(raw.intent) + ") لا يطابق نوع البند في الخطة (" + kind + ").", path, qid)] };
    const r = (0, aiQuestionDraft_1.normalizeAiQuestionDraft)(raw, { request });
    if (!r.ok)
        return { ok: false, issues: r.issues.length ? r.issues.map(i => issue(r.code, i.message, path, qid)) : [issue(r.code, r.message, path, qid)] };
    return { ok: true, value: { ...r.question, examQuestionId: qid, marks } };
}
function labelOf(raw, i) { const t = (0, composerSchemaKit_1.cleanText)(raw); return t && t.length <= 40 ? t : LETTERS[i] ?? String(i + 1); }
function buildComposite(raw, qid, marks, plan, request, path) {
    const issues = [];
    if (!(0, composerSchemaKit_1.hasExactKeys)(raw, ["text", "context", "groups"]) || !(0, composerSchemaKit_1.isStr)(raw.text, L.richTextChars, 1) || !(0, composerSchemaKit_1.isArr)(raw.groups, L.compositeGroups) || !raw.groups.length)
        return { ok: false, issues: [issue("AI_COMPOSITE_MALFORMED", "السؤال المركّب غير صالح البنية.", path, qid)] };
    let sim = null;
    const contexts = [];
    if (raw.context !== null) {
        const c = raw.context;
        if (!(0, composerSchemaKit_1.hasExactKeys)(c, CTX_KEYS) || !(0, composerSchemaKit_1.isEnum)(c.kind, ["smartSim", "source"]) || !(0, composerSchemaKit_1.isStr)(c.sourceTitle, L.titleChars))
            return { ok: false, issues: [issue("AI_COMPOSITE_MALFORMED", "سياق السؤال المركّب غير صالح.", path + ".context", qid)] };
        if (c.kind === "smartSim") {
            if (c.sim === null)
                return { ok: false, issues: [issue("AI_COMPOSITE_MALFORMED", "سياق المحاكاة يحتاج إلى مواصفة محاكاة.", path + ".context", qid)] };
            const b = (0, composerSim_1.buildSimFromSpec)(c.sim, path + ".context.sim", plan.simulator, plan.scenario);
            if (!b.ok)
                return { ok: false, issues: b.issues.map(i => ({ ...i, questionId: qid })) };
            sim = b.value;
            contexts.push({ id: "ctx1", version: 1, kind: "smartSim", ...(sim.title ? { title: sim.title } : {}), ...(sim.instructions ? { instructions: sim.instructions } : {}), smartSim: sim.envelope });
        }
        else {
            if (c.sim !== null)
                return { ok: false, issues: [issue("AI_COMPOSITE_MALFORMED", "سياق المصدر لا يحمل محاكاة.", path + ".context", qid)] };
            const rc = (0, composerRich_1.mapAiRichBlocks)(c.sourceBlocks, path + ".context.sourceBlocks");
            if (!rc.ok)
                return { ok: false, issues: rc.issues.map(i => ({ ...i, questionId: qid })) };
            if (!rc.richContent)
                return { ok: false, issues: [issue("AI_COMPOSITE_MALFORMED", "سياق المصدر فارغ.", path + ".context", qid)] };
            const title = (0, composerSchemaKit_1.cleanText)(c.sourceTitle);
            contexts.push({ id: "ctx1", version: 1, kind: "source", ...(title ? { title } : {}), sources: [{ id: "src1", version: 1, kind: "rich", ...(title ? { title } : {}), richContent: rc.richContent }] });
        }
    }
    if (plan.simulator && !sim)
        issues.push(issue("AI_PLAN_SIMULATOR_MISSING", "الخطة تتطلب سياق محاكاة مشتركًا لهذا السؤال المركّب.", path, qid));
    let partNo = 0, official = 0;
    const usedChecks = new Set();
    const groups = [];
    raw.groups.forEach((g, gi) => {
        const gp = path + ".groups[" + gi + "]";
        if (!(0, composerSchemaKit_1.hasExactKeys)(g, GROUP_KEYS) || !(0, composerSchemaKit_1.isStr)(g.title, L.titleChars) || !(0, composerSchemaKit_1.isEnum)(g.policy, POLICIES) || !(0, composerSchemaKit_1.isArr)(g.parts, L.compositeParts) || !g.parts.length || !(g.requiredAnswers === null || (0, composerSchemaKit_1.isInt)(g.requiredAnswers, 1, L.compositeParts))) {
            issues.push(issue("AI_COMPOSITE_MALFORMED", "مجموعة غير صالحة البنية.", gp, qid));
            return;
        }
        const parts = [];
        g.parts.forEach((p, pi) => {
            const pp = gp + ".parts[" + pi + "]";
            if (!(0, composerSchemaKit_1.hasExactKeys)(p, PART_KEYS) || !(0, composerSchemaKit_1.isEnum)(p.kind, PART_KINDS) || typeof p.linked !== "boolean" || !(0, composerSchemaKit_1.isInt)(p.marks, 1, L.itemMarksMax) || !(0, composerSchemaKit_1.isStr)(p.label, 40) || !(0, composerSchemaKit_1.isArr)(p.simChecks, 40) || !p.simChecks.every(x => (0, composerSchemaKit_1.isStr)(x, 64, 1)) || !(0, composerSchemaKit_1.isStr)(p.simText, L.richTextChars)) {
                issues.push(issue("AI_COMPOSITE_MALFORMED", "بند فرعي غير صالح البنية.", pp, qid));
                return;
            }
            partNo++;
            const id = "p" + partNo, label = labelOf(p.label, partNo - 1);
            if (p.kind === "smartSim") {
                if (!sim || !p.linked) {
                    issues.push(issue("AI_COMPOSITE_SMARTSIM_CONTEXT", "بند المحاكاة يجب أن يرتبط بسياق المحاكاة المشترك.", pp, qid));
                    return;
                }
                if (p.question !== null || !p.simChecks.length || new Set(p.simChecks).size !== p.simChecks.length) {
                    issues.push(issue("AI_COMPOSITE_MALFORMED", "بند المحاكاة يحتاج إلى قائمة فحوص من السياق المشترك.", pp, qid));
                    return;
                }
                const picked = p.simChecks.map(cid => sim.checks.find(k => k.id === cid));
                if (picked.some(k => !k)) {
                    issues.push(issue("AI_SIM_CHECK_UNKNOWN", "فحص غير موجود في سيناريو المحاكاة: " + p.simChecks.filter((_, i) => !picked[i]).join(", "), pp, qid));
                    return;
                }
                const reused = p.simChecks.filter(cid => usedChecks.has(cid));
                if (reused.length) {
                    issues.push(issue("AI_COMPOSITE_SIM_CHECK_OVERLAP", "فحص المحاكاة مستخدم في بند آخر من السؤال نفسه (يُحتسب مرتين): " + reused.join(", "), pp, qid));
                    return;
                }
                for (const cid of p.simChecks)
                    usedChecks.add(cid);
                const checks = picked.map(k => ({ ...k }));
                issues.push(...(0, composerSim_1.simFreeCreditIssues)(sim.envelope, checks, pp).map(i => ({ ...i, questionId: qid })));
                parts.push({ id, label, type: "smartSim", questionTypeVersion: 1, contextId: "ctx1", text: (0, composerSchemaKit_1.cleanText)(p.simText) || label, marks: p.marks, answer: { scoring: "proportional", checks } });
                return;
            }
            if (p.question === null || p.simChecks.length) {
                issues.push(issue("AI_COMPOSITE_MALFORMED", "البند الفرعي يحتاج إلى مسودة سؤال.", pp, qid));
                return;
            }
            const m = mapDraftQuestion(p.question, p.kind, qid + "::p", p.marks, request, pp + ".question");
            if (!m.ok) {
                issues.push(...m.issues);
                return;
            }
            const q = m.value;
            if (q.codeStimulus !== undefined) {
                issues.push(issue("AI_COMPOSITE_PART_FIELD", "مثير الكود غير متاح داخل بند فرعي.", pp, qid));
                return;
            }
            const { examQuestionId: _id, presentationType, questionTypeVersion, text, marks: _m, displayNumber: _d, ...config } = q;
            void _id;
            void _m;
            void _d;
            parts.push({ id, label, type: presentationType, questionTypeVersion: questionTypeVersion ?? 1, ...(p.linked && contexts.length ? { contextId: "ctx1" } : {}), text, marks: p.marks, ...config });
        });
        const policy = g.policy;
        let maxMarks = null, required = null;
        if (policy === "all") {
            if (g.requiredAnswers !== null)
                issues.push(issue("AI_COMPOSITE_MARKS_MISMATCH", "مجموعة «الكل» لا تحدد عدد إجابات مطلوبًا.", gp, qid));
            official += parts.reduce((n, p) => n + p.marks, 0);
        }
        else {
            const ms = new Set(parts.map(p => p.marks));
            required = g.requiredAnswers;
            if (required === null || required > parts.length || ms.size !== 1)
                issues.push(issue("AI_COMPOSITE_MARKS_MISMATCH", "مجموعة «أول N إجابات» تحتاج إلى عدد مطلوب صالح وعلامات متساوية لكل البنود.", gp, qid));
            else {
                maxMarks = required * [...ms][0];
                official += maxMarks;
            }
        }
        const title = (0, composerSchemaKit_1.cleanText)(g.title);
        groups.push({ id: "g" + (gi + 1), ...(title ? { title } : {}), gradingPolicy: policy, requiredAnswers: required, maxMarks, parts });
    });
    if (!issues.length && official !== marks)
        issues.push(issue("AI_COMPOSITE_MARKS_MISMATCH", "مجموع علامات البنود الفرعية " + official + " ويجب أن يساوي علامة السؤال في الخطة " + marks + ".", path, qid));
    if (issues.length)
        return { ok: false, issues };
    return { ok: true, value: { examQuestionId: qid, presentationType: "composite", questionTypeVersion: 1, text: (0, composerSchemaKit_1.cleanText)(raw.text), marks, composite: { v: 1, contexts, groups } } };
}
function nestedComposite(raw, qid, path) {
    const groups = raw.compositeGroups, parts = raw.compositeParts;
    if (!(0, composerSchemaKit_1.isStr)(raw.compositeText, L.richTextChars) || !(0, composerSchemaKit_1.isArr)(groups, L.compositeGroups) || !(0, composerSchemaKit_1.isArr)(parts, L.compositeParts))
        return { present: true, issues: [issue("AI_COMPOSITE_MALFORMED", "السؤال المركّب غير صالح البنية.", path, qid)] };
    const present = raw.compositeText !== "" || raw.compositeContext !== null || groups.length > 0 || parts.length > 0;
    if (!present)
        return { present: false };
    if (!groups.every(g => (0, composerSchemaKit_1.hasExactKeys)(g, FLAT_GROUP_KEYS)) || !parts.every(p => p !== null && typeof p === "object" && !Array.isArray(p) && (0, composerSchemaKit_1.isInt)(p.group, 1, groups.length)))
        return { present: true, issues: [issue("AI_COMPOSITE_MALFORMED", "مجموعات البنود أو انتماء البنود إليها غير صالح.", path, qid)] };
    const nested = groups.map((g, gi) => ({ ...g, parts: parts.filter(p => p.group === gi + 1).map(p => { const { group: _g, ...rest } = p; void _g; return rest; }) }));
    return { present: true, value: { text: raw.compositeText, context: raw.compositeContext, groups: nested } };
}
function mapItem(raw, plan, qid, request, path) {
    const warnings = [];
    if (!(0, composerSchemaKit_1.hasExactKeys)(raw, ITEM_KEYS) || !(0, composerSchemaKit_1.isEnum)(raw.kind, composerCatalog_1.COMPOSER_ITEM_KINDS) || !(0, composerSchemaKit_1.isStr)(raw.topic, L.topicChars) || !(0, composerSchemaKit_1.isEnum)(raw.difficulty, composerPlan_1.PLAN_DIFFICULTIES) || !(0, composerSchemaKit_1.isStr)(raw.rationale, L.rationaleChars))
        return { ok: false, issues: [issue("AI_ITEM_MALFORMED", "بند السؤال غير صالح البنية.", path, qid)] };
    if (raw.kind !== plan.kind)
        return { ok: false, issues: [issue("AI_ITEM_KIND_MISMATCH", "نوع البند (" + raw.kind + ") لا يطابق الخطة (" + plan.kind + ").", path, qid)] };
    const kind = raw.kind;
    const comp = nestedComposite(raw, qid, path + ".composite");
    if (comp.issues)
        return { ok: false, issues: comp.issues };
    const present = [...["question", "smartSim"].filter(k => raw[k] !== null), ...(comp.present ? ["composite"] : [])];
    const want = kind === "smartSim" ? "smartSim" : kind === "composite" ? "composite" : "question";
    if (present.length !== 1 || present[0] !== want)
        return { ok: false, issues: [issue("AI_ITEM_PAYLOAD", "البند يجب أن يحمل محتوى نوعه فقط.", path, qid)] };
    let q;
    if (want === "question") {
        const m = mapDraftQuestion(raw.question, kind, qid, plan.marks, request, path + ".question");
        if (!m.ok)
            return m;
        q = m.value;
    }
    else if (want === "smartSim") {
        const s = raw.smartSim;
        if (!(0, composerSchemaKit_1.hasExactKeys)(s, ["text", "sim"]) || !(0, composerSchemaKit_1.isStr)(s.text, L.richTextChars, 1))
            return { ok: false, issues: [issue("AI_ITEM_MALFORMED", "سؤال المحاكاة غير صالح.", path, qid)] };
        const b = (0, composerSim_1.buildSimFromSpec)(s.sim, path + ".smartSim.sim", plan.simulator, plan.scenario);
        if (!b.ok)
            return { ok: false, issues: b.issues.map(i => ({ ...i, questionId: qid })) };
        const free = (0, composerSim_1.simFreeCreditIssues)(b.value.envelope, b.value.checks, path);
        if (free.length)
            return { ok: false, issues: free.map(i => ({ ...i, questionId: qid })) };
        const id = (0, composerCatalog_1.composerItemIdentity)("smartSim");
        q = { examQuestionId: qid, presentationType: "smartSim", questionTypeVersion: id.version, text: (0, composerSchemaKit_1.cleanText)(s.text), marks: plan.marks, smartSim: b.value.envelope, answer: { scoring: "proportional", checks: b.value.checks } };
    }
    else {
        const c = buildComposite(comp.value, qid, plan.marks, plan, request, path + ".composite");
        if (!c.ok)
            return c;
        q = c.value;
    }
    const stem = (0, composerRich_1.mapAiRichBlocks)(raw.stem, path + ".stem");
    if (!stem.ok)
        return { ok: false, issues: stem.issues.map(i => ({ ...i, questionId: qid })) };
    if (stem.richContent) {
        if (kind === "parametricNumeric")
            warnings.push(issue("AI_RICH_STEM_DROPPED", "أُهمل التنسيق الغني لسؤال المعطيات المتغيرة (غير مدعوم لهذا النوع)؛ النص العادي باقٍ.", path, qid));
        else
            q = { ...q, richContent: stem.richContent };
    }
    if (raw.assetRequest !== null) {
        const a = raw.assetRequest;
        if (!(0, composerSchemaKit_1.hasExactKeys)(a, ["description"]) || !(0, composerSchemaKit_1.isStr)(a.description, L.assetDescriptionChars, 1))
            return { ok: false, issues: [issue("AI_ITEM_MALFORMED", "طلب الصورة غير صالح.", path, qid)] };
        q = { ...q, assetRequest: { v: 1, description: (0, composerSchemaKit_1.cleanText)(a.description) } };
        warnings.push(issue("AI_ASSET_REQUEST", "السؤال يحتاج إلى صورة يضيفها المعلم قبل الاعتماد: " + (0, composerSchemaKit_1.cleanText)(a.description), path, qid));
    }
    return { ok: true, value: { question: q, meta: { kind, topic: (0, composerSchemaKit_1.cleanText)(raw.topic) || plan.topic, difficulty: raw.difficulty, rationale: (0, composerSchemaKit_1.cleanText)(raw.rationale) }, warnings } };
}
function normalizeComposerItem(raw, ctx) {
    const kind = (0, composerSchemaKit_1.hasExactKeys)(raw, ITEM_KEYS) && (0, composerSchemaKit_1.isEnum)(raw.kind, composerCatalog_1.COMPOSER_ITEM_KINDS) ? raw.kind : null;
    if (!kind)
        return { ok: false, issues: [issue("AI_ITEM_MALFORMED", "بند السؤال غير صالح البنية.", ctx.path, ctx.qid)] };
    const plan = { key: "patch", kind, topic: "", difficulty: "medium", marks: ctx.marks, simulator: null, scenario: null, note: "" };
    return mapItem(raw, plan, ctx.qid, ctx.request, ctx.path);
}
function normalizeSectionDraft(raw, planSection, sectionIndex, ids) {
    if (!(0, composerSchemaKit_1.hasExactKeys)(raw, ["items"]) || !(0, composerSchemaKit_1.isArr)(raw.items, L.itemsPerSection))
        return { ok: false, issues: [issue("AI_SECTION_MALFORMED", "مسودة القسم غير صالحة البنية.", "$")] };
    if (raw.items.length !== planSection.items.length)
        return { ok: false, issues: [issue("AI_SECTION_ITEM_COUNT", "عدد البنود " + raw.items.length + " ويجب أن يطابق الخطة (" + planSection.items.length + ").", "$.items")] };
    const issues = [], warnings = [], questions = [], meta = [];
    raw.items.forEach((it, i) => {
        const qid = (0, exports.composerQuestionId)(ids, sectionIndex, i);
        const m = mapItem(it, planSection.items[i], qid, planSection.items[i].topic + " " + planSection.items[i].note, "$.items[" + i + "]");
        if (!m.ok) {
            issues.push(...m.issues);
            return;
        }
        questions.push(m.value.question);
        meta.push({ questionId: qid, ...m.value.meta });
        warnings.push(...m.value.warnings);
    });
    if (issues.length)
        return { ok: false, issues };
    const section = { id: (0, exports.composerSectionId)(ids, sectionIndex), title: planSection.title, ...(planSection.instructions ? { instructions: planSection.instructions } : {}), gradingPolicy: "all", questions };
    const canonical = (0, examQuality_1.validateStructuredExam)({ examId: "ai-check", title: "check", sections: [section] }).filter(i => i.severity === "error" && i.code !== "AI_ASSET_REQUEST_UNRESOLVED");
    if (canonical.length)
        return { ok: false, issues: canonical.map(i => ({ code: i.code, message: i.message, ...(i.questionId ? { questionId: String(i.questionId) } : {}) })) };
    return { ok: true, section, meta, warnings };
}
