// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPOSER_CAPABILITY_FLAGS = exports.COMPOSER_DIFFICULTIES = exports.COMPOSER_LANGUAGES = void 0;
exports.intentAllowedKinds = intentAllowedKinds;
exports.normalizeComposerIntent = normalizeComposerIntent;
exports.intentForPrompt = intentForPrompt;
const composerLimits_1 = require("./composerLimits");
const composerCatalog_1 = require("./composerCatalog");
const composerSchemaKit_1 = require("./composerSchemaKit");
exports.COMPOSER_LANGUAGES = Object.freeze(["ar", "en", "he"]);
exports.COMPOSER_DIFFICULTIES = Object.freeze(["easy", "medium", "hard", "mixed"]);
exports.COMPOSER_CAPABILITY_FLAGS = Object.freeze(["composite", "smartSim", "coding", "parametric", "openResponse", "richContent", "tables", "visual", "rubrics"]);
const INTENT_KEYS = ["v", "subject", "course", "grade", "language", "direction", "totalMarks", "durationMinutes", "difficulty", "difficultyProfile", "sectionTarget", "questionTarget", "allowedQuestionTypes", "requiredTopics", "excludedTopics", "capabilities", "presentationPreset", "teacherInstruction"];
const L = composerLimits_1.COMPOSER_LIMITS;
function intentAllowedKinds(intent) {
    const c = intent.capabilities;
    return (intent.allowedQuestionTypes ?? [...composerCatalog_1.COMPOSER_ITEM_KINDS]).filter(k => (k !== "composite" || c.composite) && (k !== "smartSim" || c.smartSim) && (k !== "coding" || c.coding) &&
        (k !== "parametricNumeric" || c.parametric) && (k !== "openResponse" || c.openResponse));
}
function normalizeComposerIntent(raw) {
    const issues = [];
    const bad = (path, message) => { issues.push({ code: "INTENT_INVALID", message, path }); };
    if (!(0, composerSchemaKit_1.hasOnlyKeys)(raw, INTENT_KEYS))
        return { ok: false, issues: [{ code: "INTENT_MALFORMED", message: "طلب الامتحان يحتوي حقولًا غير معروفة أو غير صالحة." }] };
    const r = raw;
    if (r.v !== 1)
        bad("v", "إصدار الطلب غير مدعوم.");
    const text = (k, max, required) => {
        const v = r[k];
        if (v === undefined || v === null || v === "") {
            if (required)
                bad(k, "الحقل مطلوب: " + k);
            return "";
        }
        if (!(0, composerSchemaKit_1.isStr)(v, max)) {
            bad(k, "قيمة غير صالحة: " + k);
            return "";
        }
        return (0, composerSchemaKit_1.cleanText)(v);
    };
    const subject = text("subject", L.shortText, true);
    const course = text("course", L.shortText, false);
    const grade = text("grade", L.shortText, false);
    const teacherInstruction = text("teacherInstruction", L.instructionChars, false);
    const language = r.language === undefined ? "ar" : r.language;
    if (!(0, composerSchemaKit_1.isEnum)(language, exports.COMPOSER_LANGUAGES))
        bad("language", "لغة غير مدعومة.");
    const direction = r.direction === undefined ? (language === "en" ? "ltr" : "rtl") : r.direction;
    if (direction !== "rtl" && direction !== "ltr")
        bad("direction", "اتجاه غير صالح.");
    if (!(0, composerSchemaKit_1.isInt)(r.totalMarks, 1, L.totalMarksMax))
        bad("totalMarks", "مجموع العلامات يجب أن يكون عددًا صحيحًا بين 1 و" + L.totalMarksMax + ".");
    const duration = r.durationMinutes ?? null;
    if (duration !== null && !(0, composerSchemaKit_1.isInt)(duration, 1, L.durationMax))
        bad("durationMinutes", "مدة الامتحان غير صالحة.");
    const difficulty = r.difficulty === undefined ? "mixed" : r.difficulty;
    if (!(0, composerSchemaKit_1.isEnum)(difficulty, exports.COMPOSER_DIFFICULTIES))
        bad("difficulty", "مستوى صعوبة غير معروف.");
    let profile = null;
    if (r.difficultyProfile !== undefined && r.difficultyProfile !== null) {
        const p = r.difficultyProfile;
        if (!(0, composerSchemaKit_1.hasOnlyKeys)(p, ["easy", "medium", "hard"]) || !(0, composerSchemaKit_1.isInt)(p.easy, 0, 100) || !(0, composerSchemaKit_1.isInt)(p.medium, 0, 100) || !(0, composerSchemaKit_1.isInt)(p.hard, 0, 100) || p.easy + p.medium + p.hard !== 100)
            bad("difficultyProfile", "توزيع الصعوبة يجب أن يكون نسبًا صحيحة مجموعها 100.");
        else
            profile = { easy: p.easy, medium: p.medium, hard: p.hard };
    }
    const sectionTarget = r.sectionTarget ?? null;
    if (sectionTarget !== null && !(0, composerSchemaKit_1.isInt)(sectionTarget, 1, L.sections))
        bad("sectionTarget", "عدد الأقسام بين 1 و" + L.sections + ".");
    const questionTarget = r.questionTarget ?? null;
    if (questionTarget !== null && !(0, composerSchemaKit_1.isInt)(questionTarget, 1, L.items))
        bad("questionTarget", "عدد الأسئلة بين 1 و" + L.items + ".");
    let allowed = null;
    if (r.allowedQuestionTypes !== undefined && r.allowedQuestionTypes !== null) {
        const a = r.allowedQuestionTypes;
        if (!(0, composerSchemaKit_1.isArr)(a, composerCatalog_1.COMPOSER_ITEM_KINDS.length) || !a.length || !a.every(k => (0, composerSchemaKit_1.isEnum)(k, composerCatalog_1.COMPOSER_ITEM_KINDS)) || new Set(a).size !== a.length)
            bad("allowedQuestionTypes", "قائمة الأنواع المسموحة تحتوي نوعًا غير مدعوم.");
        else
            allowed = a;
    }
    const topics = (k) => {
        const v = r[k];
        if (v === undefined || v === null)
            return [];
        if (!(0, composerSchemaKit_1.isArr)(v, L.topics) || !v.every(t => (0, composerSchemaKit_1.isStr)(t, L.topicChars, 1))) {
            bad(k, "قائمة الموضوعات غير صالحة.");
            return [];
        }
        return [...new Set(v.map(composerSchemaKit_1.cleanText).filter(Boolean))];
    };
    const requiredTopics = topics("requiredTopics");
    const excludedTopics = topics("excludedTopics");
    const caps = {};
    const rc = r.capabilities ?? {};
    if (!(0, composerSchemaKit_1.hasOnlyKeys)(rc, exports.COMPOSER_CAPABILITY_FLAGS))
        bad("capabilities", "خيارات الميزات غير صالحة.");
    else
        for (const f of exports.COMPOSER_CAPABILITY_FLAGS) {
            const v = rc[f];
            if (v !== undefined && typeof v !== "boolean")
                bad("capabilities." + f, "قيمة غير صالحة.");
            caps[f] = v === undefined ? f !== "visual" : v === true;
        }
    const preset = r.presentationPreset ?? null;
    if (preset !== null && preset !== "auto" && !(0, composerSchemaKit_1.isEnum)(preset, composerCatalog_1.COMPOSER_PRESETS))
        bad("presentationPreset", "قالب العرض غير معروف.");
    if (issues.length)
        return { ok: false, issues };
    const intent = {
        v: 1, subject, course, grade, language: language, direction: direction,
        totalMarks: r.totalMarks, durationMinutes: duration,
        difficulty: difficulty, difficultyProfile: profile,
        sectionTarget: sectionTarget, questionTarget: questionTarget,
        allowedQuestionTypes: allowed, requiredTopics, excludedTopics, capabilities: caps,
        presentationPreset: preset === "auto" ? null : preset, teacherInstruction,
        unsupportedRequested: (0, composerCatalog_1.detectUnsupportedCapabilities)(teacherInstruction + " " + requiredTopics.join(" "))
    };
    if (!intentAllowedKinds(intent).length)
        return { ok: false, issues: [{ code: "INTENT_NO_TYPES", message: "لا يبقى أي نوع سؤال مسموح بعد تطبيق الخيارات المحددة.", path: "allowedQuestionTypes" }] };
    return { ok: true, intent };
}
function intentForPrompt(intent) {
    const c = intent.capabilities;
    return [
        "STRUCTURED CONSTRAINTS (authoritative; they override the free instruction whenever they conflict):",
        "subject: " + intent.subject + (intent.course ? " | course: " + intent.course : "") + (intent.grade ? " | grade: " + intent.grade : ""),
        "language: " + intent.language + " | direction: " + intent.direction + " | total marks (exact): " + intent.totalMarks + (intent.durationMinutes ? " | duration: " + intent.durationMinutes + " min" : ""),
        "difficulty: " + intent.difficulty + (intent.difficultyProfile ? " (easy " + intent.difficultyProfile.easy + "%, medium " + intent.difficultyProfile.medium + "%, hard " + intent.difficultyProfile.hard + "%)" : ""),
        (intent.sectionTarget ? "sections (exact): " + intent.sectionTarget : "sections: choose 1-" + composerLimits_1.COMPOSER_LIMITS.sections) + " | " + (intent.questionTarget ? "questions (target): " + intent.questionTarget : "questions: choose a sensible number"),
        "allowed item kinds: " + intentAllowedKinds(intent).join(", "),
        "features: " + exports.COMPOSER_CAPABILITY_FLAGS.map(f => f + "=" + (c[f] ? "on" : "off")).join(", "),
        "required topics: " + (intent.requiredTopics.join(", ") || "(none)") + " | excluded topics: " + (intent.excludedTopics.join(", ") || "(none)"),
        "presentation preset: " + (intent.presentationPreset ?? "choose the best fitting preset"),
        intent.unsupportedRequested.length ? "requested but NOT supported by the platform (never simulate; report in unsupportedRequests with a safe alternative): " + intent.unsupportedRequested.map(u => u.label).join(", ") : ""
    ].filter(Boolean).join("\n");
}
