// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.allQuestions = exports.composerMetadataOf = void 0;
exports.assembleComposerExam = assembleComposerExam;
exports.withComposerHistory = withComposerHistory;
exports.composerVerdict = composerVerdict;
exports.verifyAiQuestion = verifyAiQuestion;
exports.verifyGeneratedExam = verifyGeneratedExam;
const examFinalization_1 = require("../examFinalization");
const examBuilderState_1 = require("../examBuilderState");
const questionTypeCatalog_1 = require("../questionTypeCatalog");
const aiQuestionDraft_1 = require("../aiQuestionDraft");
const presentationModel_1 = require("../presentation/presentationModel");
const composerLimits_1 = require("./composerLimits");
const composerCatalog_1 = require("./composerCatalog");
const composerSim_1 = require("./composerSim");
function assembleComposerExam(input) {
    let n = 0;
    const sections = input.sections.map(s => ({ ...s, questions: s.questions.map(q => ({ ...q, displayNumber: String(++n) })) }));
    const presentation = { schemaVersion: 1, preset: input.plan.presentationPreset, direction: input.intent.direction };
    const pv = (0, presentationModel_1.validatePresentation)(presentation);
    const metadata = { v: 1, catalog: composerCatalog_1.COMPOSER_CATALOG_VERSION, coverage: input.meta.map(m => ({ questionId: m.questionId, topic: m.topic, difficulty: m.difficulty })), history: [] };
    return {
        schemaVersion: 2, examId: input.examId, title: input.plan.title, status: "draft",
        ...(pv.ok && pv.value ? { presentation: pv.value } : {}),
        metadata: { aiComposer: metadata },
        sections
    };
}
const composerMetadataOf = (exam) => {
    const m = exam.metadata?.aiComposer;
    return m && typeof m === "object" && m.v === 1 && Array.isArray(m.coverage) && Array.isArray(m.history) ? m : null;
};
exports.composerMetadataOf = composerMetadataOf;
function withComposerHistory(exam, entry, coverage) {
    const prev = (0, exports.composerMetadataOf)(exam) ?? { v: 1, catalog: composerCatalog_1.COMPOSER_CATALOG_VERSION, coverage: [], history: [] };
    const summary = entry.summary.slice(0, composerLimits_1.COMPOSER_LIMITS.historySummaryChars);
    const ids = new Set((0, exports.allQuestions)(exam).map(q => q.examQuestionId));
    const mergedCoverage = [...prev.coverage.filter(c => ids.has(c.questionId) && !(coverage ?? []).some(x => x.questionId === c.questionId)), ...(coverage ?? [])];
    const next = { v: 1, catalog: composerCatalog_1.COMPOSER_CATALOG_VERSION, coverage: mergedCoverage, history: [...prev.history, { ...entry, summary }].slice(-composerLimits_1.COMPOSER_LIMITS.historyEntries) };
    return { ...exam, metadata: { ...exam.metadata, aiComposer: next } };
}
const allQuestions = (exam) => (exam.sections || []).flatMap(s => s.questions || []);
exports.allQuestions = allQuestions;
const partsOf = (q) => {
    const c = q.composite;
    return c && Array.isArray(c.groups) ? c.groups.flatMap(g => (Array.isArray(g.parts) ? g.parts : [])) : [];
};
function isManual(type, node) {
    const def = (0, questionTypeCatalog_1.questionTypeDefinition)(type);
    if (!def)
        return true;
    if (type === "coding")
        return (node.answer?.gradingMode) !== "hiddenTests";
    if (type === "shortAnswer") {
        const t = node.answer?.text;
        return !(typeof t === "string" && t.trim());
    }
    return def.gradingMode === "manual";
}
function marksSplit(q) {
    if (q.presentationType !== "composite")
        return isManual(q.presentationType, q) ? { auto: 0, manual: Number(q.marks) || 0 } : { auto: Number(q.marks) || 0, manual: 0 };
    const groups = q.composite?.groups ?? [];
    let auto = 0, manual = 0;
    for (const g of groups) {
        const parts = g.parts ?? [];
        const sum = parts.reduce((n, p) => n + (Number(p.marks) || 0), 0);
        const scale = g.gradingPolicy === "firstNAnswered" && sum > 0 ? (Number(g.maxMarks) || 0) / sum : 1;
        for (const p of parts) {
            const m = (Number(p.marks) || 0) * scale;
            if (isManual(String(p.type), p))
                manual += m;
            else
                auto += m;
        }
    }
    return { auto, manual };
}
const SIM_ALLOWED = new Set(composerCatalog_1.COMPOSER_SIM_PLUGINS.map(p => p.pluginKey + "@" + p.pluginVersion));
const normStem = (t) => String(t ?? "").replace(/\s+/g, " ").replace(/[^\p{L}\p{N} ]/gu, "").trim().toLowerCase();
const r2 = (n) => Math.round(n * 100) / 100;
function aiQuestionIssues(q) {
    const out = [];
    const qid = q.examQuestionId;
    const node = q;
    const ident = (type, version, where) => {
        if (!(0, questionTypeCatalog_1.questionTypeDefinition)(type) || !(0, questionTypeCatalog_1.supportsQuestionTypeVersion)(type, version ?? 1))
            out.push({ code: "COMPOSER_UNSUPPORTED_TYPE", message: "نوع / إصدار غير مدعوم: " + type + "@" + String(version ?? 1) + " (" + where + ").", questionId: qid });
    };
    ident(q.presentationType, q.questionTypeVersion, "السؤال");
    const sim = (env, checks, where) => {
        const e = env;
        if (!e || !SIM_ALLOWED.has(String(e.pluginKey) + "@" + String(e.pluginVersion))) {
            out.push({ code: "COMPOSER_SIM_NOT_ALLOWED", message: "المحاكي غير مسموح للمؤلف الآلي (" + where + ").", questionId: qid });
            return;
        }
        if (Array.isArray(checks))
            out.push(...(0, composerSim_1.simFreeCreditIssues)(e, checks, where).map(i => ({ ...i, questionId: qid })));
    };
    const coding = (n, where) => {
        const a = n.answer ?? {};
        if ((Array.isArray(a.hiddenTests) && a.hiddenTests.length) || a.gradingMode === "hiddenTests" || (a.referenceSolutions && typeof a.referenceSolutions === "object" && Object.keys(a.referenceSolutions).length))
            out.push({ code: "AI_CODING_TRUSTED_MATERIAL_FORBIDDEN", message: "سؤال البرمجة المؤلف آليًا لا يحمل اختبارات مخفية أو حلولًا مرجعية (" + where + ").", questionId: qid });
    };
    if (q.presentationType === "smartSim")
        sim(node.smartSim, node.answer?.checks, "السؤال");
    if (q.presentationType === "coding")
        coding(node, "السؤال");
    if (q.presentationType === "composite") {
        const ctx = (node.composite?.contexts ?? []);
        for (const p of partsOf(q)) {
            ident(String(p.type), p.questionTypeVersion, "البند " + String(p.id));
            if (p.type === "coding")
                coding(p, "البند " + String(p.id));
            if (p.type === "smartSim") {
                const c = ctx.find(x => x.id === p.contextId);
                sim(c?.smartSim ?? p.smartSim, p.answer?.checks, "البند " + String(p.id));
            }
        }
        if (partsOf(q).some(p => p.type === "composite"))
            out.push({ code: "COMPOSITE_NESTED", message: "لا يُسمح بسؤال مركّب داخل سؤال مركّب.", questionId: qid });
    }
    return out;
}
function composerVerdict(exam, opts = {}) {
    const blocking = [], warnings = [];
    const fin = (0, examFinalization_1.evaluateExamFinalization)(exam);
    for (const i of fin.structuralErrors) {
        const issue = { code: i.code, message: i.message, ...(i.sectionId ? { sectionId: String(i.sectionId) } : {}), ...(i.questionId ? { questionId: String(i.questionId) } : {}) };
        if (i.code === "AI_ASSET_REQUEST_UNRESOLVED")
            warnings.push(issue);
        else
            blocking.push(issue);
    }
    for (const i of fin.structuralWarnings)
        warnings.push({ code: i.code, message: i.message, ...(i.questionId ? { questionId: String(i.questionId) } : {}) });
    const qs = (0, exports.allQuestions)(exam);
    const ai = opts.aiQuestionIds ?? new Set(qs.map(q => q.examQuestionId));
    for (const q of qs)
        if (ai.has(q.examQuestionId))
            blocking.push(...aiQuestionIssues(q));
    const total = (0, examBuilderState_1.computeTotalMarks)(exam);
    if (opts.intent && Math.abs(total - opts.intent.totalMarks) > 1e-9)
        blocking.push({ code: "COMPOSER_TOTAL_MISMATCH", message: "مجموع علامات الامتحان " + r2(total) + " والمطلوب " + opts.intent.totalMarks + "." });
    if (opts.plan) {
        if (opts.plan.sections.length !== (exam.sections || []).length)
            blocking.push({ code: "COMPOSER_PLAN_DRIFT", message: "عدد أقسام الامتحان لا يطابق الخطة." });
        else
            (exam.sections || []).forEach((s, i) => { const m = (0, examBuilderState_1.sectionMaxMarks)(s); if (Math.abs(m - opts.plan.sections[i].marks) > 1e-9)
                blocking.push({ code: "COMPOSER_SECTION_MARKS_MISMATCH", message: "علامة القسم «" + s.title + "» " + r2(m) + " والخطة " + opts.plan.sections[i].marks + ".", sectionId: s.id }); });
    }
    const typeMix = {};
    for (const q of qs)
        typeMix[q.presentationType] = (typeMix[q.presentationType] ?? 0) + 1;
    let run = 1;
    for (let i = 1; i < qs.length; i++) {
        run = qs[i].presentationType === qs[i - 1].presentationType ? run + 1 : 1;
        if (run === 5)
            warnings.push({ code: "COMPOSER_DIVERSITY_RUN", message: "خمسة أسئلة متتالية أو أكثر من النوع نفسه (" + qs[i].presentationType + ").", questionId: qs[i].examQuestionId });
    }
    if (qs.length >= 6 && !(opts.intent?.allowedQuestionTypes && opts.intent.allowedQuestionTypes.length === 1))
        for (const [t, c] of Object.entries(typeMix))
            if (c / qs.length > 0.7)
                warnings.push({ code: "COMPOSER_DIVERSITY_TYPE", message: "نسبة كبيرة من الأسئلة من نوع واحد (" + t + ": " + c + " من " + qs.length + ")." });
    const seen = new Map();
    for (const q of qs) {
        const k = normStem(q.text);
        if (k.length >= 12) {
            const prev = seen.get(k);
            if (prev)
                warnings.push({ code: "COMPOSER_DUPLICATE_STEM", message: "نص سؤال مكرر.", questionId: q.examQuestionId });
            else
                seen.set(k, q.examQuestionId);
        }
        const opts2 = Array.isArray(q.options) ? q.options.map(o => normStem(o.text)) : [];
        if (opts2.length && new Set(opts2).size !== opts2.length)
            warnings.push({ code: "COMPOSER_DUPLICATE_OPTIONS", message: "خيارات متطابقة في السؤال نفسه.", questionId: q.examQuestionId });
    }
    const meta = (0, exports.composerMetadataOf)(exam);
    const marksOf = new Map(qs.map(q => [q.examQuestionId, Number(q.marks) || 0]));
    const cov = new Map();
    for (const q of qs) {
        const t = meta?.coverage.find(c => c.questionId === q.examQuestionId)?.topic || "غير مصنّف";
        const e = cov.get(t) ?? { topic: t, marks: 0, questions: 0 };
        e.marks += marksOf.get(q.examQuestionId) ?? 0;
        e.questions += 1;
        cov.set(t, e);
    }
    const coverage = [...cov.values()].map(c => ({ ...c, marks: r2(c.marks) })).sort((a, b) => b.marks - a.marks || a.topic.localeCompare(b.topic));
    if (opts.intent)
        for (const t of opts.intent.requiredTopics)
            if (!coverage.some(c => c.topic.toLowerCase().includes(t.toLowerCase())) && !qs.some(q => String(q.text).toLowerCase().includes(t.toLowerCase())))
                warnings.push({ code: "COMPOSER_TOPIC_UNCOVERED", message: "الموضوع المطلوب «" + t + "» غير مغطّى في الأسئلة." });
    let automaticMarks = 0, manualMarks = 0;
    for (const q of qs) {
        const m = marksSplit(q);
        automaticMarks += m.auto;
        manualMarks += m.manual;
    }
    const count = (t) => qs.filter(q => q.presentationType === t).length + qs.flatMap(partsOf).filter(p => p.type === t).length;
    const richTables = qs.reduce((n, q) => n + (q.richContent?.blocks ?? []).filter(b => b.type === "table").length, 0);
    const summary = {
        totalMarks: r2(total), requestedMarks: opts.intent?.totalMarks ?? null, sections: (exam.sections || []).length, questions: qs.length, typeMix,
        automaticMarks: r2(automaticMarks), manualMarks: r2(manualMarks), composite: count("composite"), smartSim: count("smartSim"), coding: count("coding"),
        parametric: count("parametricNumeric"), openResponse: count("openResponse"), richTables,
        presentation: exam.presentation?.preset ?? null, blocking: blocking.length, warnings: warnings.length
    };
    return { ok: blocking.length === 0, blocking, warnings, summary, coverage };
}
const UNVERSIONED_19A = new Set(["multipleChoice", "trueFalse", "shortAnswer", "fillBlank", "tableFill"]);
function verifyAiQuestion(q) {
    const one = (node, type, where) => {
        if (!composerCatalog_1.COMPOSER_DRAFT_TYPES.includes(type))
            return [];
        const { richContent: _r, assetRequest: _a, displayNumber: _d, id: _i, label: _l, contextId: _c, type: _t, ...rest } = node;
        void _r;
        void _a;
        void _d;
        void _i;
        void _l;
        void _c;
        void _t;
        if (UNVERSIONED_19A.has(type) && rest.questionTypeVersion === 1)
            delete rest.questionTypeVersion;
        const v = (0, aiQuestionDraft_1.verifyAiQuestionNode)({ ...rest, presentationType: type, examQuestionId: "ai-draft" });
        return v.ok ? [] : v.issues.map(i => ({ code: v.code, message: where + ": " + i.message, questionId: q.examQuestionId }));
    };
    if (q.presentationType === "composite")
        return partsOf(q).flatMap(p => one(p, String(p.type), "البند " + String(p.id)));
    return one(q, q.presentationType, "السؤال");
}
function verifyGeneratedExam(exam, intent, plan) {
    const v = composerVerdict(exam, { intent, plan });
    const extra = (0, exports.allQuestions)(exam).flatMap(verifyAiQuestion);
    return extra.length ? { ...v, ok: false, blocking: [...v.blocking, ...extra], summary: { ...v.summary, blocking: v.blocking.length + extra.length } } : v;
}
