// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPOSER_SCIENTIFIC_MATH = exports.COMPOSER_CODING_LANGUAGES = exports.COMPOSER_TABLE_VARIANTS = exports.COMPOSER_CALLOUT_VARIANTS = exports.COMPOSER_RICH_CODE_LANGUAGES = exports.COMPOSER_RICH_BLOCKS = exports.COMPOSER_PRESETS = exports.isUnsupportedCapabilityId = exports.COMPOSER_UNSUPPORTED = exports.COMPOSER_FUNCTION_BOUNDS = exports.COMPOSER_FUNCTION_TASKS = exports.COMPOSER_PHYSICS_BOUNDS = exports.COMPOSER_PHYSICS_POINTS = exports.COMPOSER_PHYSICS_MEASUREMENTS = exports.COMPOSER_NET_SCENARIOS = exports.composerSimVersion = exports.COMPOSER_SIM_PLUGIN_KEYS = exports.COMPOSER_SIM_PLUGINS = exports.COMPOSER_ITEM_KINDS = exports.COMPOSER_DRAFT_TYPES = exports.COMPOSER_CATALOG_VERSION = void 0;
exports.composerItemIdentity = composerItemIdentity;
exports.composerNetScenario = composerNetScenario;
exports.detectUnsupportedCapabilities = detectUnsupportedCapabilities;
exports.buildComposerCatalog = buildComposerCatalog;
exports.catalogForPrompt = catalogForPrompt;
const questionTypeCatalog_1 = require("../questionTypeCatalog");
const trustedSimRegistry_1 = require("../trustedSimRegistry");
const presentationModel_1 = require("../presentation/presentationModel");
const richContentModel_1 = require("../richContent/richContentModel");
const richMath_1 = require("../richContent/richMath");
const mathFeatures_1 = require("../richContent/mathFeatures");
const codingLanguages_1 = require("../codingLanguages");
const net2Templates_1 = require("../networkTopology2/net2Templates");
const physicsFreeFallModel_1 = require("../physicsFreeFallModel");
const functionStudyModel_1 = require("../functionStudyModel");
require("../trustedSimPlugins");
exports.COMPOSER_CATALOG_VERSION = "AI_COMPOSER_CATALOG_V2";
exports.COMPOSER_DRAFT_TYPES = Object.freeze(["multipleChoice", "trueFalse", "shortAnswer", "fillBlank", "inlineCloze", "parametricNumeric", "openResponse", "tableFill", "coding", "networkCli"]);
exports.COMPOSER_ITEM_KINDS = Object.freeze([...exports.COMPOSER_DRAFT_TYPES, "smartSim", "composite"]);
function composerItemIdentity(kind) {
    return { key: kind, version: (0, questionTypeCatalog_1.authoringQuestionTypeVersion)(kind) };
}
exports.COMPOSER_SIM_PLUGINS = Object.freeze([
    { pluginKey: "networkTopology", pluginVersion: 2, subject: "networking" },
    { pluginKey: "physicsFreeFall", pluginVersion: 1, subject: "physics" },
    { pluginKey: "functionStudy2d", pluginVersion: 1, subject: "mathematics" }
]);
exports.COMPOSER_SIM_PLUGIN_KEYS = Object.freeze(exports.COMPOSER_SIM_PLUGINS.map(p => p.pluginKey));
const composerSimVersion = (key) => exports.COMPOSER_SIM_PLUGINS.find(p => p.pluginKey === key)?.pluginVersion;
exports.composerSimVersion = composerSimVersion;
const NET_TOPICS = Object.freeze({
    roas: ["VLAN", "Trunk", "Router-on-a-Stick", "IPv4"], dhcp: ["DHCP", "IPv4"], vtp: ["VTP", "VLAN", "Trunk"], portsec: ["Port Security"],
    wireless: ["Wireless", "WPA2", "DHCP"], capstone: ["VLAN", "Trunk", "Native VLAN", "VTP", "Router-on-a-Stick", "DHCP", "Port Security", "Wireless", "DNS", "HTTP"]
});
exports.COMPOSER_NET_SCENARIOS = Object.freeze(net2Templates_1.NET2_TEMPLATES.map(t => t.id));
function composerNetScenario(id) {
    const t = net2Templates_1.NET2_TEMPLATES.find(x => x.id === id);
    if (!t)
        return undefined;
    return { id: t.id, title: t.title, description: t.description, topics: NET_TOPICS[t.id] ?? [], checks: t.checks().map(c => ({ id: c.id, label: c.label, kind: c.kind })) };
}
exports.COMPOSER_PHYSICS_MEASUREMENTS = Object.freeze(["impactTime", "impactSpeed", "maxHeight", "apexTime", "heightAtTime", "velocityAtTime"]);
exports.COMPOSER_PHYSICS_POINTS = Object.freeze(["impactPoint", "apexPoint", "trajectoryPoint"]);
exports.COMPOSER_PHYSICS_BOUNDS = Object.freeze({ heightMax: physicsFreeFallModel_1.FREE_FALL_LIMITS.heightMax, velocityAbsMax: physicsFreeFallModel_1.FREE_FALL_LIMITS.velocityAbsMax, gravityMin: physicsFreeFallModel_1.FREE_FALL_LIMITS.gravityMin, gravityMax: physicsFreeFallModel_1.FREE_FALL_LIMITS.gravityMax, maxTimeMax: physicsFreeFallModel_1.FREE_FALL_LIMITS.maxTimeMax });
exports.COMPOSER_FUNCTION_TASKS = functionStudyModel_1.FUNCTION_STUDY_TASKS;
exports.COMPOSER_FUNCTION_BOUNDS = Object.freeze({ xAbsMax: functionStudyModel_1.FUNCTION_STUDY_LIMITS.xAbsMax, yAbsMax: functionStudyModel_1.FUNCTION_STUDY_LIMITS.yAbsMax, sampleMin: functionStudyModel_1.FUNCTION_STUDY_LIMITS.sampleMin, sampleMax: functionStudyModel_1.FUNCTION_STUDY_LIMITS.sampleMax, sourceChars: functionStudyModel_1.FUNCTION_STUDY_LIMITS.sourceChars });
exports.COMPOSER_UNSUPPORTED = Object.freeze([
    { id: "ospf", label: "OSPF", pattern: /\bospf\b/i }, { id: "rip", label: "RIP", pattern: /\bripv?2?\b/i }, { id: "eigrp", label: "EIGRP", pattern: /\beigrp\b/i },
    { id: "bgp", label: "BGP", pattern: /\bbgp\b/i }, { id: "staticRouting", label: "Static Routing", pattern: /static\s*rout|ip\s+route\b|التوجيه\s*الثابت/i },
    { id: "acl", label: "ACL", pattern: /\bacls?\b|access-list|قوائم\s*التحكم\s*بالوصول/i }, { id: "nat", label: "NAT / PAT", pattern: /\bnat\b|\bpat\b/i },
    { id: "stp", label: "Spanning Tree", pattern: /spanning[-\s]?tree|\bstp\b/i }, { id: "etherchannel", label: "EtherChannel", pattern: /etherchannel|port[-\s]?channel/i },
    { id: "ipv6", label: "IPv6", pattern: /ipv6/i }, { id: "vpn", label: "VPN", pattern: /\bvpn\b|ipsec/i }, { id: "metro", label: "Metro Ethernet", pattern: /metro\s*ethernet/i }
]);
function detectUnsupportedCapabilities(text) {
    const t = String(text || "");
    return exports.COMPOSER_UNSUPPORTED.filter(u => u.pattern.test(t)).map(u => ({ id: u.id, label: u.label }));
}
const isUnsupportedCapabilityId = (id) => typeof id === "string" && exports.COMPOSER_UNSUPPORTED.some(u => u.id === id);
exports.isUnsupportedCapabilityId = isUnsupportedCapabilityId;
exports.COMPOSER_PRESETS = Object.freeze(Object.keys(presentationModel_1.PRESENTATION_PRESETS));
exports.COMPOSER_RICH_BLOCKS = Object.freeze(["heading", "paragraph", "unorderedList", "orderedList", "table", "code", "cli", "quote", "callout", "divider", "keyValueGrid", "math"]);
exports.COMPOSER_RICH_CODE_LANGUAGES = richContentModel_1.RICH_CODE_LANGUAGES;
exports.COMPOSER_CALLOUT_VARIANTS = richContentModel_1.RICH_CALLOUT_VARIANTS;
exports.COMPOSER_TABLE_VARIANTS = Object.freeze(["bordered", "striped", "minimal"]);
exports.COMPOSER_CODING_LANGUAGES = Object.freeze(codingLanguages_1.CODING_LANGUAGES.map(l => l.key));
exports.COMPOSER_SCIENTIFIC_MATH = Object.freeze({
    version: richMath_1.MATH_LANGUAGE_VERSION,
    environments: richMath_1.MATH_ENVIRONMENTS,
    commands: richMath_1.MATH_COMMANDS,
    features: mathFeatures_1.MATH_FEATURES,
    limits: Object.freeze({ chars: richMath_1.MATH_LIMITS.chars, nodes: richMath_1.MATH_LIMITS.nodes, depth: richMath_1.MATH_LIMITS.depth, rows: richMath_1.MATH_GRID_LIMITS.rows, cols: richMath_1.MATH_GRID_LIMITS.cols, cells: richMath_1.MATH_GRID_LIMITS.cells, casesCols: richMath_1.MATH_GRID_LIMITS.casesCols, alignedCols: richMath_1.MATH_GRID_LIMITS.alignedCols })
});
const NOTES = Object.freeze({
    coding: "public material only (statement, language, starter code, public examples); hidden tests are never AI-authored — graded manually until the teacher adds verified hidden tests",
    networkCli: "networkCli@1 managed SWITCH only (VLANs, access / trunk ports, native VLAN, SVI address); no routing",
    smartSim: "trusted simulator: networkTopology@2 curriculum scenario, physicsFreeFall@1 bounded model, or functionStudy2d@1 safe expression",
    composite: "one question with shared context (one SmartSim or one source) and groups of child parts; never nested",
    parametricNumeric: "safe expression language only; {{var}} placeholders in the stem",
    openResponse: "rubric with 1-12 criteria, 2-8 levels, a 0-point and a full-points level per criterion; manual grading"
});
function buildComposerCatalog() {
    const questionTypes = exports.COMPOSER_ITEM_KINDS.map(kind => {
        const id = composerItemIdentity(kind);
        const def = (0, questionTypeCatalog_1.questionTypeDefinition)(id.key);
        if (!def || !(0, questionTypeCatalog_1.supportsQuestionTypeVersion)(id.key, id.version))
            throw new Error("composer catalog: unsupported production type " + id.key + "@" + id.version);
        return { kind, key: id.key, version: id.version, label: def.label, autoGraded: def.gradingMode === "auto" && kind !== "coding", compositeChild: kind !== "composite", note: NOTES[kind] ?? "" };
    });
    const smartSim = exports.COMPOSER_SIM_PLUGINS.map(p => {
        if (!(0, trustedSimRegistry_1.resolveSmartSimPlugin)(p.pluginKey, p.pluginVersion))
            throw new Error("composer catalog: SmartSim plugin not registered " + p.pluginKey + "@" + p.pluginVersion);
        return { pluginKey: p.pluginKey, pluginVersion: p.pluginVersion, subject: p.subject };
    });
    for (const b of exports.COMPOSER_RICH_BLOCKS)
        if (!richContentModel_1.RICH_BLOCK_TYPES.includes(b))
            throw new Error("composer catalog: rich block not in 20D.1 vocabulary " + b);
    for (const f of exports.COMPOSER_SCIENTIFIC_MATH.features)
        if (!(0, richMath_1.parseMath)(f.example).ok)
            throw new Error("composer catalog: math feature example refused by the parser " + f.id);
    return {
        version: exports.COMPOSER_CATALOG_VERSION,
        questionTypes,
        smartSim,
        networkScenarios: exports.COMPOSER_NET_SCENARIOS.map(id => { const s = composerNetScenario(id); return { id: s.id, title: s.title, topics: s.topics, checks: s.checks.map(c => ({ id: c.id, label: c.label })) }; }),
        physics: { measurements: exports.COMPOSER_PHYSICS_MEASUREMENTS, points: exports.COMPOSER_PHYSICS_POINTS, bounds: exports.COMPOSER_PHYSICS_BOUNDS },
        functionStudy: { language: 2, tasks: exports.COMPOSER_FUNCTION_TASKS, bounds: exports.COMPOSER_FUNCTION_BOUNDS },
        presets: exports.COMPOSER_PRESETS,
        richBlocks: exports.COMPOSER_RICH_BLOCKS,
        codingLanguages: exports.COMPOSER_CODING_LANGUAGES,
        scientificMath: exports.COMPOSER_SCIENTIFIC_MATH,
        unsupported: exports.COMPOSER_UNSUPPORTED.map(u => ({ id: u.id, label: u.label }))
    };
}
function catalogForPrompt(catalog = buildComposerCatalog()) {
    const lines = [
        "CAPABILITY CATALOG " + catalog.version + " (select ONLY from this list; exact versions; never invent a type, plugin, scenario, preset, block or language):",
        "Item kinds: " + catalog.questionTypes.map(t => t.kind + " (" + t.key + "@" + t.version + (t.autoGraded ? ", auto" : ", manual/hybrid") + (t.note ? "; " + t.note : "") + ")").join(" | "),
        "SmartSim plugins: " + catalog.smartSim.map(p => p.pluginKey + "@" + p.pluginVersion + " (" + p.subject + ")").join(", "),
        "networkTopology@2 scenarios: " + catalog.networkScenarios.map(s => s.id + " = " + s.title + " [" + s.topics.join(", ") + "] checks: " + s.checks.map(c => c.id + " " + c.label).join("; ")).join(" || "),
        "physicsFreeFall@1: model initialHeight 0.." + catalog.physics.bounds.heightMax + " m, initialVelocity ±" + catalog.physics.bounds.velocityAbsMax + " m/s (up positive), gravity " + catalog.physics.bounds.gravityMin + ".." + catalog.physics.bounds.gravityMax + " m/s²; measurements: " + catalog.physics.measurements.join(", ") + "; points: " + catalog.physics.points.join(", ") + ". Expected values are computed by code, never by you.",
        "functionStudy2d@1: expression language 2 in the single variable x (numbers, + - * / % ^, parentheses, abs, round, floor, ceil, min, max, sqrt, pow, log (natural), log10, exp; nothing else); tasks: " + catalog.functionStudy.tasks.join(", ") + "; |x| <= " + catalog.functionStudy.bounds.xAbsMax + ". Your expected answers are checked numerically against the expression.",
        "Presentation presets: " + catalog.presets.join(", "),
        "Rich blocks: " + catalog.richBlocks.join(", ") + " (no images, no HTML, no CSS, no URLs).",
        "Coding languages: " + catalog.codingLanguages.join(", "),
        scientificMathForPrompt(catalog.scientificMath),
        "NOT supported (never simulate; propose a theory question or omit and report it): " + catalog.unsupported.map(u => u.label).join(", ")
    ];
    return lines.join("\n");
}
function scientificMathForPrompt(m) {
    const L = m.limits;
    return "Math blocks (scientific notation language v" + m.version + "): type math, the formula in source WITHOUT $ delimiters; commands ONLY \\" + m.commands.join(" \\") +
        "; environments ONLY " + m.environments.join(", ") + " as \\begin{name}…\\end{name} (cells separated by &, rows by \\\\, never nested, at most " + L.rows + " rows, " + L.cols + " columns, " + L.cells + " cells; cases and aligned at most " + L.casesCols + " columns; & and \\\\ only inside an environment)" +
        "; \\mathbb only N Z Q R C; words in \\text{…} (Arabic allowed); units and chemical symbols in \\mathrm{…}; at most " + L.chars + " characters, " + L.nodes + " nodes, nesting depth " + L.depth +
        ". Examples: " + m.features.map(f => f.example).join(" ; ") + ". Anything else (\\href, \\url, \\def, \\newcommand, \\color, \\begin{array}, HTML, CSS, scripts, macros) is refused and the section is regenerated.";
}
