// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initialTaskState = exports.createTaskRuntime = exports.exactKeys = exports.TASK_ACTION_KINDS = exports.TASK_STATE_VERSION = void 0;
exports.normalizeTaskAction = normalizeTaskAction;
exports.applyTaskAction = applyTaskAction;
exports.canonicalTaskState = canonicalTaskState;
exports.replayTaskActions = replayTaskActions;
exports.evaluateReferenceValue = evaluateReferenceValue;
exports.taskRuleView = taskRuleView;
const trustedSimVocabulary_1 = require("../trustedSimVocabulary");
exports.TASK_STATE_VERSION = 1;
exports.TASK_ACTION_KINDS = Object.freeze(["measurement.set", "measurement.clear", "graphPoint.set", "graphPoint.clear"]);
const exactKeys = (o, keys) => Object.keys(o).length === keys.length && keys.every(k => Object.prototype.hasOwnProperty.call(o, k));
exports.exactKeys = exactKeys;
const value = (v, min, max) => typeof v === "number" && Number.isFinite(v) && v >= min && v <= max;
const declared = (ids, id) => typeof id === "string" && ids.includes(id);
function normalizeTaskAction(raw, b, invalidCode) {
    const bad = { ok: false, code: invalidCode }, V = b.valueAbsMax;
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw) || typeof raw.type !== "string")
        return bad;
    switch (raw.type) {
        case "measurement.set":
            if (!(0, exports.exactKeys)(raw, ["type", "measurementId", "value"]) || !declared(b.measurementIds, raw.measurementId) || !value(raw.value, -V, V))
                return bad;
            return { ok: true, action: { type: "measurement.set", measurementId: raw.measurementId, value: raw.value } };
        case "measurement.clear":
            if (!(0, exports.exactKeys)(raw, ["type", "measurementId"]) || !declared(b.measurementIds, raw.measurementId))
                return bad;
            return { ok: true, action: { type: "measurement.clear", measurementId: raw.measurementId } };
        case "graphPoint.set":
            if (!(0, exports.exactKeys)(raw, ["type", "pointId", "x", "y"]) || !declared(b.pointIds, raw.pointId) || !value(raw.x, b.pointX.min, b.pointX.max) || !value(raw.y, -V, V))
                return bad;
            return { ok: true, action: { type: "graphPoint.set", pointId: raw.pointId, x: raw.x, y: raw.y } };
        case "graphPoint.clear":
            if (!(0, exports.exactKeys)(raw, ["type", "pointId"]) || !declared(b.pointIds, raw.pointId))
                return bad;
            return { ok: true, action: { type: "graphPoint.clear", pointId: raw.pointId } };
        default:
            return bad;
    }
}
const createTaskRuntime = () => ({ measurements: new Map(), points: new Map() });
exports.createTaskRuntime = createTaskRuntime;
function applyTaskAction(rt, a) {
    const next = { measurements: new Map(rt.measurements), points: new Map(rt.points) };
    if (a.type === "measurement.set")
        next.measurements.set(a.measurementId, a.value);
    else if (a.type === "measurement.clear")
        next.measurements.delete(a.measurementId);
    else if (a.type === "graphPoint.set")
        next.points.set(a.pointId, { x: a.x, y: a.y });
    else
        next.points.delete(a.pointId);
    return next;
}
const byKey = (m) => [...m.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
function canonicalTaskState(rt) {
    const measurements = {}, points = {};
    for (const [id, v] of byKey(rt.measurements))
        measurements[id] = v;
    for (const [id, p] of byKey(rt.points))
        points[id] = { x: p.x, y: p.y };
    return { v: exports.TASK_STATE_VERSION, measurements, points };
}
const initialTaskState = () => ({ v: exports.TASK_STATE_VERSION, measurements: {}, points: {} });
exports.initialTaskState = initialTaskState;
function replayTaskActions(rawActions, b, maxActions, codes) {
    if (!Array.isArray(rawActions) || rawActions.length > maxActions)
        return { ok: false, code: codes.tooMany };
    const actions = [];
    let rt = (0, exports.createTaskRuntime)();
    for (const raw of rawActions) {
        const n = normalizeTaskAction(raw, b, codes.invalid);
        if (!n.ok)
            return n;
        actions.push(n.action);
        rt = applyTaskAction(rt, n.action);
    }
    return { ok: true, actions, state: canonicalTaskState(rt) };
}
function evaluateReferenceValue(expected, state, measurementId, tolerance, fmt) {
    const got = Object.prototype.hasOwnProperty.call(state.measurements, measurementId) ? state.measurements[measurementId] : undefined;
    const passed = typeof got === "number" && Number.isFinite(got) && expected !== null && Number.isFinite(expected) && Math.abs(got - expected) <= tolerance;
    return { expected: fmt(expected) + " ± " + fmt(tolerance), actual: typeof got === "number" ? fmt(got) : "—", passed };
}
function taskRuleView(state, measurementIds, pointIds) {
    const points = {};
    for (const id of Object.keys(state.points))
        points[id] = { x: state.points[id].x, y: state.points[id].y };
    return { ids: [...measurementIds, ...pointIds], selected: [], points, values: { ...state.measurements }, sequence: [], relations: [] };
}
