// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.answered = answered;
const nonEmptyValue = (v) => (typeof v === "boolean" ? v : String(v ?? "").trim() !== "");
function answered(a) {
    if (!a)
        return false;
    if (a.kind === "choice")
        return Number.isInteger(a.index);
    if (a.kind === "text")
        return !!a.value.trim();
    if (a.kind === "sequence" || a.kind === "table")
        return a.values.some(nonEmptyValue);
    if (a.kind === "fields")
        return Object.values(a.values).some(v => (Array.isArray(v) ? v.some(nonEmptyValue) : nonEmptyValue(v)));
    if (a.kind === "compound")
        return Object.values(a.parts).some(answered);
    return false;
}
