// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SOURCE_LABEL = exports.isThresholdQualityRule = exports.isCoverageQualityRule = exports.EFFECT_LABEL = exports.QUALITY_THRESHOLD_METRICS = exports.QUALITY_TRIGGER_RELATIONS = exports.QUALITY_EFFECTS = exports.ASSESSMENT_QUALITY_POLICY_SCHEMA_VERSION = void 0;
exports.emptyQualityPolicy = emptyQualityPolicy;
exports.newQualityRuleId = newQualityRuleId;
exports.validateAssessmentQualityPolicy = validateAssessmentQualityPolicy;
exports.withQualityPolicy = withQualityPolicy;
exports.setQualityPolicyEnabled = setQualityPolicyEnabled;
exports.addQualityRule = addQualityRule;
exports.updateQualityRule = updateQualityRule;
exports.replaceQualityRule = replaceQualityRule;
exports.removeQualityRule = removeQualityRule;
exports.qualityRuleSourceKey = qualityRuleSourceKey;
exports.parseQualityRuleSourceKey = parseQualityRuleSourceKey;
exports.defaultQualityRule = defaultQualityRule;
exports.retargetQualityRule = retargetQualityRule;
exports.describeConstraint = describeConstraint;
const assessmentTypes_1 = require("./assessmentTypes");
Object.defineProperty(exports, "ASSESSMENT_QUALITY_POLICY_SCHEMA_VERSION", { enumerable: true, get: function () { return assessmentTypes_1.ASSESSMENT_QUALITY_POLICY_SCHEMA_VERSION; } });
Object.defineProperty(exports, "QUALITY_EFFECTS", { enumerable: true, get: function () { return assessmentTypes_1.QUALITY_EFFECTS; } });
Object.defineProperty(exports, "QUALITY_TRIGGER_RELATIONS", { enumerable: true, get: function () { return assessmentTypes_1.QUALITY_TRIGGER_RELATIONS; } });
Object.defineProperty(exports, "QUALITY_THRESHOLD_METRICS", { enumerable: true, get: function () { return assessmentTypes_1.QUALITY_THRESHOLD_METRICS; } });
const assessmentBlueprint_1 = require("./assessmentBlueprint");
const examTypes_1 = require("./examTypes");
function emptyQualityPolicy() { return { schemaVersion: assessmentTypes_1.ASSESSMENT_QUALITY_POLICY_SCHEMA_VERSION, enabled: false, rules: [] }; }
let ruleSeq = 0;
function newQualityRuleId() { ruleSeq += 1; return "qr" + Date.now().toString(36) + ruleSeq.toString(36); }
const isPlainObject = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const SOURCE_KINDS = ["constraint", "total-questions", "total-marks", "unclassified", "unmapped-bank"];
exports.EFFECT_LABEL = { warning: "تنبيه", "block-finalization": "يمنع الاعتماد النهائي" };
function validateAssessmentQualityPolicy(policy, blueprint) {
    const issues = [];
    const add = (code, message, path, ruleId) => issues.push({ code, message, path, ruleId });
    if (policy === undefined)
        return issues;
    if (!isPlainObject(policy))
        return [{ code: "INVALID_POLICY", message: "سياسة الجودة غير صالحة.", path: "qualityPolicy" }];
    if (policy.schemaVersion !== assessmentTypes_1.ASSESSMENT_QUALITY_POLICY_SCHEMA_VERSION)
        return [{ code: "UNSUPPORTED_POLICY_SCHEMA", message: "إصدار سياسة الجودة غير مدعوم.", path: "qualityPolicy.schemaVersion" }];
    if (typeof policy.enabled !== "boolean")
        add("INVALID_ENABLED", "حالة تفعيل السياسة غير صالحة.", "qualityPolicy.enabled");
    if (!Array.isArray(policy.rules)) {
        add("INVALID_RULES", "قائمة القواعد غير صالحة.", "qualityPolicy.rules");
        return issues;
    }
    const constraintIds = new Set((blueprint?.constraints ?? []).map(c => c.id).filter((id) => typeof id === "string"));
    const targets = blueprint?.targets;
    const seen = new Set();
    policy.rules.forEach((r, i) => {
        const path = "rules[" + i + "]";
        if (!isPlainObject(r)) {
            add("INVALID_RULE", "قاعدة غير صالحة.", path);
            return;
        }
        const ruleId = typeof r.id === "string" && r.id.trim() ? r.id : undefined;
        if (!ruleId)
            add("MISSING_RULE_ID", "معرّف القاعدة مطلوب.", path + ".id");
        else if (seen.has(ruleId))
            add("DUPLICATE_RULE_ID", "معرّف القاعدة مكرر: " + ruleId, path + ".id", ruleId);
        else
            seen.add(ruleId);
        if (typeof r.enabled !== "boolean")
            add("INVALID_RULE_ENABLED", "حالة تفعيل القاعدة غير صالحة.", path + ".enabled", ruleId);
        if (!assessmentTypes_1.QUALITY_EFFECTS.includes(r.effect))
            add("INVALID_EFFECT", "أثر القاعدة غير معروف.", path + ".effect", ruleId);
        if (r.note !== undefined && typeof r.note !== "string")
            add("INVALID_NOTE", "ملاحظة القاعدة غير صالحة.", path + ".note", ruleId);
        const src = r.source;
        if (!isPlainObject(src)) {
            add("INVALID_SOURCE", "مصدر القاعدة غير صالح.", path + ".source", ruleId);
            return;
        }
        if (!SOURCE_KINDS.includes(src.kind)) {
            add("UNSUPPORTED_SOURCE_KIND", "نوع مصدر القاعدة غير مدعوم.", path + ".source.kind", ruleId);
            return;
        }
        if (src.kind === "constraint") {
            if (typeof src.constraintId !== "string" || !constraintIds.has(src.constraintId))
                add("BROKEN_CONSTRAINT_REF", "القاعدة تشير إلى قيد غير موجود في المخطط: " + String(src.constraintId ?? ""), path + ".source.constraintId", ruleId);
        }
        if (src.kind === "total-questions" && (!targets || !("totalQuestions" in targets)))
            add("MISSING_TOTAL_TARGET", "لا يوجد هدف إجمالي للأسئلة في المخطط.", path + ".source", ruleId);
        if (src.kind === "total-marks" && (!targets || !("totalMarks" in targets)))
            add("MISSING_TOTAL_TARGET", "لا يوجد هدف إجمالي للعلامات في المخطط.", path + ".source", ruleId);
        if (src.kind === "constraint" || src.kind === "total-questions" || src.kind === "total-marks") {
            if (!Array.isArray(r.relations))
                add("INVALID_RELATIONS", "قائمة العلاقات غير صالحة.", path + ".relations", ruleId);
            else if (r.relations.length === 0)
                add("EMPTY_RELATIONS", "القاعدة لا تحدد أي علاقة مُفعِّلة.", path + ".relations", ruleId);
            else
                for (const rel of r.relations)
                    if (!assessmentTypes_1.QUALITY_TRIGGER_RELATIONS.includes(rel))
                        add("UNKNOWN_RELATION", "علاقة غير معروفة: " + String(rel), path + ".relations", ruleId);
        }
        else {
            const allowed = src.kind === "unclassified" ? assessmentTypes_1.QUALITY_THRESHOLD_METRICS : ["count"];
            if (!allowed.includes(r.metric))
                add("INVALID_METRIC", "مقياس القاعدة غير صالح لهذا المصدر.", path + ".metric", ruleId);
            if (typeof r.max !== "number" || !Number.isFinite(r.max) || r.max < 0)
                add("INVALID_THRESHOLD", "الحد الأقصى يجب أن يكون رقمًا غير سالب.", path + ".max", ruleId);
        }
    });
    return issues;
}
const sameRule = (a, b) => JSON.stringify(a) === JSON.stringify(b);
function withQualityPolicy(bp, fn) {
    const cur = bp.qualityPolicy ?? emptyQualityPolicy();
    const next = fn(cur);
    if (next === cur)
        return bp;
    return { ...bp, qualityPolicy: next };
}
function setQualityPolicyEnabled(bp, enabled) {
    if (!bp.qualityPolicy && !enabled)
        return bp;
    return withQualityPolicy(bp, p => (p.enabled === enabled ? p : { ...p, enabled }));
}
function addQualityRule(bp, rule) { return withQualityPolicy(bp, p => ({ ...p, rules: [...p.rules, rule] })); }
function updateQualityRule(bp, id, patch) {
    return withQualityPolicy(bp, p => {
        const i = p.rules.findIndex(r => r.id === id);
        if (i < 0)
            return p;
        const next = { ...p.rules[i], ...patch };
        if (sameRule(next, p.rules[i]))
            return p;
        const rules = p.rules.slice();
        rules[i] = next;
        return { ...p, rules };
    });
}
function replaceQualityRule(bp, id, rule) {
    return withQualityPolicy(bp, p => { const i = p.rules.findIndex(r => r.id === id); if (i < 0 || sameRule(rule, p.rules[i]))
        return p; const rules = p.rules.slice(); rules[i] = rule; return { ...p, rules }; });
}
function removeQualityRule(bp, id) {
    return withQualityPolicy(bp, p => (p.rules.some(r => r.id === id) ? { ...p, rules: p.rules.filter(r => r.id !== id) } : p));
}
function qualityRuleSourceKey(source) { return source.kind === "constraint" ? "constraint:" + source.constraintId : source.kind; }
function parseQualityRuleSourceKey(key) {
    if (key.startsWith("constraint:"))
        return { kind: "constraint", constraintId: key.slice("constraint:".length) };
    return SOURCE_KINDS.includes(key) && key !== "constraint" ? { kind: key } : null;
}
const isCoverageQualityRule = (r) => r.source.kind === "constraint" || r.source.kind === "total-questions" || r.source.kind === "total-marks";
exports.isCoverageQualityRule = isCoverageQualityRule;
const isThresholdQualityRule = (r) => r.source.kind === "unclassified" || r.source.kind === "unmapped-bank";
exports.isThresholdQualityRule = isThresholdQualityRule;
function defaultQualityRule(bp) {
    const first = bp?.constraints.find(c => typeof c.id === "string" && c.id);
    if (first)
        return { id: newQualityRuleId(), enabled: true, source: { kind: "constraint", constraintId: first.id }, relations: ["below-min"], effect: "warning" };
    return { id: newQualityRuleId(), enabled: true, source: { kind: "unclassified" }, metric: "count", max: 0, effect: "warning" };
}
function retargetQualityRule(rule, source) {
    const base = { id: rule.id, enabled: rule.enabled, effect: rule.effect, ...(rule.note !== undefined ? { note: rule.note } : {}) };
    if (source.kind === "unclassified" || source.kind === "unmapped-bank") {
        const metric = (0, exports.isThresholdQualityRule)(rule) && source.kind === "unclassified" ? rule.metric : "count";
        return { ...base, source, metric, max: (0, exports.isThresholdQualityRule)(rule) ? rule.max : 0 };
    }
    return { ...base, source, relations: (0, exports.isCoverageQualityRule)(rule) ? rule.relations : ["below-min"] };
}
const DIM_LABEL = { topic: "موضوع", objective: "هدف تعليمي", difficulty: "صعوبة", cognitiveLevel: "مستوى معرفي", questionType: "نوع السؤال", capability: "مهارة / قدرة", section: "قسم" };
function describeConstraint(bp, c, sections = []) {
    const ref = String(c.ref ?? "");
    let label = ref;
    switch (c.dimension) {
        case "topic":
            label = bp.topics.find(t => t.id === ref)?.label || ref;
            break;
        case "objective":
            label = bp.objectives.find(o => o.id === ref)?.label || ref;
            break;
        case "difficulty": {
            const l = (0, assessmentBlueprint_1.blueprintDifficultyScale)(bp).labels?.[ref];
            label = l ? ref + " — " + l : ref;
            break;
        }
        case "cognitiveLevel":
            label = (0, assessmentBlueprint_1.blueprintCognitiveLevels)(bp).find(l => l.id === ref)?.label || ref;
            break;
        case "questionType":
            label = examTypes_1.QUESTION_TYPE_LABELS[ref] || ref;
            break;
        case "section":
            label = sections.find(s => s.id === ref)?.title || ref;
            break;
    }
    return (DIM_LABEL[c.dimension] || c.dimension) + ": " + label + " — " + (c.metric === "marks" ? "العلامات" : "عدد الأسئلة") + (c.unit === "percent" ? " (نسبة مئوية)" : "");
}
exports.SOURCE_LABEL = { "total-questions": "إجمالي الأسئلة", "total-marks": "إجمالي العلامات الرسمية", unclassified: "الأسئلة غير المصنفة", "unmapped-bank": "مواضيع البنك غير المربوطة" };
