// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultCodingAnswerKey = exports.defaultCodingConfig = exports.codingGradingMode = exports.CODING_GRADING_MODES = exports.DEFAULT_CODING_COMPARATOR = exports.CODING_COMPARATORS = exports.CODING_TEST_ID_PATTERN = exports.CODING_TEST_LIMITS = exports.CODE_SOURCE_MAX_BYTES = exports.DEFAULT_CODING_LIMITS = exports.CODING_LIMIT_RANGES = exports.CODING_LANGUAGE_KEY_PATTERN = exports.isCodingLanguage = exports.codingLanguage = exports.CODING_LANGUAGES = void 0;
exports.utf8ByteLength = utf8ByteLength;
exports.normalizeCodeAnswer = normalizeCodeAnswer;
exports.projectCodingConfigForStudent = projectCodingConfigForStudent;
exports.bindCodeAnswerToQuestion = bindCodeAnswerToQuestion;
exports.validateCodingQuestion = validateCodingQuestion;
const lang = (key, label, extension, indentUnit, flags) => Object.freeze({ key, version: 1, label, extension, editorLanguage: key, indentUnit, capabilities: Object.freeze({ compile: flags.includes("c"), run: flags.includes("r"), stdin: flags.includes("r"), tests: flags.includes("r") }) });
exports.CODING_LANGUAGES = Object.freeze([
    lang("python", "Python", ".py", "    ", "r"),
    lang("java", "Java", ".java", "    ", "cr"),
    lang("csharp", "C#", ".cs", "    ", "cr")
]);
const LANGUAGE_INDEX = new Map(exports.CODING_LANGUAGES.map(l => [l.key, l]));
const codingLanguage = (key) => (typeof key === "string" ? LANGUAGE_INDEX.get(key) : undefined);
exports.codingLanguage = codingLanguage;
const isCodingLanguage = (key) => (0, exports.codingLanguage)(key) !== undefined;
exports.isCodingLanguage = isCodingLanguage;
exports.CODING_LANGUAGE_KEY_PATTERN = /^[a-z][a-z0-9]{0,31}$/;
exports.CODING_LIMIT_RANGES = Object.freeze({ sourceBytes: [1024, 65536], outputBytes: [1024, 262144], timeMs: [250, 10000], memoryMb: [16, 512] });
exports.DEFAULT_CODING_LIMITS = Object.freeze({ sourceBytes: 65536, outputBytes: 65536, timeMs: 2000, memoryMb: 256 });
exports.CODE_SOURCE_MAX_BYTES = 65536;
exports.CODING_TEST_LIMITS = Object.freeze({ publicTests: 10, hiddenTests: 50, ioBytes: 16384, totalBytes: 262144 });
exports.CODING_TEST_ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;
exports.CODING_COMPARATORS = Object.freeze(["exact", "trimTrailingWhitespace", "normalizeWhitespace"]);
exports.DEFAULT_CODING_COMPARATOR = "trimTrailingWhitespace";
exports.CODING_GRADING_MODES = Object.freeze(["manual", "hiddenTests"]);
const codingGradingMode = (answerKey) => (!!answerKey && typeof answerKey === "object" && !Array.isArray(answerKey) && answerKey.gradingMode === "hiddenTests" ? "hiddenTests" : "manual");
exports.codingGradingMode = codingGradingMode;
const defaultCodingConfig = () => ({ allowedLanguages: ["python"], defaultLanguage: "python", starterCode: {}, taskMode: "program", inputMode: "stdin", outputMode: "stdout", limits: { ...exports.DEFAULT_CODING_LIMITS }, publicTests: [] });
exports.defaultCodingConfig = defaultCodingConfig;
const defaultCodingAnswerKey = () => ({ hiddenTests: [], comparator: exports.DEFAULT_CODING_COMPARATOR, referenceSolutions: {}, gradingMode: "manual" });
exports.defaultCodingAnswerKey = defaultCodingAnswerKey;
function utf8ByteLength(s) {
    let n = 0;
    for (let i = 0; i < s.length; i++) {
        const c = s.charCodeAt(i);
        if (c < 0x80)
            n += 1;
        else if (c < 0x800)
            n += 2;
        else if (c >= 0xd800 && c <= 0xdbff && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
            n += 4;
            i++;
        }
        else
            n += 3;
    }
    return n;
}
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
function normalizeCodeAnswer(a) {
    if (!isObj(a) || a.kind !== "code" || typeof a.source !== "string" || typeof a.language !== "string" || !exports.CODING_LANGUAGE_KEY_PATTERN.test(a.language))
        return { ok: false, code: "CODE_ANSWER_INVALID" };
    if (typeof a.languageVersion !== "number" || !Number.isInteger(a.languageVersion) || a.languageVersion < 1 || a.languageVersion > 1000)
        return { ok: false, code: "CODE_ANSWER_INVALID" };
    const def = (0, exports.codingLanguage)(a.language);
    if (!def || a.languageVersion !== def.version)
        return { ok: false, code: "CODE_ANSWER_INVALID" };
    if (utf8ByteLength(a.source) > exports.CODE_SOURCE_MAX_BYTES)
        return { ok: false, code: "CODE_SOURCE_TOO_LARGE" };
    return { ok: true, answer: { kind: "code", language: a.language, languageVersion: a.languageVersion, source: a.source } };
}
const PUBLIC_KEYS = new Set(["allowedLanguages", "defaultLanguage", "starterCode", "taskMode", "inputMode", "outputMode", "limits", "publicTests"]);
const str = (v) => (typeof v === "string" ? v : undefined);
function projectCodingConfigForStudent(cfg) {
    if (!isObj(cfg))
        return undefined;
    const out = {};
    if (Array.isArray(cfg.allowedLanguages))
        out.allowedLanguages = cfg.allowedLanguages.filter(l => typeof l === "string" && (0, exports.isCodingLanguage)(l));
    if (typeof cfg.defaultLanguage === "string")
        out.defaultLanguage = cfg.defaultLanguage;
    if (isObj(cfg.starterCode)) {
        const sc = {};
        for (const k of Object.keys(cfg.starterCode)) {
            const v = cfg.starterCode[k];
            if (typeof v === "string" && (0, exports.isCodingLanguage)(k))
                sc[k] = v;
        }
        out.starterCode = sc;
    }
    for (const k of ["taskMode", "inputMode", "outputMode"])
        if (typeof cfg[k] === "string")
            out[k] = cfg[k];
    if (isObj(cfg.limits)) {
        const l = {};
        for (const k of Object.keys(exports.CODING_LIMIT_RANGES)) {
            const v = cfg.limits[k];
            if (typeof v === "number" && Number.isFinite(v))
                l[k] = v;
        }
        out.limits = l;
    }
    if (Array.isArray(cfg.publicTests))
        out.publicTests = cfg.publicTests.filter(isObj).map(t => { const p = {}; for (const k of ["id", "title", "input", "sampleOutput"]) {
            const v = str(t[k]);
            if (v !== undefined)
                p[k] = v;
        } return p; });
    return out;
}
function bindCodeAnswerToQuestion(a, question) {
    const base = normalizeCodeAnswer(a);
    if (!base.ok)
        return base;
    if (!isObj(question) || String(question.presentationType ?? question.type ?? "") !== "coding" || (question.questionTypeVersion !== undefined && question.questionTypeVersion !== 1))
        return { ok: false, code: "CODE_QUESTION_MISMATCH" };
    const cfg = projectCodingConfigForStudent(question.coding);
    if (!cfg || !Array.isArray(cfg.allowedLanguages) || !cfg.allowedLanguages.includes(base.answer.language))
        return { ok: false, code: "CODE_LANGUAGE_NOT_ALLOWED" };
    const configured = cfg.limits && typeof cfg.limits.sourceBytes === "number" && Number.isInteger(cfg.limits.sourceBytes) && cfg.limits.sourceBytes > 0 ? cfg.limits.sourceBytes : exports.CODE_SOURCE_MAX_BYTES;
    if (utf8ByteLength(base.answer.source) > Math.min(configured, exports.CODE_SOURCE_MAX_BYTES))
        return { ok: false, code: "CODE_SOURCE_TOO_LARGE" };
    return base;
}
const err = (code, message, path) => ({ code, message, severity: "error", path });
const validLimit = (k, v) => typeof v === "number" && Number.isInteger(v) && v >= exports.CODING_LIMIT_RANGES[k][0] && v <= exports.CODING_LIMIT_RANGES[k][1];
function validateCodingQuestion(node) {
    const out = [];
    const cfg = node.coding;
    if (!isObj(cfg))
        return [err("CODING_CONFIG_MISSING", "إعداد سؤال البرمجة مفقود أو غير صالح.", "coding")];
    for (const k of Object.keys(cfg))
        if (!PUBLIC_KEYS.has(k))
            out.push(err("CODING_CONFIG_UNKNOWN_KEY", "حقل غير معروف في إعداد سؤال البرمجة: " + k, "coding." + k));
    const langs = Array.isArray(cfg.allowedLanguages) ? cfg.allowedLanguages : [];
    if (!langs.length)
        out.push(err("CODING_NO_LANGUAGES", "اختر لغة برمجة واحدة على الأقل.", "coding.allowedLanguages"));
    const allowed = new Set();
    for (const l of langs) {
        if (!(0, exports.isCodingLanguage)(l))
            out.push(err("CODING_LANGUAGE_UNKNOWN", "لغة برمجة غير مدعومة: " + String(l), "coding.allowedLanguages"));
        else if (allowed.has(l))
            out.push(err("CODING_LANGUAGE_DUPLICATE", "لغة مكررة: " + String(l), "coding.allowedLanguages"));
        else
            allowed.add(l);
    }
    if (langs.length && !(typeof cfg.defaultLanguage === "string" && allowed.has(cfg.defaultLanguage)))
        out.push(err("CODING_DEFAULT_LANGUAGE_INVALID", "اللغة الافتراضية يجب أن تكون إحدى اللغات المسموحة.", "coding.defaultLanguage"));
    if (cfg.taskMode !== "program" || cfg.inputMode !== "stdin" || cfg.outputMode !== "stdout")
        out.push(err("CODING_TASK_MODE_UNSUPPORTED", "وضع المهمة المدعوم: برنامج كامل يقرأ من الإدخال القياسي ويكتب إلى الإخراج القياسي.", "coding.taskMode"));
    const limits = isObj(cfg.limits) ? cfg.limits : null;
    if (!limits || !Object.keys(exports.CODING_LIMIT_RANGES).every(k => validLimit(k, limits[k])))
        out.push(err("CODING_LIMIT_INVALID", "حدود التنفيذ يجب أن تكون أعدادًا صحيحة ضمن المدى المسموح.", "coding.limits"));
    const sourceLimit = limits && validLimit("sourceBytes", limits.sourceBytes) ? limits.sourceBytes : exports.CODE_SOURCE_MAX_BYTES;
    if (cfg.starterCode !== undefined) {
        if (!isObj(cfg.starterCode))
            out.push(err("CODING_STARTER_INVALID", "الكود الابتدائي غير صالح.", "coding.starterCode"));
        else
            for (const [k, v] of Object.entries(cfg.starterCode)) {
                if (typeof v !== "string")
                    out.push(err("CODING_STARTER_INVALID", "الكود الابتدائي غير صالح: " + k, "coding.starterCode." + k));
                else if (!allowed.has(k))
                    out.push(err("CODING_STARTER_LANGUAGE_NOT_ALLOWED", "كود ابتدائي للغة غير مسموحة: " + k, "coding.starterCode." + k));
                else if (utf8ByteLength(v) > sourceLimit)
                    out.push(err("CODING_STARTER_TOO_LARGE", "الكود الابتدائي أكبر من حد حجم الكود: " + k, "coding.starterCode." + k));
            }
    }
    const key = isObj(node.answer) ? node.answer : {};
    const ids = new Set();
    let total = 0, hiddenWeight = 0;
    const checkTests = (list, hidden) => {
        if (list === undefined)
            return 0;
        const where = hidden ? "answer.hiddenTests" : "coding.publicTests";
        if (!Array.isArray(list)) {
            out.push(err("CODING_TEST_MALFORMED", "قائمة الاختبارات غير صالحة.", where));
            return 0;
        }
        list.forEach((t, i) => {
            const label = (hidden ? "الاختبار المخفي " : "المثال ") + (i + 1);
            if (!isObj(t)) {
                out.push(err("CODING_TEST_MALFORMED", label + " غير صالح.", where));
                return;
            }
            if (typeof t.id !== "string" || !exports.CODING_TEST_ID_PATTERN.test(t.id))
                out.push(err("CODING_TEST_ID_INVALID", label + " بلا معرّف ثابت صالح.", where));
            else if (ids.has(t.id))
                out.push(err("CODING_TEST_ID_DUPLICATE", "معرّف اختبار مكرر: " + t.id, where));
            else
                ids.add(t.id);
            const outKey = hidden ? "expectedOutput" : "sampleOutput";
            if (typeof t.input !== "string" || (hidden ? typeof t[outKey] !== "string" : t[outKey] !== undefined && typeof t[outKey] !== "string") || (t.title !== undefined && typeof t.title !== "string")) {
                out.push(err("CODING_TEST_MALFORMED", label + ": المدخلات والمخرجات يجب أن تكون نصوصًا.", where));
                return;
            }
            for (const v of [t.input, t[outKey]])
                if (v !== undefined) {
                    const b = utf8ByteLength(v);
                    total += b;
                    if (b > exports.CODING_TEST_LIMITS.ioBytes)
                        out.push(err("CODING_TEST_TOO_LARGE", label + ": المدخلات أو المخرجات أكبر من 16 KB.", where));
                }
            if (hidden) {
                if (typeof t.weight !== "number" || !Number.isFinite(t.weight) || t.weight < 0)
                    out.push(err("CODING_WEIGHT_INVALID", label + ": الوزن يجب أن يكون عددًا غير سالب.", where));
                else
                    hiddenWeight += t.weight;
            }
        });
        return list.length;
    };
    const nPublic = checkTests(cfg.publicTests, false), nHidden = checkTests(key.hiddenTests, true);
    if (nPublic > exports.CODING_TEST_LIMITS.publicTests)
        out.push(err("CODING_TOO_MANY_PUBLIC_TESTS", "الحد الأقصى للأمثلة الظاهرة " + exports.CODING_TEST_LIMITS.publicTests + ".", "coding.publicTests"));
    if (nHidden > exports.CODING_TEST_LIMITS.hiddenTests)
        out.push(err("CODING_TOO_MANY_HIDDEN_TESTS", "الحد الأقصى للاختبارات المخفية " + exports.CODING_TEST_LIMITS.hiddenTests + ".", "answer.hiddenTests"));
    if (total > exports.CODING_TEST_LIMITS.totalBytes)
        out.push(err("CODING_TEST_DATA_TOO_LARGE", "مجموع بيانات الاختبارات أكبر من 256 KB.", "answer.hiddenTests"));
    if (nHidden > 0 && hiddenWeight <= 0 && !out.some(i => i.code === "CODING_WEIGHT_INVALID"))
        out.push(err("CODING_WEIGHT_TOTAL_ZERO", "مجموع أوزان الاختبارات المخفية يجب أن يكون أكبر من صفر.", "answer.hiddenTests"));
    if (nPublic + nHidden > 0 && [...allowed].some(l => !(0, exports.codingLanguage)(l).capabilities.tests))
        out.push(err("CODING_TESTS_UNSUPPORTED_FOR_LANGUAGE", "اختبارات الإدخال/الإخراج لا تنطبق على لغة مسموحة في هذا السؤال.", "coding.allowedLanguages"));
    if (key.comparator !== undefined && !exports.CODING_COMPARATORS.includes(key.comparator))
        out.push(err("CODING_COMPARATOR_UNKNOWN", "طريقة مقارنة مخرجات غير معروفة.", "answer.comparator"));
    if (key.gradingMode !== undefined && !exports.CODING_GRADING_MODES.includes(key.gradingMode))
        out.push(err("CODING_GRADING_MODE_UNKNOWN", "طريقة تصحيح رسمي غير معروفة.", "answer.gradingMode"));
    if (key.gradingMode === "hiddenTests") {
        if (nHidden === 0)
            out.push(err("CODING_AUTO_NO_HIDDEN_TESTS", "التصحيح التلقائي يحتاج إلى اختبار مخفي واحد على الأقل.", "answer.hiddenTests"));
        const outputLimit = limits && validLimit("outputBytes", limits.outputBytes) ? limits.outputBytes : 0;
        if (Array.isArray(key.hiddenTests))
            key.hiddenTests.forEach((t, i) => {
                if (isObj(t) && typeof t.expectedOutput === "string" && outputLimit > 0 && utf8ByteLength(t.expectedOutput) > outputLimit)
                    out.push(err("CODING_EXPECTED_OUTPUT_EXCEEDS_LIMIT", "الاختبار المخفي " + (i + 1) + ": المخرجات المتوقعة أكبر من حد المخرجات المسموح للبرنامج.", "answer.hiddenTests"));
            });
    }
    if (key.referenceSolutions !== undefined) {
        if (!isObj(key.referenceSolutions))
            out.push(err("CODING_REFERENCE_INVALID", "الحلول المرجعية غير صالحة.", "answer.referenceSolutions"));
        else
            for (const [k, v] of Object.entries(key.referenceSolutions)) {
                if (!allowed.has(k))
                    out.push(err("CODING_REFERENCE_LANGUAGE_NOT_ALLOWED", "حل مرجعي للغة غير مسموحة: " + k, "answer.referenceSolutions." + k));
                else if (typeof v !== "string" || utf8ByteLength(v) > exports.CODE_SOURCE_MAX_BYTES)
                    out.push(err("CODING_REFERENCE_INVALID", "الحل المرجعي غير صالح: " + k, "answer.referenceSolutions." + k));
            }
    }
    return out;
}
