// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isCodeTemplateAnswered = exports.templateStarterValues = exports.templateGapIds = exports.isTemplateGapId = exports.CODING_TEMPLATE_LIMITS = void 0;
exports.validateCodingTemplate = validateCodingTemplate;
exports.reconstructTemplateSource = reconstructTemplateSource;
exports.normalizeCodeTemplateAnswer = normalizeCodeTemplateAnswer;
exports.bindCodeTemplateAnswer = bindCodeTemplateAnswer;
const codingLanguages_1 = require("./codingLanguages");
exports.CODING_TEMPLATE_LIMITS = Object.freeze({ segments: 100, gaps: 30, gapBytes: 16384 });
const FORBIDDEN_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const GAP_ID = /^[A-Za-z][A-Za-z0-9_-]{0,31}$/;
const isPlain = (v) => {
    if (!v || typeof v !== "object" || Array.isArray(v))
        return false;
    const p = Object.getPrototypeOf(v);
    return p === Object.prototype || p === null;
};
const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
const exactKeys = (o, keys) => Object.keys(o).length === keys.length && keys.every(k => own(o, k)) && Object.keys(o).every(k => !FORBIDDEN_KEYS.has(k));
const isTemplateGapId = (v) => typeof v === "string" && GAP_ID.test(v) && !FORBIDDEN_KEYS.has(v);
exports.isTemplateGapId = isTemplateGapId;
const err = (code, message, path) => ({ code, message, severity: "error", ...(path ? { path } : {}) });
const M = {
    invalid: "القالب المقفل غير صالح أو يحتوي حقولًا غير معروفة.",
    language: "لغة القالب المقفل يجب أن تكون لغة برمجة مدعومة.",
    segments: "القالب المقفل يحتاج من 1 إلى " + exports.CODING_TEMPLATE_LIMITS.segments + " مقطعًا.",
    segment: "مقطع غير صالح في القالب المقفل.",
    locked: "المقطع المقفل يجب أن يكون نصًا غير فارغ.",
    adjacent: "لا يجوز أن يتجاور مقطعان مقفلان: ادمجهما في مقطع واحد.",
    gapId: "معرّف الفراغ غير صالح (حرف إنجليزي أولًا، حتى 32 حرفًا).",
    gapDup: "معرّف الفراغ مكرر.",
    gapCount: "القالب المقفل يحتاج من 1 إلى " + exports.CODING_TEMPLATE_LIMITS.gaps + " فراغًا قابلًا للتعديل.",
    starter: "النص الابتدائي للفراغ يجب أن يكون نصًا حتى " + exports.CODING_TEMPLATE_LIMITS.gapBytes + " بايت.",
    tooLarge: "الكود الكامل للقالب (مع النصوص الابتدائية) أكبر من حد حجم الكود."
};
function validateCodingTemplate(raw, sourceLimit = codingLanguages_1.CODE_SOURCE_MAX_BYTES) {
    const path = "coding.template";
    if (!isPlain(raw) || !exactKeys(raw, ["language", "segments"]))
        return { ok: false, issues: [err("CODING_TEMPLATE_INVALID", M.invalid, path)] };
    const issues = [];
    if (!(0, codingLanguages_1.codingLanguage)(raw.language))
        issues.push(err("CODING_TEMPLATE_LANGUAGE_INVALID", M.language, path + ".language"));
    const list = raw.segments;
    if (!Array.isArray(list) || list.length === 0 || list.length > exports.CODING_TEMPLATE_LIMITS.segments)
        return { ok: false, issues: [...issues, err("CODING_TEMPLATE_SEGMENTS_COUNT", M.segments, path + ".segments")] };
    const segments = [];
    const ids = new Set();
    let previousLocked = false;
    list.forEach((s, i) => {
        const p = path + ".segments." + i;
        if (isPlain(s) && s.kind === "locked" && exactKeys(s, ["kind", "text"])) {
            if (typeof s.text !== "string" || s.text === "") {
                issues.push(err("CODING_TEMPLATE_LOCKED_INVALID", M.locked, p));
                return;
            }
            if (previousLocked)
                issues.push(err("CODING_TEMPLATE_ADJACENT_LOCKED", M.adjacent, p));
            previousLocked = true;
            segments.push({ kind: "locked", text: s.text });
            return;
        }
        if (isPlain(s) && s.kind === "editable" && exactKeys(s, ["kind", "id", "starter"])) {
            previousLocked = false;
            if (!(0, exports.isTemplateGapId)(s.id))
                issues.push(err("CODING_TEMPLATE_GAP_ID_INVALID", M.gapId, p + ".id"));
            else if (ids.has(s.id))
                issues.push(err("CODING_TEMPLATE_GAP_ID_DUPLICATE", M.gapDup, p + ".id"));
            else
                ids.add(s.id);
            if (typeof s.starter !== "string" || (0, codingLanguages_1.utf8ByteLength)(s.starter) > exports.CODING_TEMPLATE_LIMITS.gapBytes)
                issues.push(err("CODING_TEMPLATE_STARTER_INVALID", M.starter, p + ".starter"));
            segments.push({ kind: "editable", id: s.id, starter: typeof s.starter === "string" ? s.starter : "" });
            return;
        }
        previousLocked = false;
        issues.push(err("CODING_TEMPLATE_SEGMENT_INVALID", M.segment, p));
    });
    const gaps = segments.filter(s => s.kind === "editable").length;
    if (gaps === 0 || gaps > exports.CODING_TEMPLATE_LIMITS.gaps)
        issues.push(err("CODING_TEMPLATE_GAP_COUNT", M.gapCount, path + ".segments"));
    if (issues.length)
        return { ok: false, issues };
    const template = { language: raw.language, segments };
    const starters = {};
    for (const s of segments)
        if (s.kind === "editable")
            starters[s.id] = s.starter;
    if ((0, codingLanguages_1.utf8ByteLength)(reconstructTemplateSource(template, starters)) > Math.min(sourceLimit, codingLanguages_1.CODE_SOURCE_MAX_BYTES))
        return { ok: false, issues: [err("CODING_TEMPLATE_TOO_LARGE", M.tooLarge, path)] };
    return { ok: true, template, issues: [] };
}
const templateGapIds = (t) => t.segments.flatMap(s => (s.kind === "editable" ? [s.id] : []));
exports.templateGapIds = templateGapIds;
const templateStarterValues = (t) => Object.fromEntries(t.segments.flatMap(s => (s.kind === "editable" ? [[s.id, s.starter]] : [])));
exports.templateStarterValues = templateStarterValues;
function reconstructTemplateSource(t, values) {
    let out = "";
    for (const s of t.segments)
        out += s.kind === "locked" ? s.text : values[s.id];
    return out;
}
function normalizeCodeTemplateAnswer(a) {
    if (!isPlain(a) || a.kind !== "codeTemplate" || typeof a.language !== "string" || !isPlain(a.values))
        return { ok: false, code: "CODE_TEMPLATE_ANSWER_INVALID" };
    const def = (0, codingLanguages_1.codingLanguage)(a.language);
    if (!def || a.languageVersion !== def.version)
        return { ok: false, code: "CODE_TEMPLATE_ANSWER_INVALID" };
    const keys = Object.keys(a.values);
    if (keys.length > exports.CODING_TEMPLATE_LIMITS.gaps)
        return { ok: false, code: "CODE_TEMPLATE_ANSWER_INVALID" };
    const values = {};
    for (const k of keys) {
        const v = a.values[k];
        if (!(0, exports.isTemplateGapId)(k))
            return { ok: false, code: "CODE_TEMPLATE_GAP_UNKNOWN" };
        if (typeof v !== "string")
            return { ok: false, code: "CODE_TEMPLATE_ANSWER_INVALID" };
        if ((0, codingLanguages_1.utf8ByteLength)(v) > exports.CODING_TEMPLATE_LIMITS.gapBytes)
            return { ok: false, code: "CODE_TEMPLATE_GAP_TOO_LARGE" };
        values[k] = v;
    }
    return { ok: true, answer: { kind: "codeTemplate", language: a.language, languageVersion: def.version, values } };
}
function bindCodeTemplateAnswer(a, template, sourceLimit) {
    const base = normalizeCodeTemplateAnswer(a);
    if (!base.ok)
        return base;
    if (base.answer.language !== template.language)
        return { ok: false, code: "CODE_LANGUAGE_NOT_ALLOWED" };
    const ids = (0, exports.templateGapIds)(template), given = base.answer.values;
    for (const k of Object.keys(given))
        if (!ids.includes(k))
            return { ok: false, code: "CODE_TEMPLATE_GAP_UNKNOWN" };
    for (const id of ids)
        if (!own(given, id))
            return { ok: false, code: "CODE_TEMPLATE_GAP_MISSING" };
    const values = {};
    for (const id of ids)
        values[id] = given[id];
    const source = reconstructTemplateSource(template, values);
    if ((0, codingLanguages_1.utf8ByteLength)(source) > Math.min(sourceLimit, codingLanguages_1.CODE_SOURCE_MAX_BYTES))
        return { ok: false, code: "CODE_SOURCE_TOO_LARGE" };
    return { ok: true, answer: { ...base.answer, values }, source };
}
const isCodeTemplateAnswered = (a) => isPlain(a) && a.kind === "codeTemplate" && isPlain(a.values) && Object.values(a.values).some(v => typeof v === "string" && v.trim() !== "");
exports.isCodeTemplateAnswered = isCodeTemplateAnswered;
