// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.REFUSED_COMPOSITE_CHILD_TYPES = exports.COMPOSITE_CHILD_IDENTITIES = void 0;
exports.isSupportedCompositeChild = isSupportedCompositeChild;
exports.compositeStructure = compositeStructure;
exports.compositeChildNode = compositeChildNode;
exports.validateCompositeQuestion = validateCompositeQuestion;
exports.projectCompositeContextForStudent = projectCompositeContextForStudent;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const scenarioSource_1 = require("./scenarioSource");
const trustedSimPlugins_1 = require("./trustedSimPlugins");
const compositeModel_1 = require("./compositeModel");
__exportStar(require("./compositeModel"), exports);
exports.COMPOSITE_CHILD_IDENTITIES = Object.freeze([
    "multipleChoice@1", "trueFalse@1", "multiTrueFalse@1", "shortAnswer@1", "fillBlank@1", "wordBank@1", "matching@1", "ordering@1", "tableFill@1", "cliFill@1",
    "multipleSelect@1", "numericResponse@1", "matrix@1", "categorization@1", "simulation@1", "coding@1", "coding@2", "coding@3", "networkCli@1", "inlineCloze@1",
    "parametricNumeric@1", "hotspot@1", "labelDiagram@1", "openResponse@1", "smartSim@1"
]);
const CHILD_IDENTITY_SET = new Set(exports.COMPOSITE_CHILD_IDENTITIES);
exports.REFUSED_COMPOSITE_CHILD_TYPES = Object.freeze(["compound", "composite"]);
function isSupportedCompositeChild(type, version) {
    if (typeof type !== "string" || exports.REFUSED_COMPOSITE_CHILD_TYPES.includes(type) || !(0, questionTypeCatalog_1.isKnownQuestionType)(type) || (0, questionTypeCatalog_1.questionTypeDefinition)(type)?.key !== type)
        return false;
    const v = (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(type, version);
    return v !== undefined && CHILD_IDENTITY_SET.has(type + "@" + v);
}
const ROOT_KEYS = new Set(["v", "contexts", "groups"]);
const SOURCE_CONTEXT_KEYS = new Set(["id", "version", "kind", "title", "instructions", "sources"]);
const SMARTSIM_CONTEXT_KEYS = new Set(["id", "version", "kind", "title", "instructions", "smartSim"]);
const GROUP_KEYS = new Set(["id", "title", "instructions", "gradingPolicy", "requiredAnswers", "maxMarks", "parts"]);
const QUESTION_KEYS = new Set(["examQuestionId", "id", "number", "displayNumber", "presentationType", "type", "questionTypeVersion", "text", "marks", "composite", "answer", "assessmentMeta", "groupId", "activity", "codeStimulus", "image", "images"]);
const PART_COMMON_KEYS = ["id", "label", "type", "questionTypeVersion", "text", "marks", "contextId", "answer", "image", "images", "assessmentMeta"];
const PART_TYPE_KEYS = Object.freeze({
    multipleChoice: ["options"], trueFalse: ["options"], multiTrueFalse: ["fields"], shortAnswer: [], fillBlank: ["fields", "wordBank"], wordBank: ["fields", "wordBank"],
    matching: ["fields", "tableHeaders"], ordering: ["fields", "wordBank"], tableFill: ["fields", "tableHeaders", "tableRows"], cliFill: ["fields", "cli"],
    multipleSelect: ["options"], numericResponse: ["numeric"], matrix: ["matrix"], categorization: ["categorization"], simulation: ["simulation"], coding: ["coding"],
    networkCli: ["networkCli"], inlineCloze: ["inlineCloze"], parametricNumeric: ["parametric"], hotspot: ["hotspot"], labelDiagram: ["labelDiagram"],
    openResponse: ["openResponse"], smartSim: ["smartSim"]
});
const ALL_CONFIG_KEYS = new Set(Object.values(PART_TYPE_KEYS).flat());
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const err = (code, message, path) => (path === undefined ? { code, message, severity: "error" } : { code, message, severity: "error", path });
const ORDINALS = ["أ", "ب", "ج", "د", "هـ", "و", "ز", "ح", "ط", "ي", "ك", "ل", "م", "ن", "س", "ع", "ف", "ص", "ق", "ر", "ش", "ت", "ث", "خ", "ذ", "ض", "ظ", "غ"];
function utf8Bytes(s) {
    let n = 0;
    for (let i = 0; i < s.length; i++) {
        const c = s.charCodeAt(i);
        n += c < 0x80 ? 1 : c < 0x800 ? 2 : c >= 0xd800 && c <= 0xdbff ? (i++, 4) : 3;
    }
    return n;
}
function configBytes(root) {
    try {
        return utf8Bytes(JSON.stringify(root, (k, v) => (k === "dataUrl" && typeof v === "string" && v.startsWith("data:image/") ? "" : v)) ?? "");
    }
    catch {
        return Infinity;
    }
}
const optText = (v, max) => v === undefined || (typeof v === "string" && v.length <= max);
function compositeStructure(node) {
    const shaped = (0, compositeModel_1.compositeShape)(node);
    const issues = shaped.ok ? [] : shaped.issues.map(i => err(i.code, i.message, i.path));
    if (!(0, compositeModel_1.isCompositeQuestionNode)(node) || !isObj(node.composite))
        return { ok: false, issues: issues.length ? issues : [err("COMPOSITE_MISSING", "بنية السؤال المركّب المتقدّم مفقودة.", "composite")] };
    const root = node.composite;
    if ("parts" in node)
        issues.push(err("COMPOSITE_UNKNOWN_KEY", "السؤال المركّب المتقدّم لا يحمل بنودًا قديمة (parts)؛ البنود داخل المجموعات فقط.", "parts"));
    for (const k of Object.keys(root))
        if (!ROOT_KEYS.has(k))
            issues.push(err("COMPOSITE_UNKNOWN_KEY", "حقل غير مسموح في السؤال المركّب: " + k, "composite." + k));
    if (configBytes(root) > compositeModel_1.COMPOSITE_LIMITS.configBytes)
        issues.push(err("COMPOSITE_LIMIT", "حجم بيانات السؤال المركّب يتجاوز الحد المسموح.", "composite"));
    const contexts = [];
    const sourceIds = new Set();
    (Array.isArray(root.contexts) ? root.contexts : []).forEach((c, i) => {
        const path = "composite.contexts[" + i + "]";
        if (!isObj(c))
            return;
        const allowed = c.kind === "source" ? SOURCE_CONTEXT_KEYS : c.kind === "smartSim" ? SMARTSIM_CONTEXT_KEYS : null;
        if (!allowed)
            return;
        for (const k of Object.keys(c))
            if (!allowed.has(k))
                issues.push(err("COMPOSITE_UNKNOWN_KEY", "حقل غير مسموح في السياق المشترك: " + k, path + "." + k));
        if (!optText(c.title, compositeModel_1.COMPOSITE_LIMITS.titleChars) || !optText(c.instructions, compositeModel_1.COMPOSITE_LIMITS.instructionsChars))
            issues.push(err("COMPOSITE_LIMIT", "عنوان السياق أو تعليماته طويلة جدًا أو غير نصية.", path));
        const head = { id: String(c.id), ...(typeof c.title === "string" ? { title: c.title } : {}), ...(typeof c.instructions === "string" ? { instructions: c.instructions } : {}) };
        if (c.kind === "source") {
            const list = c.sources;
            if (!Array.isArray(list) || list.length === 0 || list.length > compositeModel_1.COMPOSITE_LIMITS.sourcesPerContext) {
                issues.push(err("COMPOSITE_SOURCE_INVALID", "مصدر مشترك بلا محتوى أو بعدد يتجاوز الحد (" + compositeModel_1.COMPOSITE_LIMITS.sourcesPerContext + ").", path + ".sources"));
                return;
            }
            const sources = [];
            list.forEach((s, si) => {
                const r = (0, scenarioSource_1.validateSourceStimulus)(s, path + ".sources[" + si + "]");
                if (!r.ok) {
                    issues.push(err("COMPOSITE_SOURCE_INVALID", r.issues.map(x => x.message).join(" — ") || "مصدر غير صالح.", path + ".sources[" + si + "]"));
                    return;
                }
                if (sourceIds.has(r.source.id)) {
                    issues.push(err("COMPOSITE_ID_DUPLICATE", "معرّف مصدر مكرّر: " + r.source.id, path + ".sources[" + si + "].id"));
                    return;
                }
                sourceIds.add(r.source.id);
                sources.push(r.source);
            });
            contexts.push({ ...head, kind: "source", sources });
        }
        else {
            const env = (0, trustedSimPlugins_1.validateSmartSimEnvelope)(c.smartSim);
            if (!env.ok) {
                issues.push(err("COMPOSITE_SMARTSIM_CONTEXT_INVALID", "إعداد المحاكاة المشتركة غير صالح: " + env.issues.map(x => x.message).join(" — "), path + ".smartSim"));
                return;
            }
            contexts.push({ ...head, kind: "smartSim", envelope: env.envelope });
        }
    });
    const contextById = new Map(contexts.map(c => [c.id, c]));
    const groups = [];
    const partById = new Map();
    let ordinal = 0;
    (Array.isArray(root.groups) ? root.groups : []).forEach((g, gi) => {
        const path = "composite.groups[" + gi + "]";
        if (!isObj(g))
            return;
        for (const k of Object.keys(g))
            if (!GROUP_KEYS.has(k))
                issues.push(err("COMPOSITE_UNKNOWN_KEY", "حقل غير مسموح في المجموعة: " + k, path + "." + k));
        if (!optText(g.title, compositeModel_1.COMPOSITE_LIMITS.titleChars) || !optText(g.instructions, compositeModel_1.COMPOSITE_LIMITS.instructionsChars))
            issues.push(err("COMPOSITE_LIMIT", "عنوان المجموعة أو تعليماتها طويلة جدًا أو غير نصية.", path));
        const parts = [];
        (Array.isArray(g.parts) ? g.parts : []).forEach((p, pi) => {
            const pp = path + ".parts[" + pi + "]";
            const index = ordinal++;
            if (!isObj(p))
                return;
            const type = typeof p.type === "string" ? p.type : "";
            if (exports.REFUSED_COMPOSITE_CHILD_TYPES.includes(type)) {
                issues.push(err("COMPOSITE_CHILD_TYPE_REFUSED", "لا يمكن تضمين سؤال مركّب داخل سؤال مركّب.", pp + ".type"));
                return;
            }
            if (!Object.prototype.hasOwnProperty.call(PART_TYPE_KEYS, type)) {
                issues.push(err("COMPOSITE_CHILD_TYPE_UNSUPPORTED", "نوع البند غير مدعوم داخل السؤال المركّب: " + type.slice(0, 40), pp + ".type"));
                return;
            }
            const own = new Set(PART_TYPE_KEYS[type]);
            for (const k of Object.keys(p)) {
                if (PART_COMMON_KEYS.includes(k) || own.has(k))
                    continue;
                issues.push(ALL_CONFIG_KEYS.has(k) ? err("COMPOSITE_CHILD_CONFIG_FOREIGN", "إعداد «" + k + "» لا ينتمي إلى نوع البند «" + type + "».", pp + "." + k) : err("COMPOSITE_UNKNOWN_KEY", "حقل غير مسموح في البند: " + k, pp + "." + k));
            }
            if (!optText(p.label, compositeModel_1.COMPOSITE_LIMITS.labelChars) || !optText(p.text, 20000))
                issues.push(err("COMPOSITE_LIMIT", "تسمية البند أو نصه طويلة جدًا أو غير نصية.", pp));
            const linked = type === "smartSim" && p.contextId !== undefined;
            if (type === "smartSim") {
                if (linked && "smartSim" in p)
                    issues.push(err("COMPOSITE_SMARTSIM_LINKED_ENVELOPE", "بند المحاكاة المرتبط بسياق مشترك يقرأ إعداد السياق فقط؛ لا يحمل إعداد محاكاة خاصًا به.", pp + ".smartSim"));
                if (!linked && !("smartSim" in p))
                    issues.push(err("COMPOSITE_SMARTSIM_CONTEXT_REQUIRED", "بند المحاكاة يحتاج سياق محاكاة مشتركًا أو إعداد محاكاة مستقلًا.", pp));
            }
            if (typeof p.id !== "string" || typeof p.marks !== "number")
                return;
            const label = typeof p.label === "string" && p.label.trim() ? p.label : ORDINALS[index] || String(index + 1);
            const part = { id: p.id, groupId: String(g.id), index, label, type, marks: p.marks, ...(typeof p.contextId === "string" ? { contextId: p.contextId } : {}), linkedSmartSim: linked, raw: p };
            parts.push(part);
            partById.set(part.id, part);
        });
        const sg = shaped.ok ? shaped.shape.groups.find(x => x.id === g.id) : undefined;
        groups.push({ id: String(g.id), ...(typeof g.title === "string" ? { title: g.title } : {}), ...(typeof g.instructions === "string" ? { instructions: g.instructions } : {}), gradingPolicy: g.gradingPolicy === "firstNAnswered" ? "firstNAnswered" : "all", requiredAnswers: sg ? sg.requiredAnswers : null, maxMarks: sg ? sg.maxMarks : null, officialMax: sg ? sg.officialMax : 0, parts });
    });
    if (issues.length || !shaped.ok)
        return { ok: false, issues };
    return { ok: true, model: { officialMax: shaped.shape.officialMax, shape: shaped.shape, contexts, groups, partById, contextById } };
}
function compositeChildNode(part) {
    const { contextId: _ignored, ...rest } = part;
    void _ignored;
    return { ...rest, presentationType: part.type };
}
function validateCompositeQuestion(node) {
    const out = [];
    if ((0, compositeModel_1.compositeQuestionVersion)(node) === undefined)
        out.push(err("UNSUPPORTED_QUESTION_TYPE_VERSION", "إصدار السؤال المركّب المتقدّم غير مدعوم في هذا الإصدار من التطبيق.", "questionTypeVersion"));
    for (const k of Object.keys(node))
        if (!QUESTION_KEYS.has(k) && k !== "parts")
            out.push(err("COMPOSITE_UNKNOWN_KEY", "حقل غير مسموح في السؤال المركّب: " + k, k));
    if (node.examQuestionId !== undefined && !(0, compositeModel_1.isCompositeQuestionId)(node.examQuestionId))
        out.push(err("COMPOSITE_QUESTION_ID_INVALID", "معرّف السؤال المركّب يجب أن يكون من حروف لاتينية وأرقام و . _ : - (حتى 80) دون الفاصل ::part::.", "examQuestionId"));
    if (node.answer !== undefined && !(isObj(node.answer) && Object.keys(node.answer).length === 0))
        out.push(err("COMPOSITE_ANSWER_KEY_FORBIDDEN", "مفاتيح الإجابة تُحفظ في البنود فقط، لا على السؤال المركّب.", "answer"));
    const st = compositeStructure(node);
    if (!st.ok)
        return [...out, ...st.issues.filter(i => !(i.code === "UNSUPPORTED_QUESTION_TYPE_VERSION" && out.some(o => o.code === i.code)))];
    for (const g of st.model.groups)
        for (const p of g.parts) {
            if (!isSupportedCompositeChild(p.type, p.raw.questionTypeVersion)) {
                out.push(err("COMPOSITE_CHILD_TYPE_UNSUPPORTED", "نوع البند «" + p.label + "» أو إصداره غير مدعوم داخل السؤال المركّب: " + p.type + (p.raw.questionTypeVersion !== undefined ? "@" + String(p.raw.questionTypeVersion) : ""), "composite.parts." + p.id));
                continue;
            }
            if (!p.linkedSmartSim)
                continue;
            const ctx = p.contextId ? st.model.contextById.get(p.contextId) : undefined;
            if (!ctx || ctx.kind !== "smartSim")
                continue;
            const env = (0, trustedSimPlugins_1.validateSmartSimEnvelope)(ctx.envelope);
            if (!env.ok)
                continue;
            const key = (0, trustedSimPlugins_1.validateSmartSimAnswerKey)(p.raw.answer, env.plugin, env.envelope.config);
            if (!key.ok)
                out.push(err("COMPOSITE_SMARTSIM_KEY_INVALID", "فحوص البند «" + p.label + "» غير صالحة على المحاكاة المشتركة: " + key.issues.map(i => i.message).join(" — "), "composite.parts." + p.id + ".answer"));
        }
    return out;
}
function projectCompositeContextForStudent(ctx) {
    const head = { id: ctx.id, version: 1, kind: ctx.kind, ...(ctx.title !== undefined ? { title: ctx.title } : {}), ...(ctx.instructions !== undefined ? { instructions: ctx.instructions } : {}) };
    return ctx.kind === "source" ? { ...head, sources: ctx.sources.map(s => ({ ...s })) } : { ...head, smartSim: ctx.envelope };
}
