// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.compositeQuestionVersion = exports.isCompositeQuestionNode = exports.compositeChildKey = exports.isCompositeQuestionId = exports.COMPOSITE_CHILD_SEPARATOR = exports.COMPOSITE_QUESTION_ID = exports.isCompositeId = exports.COMPOSITE_ID = exports.COMPOSITE_GROUP_POLICIES = exports.COMPOSITE_LIMITS = exports.COMPOSITE_CONTEXT_VERSION = exports.COMPOSITE_SCHEMA_VERSION = exports.COMPOSITE_TYPE_KEY = void 0;
exports.parseCompositeChildKey = parseCompositeChildKey;
exports.compositeShape = compositeShape;
exports.compositeOfficialMaxMarks = compositeOfficialMaxMarks;
exports.compositeQuestionMaxMarks = compositeQuestionMaxMarks;
exports.isCompositeAnswerAnswered = isCompositeAnswerAnswered;
exports.selectCompositeCountedParts = selectCompositeCountedParts;
exports.cloneCompositeWithNewIds = cloneCompositeWithNewIds;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const answerState_1 = require("./answerState");
exports.COMPOSITE_TYPE_KEY = "composite";
exports.COMPOSITE_SCHEMA_VERSION = 1;
exports.COMPOSITE_CONTEXT_VERSION = 1;
exports.COMPOSITE_LIMITS = Object.freeze({
    groups: 12, parts: 40, contexts: 8, smartSimContexts: 3, sourceContexts: 6, sourcesPerContext: 8, codingChildren: 4,
    titleChars: 200, instructionsChars: 4000, labelChars: 40, questionIdChars: 80,
    configBytes: 1048576,
    answerBytes: 1048576,
    contextActions: 3000
});
exports.COMPOSITE_GROUP_POLICIES = Object.freeze(["all", "firstNAnswered"]);
exports.COMPOSITE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,39}$/;
const FORBIDDEN_IDS = new Set(["constructor", "prototype", "toString", "toLocaleString", "valueOf", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable", "__proto__", "__defineGetter__", "__defineSetter__", "__lookupGetter__", "__lookupSetter__"]);
const isCompositeId = (v) => typeof v === "string" && exports.COMPOSITE_ID.test(v) && !FORBIDDEN_IDS.has(v);
exports.isCompositeId = isCompositeId;
exports.COMPOSITE_QUESTION_ID = /^[A-Za-z0-9._:-]{1,80}$/;
exports.COMPOSITE_CHILD_SEPARATOR = "::part::";
const isCompositeQuestionId = (v) => typeof v === "string" && exports.COMPOSITE_QUESTION_ID.test(v) && !v.includes(exports.COMPOSITE_CHILD_SEPARATOR);
exports.isCompositeQuestionId = isCompositeQuestionId;
const compositeChildKey = (questionId, partId) => questionId + exports.COMPOSITE_CHILD_SEPARATOR + partId;
exports.compositeChildKey = compositeChildKey;
function parseCompositeChildKey(key) {
    if (typeof key !== "string")
        return null;
    const i = key.lastIndexOf(exports.COMPOSITE_CHILD_SEPARATOR);
    if (i <= 0)
        return null;
    const questionId = key.slice(0, i), partId = key.slice(i + exports.COMPOSITE_CHILD_SEPARATOR.length);
    return (0, exports.isCompositeId)(partId) && (0, exports.isCompositeQuestionId)(questionId) ? { questionId, partId } : null;
}
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const finitePositive = (v) => typeof v === "number" && Number.isFinite(v) && v > 0;
const EPS = 1e-9;
const isCompositeQuestionNode = (q) => isObj(q) && String(q.presentationType ?? q.type ?? "") === exports.COMPOSITE_TYPE_KEY;
exports.isCompositeQuestionNode = isCompositeQuestionNode;
const compositeQuestionVersion = (node) => (isObj(node) ? (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(exports.COMPOSITE_TYPE_KEY, node.questionTypeVersion) : undefined);
exports.compositeQuestionVersion = compositeQuestionVersion;
function compositeShape(node) {
    const issues = [];
    const add = (code, message, path) => { issues.push(path === undefined ? { code, message } : { code, message, path }); };
    if (!(0, exports.isCompositeQuestionNode)(node))
        return { ok: false, issues: [{ code: "COMPOSITE_MISSING", message: "ليس سؤالًا مركّبًا متقدّمًا." }] };
    if ((0, exports.compositeQuestionVersion)(node) !== 1)
        add("UNSUPPORTED_QUESTION_TYPE_VERSION", "إصدار السؤال المركّب المتقدّم غير مدعوم في هذا الإصدار من التطبيق.", "questionTypeVersion");
    const root = node.composite;
    if (!isObj(root)) {
        add("COMPOSITE_MISSING", "بنية السؤال المركّب المتقدّم مفقودة.", "composite");
        return { ok: false, issues };
    }
    if (root.v !== exports.COMPOSITE_SCHEMA_VERSION) {
        add("COMPOSITE_SCHEMA_UNSUPPORTED", "إصدار مخطط السؤال المركّب غير مدعوم (لا يُرقّى تلقائيًا).", "composite.v");
        return { ok: false, issues };
    }
    const seen = new Set();
    const claim = (id, path) => {
        if (!(0, exports.isCompositeId)(id)) {
            add("COMPOSITE_ID_INVALID", "معرّف غير صالح: " + String(id).slice(0, 60), path);
            return false;
        }
        if (seen.has(id)) {
            add("COMPOSITE_ID_DUPLICATE", "معرّف مكرّر داخل السؤال المركّب: " + id, path);
            return false;
        }
        seen.add(id);
        return true;
    };
    const contexts = [];
    if (!Array.isArray(root.contexts))
        add("COMPOSITE_CONTEXT_INVALID", "قائمة السياقات المشتركة غير صالحة.", "composite.contexts");
    else if (root.contexts.length > exports.COMPOSITE_LIMITS.contexts)
        add("COMPOSITE_LIMIT", "عدد السياقات المشتركة يتجاوز الحد (" + exports.COMPOSITE_LIMITS.contexts + ").", "composite.contexts");
    else
        root.contexts.forEach((c, i) => {
            const path = "composite.contexts[" + i + "]";
            if (!isObj(c)) {
                add("COMPOSITE_CONTEXT_INVALID", "سياق مشترك غير صالح.", path);
                return;
            }
            if (c.version !== exports.COMPOSITE_CONTEXT_VERSION || (c.kind !== "source" && c.kind !== "smartSim")) {
                add("COMPOSITE_CONTEXT_INVALID", "نوع السياق أو إصداره غير مدعوم.", path);
                return;
            }
            if (claim(c.id, path + ".id"))
                contexts.push({ id: c.id, kind: c.kind });
        });
    if (contexts.filter(c => c.kind === "smartSim").length > exports.COMPOSITE_LIMITS.smartSimContexts)
        add("COMPOSITE_LIMIT", "عدد سياقات المحاكاة المشتركة يتجاوز الحد (" + exports.COMPOSITE_LIMITS.smartSimContexts + ").", "composite.contexts");
    if (contexts.filter(c => c.kind === "source").length > exports.COMPOSITE_LIMITS.sourceContexts)
        add("COMPOSITE_LIMIT", "عدد مصادر النصوص المشتركة يتجاوز الحد (" + exports.COMPOSITE_LIMITS.sourceContexts + ").", "composite.contexts");
    const contextKind = new Map(contexts.map(c => [c.id, c.kind]));
    const groups = [];
    let totalParts = 0, coding = 0;
    if (!Array.isArray(root.groups) || root.groups.length === 0)
        add("COMPOSITE_GROUPS_EMPTY", "أضف مجموعة واحدة على الأقل إلى السؤال المركّب.", "composite.groups");
    else if (root.groups.length > exports.COMPOSITE_LIMITS.groups)
        add("COMPOSITE_LIMIT", "عدد المجموعات يتجاوز الحد (" + exports.COMPOSITE_LIMITS.groups + ").", "composite.groups");
    else
        root.groups.forEach((g, gi) => {
            const path = "composite.groups[" + gi + "]";
            if (!isObj(g)) {
                add("COMPOSITE_GROUP_INVALID", "مجموعة غير صالحة.", path);
                return;
            }
            const gid = claim(g.id, path + ".id") ? g.id : "";
            const policy = g.gradingPolicy === "all" || g.gradingPolicy === "firstNAnswered" ? g.gradingPolicy : undefined;
            if (!policy)
                add("COMPOSITE_GROUP_POLICY_INVALID", "قاعدة تصحيح المجموعة غير معروفة (جميع البنود أو أول عدد محدد).", path + ".gradingPolicy");
            const parts = [];
            if (!Array.isArray(g.parts) || g.parts.length === 0) {
                add("COMPOSITE_GROUP_EMPTY", "المجموعة «" + String(g.title ?? gid) + "» بلا بنود.", path + ".parts");
            }
            else
                g.parts.forEach((p, pi) => {
                    const pp = path + ".parts[" + pi + "]";
                    totalParts++;
                    if (!isObj(p)) {
                        add("COMPOSITE_PART_INVALID", "بند غير صالح.", pp);
                        return;
                    }
                    const pid = claim(p.id, pp + ".id") ? p.id : "";
                    if (!finitePositive(p.marks))
                        add("COMPOSITE_PART_MARKS_INVALID", "علامة البند يجب أن تكون عددًا موجبًا.", pp + ".marks");
                    if (typeof p.type !== "string")
                        add("COMPOSITE_CHILD_TYPE_UNSUPPORTED", "نوع البند مفقود.", pp + ".type");
                    if (p.type === "coding")
                        coding++;
                    if (p.contextId !== undefined) {
                        if (typeof p.contextId !== "string" || !contextKind.has(p.contextId))
                            add("COMPOSITE_CONTEXT_REF_DANGLING", "البند يشير إلى سياق مشترك غير موجود.", pp + ".contextId");
                        else if (p.type === "smartSim" && contextKind.get(p.contextId) !== "smartSim")
                            add("COMPOSITE_CONTEXT_REF_KIND", "بند المحاكاة يرتبط بسياق محاكاة مشترك فقط.", pp + ".contextId");
                    }
                    if (pid && finitePositive(p.marks) && typeof p.type === "string")
                        parts.push({ id: pid, type: p.type, marks: p.marks, groupId: gid, ...(typeof p.contextId === "string" ? { contextId: p.contextId } : {}) });
                });
            let officialMax = parts.reduce((s, p) => s + p.marks, 0), requiredAnswers = null, maxMarks = null;
            if (policy === "all") {
                if ((g.requiredAnswers !== null && g.requiredAnswers !== undefined) || (g.maxMarks !== null && g.maxMarks !== undefined))
                    add("COMPOSITE_GROUP_POLICY_INVALID", "مجموعة «جميع البنود» لا تحمل عددًا مطلوبًا ولا حدًّا أقصى.", path);
            }
            else if (policy === "firstNAnswered") {
                const n = g.requiredAnswers, partCount = Array.isArray(g.parts) ? g.parts.length : 0;
                const marks = parts.map(p => p.marks);
                const equal = marks.length > 0 && marks.every(m => Math.abs(m - marks[0]) <= EPS);
                if (typeof n !== "number" || !Number.isInteger(n) || n < 1 || n > partCount)
                    add("COMPOSITE_FIRSTN_INVALID", "عدد الإجابات المطلوبة في المجموعة يجب أن يكون عددًا صحيحًا بين 1 وعدد البنود.", path + ".requiredAnswers");
                else if (!finitePositive(g.maxMarks))
                    add("COMPOSITE_FIRSTN_INVALID", "مجموعة «أول عدد محدد» تحتاج علامة قصوى صريحة.", path + ".maxMarks");
                else if (!equal)
                    add("COMPOSITE_FIRSTN_INVALID", "بنود مجموعة «أول عدد محدد» يجب أن تحمل علامات متساوية.", path + ".parts");
                else if (Math.abs(g.maxMarks - n * marks[0]) > EPS)
                    add("COMPOSITE_FIRSTN_INVALID", "العلامة القصوى للمجموعة يجب أن تساوي عدد الإجابات المطلوبة × علامة البند.", path + ".maxMarks");
                else {
                    requiredAnswers = n;
                    maxMarks = g.maxMarks;
                    officialMax = g.maxMarks;
                }
                if (Array.isArray(g.parts) && g.parts.some(p => isObj(p) && p.type === "smartSim" && p.contextId !== undefined))
                    add("COMPOSITE_FIRSTN_SHARED_SMARTSIM", "بنود المحاكاة المرتبطة بسياق مشترك غير مسموحة في مجموعة «أول عدد محدد».", path);
            }
            if (gid && policy)
                groups.push({ id: gid, gradingPolicy: policy, requiredAnswers, maxMarks, officialMax, parts });
        });
    if (totalParts > exports.COMPOSITE_LIMITS.parts)
        add("COMPOSITE_LIMIT", "عدد البنود يتجاوز الحد (" + exports.COMPOSITE_LIMITS.parts + ").", "composite.groups");
    if (coding > exports.COMPOSITE_LIMITS.codingChildren)
        add("COMPOSITE_LIMIT", "عدد بنود البرمجة يتجاوز الحد (" + exports.COMPOSITE_LIMITS.codingChildren + ").", "composite.groups");
    if (issues.length)
        return { ok: false, issues };
    const officialMax = groups.reduce((s, g) => s + g.officialMax, 0);
    if (!finitePositive(node.marks) || Math.abs(node.marks - officialMax) > EPS)
        return { ok: false, issues: [{ code: "COMPOSITE_MARKS_MISMATCH", message: "علامة السؤال (" + String(node.marks) + ") لا تساوي مجموع العلامات الرسمية للمجموعات (" + officialMax + ").", path: "marks" }] };
    return { ok: true, shape: { groups, contexts, officialMax } };
}
function compositeOfficialMaxMarks(node) {
    const s = compositeShape(node);
    return s.ok ? s.shape.officialMax : undefined;
}
function compositeQuestionMaxMarks(node) {
    const m = compositeOfficialMaxMarks(node);
    if (m !== undefined)
        return m;
    const n = Number(node.marks ?? node.points);
    return Number.isFinite(n) ? Math.max(0, n) : 0;
}
function isCompositeAnswerAnswered(a) {
    if (!isObj(a) || a.kind !== "composite")
        return false;
    const parts = isObj(a.parts) ? Object.values(a.parts) : [], contexts = isObj(a.contexts) ? Object.values(a.contexts) : [];
    return parts.some(p => (0, answerState_1.answered)(p)) || contexts.some(c => (0, answerState_1.answered)(c));
}
const partAnswerOf = (a, pid) => (isObj(a) && a.kind === "composite" && isObj(a.parts) && Object.prototype.hasOwnProperty.call(a.parts, pid) ? a.parts[pid] : undefined);
function selectCompositeCountedParts(node, answer) {
    const out = new Map();
    const s = compositeShape(node);
    if (!s.ok)
        return out;
    for (const g of s.shape.groups) {
        let taken = 0;
        for (const p of g.parts) {
            const isAnswered = (0, answerState_1.answered)(partAnswerOf(answer, p.id));
            if (g.gradingPolicy !== "firstNAnswered") {
                out.set(p.id, { counted: true, answered: isAnswered, ignored: false });
                continue;
            }
            if (isAnswered && taken < g.requiredAnswers) {
                taken++;
                out.set(p.id, { counted: true, answered: true, ignored: false });
            }
            else
                out.set(p.id, isAnswered ? { counted: false, answered: true, ignored: true } : { counted: false, answered: false, ignored: false });
        }
    }
    return out;
}
function cloneCompositeWithNewIds(root, newId) {
    const copy = JSON.parse(JSON.stringify(root ?? null));
    if (!isObj(copy))
        return copy;
    const ctxMap = new Map();
    if (Array.isArray(copy.contexts))
        for (const c of copy.contexts)
            if (isObj(c) && typeof c.id === "string") {
                const id = newId("ctx");
                ctxMap.set(c.id, id);
                c.id = id;
            }
    if (Array.isArray(copy.groups))
        for (const g of copy.groups) {
            if (!isObj(g))
                continue;
            g.id = newId("g");
            if (Array.isArray(g.parts))
                for (const p of g.parts) {
                    if (!isObj(p))
                        continue;
                    p.id = newId("p");
                    if (typeof p.contextId === "string" && ctxMap.has(p.contextId))
                        p.contextId = ctxMap.get(p.contextId);
                }
        }
    return copy;
}
