// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.examHasQuestions = exports.isStructuredExam = exports.GRADING_POLICY_LABELS = exports.QUESTION_TYPE_LABELS = exports.BUILDER_PART_TYPES = exports.BUILDER_QUESTION_TYPES = void 0;
exports.examQuestionCount = examQuestionCount;
exports.BUILDER_QUESTION_TYPES = Object.freeze([
    "multipleChoice", "trueFalse", "multiTrueFalse", "shortAnswer", "fillBlank", "wordBank", "matching", "ordering", "tableFill", "cliFill", "compound",
]);
exports.BUILDER_PART_TYPES = Object.freeze(exports.BUILDER_QUESTION_TYPES.filter((t) => t !== "compound"));
exports.QUESTION_TYPE_LABELS = {
    multipleChoice: "اختيار من متعدد",
    trueFalse: "صح أو خطأ",
    multiTrueFalse: "صح/خطأ متعدد",
    shortAnswer: "إجابة قصيرة / مفتوحة",
    fillBlank: "إكمال فراغات",
    wordBank: "مخزن كلمات",
    matching: "مطابقة",
    ordering: "ترتيب",
    tableFill: "إكمال جدول",
    cliFill: "أوامر CLI",
    compound: "سؤال مركّب"
};
exports.GRADING_POLICY_LABELS = {
    all: "تصحيح جميع الأسئلة",
    capScore: "تصحيح الإجابات مع سقف للعلامة",
    firstNAnswered: "تصحيح أول عدد محدد من الإجابات"
};
const isStructuredExam = (exam) => !!exam && typeof exam === "object" && Array.isArray(exam.sections);
exports.isStructuredExam = isStructuredExam;
function examQuestionCount(exam) {
    if (!exam || typeof exam !== "object")
        return 0;
    const e = exam;
    if (Array.isArray(e.sections)) {
        return e.sections.reduce((n, s) => n + (Array.isArray(s.questions) ? s.questions.length : 0), 0);
    }
    return Array.isArray(e.questions) ? e.questions.length : 0;
}
const examHasQuestions = (exam) => examQuestionCount(exam) > 0;
exports.examHasQuestions = examHasQuestions;
