// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.THEME_LABELS = exports.EXAM_THEMES = void 0;
exports.normalizeExamTheme = normalizeExamTheme;
exports.clampFocusIndex = clampFocusIndex;
exports.nextFocusIndex = nextFocusIndex;
exports.previousFocusIndex = previousFocusIndex;
exports.focusProgressPercent = focusProgressPercent;
exports.EXAM_THEMES = ["default", "cards", "classic", "focus", "compact", "modern"];
exports.THEME_LABELS = {
    default: { name: "الافتراضي", description: "الشكل الحالي للامتحان" },
    cards: { name: "بطاقات", description: "كل سؤال يظهر داخل بطاقة مستقلة" },
    classic: { name: "ورقة امتحان", description: "شكل قريب من الامتحان الورقي التقليدي" },
    focus: { name: "تركيز", description: "سؤال واحد فقط في كل مرة" },
    compact: { name: "مدمج", description: "مساحات أقل، رؤية أسئلة أكثر" },
    modern: { name: "حديث", description: "واجهة عصرية ومريحة" }
};
function normalizeExamTheme(value) {
    return typeof value === "string" && exports.EXAM_THEMES.includes(value)
        ? value
        : "default";
}
function clampFocusIndex(index, total) {
    if (total <= 0) {
        return 0;
    }
    return Math.min(Math.max(index, 0), total - 1);
}
function nextFocusIndex(current, total) {
    return clampFocusIndex(current + 1, total);
}
function previousFocusIndex(current, total) {
    return clampFocusIndex(current - 1, total);
}
function focusProgressPercent(index, total) {
    if (total <= 0) {
        return 0;
    }
    return Math.round(((clampFocusIndex(index, total) + 1) / total) * 100);
}
