// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.unitKey = exports.isAnswerUnitAnswered = exports.isCompound = exports.questionParts = exports.partLabel = exports.fieldId = exports.partId = exports.sectionQuestionId = exports.questionId = void 0;
exports.distributePartMarks = distributePartMarks;
exports.questionMaxMarks = questionMaxMarks;
exports.normalizeExamStructure = normalizeExamStructure;
exports.getAnswerUnits = getAnswerUnits;
exports.selectGradedUnits = selectGradedUnits;
exports.calculateSectionProgress = calculateSectionProgress;
const answerState_1 = require("./answerState");
const POLICIES = ["all", "capScore", "firstNAnswered"];
const questionId = (q, i) => String(q?.examQuestionId ?? q?.id ?? q?.number ?? i + 1);
exports.questionId = questionId;
const sectionQuestionId = (section, q, i) => {
    if (q && q.examQuestionId != null && q.examQuestionId !== "")
        return String(q.examQuestionId);
    if (q && q.id != null && q.id !== "")
        return String(q.id);
    if (section && section.id && section.id !== "__default__")
        return section.id + "::q" + (i + 1);
    return String((q && q.number) || i + 1);
};
exports.sectionQuestionId = sectionQuestionId;
const partId = (p, i) => String(p?.id ?? i + 1);
exports.partId = partId;
const fieldId = (f, i) => String(f?.id ?? f?.number ?? i + 1);
exports.fieldId = fieldId;
const ARABIC_ORDINALS = ["أ", "ب", "ج", "د", "هـ", "و", "ز", "ح", "ط", "ي", "ك", "ل", "م", "ن", "س", "ع", "ف", "ص", "ق", "ر", "ش", "ت", "ث", "خ", "ذ", "ض", "ظ", "غ"];
const partLabel = (part, i) => part && part.label != null && String(part.label).trim() !== "" ? String(part.label) : (ARABIC_ORDINALS[i] || String(i + 1));
exports.partLabel = partLabel;
const num = (v, fallback = 0) => {
    const n = Number(v);
    return Number.isFinite(n) ? n : fallback;
};
const questionParts = (q) => (Array.isArray(q?.parts) ? q.parts : []);
exports.questionParts = questionParts;
const isCompound = (q) => (0, exports.questionParts)(q).length > 0;
exports.isCompound = isCompound;
function distributePartMarks(q) {
    const parts = (0, exports.questionParts)(q);
    if (!parts.length)
        return [];
    const total = num(q?.marks, 0);
    const hasMark = parts.map(p => p && p.marks != null && Number.isFinite(Number(p.marks)));
    if (hasMark.every(Boolean))
        return parts.map(p => num(p.marks));
    if (!hasMark.some(Boolean)) {
        const each = total / parts.length;
        return parts.map(() => each);
    }
    const known = parts.reduce((s, p, i) => s + (hasMark[i] ? num(p.marks) : 0), 0);
    const restCount = hasMark.filter(x => !x).length;
    const each = restCount ? Math.max(0, total - known) / restCount : 0;
    return parts.map((p, i) => (hasMark[i] ? num(p.marks) : each));
}
function questionMaxMarks(q) {
    if ((0, exports.isCompound)(q)) {
        return distributePartMarks(q).reduce((s, m) => s + Math.max(0, num(m, 0)), 0);
    }
    const raw = q;
    return Math.max(0, num(raw.marks != null ? raw.marks : raw.points, 0));
}
const isAnswerUnitAnswered = (a) => (0, answerState_1.answered)(a);
exports.isAnswerUnitAnswered = isAnswerUnitAnswered;
function normalizeSection(s, si) {
    const policy = POLICIES.includes(s?.gradingPolicy)
        ? s.gradingPolicy
        : "all";
    return {
        id: String(s?.id ?? "section-" + (si + 1)),
        title: String(s?.title ?? ""),
        instructions: String(s?.instructions ?? ""),
        maxMarks: s?.maxMarks == null ? null : num(s.maxMarks),
        gradingPolicy: policy,
        requiredAnswers: s?.requiredAnswers == null ? null : Math.max(0, Math.floor(num(s.requiredAnswers))),
        answerUnit: s?.answerUnit === "part" ? "part" : "question",
        stimuli: s && s.stimuli && typeof s.stimuli === "object" ? s.stimuli : null,
        questions: Array.isArray(s?.questions) ? s.questions : []
    };
}
function normalizeExamStructure(exam) {
    const ex = exam || {};
    if (Array.isArray(ex.sections) && ex.sections.length) {
        return { structured: true, sections: ex.sections.map(normalizeSection) };
    }
    return {
        structured: false,
        sections: [
            {
                id: "__default__",
                title: "",
                instructions: "",
                maxMarks: null,
                gradingPolicy: "all",
                requiredAnswers: null,
                answerUnit: "question",
                stimuli: null,
                questions: Array.isArray(ex.questions) ? ex.questions : []
            }
        ]
    };
}
const unitKey = (u) => u.partId ? u.questionId + "::" + u.partId : u.questionId;
exports.unitKey = unitKey;
function getAnswerUnits(section, answers) {
    const units = [];
    section.questions.forEach((q, qi) => {
        const qid = (0, exports.sectionQuestionId)(section, q, qi);
        const resp = answers ? answers[qid] : undefined;
        if (section.answerUnit === "part" && (0, exports.isCompound)(q)) {
            (0, exports.questionParts)(q).forEach((p, pi) => {
                const pid = (0, exports.partId)(p, pi);
                const pans = resp && resp.kind === "compound" ? resp.parts?.[pid] : undefined;
                units.push({ questionId: qid, partId: pid, answered: (0, exports.isAnswerUnitAnswered)(pans) });
            });
        }
        else {
            units.push({ questionId: qid, partId: null, answered: (0, exports.isAnswerUnitAnswered)(resp) });
        }
    });
    return units;
}
function selectGradedUnits(section, answers) {
    const units = getAnswerUnits(section, answers);
    if (section.gradingPolicy !== "firstNAnswered" || section.requiredAnswers == null) {
        return { countedKeys: new Set(units.map(exports.unitKey)), units };
    }
    const countedKeys = new Set();
    let taken = 0;
    for (const u of units) {
        if (taken >= section.requiredAnswers)
            break;
        if (u.answered) {
            countedKeys.add((0, exports.unitKey)(u));
            taken++;
        }
    }
    return { countedKeys, units };
}
function calculateSectionProgress(section, answers) {
    const units = getAnswerUnits(section, answers);
    const total = units.length;
    const answeredCount = units.filter(u => u.answered).length;
    const required = section.gradingPolicy === "firstNAnswered" ? section.requiredAnswers : null;
    const excess = required != null ? Math.max(0, answeredCount - required) : 0;
    return {
        total,
        answered: answeredCount,
        required,
        counted: required != null ? Math.min(answeredCount, required) : answeredCount,
        excess,
        gradingPolicy: section.gradingPolicy,
        maxMarks: section.maxMarks
    };
}
