// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.evaluateFunctionAt = exports.FUNCTION_STUDY_TASKS = exports.FUNCTION_STUDY_LIMITS = exports.FUNCTION_STUDY_CONFIG_VERSION = exports.FUNCTION_STUDY_PLUGIN_VERSION = exports.FUNCTION_STUDY_PLUGIN_KEY = void 0;
exports.compileFunction = compileFunction;
exports.validateFunctionStudyConfig = validateFunctionStudyConfig;
exports.sampleFunction = sampleFunction;
const parametricEngine_1 = require("./parametricEngine");
const trustedSimVocabulary_1 = require("./trustedSimVocabulary");
exports.FUNCTION_STUDY_PLUGIN_KEY = "functionStudy2d";
exports.FUNCTION_STUDY_PLUGIN_VERSION = 1;
exports.FUNCTION_STUDY_CONFIG_VERSION = 1;
exports.FUNCTION_STUDY_LIMITS = Object.freeze({ sampleMin: 50, sampleMax: 2000, xAbsMax: 10000, yAbsMax: 1e6, sourceChars: parametricEngine_1.PARAMETRIC_LIMITS.expressionChars, items: 20, valueAbsMax: 1e6, toleranceMax: 1000 });
exports.FUNCTION_STUDY_TASKS = Object.freeze(["domainExclusions", "xIntercepts", "yIntercept", "verticalAsymptotes", "horizontalAsymptotes", "extrema", "monotonicIntervals"]);
const L = exports.FUNCTION_STUDY_LIMITS;
const ROOT_KEYS = ["v", "expression", "window", "tasks"];
const WINDOW_KEYS = ["xMin", "xMax", "yMin", "yMax", "sampleCount"];
const exactKeys = (o, keys) => Object.keys(o).length === keys.length && keys.every(k => Object.prototype.hasOwnProperty.call(o, k));
const finiteIn = (v, max) => typeof v === "number" && Number.isFinite(v) && Math.abs(v) <= max;
function compileFunction(source) {
    if (typeof source !== "string" || !source.trim())
        return { ok: false, code: "FUNCSTUDY_EXPRESSION_EMPTY" };
    const p = (0, parametricEngine_1.parseExpression)(source, { language: 2 });
    if (!p.ok)
        return { ok: false, code: p.code };
    if (p.refs.some(r => r !== "x"))
        return { ok: false, code: "FUNCSTUDY_VARIABLE_UNDECLARED" };
    return { ok: true, ast: p.ast };
}
const evaluateFunctionAt = (ast, x) => (0, parametricEngine_1.evaluateExpression)(ast, new Map([["x", x]]));
exports.evaluateFunctionAt = evaluateFunctionAt;
function validateFunctionStudyConfig(raw) {
    const issues = [];
    const add = (code, message, path) => { issues.push({ code, message, path }); };
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw))
        return { ok: false, issues: [{ code: "FUNCSTUDY_CONFIG_INVALID", message: "إعداد دراسة الدالة مفقود أو غير صالح.", path: "smartSim.config" }] };
    for (const k of Object.keys(raw))
        if (!ROOT_KEYS.includes(k))
            add("FUNCSTUDY_CONFIG_UNKNOWN_KEY", "حقل غير مسموح في إعداد دراسة الدالة: " + k, "smartSim.config." + k);
    if (raw.v !== exports.FUNCTION_STUDY_CONFIG_VERSION)
        add("FUNCSTUDY_CONFIG_VERSION_UNSUPPORTED", "إصدار إعداد دراسة الدالة غير مدعوم.", "smartSim.config.v");
    let expression;
    const e = raw.expression;
    if (!(0, trustedSimVocabulary_1.isPlainObject)(e) || !exactKeys(e, ["language", "variable", "source"]) || e.language !== 2 || e.variable !== "x" || typeof e.source !== "string" || e.source.length > L.sourceChars)
        add("FUNCSTUDY_EXPRESSION_INVALID", "الدالة يجب أن تُكتب بلغة التعابير الآمنة (الإصدار 2) بالمتغير x فقط، حتى " + L.sourceChars + " حرف.", "smartSim.config.expression");
    else {
        const c = compileFunction(e.source);
        if (!c.ok)
            add("FUNCSTUDY_EXPRESSION_INVALID", "تعذّر قراءة الدالة (" + c.code + "): استخدم x والأعداد و + − × ÷ ^ والدوال المسموحة فقط.", "smartSim.config.expression.source");
        else
            expression = { language: 2, variable: "x", source: e.source };
    }
    let win;
    const w = raw.window;
    if (!(0, trustedSimVocabulary_1.isPlainObject)(w) || !exactKeys(w, WINDOW_KEYS) || !finiteIn(w.xMin, L.xAbsMax) || !finiteIn(w.xMax, L.xAbsMax) || !finiteIn(w.yMin, L.yAbsMax) || !finiteIn(w.yMax, L.yAbsMax)
        || w.xMin >= w.xMax || w.yMin >= w.yMax || typeof w.sampleCount !== "number" || !Number.isInteger(w.sampleCount) || w.sampleCount < L.sampleMin || w.sampleCount > L.sampleMax)
        add("FUNCSTUDY_WINDOW_INVALID", "نافذة الرسم غير صالحة: xMin < xMax ضمن ±" + L.xAbsMax + "، yMin < yMax، وعدد العينات عدد صحيح من " + L.sampleMin + " إلى " + L.sampleMax + ".", "smartSim.config.window");
    else
        win = { xMin: w.xMin, xMax: w.xMax, yMin: w.yMin, yMax: w.yMax, sampleCount: w.sampleCount };
    let tasks;
    const t = raw.tasks;
    if (!(0, trustedSimVocabulary_1.isPlainObject)(t) || !exactKeys(t, exports.FUNCTION_STUDY_TASKS) || !exports.FUNCTION_STUDY_TASKS.every(k => typeof t[k] === "boolean"))
        add("FUNCSTUDY_TASKS_INVALID", "مهام التحليل غير صالحة (مفاتيح محددة بقيم صح/خطأ).", "smartSim.config.tasks");
    else if (!exports.FUNCTION_STUDY_TASKS.some(k => t[k] === true))
        add("FUNCSTUDY_TASKS_EMPTY", "فعّل مهمة تحليل واحدة على الأقل.", "smartSim.config.tasks");
    else {
        const out = {};
        for (const k of exports.FUNCTION_STUDY_TASKS)
            out[k] = t[k];
        tasks = out;
    }
    if (issues.length || !expression || !win || !tasks)
        return { ok: false, issues };
    return { ok: true, config: { v: exports.FUNCTION_STUDY_CONFIG_VERSION, expression, window: win, tasks } };
}
function sampleFunction(config) {
    const c = compileFunction(config.expression.source);
    if (!c.ok)
        return { segments: [], evaluated: 0 };
    const { xMin, xMax, yMin, yMax, sampleCount } = config.window;
    const n = Math.max(L.sampleMin, Math.min(L.sampleMax, Math.floor(sampleCount)));
    const height = yMax - yMin;
    const segments = [];
    let current = [];
    const flush = () => { if (current.length)
        segments.push(current); current = []; };
    for (let i = 0; i < n; i++) {
        const x = xMin + (i * (xMax - xMin)) / (n - 1);
        const r = (0, exports.evaluateFunctionAt)(c.ast, x);
        if (!r.ok) {
            flush();
            continue;
        }
        const prev = current.length ? current[current.length - 1] : undefined;
        if (prev && Math.abs(r.value - prev.y) > height) {
            const mid = (0, exports.evaluateFunctionAt)(c.ast, (prev.x + x) / 2);
            const lo = Math.min(prev.y, r.value), hi = Math.max(prev.y, r.value);
            if (!mid.ok || mid.value < lo || mid.value > hi)
                flush();
        }
        current.push({ x, y: r.value });
    }
    flush();
    return { segments, evaluated: n };
}
