// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.functionStudy2dPluginV1 = exports.FUNCTION_STUDY_DESCRIPTOR_V1 = exports.FUNCTION_STUDY_CHECK_KINDS = exports.initialFunctionStudyState = exports.FUNCTION_STUDY_ACTION_KINDS = exports.FUNCTION_STUDY_MAX_ACTIONS = exports.FUNCTION_STUDY_STATE_VERSION = exports.FUNCTION_STUDY_LABEL = void 0;
exports.normalizeFunctionStudyAction = normalizeFunctionStudyAction;
exports.replayFunctionStudy = replayFunctionStudy;
exports.validateFunctionStudyCheck = validateFunctionStudyCheck;
exports.evaluateFunctionStudyCheck = evaluateFunctionStudyCheck;
const functionStudyModel_1 = require("./functionStudyModel");
const trustedSimVocabulary_1 = require("./trustedSimVocabulary");
exports.FUNCTION_STUDY_LABEL = "دراسة دالة (رياضيات)";
exports.FUNCTION_STUDY_STATE_VERSION = 1;
exports.FUNCTION_STUDY_MAX_ACTIONS = 300;
const ACTIONS = Object.freeze({
    "domain.setExclusions": ["domainExclusions", "values"],
    "intercepts.setX": ["xIntercepts", "points"],
    "intercept.setY": ["yIntercept", "y"],
    "asymptotes.setVertical": ["verticalAsymptotes", "values"],
    "asymptotes.setHorizontal": ["horizontalAsymptotes", "values"],
    "extrema.set": ["extrema", "points"],
    "intervals.set": ["monotonicIntervals", "intervals"]
});
exports.FUNCTION_STUDY_ACTION_KINDS = Object.freeze(Object.keys(ACTIONS));
const L = functionStudyModel_1.FUNCTION_STUDY_LIMITS;
const exactKeys = (o, keys) => Object.keys(o).length === keys.length && keys.every(k => Object.prototype.hasOwnProperty.call(o, k));
const num = (v) => typeof v === "number" && Number.isFinite(v) && Math.abs(v) <= L.valueAbsMax;
const z = (v) => (v === 0 ? 0 : v);
const list = (raw, item, sameItem) => {
    if (!Array.isArray(raw) || raw.length > L.items)
        return undefined;
    const out = [];
    for (const r of raw) {
        const v = item(r);
        if (v === undefined || out.some(o => sameItem(o, v)))
            return undefined;
        out.push(v);
    }
    return out;
};
const numbers = (raw) => list(raw, v => (num(v) ? z(v) : undefined), (a, b) => a === b);
const point = (v) => ((0, trustedSimVocabulary_1.isPlainObject)(v) && exactKeys(v, ["x", "y"]) && num(v.x) && num(v.y) ? { x: z(v.x), y: z(v.y) } : undefined);
const points = (raw) => list(raw, point, (a, b) => a.x === b.x);
const extremum = (v) => ((0, trustedSimVocabulary_1.isPlainObject)(v) && exactKeys(v, ["kind", "x", "y"]) && (v.kind === "min" || v.kind === "max") && num(v.x) && num(v.y) ? { kind: v.kind, x: z(v.x), y: z(v.y) } : undefined);
const extremaList = (raw) => list(raw, extremum, (a, b) => a.x === b.x);
function interval(v) {
    if (!(0, trustedSimVocabulary_1.isPlainObject)(v) || !exactKeys(v, ["kind", "from", "to"]) || (v.kind !== "increasing" && v.kind !== "decreasing"))
        return undefined;
    const from = v.from === "-inf" ? "-inf" : num(v.from) ? z(v.from) : undefined;
    const to = v.to === "+inf" ? "+inf" : num(v.to) ? z(v.to) : undefined;
    if (from === undefined || to === undefined || (typeof from === "number" && typeof to === "number" && !(from < to)))
        return undefined;
    return { kind: v.kind, from, to };
}
const intervals = (raw) => list(raw, interval, (a, b) => a.from === b.from && a.to === b.to);
function normalizeFunctionStudyAction(raw, config) {
    const bad = { ok: false, code: "FUNCSTUDY_ACTION_INVALID" };
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw) || typeof raw.type !== "string" || !Object.prototype.hasOwnProperty.call(ACTIONS, raw.type))
        return bad;
    const [task, field] = ACTIONS[raw.type];
    if (config.tasks[task] !== true || !exactKeys(raw, ["type", field]))
        return bad;
    const p = raw[field];
    switch (raw.type) {
        case "domain.setExclusions":
        case "asymptotes.setVertical":
        case "asymptotes.setHorizontal": {
            const v = numbers(p);
            return v ? { ok: true, action: { type: raw.type, values: v } } : bad;
        }
        case "intercepts.setX": {
            const v = points(p);
            return v ? { ok: true, action: { type: "intercepts.setX", points: v } } : bad;
        }
        case "intercept.setY": return p === null ? { ok: true, action: { type: "intercept.setY", y: null } } : num(p) ? { ok: true, action: { type: "intercept.setY", y: z(p) } } : bad;
        case "extrema.set": {
            const v = extremaList(p);
            return v ? { ok: true, action: { type: "extrema.set", points: v } } : bad;
        }
        case "intervals.set": {
            const v = intervals(p);
            return v ? { ok: true, action: { type: "intervals.set", intervals: v } } : bad;
        }
    }
    return bad;
}
const initialFunctionStudyState = () => ({ v: exports.FUNCTION_STUDY_STATE_VERSION, domainExclusions: [], xIntercepts: [], yIntercept: null, verticalAsymptotes: [], horizontalAsymptotes: [], extrema: [], monotonicIntervals: [] });
exports.initialFunctionStudyState = initialFunctionStudyState;
const startKey = (e) => (e === "-inf" ? -Infinity : e === "+inf" ? Infinity : e);
const asc = (a, b) => a - b;
const byInterval = (a, b) => startKey(a.from) - startKey(b.from) || startKey(a.to) - startKey(b.to);
function applyAction(s, a) {
    const n = { ...s };
    switch (a.type) {
        case "domain.setExclusions":
            n.domainExclusions = [...a.values].sort(asc);
            break;
        case "asymptotes.setVertical":
            n.verticalAsymptotes = [...a.values].sort(asc);
            break;
        case "asymptotes.setHorizontal":
            n.horizontalAsymptotes = [...a.values].sort(asc);
            break;
        case "intercepts.setX":
            n.xIntercepts = a.points.map(p => ({ x: p.x, y: p.y })).sort((p, q) => p.x - q.x);
            break;
        case "intercept.setY":
            n.yIntercept = a.y === null ? null : { x: 0, y: a.y };
            break;
        case "extrema.set":
            n.extrema = a.points.map(p => ({ kind: p.kind, x: p.x, y: p.y })).sort((p, q) => p.x - q.x);
            break;
        case "intervals.set":
            n.monotonicIntervals = a.intervals.map(i => ({ kind: i.kind, from: i.from, to: i.to })).sort(byInterval);
            break;
    }
    return n;
}
const canonical = (s) => ({
    v: exports.FUNCTION_STUDY_STATE_VERSION, domainExclusions: [...s.domainExclusions], xIntercepts: s.xIntercepts.map(p => ({ x: p.x, y: p.y })), yIntercept: s.yIntercept ? { x: 0, y: s.yIntercept.y } : null,
    verticalAsymptotes: [...s.verticalAsymptotes], horizontalAsymptotes: [...s.horizontalAsymptotes], extrema: s.extrema.map(p => ({ kind: p.kind, x: p.x, y: p.y })),
    monotonicIntervals: s.monotonicIntervals.map(i => ({ kind: i.kind, from: i.from, to: i.to }))
});
function replayFunctionStudy(config, rawActions) {
    if (!Array.isArray(rawActions) || rawActions.length > exports.FUNCTION_STUDY_MAX_ACTIONS)
        return { ok: false, code: "FUNCSTUDY_ACTIONS_TOO_MANY" };
    const actions = [];
    let s = (0, exports.initialFunctionStudyState)();
    for (const raw of rawActions) {
        const r = normalizeFunctionStudyAction(raw, config);
        if (!r.ok)
            return r;
        actions.push(r.action);
        s = applyAction(s, r.action);
    }
    return { ok: true, actions, state: canonical(s) };
}
const nonEmpty = (f) => (v) => { const r = f(v); return r && r.length ? r : undefined; };
const CHECKS = Object.freeze({
    "domain.exclusions": { task: "domainExclusions", parse: nonEmpty(numbers) },
    "intercepts.x": { task: "xIntercepts", parse: nonEmpty(points) },
    "intercept.y": { task: "yIntercept", parse: v => (num(v) ? [z(v)] : undefined) },
    "asymptotes.vertical": { task: "verticalAsymptotes", parse: nonEmpty(numbers) },
    "asymptotes.horizontal": { task: "horizontalAsymptotes", parse: nonEmpty(numbers) },
    "extrema.points": { task: "extrema", parse: nonEmpty(extremaList) },
    "monotonic.intervals": { task: "monotonicIntervals", parse: nonEmpty(intervals) }
});
exports.FUNCTION_STUDY_CHECK_KINDS = Object.freeze(Object.keys(CHECKS));
function validateFunctionStudyCheck(raw, config) {
    const fail = (message) => ({ ok: false, issues: [{ code: "FUNCSTUDY_CHECK_INVALID", message }] });
    const spec = typeof raw.kind === "string" && Object.prototype.hasOwnProperty.call(CHECKS, raw.kind) ? CHECKS[raw.kind] : undefined;
    if (!spec)
        return fail("نوع فحص غير معروف.");
    if (!exactKeys(raw, ["id", "label", "weight", "kind", "expected", "tolerance"]))
        return fail("الفحص «" + String(raw.label) + "» يجب أن يحوي الإجابة المتوقعة والسماحية فقط.");
    if (config.tasks[spec.task] !== true)
        return fail("الفحص «" + String(raw.label) + "» يقيّم مهمة غير مفعّلة في إعداد الدالة.");
    if (typeof raw.tolerance !== "number" || !Number.isFinite(raw.tolerance) || raw.tolerance < 0 || raw.tolerance > L.toleranceMax)
        return fail("السماحية في الفحص «" + String(raw.label) + "» يجب أن تكون عددًا غير سالب.");
    const parsed = spec.parse(raw.expected);
    if (!parsed)
        return fail("الإجابة المتوقعة في الفحص «" + String(raw.label) + "» غير صالحة أو فارغة (قيم منتهية، بلا تكرار، ∞ في موضعه الصحيح).");
    const expected = raw.kind === "intercept.y" ? parsed[0] : parsed;
    return { ok: true, check: { id: raw.id, label: raw.label, weight: raw.weight, kind: raw.kind, expected, tolerance: raw.tolerance } };
}
const near = (a, b, tol) => Math.abs(a - b) <= tol;
const endpointNear = (a, b, tol) => (typeof a === "number" && typeof b === "number" ? near(a, b, tol) : a === b);
function sameSet(want, got, key, match) {
    if (want.length !== got.length)
        return false;
    const w = [...want].sort((a, b) => key(a) - key(b)), g = [...got].sort((a, b) => key(a) - key(b));
    return w.every((v, i) => match(v, g[i]));
}
const showNum = (n) => String(Number(n.toPrecision(10)));
const showEnd = (e) => (e === "-inf" ? "−∞" : e === "+inf" ? "+∞" : showNum(e));
const showList = (kind, v) => {
    if (!Array.isArray(v))
        return typeof v === "number" ? showNum(v) : v && typeof v === "object" ? showNum(v.y) : "—";
    if (!v.length)
        return "—";
    if (kind === "intercepts.x")
        return v.map(p => "(" + showNum(p.x) + ", " + showNum(p.y) + ")").join("، ");
    if (kind === "extrema.points")
        return v.map(p => (p.kind === "min" ? "صغرى" : "عظمى") + " (" + showNum(p.x) + ", " + showNum(p.y) + ")").join("، ");
    if (kind === "monotonic.intervals")
        return v.map(i => (i.kind === "increasing" ? "متزايدة" : "متناقصة") + " (" + showEnd(i.from) + ", " + showEnd(i.to) + ")").join("، ");
    return v.map(showNum).join("، ");
};
function evaluateFunctionStudyCheck(check, state) {
    const tol = check.tolerance;
    let actual, passed = false;
    switch (check.kind) {
        case "domain.exclusions":
            actual = state.domainExclusions;
            passed = sameSet(check.expected, state.domainExclusions, v => v, (a, b) => near(a, b, tol));
            break;
        case "asymptotes.vertical":
            actual = state.verticalAsymptotes;
            passed = sameSet(check.expected, state.verticalAsymptotes, v => v, (a, b) => near(a, b, tol));
            break;
        case "asymptotes.horizontal":
            actual = state.horizontalAsymptotes;
            passed = sameSet(check.expected, state.horizontalAsymptotes, v => v, (a, b) => near(a, b, tol));
            break;
        case "intercepts.x":
            actual = state.xIntercepts;
            passed = sameSet(check.expected, state.xIntercepts, p => p.x, (a, b) => near(a.x, b.x, tol) && near(a.y, b.y, tol));
            break;
        case "intercept.y":
            actual = state.yIntercept ?? "—";
            passed = state.yIntercept !== null && near(check.expected, state.yIntercept.y, tol);
            break;
        case "extrema.points":
            actual = state.extrema;
            passed = sameSet(check.expected, state.extrema, p => p.x, (a, b) => a.kind === b.kind && near(a.x, b.x, tol) && near(a.y, b.y, tol));
            break;
        case "monotonic.intervals":
            actual = state.monotonicIntervals;
            passed = sameSet(check.expected, state.monotonicIntervals, i => startKey(i.from), (a, b) => a.kind === b.kind && endpointNear(a.from, b.from, tol) && endpointNear(a.to, b.to, tol));
            break;
    }
    return { expected: showList(check.kind, check.expected) + " (± " + showNum(tol) + ")", actual: actual === "—" ? "—" : showList(check.kind, actual), passed };
}
exports.FUNCTION_STUDY_DESCRIPTOR_V1 = {
    descriptorVersion: 1, key: functionStudyModel_1.FUNCTION_STUDY_PLUGIN_KEY, version: functionStudyModel_1.FUNCTION_STUDY_PLUGIN_VERSION, label: exports.FUNCTION_STUDY_LABEL, domain: "mathematics",
    sceneKinds: ["2d"], rendererFamilies: ["graph2d", "form"],
    capabilities: ["scene.2d", "graph.2d", "point.place", "value.set"],
    actionKinds: [...exports.FUNCTION_STUDY_ACTION_KINDS], checkKinds: [...exports.FUNCTION_STUDY_CHECK_KINDS], genericRules: [], assetKinds: [],
    tools: ["form", "placePoint"], accessibility: ["keyboardAlternative", "semanticLabels", "toolLabels", "textTranscript"],
    supports: { autosave: true, restore: true, reset: true, partialCredit: true, offline: true, twoDimensional: true, threeDimensional: false }
};
exports.functionStudy2dPluginV1 = Object.freeze({
    key: functionStudyModel_1.FUNCTION_STUDY_PLUGIN_KEY,
    version: functionStudyModel_1.FUNCTION_STUDY_PLUGIN_VERSION,
    label: exports.FUNCTION_STUDY_LABEL,
    maxActions: exports.FUNCTION_STUDY_MAX_ACTIONS,
    descriptor: exports.FUNCTION_STUDY_DESCRIPTOR_V1,
    checkKinds: exports.FUNCTION_STUDY_CHECK_KINDS,
    validateConfig: (raw) => (0, functionStudyModel_1.validateFunctionStudyConfig)(raw),
    createRuntime: () => (0, exports.initialFunctionStudyState)(),
    normalizeAction: normalizeFunctionStudyAction,
    applyAction: (s, a) => applyAction(s, a),
    canonicalState: (s) => canonical(s),
    serializeState: (s) => JSON.stringify(canonical(s)),
    validateCheck: validateFunctionStudyCheck,
    evaluateCheck: (c, s) => evaluateFunctionStudyCheck(c, s)
});
