// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HOTSPOT_FAIL_CLOSED = exports.isHotspotAnswerAnswered = exports.hotspotQuestionVersion = exports.defaultHotspotAnswerKey = exports.defaultHotspotConfig = exports.HOTSPOT_LIMITS = exports.HOTSPOT_CONFIG_VERSION = exports.HOTSPOT_TYPE_KEY = void 0;
exports.validateHotspotConfig = validateHotspotConfig;
exports.validateHotspotAnswerKey = validateHotspotAnswerKey;
exports.validateHotspotQuestion = validateHotspotQuestion;
exports.projectHotspotConfigForStudent = projectHotspotConfigForStudent;
exports.normalizeHotspotAnswer = normalizeHotspotAnswer;
exports.bindHotspotAnswerToQuestion = bindHotspotAnswerToQuestion;
exports.scoreHotspot = scoreHotspot;
exports.evaluateHotspot = evaluateHotspot;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const visualGeometry_1 = require("./visualGeometry");
exports.HOTSPOT_TYPE_KEY = "hotspot";
exports.HOTSPOT_CONFIG_VERSION = 1;
exports.HOTSPOT_LIMITS = Object.freeze({ regions: 50, selections: 50, points: 50, altMin: 3, altChars: 500 });
const err = (code, message, path) => ({ code, message, severity: "error", ...(path ? { path } : {}) });
const FORBIDDEN_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const isPlain = (v) => {
    if (!v || typeof v !== "object" || Array.isArray(v))
        return false;
    const p = Object.getPrototypeOf(v);
    return p === Object.prototype || p === null;
};
const onlyKeys = (o, allowed) => Object.keys(o).every(k => allowed.includes(k) && !FORBIDDEN_KEYS.has(k));
const defaultHotspotConfig = () => ({ v: 1, mode: "single", selections: 1, alt: "" });
exports.defaultHotspotConfig = defaultHotspotConfig;
const defaultHotspotAnswerKey = () => ({ scoring: "allOrNothing", regions: [] });
exports.defaultHotspotAnswerKey = defaultHotspotAnswerKey;
const hotspotQuestionVersion = (node) => (isPlain(node) ? (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(exports.HOTSPOT_TYPE_KEY, node.questionTypeVersion) : undefined);
exports.hotspotQuestionVersion = hotspotQuestionVersion;
function validateHotspotConfig(raw) {
    if (!isPlain(raw))
        return { ok: false, issues: [err("HOTSPOT_CONFIG_MISSING", "إعداد سؤال «تحديد منطقة على صورة» مفقود أو غير صالح.", "hotspot")] };
    const issues = [];
    if (!onlyKeys(raw, ["v", "mode", "selections", "alt"]))
        issues.push(err("HOTSPOT_CONFIG_UNKNOWN_KEY", "إعداد السؤال يحتوي حقولًا غير معروفة.", "hotspot"));
    if (raw.v !== exports.HOTSPOT_CONFIG_VERSION)
        issues.push(err("HOTSPOT_CONFIG_VERSION", "إصدار بنية سؤال الصورة غير مدعوم.", "hotspot.v"));
    const mode = raw.mode;
    if (mode !== "single" && mode !== "multiple")
        issues.push(err("HOTSPOT_MODE_UNKNOWN", "طريقة التحديد غير معروفة (المدعوم: نقطة واحدة أو عدة نقاط).", "hotspot.mode"));
    const s = raw.selections;
    const sOk = typeof s === "number" && Number.isInteger(s) && (mode === "single" ? s === 1 : mode === "multiple" ? s >= 2 && s <= exports.HOTSPOT_LIMITS.selections : true);
    if (!sOk)
        issues.push(err("HOTSPOT_SELECTIONS_INVALID", mode === "multiple" ? "وضع «عدة نقاط» يحتاج من 2 إلى " + exports.HOTSPOT_LIMITS.selections + " منطقة صحيحة." : "وضع «نقطة واحدة» يقبل تحديدًا واحدًا فقط.", "hotspot.selections"));
    const alt = typeof raw.alt === "string" ? raw.alt.trim() : null;
    if (alt === null || alt.length < exports.HOTSPOT_LIMITS.altMin || alt.length > exports.HOTSPOT_LIMITS.altChars)
        issues.push(err("HOTSPOT_ALT_INVALID", "اكتب وصفًا واضحًا للصورة (من " + exports.HOTSPOT_LIMITS.altMin + " إلى " + exports.HOTSPOT_LIMITS.altChars + " حرفًا) لمن لا يرى الصورة.", "hotspot.alt"));
    if (issues.length)
        return { ok: false, issues };
    return { ok: true, config: { v: 1, mode: mode, selections: s, alt: alt }, issues: [] };
}
function validateHotspotAnswerKey(raw, rawConfig) {
    const cfg = validateHotspotConfig(rawConfig);
    if (!cfg.ok)
        return { ok: false, issues: [err("HOTSPOT_KEY_CONFIG_INVALID", "لا يمكن التحقق من المناطق الصحيحة لأن إعداد السؤال غير صالح.", "hotspot")] };
    return checkAnswerKey(raw, cfg.config);
}
function checkAnswerKey(raw, cfg) {
    if (!isPlain(raw))
        return { ok: false, issues: [err("HOTSPOT_ANSWER_KEY_INVALID", "مفتاح تصحيح سؤال الصورة مفقود أو غير صالح.", "answer")] };
    const issues = [];
    if (!onlyKeys(raw, ["scoring", "regions"]))
        issues.push(err("HOTSPOT_ANSWER_KEY_INVALID", "مفتاح التصحيح يحتوي حقولًا غير معروفة.", "answer"));
    const scoring = raw.scoring;
    if (scoring !== "proportional" && scoring !== "allOrNothing")
        issues.push(err("HOTSPOT_SCORING_UNKNOWN", "طريقة الاحتساب غير معروفة (المدعوم: نسبية أو الكل أو لا شيء).", "answer.scoring"));
    const list = raw.regions;
    if (!Array.isArray(list) || list.length === 0 || list.length > exports.HOTSPOT_LIMITS.regions) {
        issues.push(err("HOTSPOT_REGIONS_INVALID", "حدّد على الصورة منطقة صحيحة واحدة على الأقل (حتى " + exports.HOTSPOT_LIMITS.regions + ").", "answer.regions"));
        return { ok: false, issues };
    }
    const regions = [];
    const ids = new Set();
    list.forEach((r, i) => {
        const path = "answer.regions." + i, n = i + 1;
        if (!isPlain(r) || !onlyKeys(r, ["id", "shape"]) || !("id" in r) || !("shape" in r)) {
            issues.push(err("HOTSPOT_REGION_INVALID", "المنطقة " + n + " غير صالحة.", path));
            return;
        }
        if (!(0, visualGeometry_1.isVisualId)(r.id)) {
            issues.push(err("HOTSPOT_REGION_ID_INVALID", "معرّف المنطقة " + n + " غير صالح.", path + ".id"));
            return;
        }
        if (ids.has(r.id)) {
            issues.push(err("HOTSPOT_REGION_ID_DUPLICATE", "معرّف المنطقة «" + r.id + "» مكرّر.", path + ".id"));
            return;
        }
        ids.add(r.id);
        const shape = (0, visualGeometry_1.validateVisualShape)(r.shape);
        if (!shape.ok) {
            issues.push(err("HOTSPOT_REGION_SHAPE_INVALID", "المنطقة " + n + ": " + (visualGeometry_1.VISUAL_SHAPE_MESSAGES[shape.code] ?? "شكل غير صالح."), path + ".shape"));
            return;
        }
        regions.push({ id: r.id, shape: shape.shape });
    });
    if (!issues.length && cfg && regions.length !== cfg.selections)
        issues.push(err("HOTSPOT_TARGET_COUNT", cfg.mode === "single" ? "وضع «نقطة واحدة» يحتاج منطقة صحيحة واحدة فقط." : "عدد المناطق الصحيحة (" + regions.length + ") يجب أن يساوي عدد التحديدات المطلوبة (" + cfg.selections + ").", "answer.regions"));
    if (issues.length)
        return { ok: false, issues };
    return { ok: true, key: { scoring: scoring, regions }, issues: [] };
}
function validateHotspotQuestion(node) {
    const out = [];
    if ((0, exports.hotspotQuestionVersion)(node) === undefined)
        out.push(err("HOTSPOT_VERSION_UNSUPPORTED", "إصدار سؤال «تحديد منطقة على صورة» غير مدعوم في هذا الإصدار من التطبيق.", "questionTypeVersion"));
    const cfg = validateHotspotConfig(node.hotspot);
    if (!cfg.ok)
        out.push(...cfg.issues);
    const key = checkAnswerKey(node.answer, cfg.ok ? cfg.config : null);
    if (!key.ok)
        out.push(...key.issues);
    const img = (0, visualGeometry_1.validateVisualImage)(node.image);
    if (!img.ok)
        out.push(err(img.code, visualGeometry_1.VISUAL_IMAGE_MESSAGES[img.code], "image"));
    return out;
}
function projectHotspotConfigForStudent(raw) {
    const r = validateHotspotConfig(raw);
    return r.ok ? r.config : null;
}
const readPoint = (p) => (isPlain(p) && (0, visualGeometry_1.isNormalizedCoordinate)(p.x) && (0, visualGeometry_1.isNormalizedCoordinate)(p.y) ? { x: p.x, y: p.y } : null);
function responsePoints(response, max) {
    if (!isPlain(response) || response.kind !== "hotspot" || !Array.isArray(response.points) || response.points.length > max)
        return null;
    const out = [];
    for (const p of response.points) {
        const q = readPoint(p);
        if (!q)
            return null;
        out.push(q);
    }
    return out;
}
function normalizeHotspotAnswer(a) {
    const points = responsePoints(a, exports.HOTSPOT_LIMITS.points);
    return points ? { ok: true, answer: { kind: "hotspot", points } } : { ok: false, code: "HOTSPOT_ANSWER_INVALID" };
}
function bindHotspotAnswerToQuestion(a, question) {
    if (!isPlain(question) || question.presentationType !== exports.HOTSPOT_TYPE_KEY)
        return { ok: false, code: "HOTSPOT_QUESTION_MISMATCH" };
    const cfg = projectHotspotConfigForStudent(question.hotspot);
    const points = responsePoints(a, cfg ? cfg.selections : exports.HOTSPOT_LIMITS.points);
    return points ? { ok: true, answer: { kind: "hotspot", points } } : { ok: false, code: "HOTSPOT_ANSWER_INVALID" };
}
const isHotspotAnswerAnswered = (a) => isPlain(a) && a.kind === "hotspot" && Array.isArray(a.points) && a.points.length > 0;
exports.isHotspotAnswerAnswered = isHotspotAnswerAnswered;
exports.HOTSPOT_FAIL_CLOSED = Object.freeze({ score: 0, correct: false, manualReview: true, parts: Object.freeze({ correct: 0, total: 0 }) });
function authorityOf(rawConfig, rawKey, rawImage) {
    const cfg = validateHotspotConfig(rawConfig);
    if (!cfg.ok)
        return null;
    const key = validateHotspotAnswerKey(rawKey, rawConfig);
    if (!key.ok || !(0, visualGeometry_1.validateVisualImage)(rawImage).ok)
        return null;
    return { config: cfg.config, key: key.key };
}
function scoreHotspot(input) {
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const auth = authorityOf(input.config, input.answerKey, input.image);
    if (!auth)
        return { ...exports.HOTSPOT_FAIL_CLOSED, parts: { ...exports.HOTSPOT_FAIL_CLOSED.parts } };
    const total = auth.key.regions.length;
    const points = responsePoints(input.response, auth.config.selections);
    if (!points)
        return { score: 0, correct: false, manualReview: false, parts: { correct: 0, total } };
    const matched = (0, visualGeometry_1.maxOneToOneMatching)(points, auth.key.regions.map(r => r.shape)).size;
    const all = matched === total;
    const score = auth.key.scoring === "allOrNothing" ? (all ? max : 0) : max * matched / total;
    return { score: Math.min(max, Math.max(0, score)), correct: all, manualReview: false, parts: { correct: matched, total } };
}
function evaluateHotspot(rawConfig, rawKey, rawImage, response) {
    const auth = authorityOf(rawConfig, rawKey, rawImage);
    if (!auth) {
        const cfg = validateHotspotConfig(rawConfig), key = validateHotspotAnswerKey(rawKey, rawConfig), img = (0, visualGeometry_1.validateVisualImage)(rawImage);
        return { ok: false, issues: [...(cfg.ok ? [] : cfg.issues), ...(cfg.ok && !key.ok ? key.issues : []), ...(img.ok ? [] : [err(img.code, visualGeometry_1.VISUAL_IMAGE_MESSAGES[img.code], "image")])] };
    }
    const points = responsePoints(response, auth.config.selections) ?? [];
    const m = (0, visualGeometry_1.maxOneToOneMatching)(points, auth.key.regions.map(r => r.shape));
    const hit = new Set(m.targetOfPoint.filter((j) => j !== null));
    return {
        ok: true, matched: m.size, total: auth.key.regions.length,
        targets: auth.key.regions.map((r, j) => ({ id: r.id, index: j + 1, shape: r.shape, matched: hit.has(j) })),
        points: points.map((p, i) => { const j = m.targetOfPoint[i]; return { x: p.x, y: p.y, target: j === null ? null : auth.key.regions[j].id }; })
    };
}
