// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INLINE_CLOZE_FAIL_CLOSED = exports.inlineClozeQuestionVersion = exports.defaultInlineClozeAnswerKey = exports.defaultInlineClozeConfig = exports.INLINE_CLOZE_SCORING_MODES = exports.INLINE_CLOZE_LIMITS = exports.INLINE_CLOZE_CONFIG_VERSION = exports.INLINE_CLOZE_TYPE_KEY = void 0;
exports.normalizeClozeText = normalizeClozeText;
exports.inlineClozeBlanks = inlineClozeBlanks;
exports.inlineClozePreviewText = inlineClozePreviewText;
exports.validateInlineClozeConfig = validateInlineClozeConfig;
exports.validateInlineClozeAnswerKey = validateInlineClozeAnswerKey;
exports.validateInlineClozeQuestion = validateInlineClozeQuestion;
exports.projectInlineClozeConfigForStudent = projectInlineClozeConfigForStudent;
exports.bindInlineClozeAnswerToQuestion = bindInlineClozeAnswerToQuestion;
exports.scoreInlineCloze = scoreInlineCloze;
exports.evaluateInlineCloze = evaluateInlineCloze;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
exports.INLINE_CLOZE_TYPE_KEY = "inlineCloze";
exports.INLINE_CLOZE_CONFIG_VERSION = 1;
exports.INLINE_CLOZE_LIMITS = Object.freeze({ segments: 400, textChars: 2000, passageChars: 20000, blanks: 50, minOptions: 2, options: 12, labelChars: 200, accepted: 20, acceptedChars: 200, responseChars: 500 });
exports.INLINE_CLOZE_SCORING_MODES = Object.freeze(["proportional", "allOrNothing"]);
const err = (code, message, path) => ({ code, message, severity: "error", ...(path ? { path } : {}) });
const isPlain = (v) => {
    if (!v || typeof v !== "object" || Array.isArray(v))
        return false;
    const p = Object.getPrototypeOf(v);
    return p === Object.prototype || p === null;
};
const FORBIDDEN_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const ID_RE = /^[A-Za-z][A-Za-z0-9_-]{0,31}$/;
const isId = (v) => typeof v === "string" && ID_RE.test(v) && !FORBIDDEN_KEYS.has(v);
const onlyKeys = (o, allowed) => Object.keys(o).every(k => allowed.includes(k) && !FORBIDDEN_KEYS.has(k));
const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
function normalizeClozeText(value, caseSensitive) {
    const s = String(value).normalize("NFC").replace(/\s+/g, " ").trim();
    return caseSensitive ? s : s.toLowerCase();
}
const defaultInlineClozeConfig = () => ({ v: 1, segments: [{ type: "text", text: "اكتب النص هنا، ثم أدرج فراغًا: " }, { type: "blank", id: "b1", control: "text" }] });
exports.defaultInlineClozeConfig = defaultInlineClozeConfig;
const defaultInlineClozeAnswerKey = () => ({ scoring: "proportional", blanks: { b1: { accepted: [], caseSensitive: false } } });
exports.defaultInlineClozeAnswerKey = defaultInlineClozeAnswerKey;
const inlineClozeQuestionVersion = (node) => (isPlain(node) ? (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(exports.INLINE_CLOZE_TYPE_KEY, node.questionTypeVersion) : undefined);
exports.inlineClozeQuestionVersion = inlineClozeQuestionVersion;
function inlineClozeBlanks(cfg) {
    const out = [];
    for (const s of cfg.segments)
        if (s.type === "blank")
            out.push({ ...s, index: out.length + 1 });
    return out;
}
function inlineClozePreviewText(cfg) {
    let n = 0;
    return cfg.segments.map(s => (s.type === "text" ? s.text : "[فراغ " + ++n + "]")).join("");
}
function validateInlineClozeConfig(raw) {
    if (!isPlain(raw))
        return { ok: false, issues: [err("CLOZE_CONFIG_MISSING", "إعداد سؤال «إكمال نص تفاعلي» مفقود أو غير صالح.", "inlineCloze")] };
    const issues = [];
    if (!onlyKeys(raw, ["v", "segments"]))
        issues.push(err("CLOZE_CONFIG_UNKNOWN_KEY", "إعداد النص التفاعلي يحتوي حقولًا غير معروفة.", "inlineCloze"));
    if (raw.v !== exports.INLINE_CLOZE_CONFIG_VERSION)
        issues.push(err("CLOZE_CONFIG_VERSION", "إصدار بنية النص التفاعلي غير مدعوم.", "inlineCloze.v"));
    const segs = raw.segments;
    if (!Array.isArray(segs) || segs.length === 0 || segs.length > exports.INLINE_CLOZE_LIMITS.segments) {
        issues.push(err("CLOZE_SEGMENTS_INVALID", "النص التفاعلي يحتاج مقاطع (نص وفراغات) ضمن الحد المسموح.", "inlineCloze.segments"));
        return { ok: false, issues };
    }
    const segments = [];
    const blankIds = new Set();
    let blanks = 0, chars = 0;
    segs.forEach((s, i) => {
        const path = "inlineCloze.segments." + i;
        if (!isPlain(s)) {
            issues.push(err("CLOZE_SEGMENT_INVALID", "مقطع غير صالح في النص التفاعلي (رقم " + (i + 1) + ").", path));
            return;
        }
        if (s.type === "text") {
            if (!onlyKeys(s, ["type", "text"]) || typeof s.text !== "string" || s.text.length === 0 || s.text.length > exports.INLINE_CLOZE_LIMITS.textChars) {
                issues.push(err("CLOZE_SEGMENT_INVALID", "مقطع نصي فارغ أو غير صالح في النص التفاعلي (رقم " + (i + 1) + ").", path));
                return;
            }
            chars += s.text.length;
            segments.push({ type: "text", text: s.text });
            return;
        }
        if (s.type !== "blank") {
            issues.push(err("CLOZE_SEGMENT_INVALID", "نوع مقطع غير معروف في النص التفاعلي (رقم " + (i + 1) + ").", path));
            return;
        }
        blanks++;
        if (!isId(s.id)) {
            issues.push(err("CLOZE_BLANK_ID_INVALID", "معرّف فراغ غير صالح في النص التفاعلي.", path + ".id"));
            return;
        }
        if (blankIds.has(s.id))
            issues.push(err("CLOZE_BLANK_ID_DUPLICATE", "معرّف الفراغ «" + s.id + "» مكرّر.", path + ".id"));
        blankIds.add(s.id);
        if (s.control === "text") {
            if (!onlyKeys(s, ["type", "id", "control"])) {
                issues.push(err("CLOZE_SEGMENT_INVALID", "فراغ الكتابة «" + s.id + "» يحتوي حقولًا غير معروفة.", path));
                return;
            }
            segments.push({ type: "blank", id: s.id, control: "text" });
            return;
        }
        if (s.control !== "dropdown") {
            issues.push(err("CLOZE_CONTROL_UNKNOWN", "نوع الفراغ «" + String(s.control) + "» غير مدعوم (المدعوم: كتابة أو قائمة منسدلة).", path + ".control"));
            return;
        }
        if (!onlyKeys(s, ["type", "id", "control", "options"])) {
            issues.push(err("CLOZE_SEGMENT_INVALID", "القائمة المنسدلة «" + s.id + "» تحتوي حقولًا غير معروفة.", path));
            return;
        }
        const opts = s.options;
        if (!Array.isArray(opts) || opts.length < exports.INLINE_CLOZE_LIMITS.minOptions || opts.length > exports.INLINE_CLOZE_LIMITS.options) {
            issues.push(err("CLOZE_DROPDOWN_OPTIONS_INVALID", "القائمة المنسدلة «" + s.id + "» تحتاج من " + exports.INLINE_CLOZE_LIMITS.minOptions + " إلى " + exports.INLINE_CLOZE_LIMITS.options + " خيارات.", path + ".options"));
            return;
        }
        const options = [];
        const optionIds = new Set(), labels = new Set();
        let ok = true;
        opts.forEach((o, j) => {
            if (!isPlain(o) || !onlyKeys(o, ["id", "label"]) || !isId(o.id) || typeof o.label !== "string" || o.label.trim() === "" || o.label.length > exports.INLINE_CLOZE_LIMITS.labelChars) {
                issues.push(err("CLOZE_OPTION_INVALID", "الخيار " + (j + 1) + " في القائمة المنسدلة «" + s.id + "» غير صالح (معرّف ونص غير فارغ فقط).", path + ".options." + j));
                ok = false;
                return;
            }
            if (optionIds.has(o.id)) {
                issues.push(err("CLOZE_OPTION_ID_DUPLICATE", "معرّف خيار مكرّر في القائمة المنسدلة «" + s.id + "».", path + ".options." + j));
                ok = false;
            }
            const norm = normalizeClozeText(o.label, false);
            if (labels.has(norm)) {
                issues.push(err("CLOZE_OPTION_LABEL_DUPLICATE", "نص خيار مكرّر في القائمة المنسدلة «" + s.id + "».", path + ".options." + j));
                ok = false;
            }
            optionIds.add(o.id);
            labels.add(norm);
            options.push({ id: o.id, label: o.label });
        });
        if (ok)
            segments.push({ type: "blank", id: s.id, control: "dropdown", options });
    });
    if (blanks === 0)
        issues.push(err("CLOZE_NO_BLANKS", "النص التفاعلي يحتاج فراغًا واحدًا على الأقل.", "inlineCloze.segments"));
    if (blanks > exports.INLINE_CLOZE_LIMITS.blanks)
        issues.push(err("CLOZE_TOO_MANY_BLANKS", "عدد الفراغات يتجاوز الحد (" + exports.INLINE_CLOZE_LIMITS.blanks + ").", "inlineCloze.segments"));
    if (chars > exports.INLINE_CLOZE_LIMITS.passageChars)
        issues.push(err("CLOZE_PASSAGE_TOO_LONG", "النص التفاعلي أطول من الحد المسموح.", "inlineCloze.segments"));
    if (issues.length)
        return { ok: false, issues };
    return { ok: true, config: { v: 1, segments }, issues: [] };
}
function validateInlineClozeAnswerKey(raw, rawConfig) {
    const cfg = validateInlineClozeConfig(rawConfig);
    if (!cfg.ok)
        return { ok: false, issues: [err("CLOZE_KEY_CONFIG_INVALID", "لا يمكن التحقق من مفتاح التصحيح لأن إعداد النص التفاعلي غير صالح.", "inlineCloze")] };
    if (!isPlain(raw))
        return { ok: false, issues: [err("CLOZE_ANSWER_KEY_INVALID", "مفتاح تصحيح النص التفاعلي مفقود أو غير صالح.", "answer")] };
    const issues = [];
    if (!onlyKeys(raw, ["scoring", "blanks"]))
        issues.push(err("CLOZE_ANSWER_KEY_INVALID", "مفتاح التصحيح يحتوي حقولًا غير معروفة.", "answer"));
    const scoring = raw.scoring;
    if (scoring !== "proportional" && scoring !== "allOrNothing")
        issues.push(err("CLOZE_SCORING_UNKNOWN", "طريقة الاحتساب غير معروفة (المدعوم: نسبية أو كل شيء أو لا شيء).", "answer.scoring"));
    const blanksRaw = raw.blanks;
    if (!isPlain(blanksRaw) || Object.keys(blanksRaw).some(k => FORBIDDEN_KEYS.has(k))) {
        issues.push(err("CLOZE_ANSWER_KEY_INVALID", "إجابات الفراغات في مفتاح التصحيح غير صالحة.", "answer.blanks"));
        return { ok: false, issues };
    }
    const blanks = inlineClozeBlanks(cfg.config);
    const known = new Map(blanks.map(b => [b.id, b]));
    for (const id of Object.keys(blanksRaw))
        if (!known.has(id))
            issues.push(err("CLOZE_KEY_UNKNOWN_BLANK", "مفتاح التصحيح يذكر فراغًا غير موجود «" + id + "».", "answer.blanks." + id));
    const out = {};
    for (const b of blanks) {
        const path = "answer.blanks." + b.id;
        if (!own(blanksRaw, b.id)) {
            issues.push(err("CLOZE_KEY_MISSING_BLANK", "الفراغ " + b.index + " بلا إجابة صحيحة في مفتاح التصحيح.", path));
            continue;
        }
        const k = blanksRaw[b.id];
        if (b.control === "dropdown") {
            if (!isPlain(k) || !onlyKeys(k, ["correctOptionId"]) || typeof k.correctOptionId !== "string" || !b.options.some(o => o.id === k.correctOptionId)) {
                issues.push(err("CLOZE_DROPDOWN_KEY_INVALID", "الفراغ " + b.index + " (قائمة منسدلة) يحتاج خيارًا صحيحًا واحدًا من خياراته.", path));
                continue;
            }
            out[b.id] = { control: "dropdown", correctOptionId: k.correctOptionId };
            continue;
        }
        if (!isPlain(k) || !onlyKeys(k, ["accepted", "caseSensitive"]) || !Array.isArray(k.accepted) || k.accepted.length > exports.INLINE_CLOZE_LIMITS.accepted || !k.accepted.every(a => typeof a === "string" && a.length <= exports.INLINE_CLOZE_LIMITS.acceptedChars) || (k.caseSensitive !== undefined && typeof k.caseSensitive !== "boolean")) {
            issues.push(err("CLOZE_TEXT_KEY_INVALID", "مفتاح الفراغ " + b.index + " غير صالح (قائمة إجابات مقبولة ومطابقة حالة الأحرف فقط).", path));
            continue;
        }
        const caseSensitive = k.caseSensitive === true;
        const accepted = k.accepted.map(a => normalizeClozeText(a, true));
        if (accepted.length === 0 || accepted.some(a => a === "")) {
            issues.push(err("CLOZE_TEXT_ACCEPTED_EMPTY", "الفراغ " + b.index + " يحتاج إجابة مقبولة واحدة على الأقل (ولا إجابة فارغة).", path));
            continue;
        }
        out[b.id] = { control: "text", accepted: [...new Set(accepted)], caseSensitive };
    }
    if (issues.length)
        return { ok: false, issues };
    return { ok: true, key: { scoring: scoring, blanks: out, parts: blanks.length }, issues: [] };
}
function validateInlineClozeQuestion(node) {
    const out = [];
    if ((0, exports.inlineClozeQuestionVersion)(node) === undefined)
        out.push(err("CLOZE_VERSION_UNSUPPORTED", "إصدار سؤال «إكمال نص تفاعلي» غير مدعوم في هذا الإصدار من التطبيق.", "questionTypeVersion"));
    const cfg = validateInlineClozeConfig(node.inlineCloze);
    if (!cfg.ok)
        return [...out, ...cfg.issues];
    const key = validateInlineClozeAnswerKey(node.answer, node.inlineCloze);
    return key.ok ? out : [...out, ...key.issues];
}
function projectInlineClozeConfigForStudent(raw) {
    const r = validateInlineClozeConfig(raw);
    return r.ok ? r.config : null;
}
function bindInlineClozeAnswerToQuestion(a, question) {
    if (!isPlain(a) || a.kind !== "fields" || !isPlain(a.values))
        return { ok: false, code: "CLOZE_ANSWER_INVALID" };
    const cfg = isPlain(question) ? projectInlineClozeConfigForStudent(question.inlineCloze) : null;
    const allowed = cfg ? new Set(inlineClozeBlanks(cfg).map(b => b.id)) : null;
    const values = {};
    let n = 0;
    for (const id of Object.keys(a.values)) {
        if (!isId(id) || (allowed && !allowed.has(id)))
            continue;
        const v = a.values[id];
        if (typeof v !== "string")
            continue;
        if (++n > exports.INLINE_CLOZE_LIMITS.blanks)
            break;
        values[id] = v.slice(0, exports.INLINE_CLOZE_LIMITS.responseChars);
    }
    return { ok: true, answer: { kind: "fields", values } };
}
function responseValues(response) {
    if (!isPlain(response) || response.kind !== "fields" || !isPlain(response.values))
        return null;
    const out = {};
    for (const k of Object.keys(response.values)) {
        const v = response.values[k];
        if (!FORBIDDEN_KEYS.has(k) && typeof v === "string")
            out[k] = v;
    }
    return out;
}
const blankCorrect = (key, value) => {
    if (typeof value !== "string" || value.length > exports.INLINE_CLOZE_LIMITS.responseChars)
        return false;
    if (key.control === "dropdown")
        return value === key.correctOptionId;
    const given = normalizeClozeText(value, key.caseSensitive);
    return given !== "" && key.accepted.some(a => normalizeClozeText(a, key.caseSensitive) === given);
};
exports.INLINE_CLOZE_FAIL_CLOSED = Object.freeze({ score: 0, correct: false, manualReview: true, parts: Object.freeze({ correct: 0, total: 0 }) });
function scoreInlineCloze(input) {
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const key = validateInlineClozeAnswerKey(input.answerKey, input.config);
    if (!key.ok)
        return { ...exports.INLINE_CLOZE_FAIL_CLOSED, parts: { ...exports.INLINE_CLOZE_FAIL_CLOSED.parts } };
    const total = key.key.parts;
    const values = responseValues(input.response);
    if (!values)
        return { score: 0, correct: false, manualReview: false, parts: { correct: 0, total } };
    let correct = 0;
    for (const id of Object.keys(key.key.blanks))
        if (blankCorrect(key.key.blanks[id], own(values, id) ? values[id] : undefined))
            correct++;
    const all = total > 0 && correct === total;
    const score = key.key.scoring === "allOrNothing" ? (all ? max : 0) : (total ? max * correct / total : 0);
    return { score: Math.min(max, Math.max(0, score)), correct: all, manualReview: false, parts: { correct, total } };
}
function evaluateInlineCloze(rawConfig, rawKey, rawValues) {
    const cfg = validateInlineClozeConfig(rawConfig);
    if (!cfg.ok)
        return { ok: false, issues: cfg.issues };
    const key = validateInlineClozeAnswerKey(rawKey, rawConfig);
    if (!key.ok)
        return { ok: false, issues: key.issues };
    const values = isPlain(rawValues) ? responseValues({ kind: "fields", values: rawValues }) ?? {} : {};
    const results = inlineClozeBlanks(cfg.config).map(b => {
        const k = key.key.blanks[b.id];
        const raw = own(values, b.id) ? values[b.id] : "";
        const ok = blankCorrect(k, raw === "" ? undefined : raw);
        if (b.control === "dropdown" && k.control === "dropdown") {
            const chosen = b.options.find(o => o.id === raw);
            return { id: b.id, index: b.index, control: b.control, given: chosen ? chosen.label : raw, ok, expected: b.options.filter(o => o.id === k.correctOptionId).map(o => o.label) };
        }
        return { id: b.id, index: b.index, control: b.control, given: raw, ok, expected: k.control === "text" ? [...k.accepted] : [] };
    });
    const correct = results.filter(r => r.ok).length;
    return { ok: true, results, correct, total: results.length };
}
