// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseTable = parseTable;
exports.resolveTableRowOptions = resolveTableRowOptions;
exports.isCheckboxTableText = isCheckboxTableText;
exports.legacyTableCellControl = legacyTableCellControl;
function parseTable(text) {
    const lines = text.split(/\r?\n/).map(x => x.trim()).filter(x => x.startsWith("|") && x.endsWith("|"));
    if (lines.length < 2)
        return null;
    const split = (x) => x.slice(1, -1).split("|").map(y => y.trim());
    const all = lines.map(split), headers = all[0], rows = all.slice(1).filter(r => !r.every(c => /^:?-{3,}:?$/.test(c.replace(/\s/g, ""))));
    return rows.length ? { headers, rows } : null;
}
function resolveTableRowOptions(q, rowIndex) {
    const fields = (Array.isArray(q.fields) ? q.fields : []).map(f => (f && typeof f === "object" ? f : {}));
    const field = fields.find(f => f.order === rowIndex) ?? fields[rowIndex];
    if (Array.isArray(field?.options) && field.options.length) {
        const values = field.options.map(o => (o && typeof o === "object" ? o.value ?? o.text ?? o.label ?? "" : "")).filter(Boolean);
        if (values.length)
            return { values, isBoolean: false };
    }
    if (field?.kind === "boolean") {
        return { values: ["true", "false"], isBoolean: true };
    }
    if (fields.length && Array.isArray(q.wordBank) && q.wordBank.length) {
        return { values: q.wordBank, isBoolean: false };
    }
    return null;
}
function isCheckboxTableText(text) {
    return /وضع علامة|✓|خاص بالشبكات الخاصة\?|private\?/i.test(String(text ?? ""));
}
function legacyTableCellControl(q, rowIndex) {
    if (resolveTableRowOptions(q, rowIndex))
        return "select";
    return isCheckboxTableText(q.text) ? "checkbox" : "text";
}
