// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROUTER_PORTS = exports.macOf = exports.hostConnected = exports.peerOf = exports.isErrDisabled = exports.emptyOps = exports.NET2_OPS_LIMITS = void 0;
exports.makeNet = makeNet;
exports.linkUp = linkUp;
exports.l3Of = l3Of;
exports.endpointsOf = endpointsOf;
exports.derivePortSecurity = derivePortSecurity;
exports.l2Deliver = l2Deliver;
exports.arpResolve = arpResolve;
exports.forwardLeg = forwardLeg;
exports.probe = probe;
exports.pickSource = pickSource;
exports.reachDevices = reachDevices;
exports.dnsLookup = dnsLookup;
exports.httpGet = httpGet;
exports.computeVtp = computeVtp;
exports.effectiveVlanNames = effectiveVlanNames;
exports.computeWifi = computeWifi;
exports.lowestFree = lowestFree;
exports.canonicalOps = canonicalOps;
exports.reconcile = reconcile;
exports.withTraffic = withTraffic;
exports.switchContext = switchContext;
exports.routerContext = routerContext;
const networkCliEngine_1 = require("./networkCliEngine");
const routerCliEngine_1 = require("./routerCliEngine");
Object.defineProperty(exports, "ROUTER_PORTS", { enumerable: true, get: function () { return routerCliEngine_1.ROUTER_PORTS; } });
const net2Common_1 = require("./net2Common");
const net2SwitchCli_1 = require("./net2SwitchCli");
const net2RouterCli_1 = require("./net2RouterCli");
const net2Model_1 = require("./net2Model");
exports.NET2_OPS_LIMITS = Object.freeze({ reconcileRounds: 6, portSecuritySeen: 16, arpEntries: 16, macEntriesPerSwitch: 64 });
const emptyOps = () => ({ adapters: {}, wifi: {}, dhcpBindings: {}, vtp: {}, portSecurity: {}, arp: {}, macTables: {} });
exports.emptyOps = emptyOps;
const clone = (v) => JSON.parse(JSON.stringify(v));
const key = (dev, port) => dev + "|" + port;
const sameEp = (a, b) => a.dev === b.dev && a.iface === b.iface;
const sortedIds = (net, kind) => net.config.devices.filter(d => !kind || d.kind === kind).map(d => d.id).sort();
function makeNet(config, devices, ops, record = false) {
    const dev = new Map(config.devices.map(d => [d.id, d]));
    const peers = new Map();
    for (const l of config.links) {
        peers.set(key(l.a.deviceId, l.a.port), l.b);
        peers.set(key(l.b.deviceId, l.b.port), l.a);
    }
    const cabled = new Map();
    for (const d of config.devices)
        cabled.set(d.id, (d.kind === "switch" ? networkCliEngine_1.SWITCH_PORTS : d.kind === "router" ? routerCliEngine_1.ROUTER_PORTS : ["eth0"]).flatMap(p => { const peer = peers.get(key(d.id, p)); return peer ? [{ port: p, peer }] : []; }));
    const net = { config, devices, ops, record, dev, peers, vlanDb: new Map(), learn: false, eff: new Map(), cabled, up: new Map(), swPorts: new Map() };
    refreshVlanDb(net);
    return net;
}
function refreshVlanDb(net) {
    net.vlanDb.clear();
    for (const id of sortedIds(net, "switch")) {
        const v = net.ops.vtp[id];
        net.vlanDb.set(id, new Set(v ? v.vlans : [1, ...Object.keys(net.devices[id].vlans).map(Number)]));
    }
}
const kindOf = (net, id) => net.dev.get(id)?.kind;
function switchPorts(net, sw) {
    let list = net.swPorts.get(sw);
    if (!list) {
        list = (net.cabled.get(sw) ?? []).map(c => ({ port: c.port, e: effIf(net, sw, c.port) }));
        net.swPorts.set(sw, list);
    }
    return list;
}
function effIf(net, sw, name) {
    let m = net.eff.get(sw);
    if (!m) {
        m = new Map();
        net.eff.set(sw, m);
    }
    let e = m.get(name);
    if (!e) {
        e = (0, net2SwitchCli_1.effectiveSwitchIf)(net.devices[sw], name);
        m.set(name, e);
    }
    return e;
}
const swState = (net, id) => net.devices[id];
const rtState = (net, id) => net.devices[id];
const hostState = (net, id) => net.devices[id];
const apState = (net, id) => net.devices[id];
const isErrDisabled = (net, dev, port) => net.ops.portSecurity[key(dev, port)]?.errDisabled === true;
exports.isErrDisabled = isErrDisabled;
function portAdminUp(net, dev, port) {
    switch (kindOf(net, dev)) {
        case "switch": return !effIf(net, dev, port).shutdown;
        case "router": return (0, net2RouterCli_1.physicalAdminUp)(rtState(net, dev), port);
        case undefined: return false;
        default: return true;
    }
}
const secureErrDisabled = (net, dev, port) => kindOf(net, dev) === "switch" && effIf(net, dev, port).portSecurity?.enabled === true && (0, exports.isErrDisabled)(net, dev, port);
function linkUp(net, dev, port) {
    let m = net.up.get(dev);
    if (!m) {
        m = new Map();
        net.up.set(dev, m);
    }
    let base = m.get(port);
    if (base === undefined) {
        const p = net.peers.get(key(dev, port));
        base = p ? { peer: p, up: portAdminUp(net, dev, port) && portAdminUp(net, p.deviceId, p.port) } : null;
        m.set(port, base);
    }
    return !!base && base.up && !secureErrDisabled(net, dev, port) && !secureErrDisabled(net, base.peer.deviceId, base.peer.port);
}
const peerOf = (net, dev, port) => net.peers.get(key(dev, port));
exports.peerOf = peerOf;
const hostConnected = (net, dev, iface) => (iface === "wlan0" ? net.ops.wifi[dev]?.status === "associated" : linkUp(net, dev, "eth0"));
exports.hostConnected = hostConnected;
function l3Of(net, ep) {
    switch (kindOf(net, ep.dev)) {
        case "router": {
            const st = rtState(net, ep.dev);
            if (!(0, net2RouterCli_1.router2IfUp)(st, ep.iface, p => linkUp(net, ep.dev, p)))
                return undefined;
            const c = ep.iface.includes(".") ? st.subinterfaces[ep.iface] : st.interfaces[ep.iface];
            return c?.ipAddress && c.subnetMask ? { ip: c.ipAddress, mask: c.subnetMask } : undefined;
        }
        case "switch": {
            const st = swState(net, ep.dev), m = /^vlan(\d+)$/.exec(ep.iface);
            if (!m || !net.vlanDb.get(ep.dev)?.has(Number(m[1])))
                return undefined;
            const e = effIf(net, ep.dev, ep.iface);
            return !e.shutdown && e.ipAddress && e.subnetMask ? { ip: e.ipAddress, mask: e.subnetMask, ...(st.defaultGateway ? { gateway: st.defaultGateway } : {}) } : undefined;
        }
        case "ap": {
            const st = apState(net, ep.dev);
            return ep.iface === "mgmt" && st.address && st.mask && (0, net2Common_1.isUsableHostAddress)(st.address, st.mask) ? { ip: st.address, mask: st.mask, ...(st.gateway ? { gateway: st.gateway } : {}) } : undefined;
        }
        case undefined: return undefined;
        default: {
            const o = net.ops.adapters[ep.dev + "/" + ep.iface];
            if (!o || !o.address || !o.mask || (o.status !== "static" && o.status !== "dhcp" && o.status !== "apipa") || !(0, exports.hostConnected)(net, ep.dev, ep.iface))
                return undefined;
            return { ip: o.address, mask: o.mask, ...(o.gateway ? { gateway: o.gateway } : {}) };
        }
    }
}
function endpointsOf(net, id) {
    const d = net.dev.get(id);
    if (!d)
        return [];
    switch (d.kind) {
        case "router": return (0, net2RouterCli_1.routerAddresses)(rtState(net, id)).map(a => ({ dev: id, iface: a.name }));
        case "switch": return Object.keys(swState(net, id).interfaces).filter(n => /^vlan\d+$/.test(n)).concat(swState(net, id).interfaces.vlan1 ? [] : ["vlan1"]).sort().map(iface => ({ dev: id, iface }));
        case "ap": return [{ dev: id, iface: "mgmt" }];
        default: return (0, net2Model_1.adapterNames)(d).map(iface => ({ dev: id, iface }));
    }
}
const macOf = (ep) => (0, net2Model_1.deriveMac)(ep.dev, ep.iface === "mgmt" ? "eth0" : ep.iface);
exports.macOf = macOf;
function derivePortSecurity(cfg, seen) {
    const statics = cfg.macs, dyn = seen.filter(m => !statics.includes(m));
    const slots = Math.max(0, cfg.maximum - statics.length);
    const secureDyn = dyn.slice(0, slots), violators = dyn.slice(slots);
    return { seen: [...seen], secure: [...statics, ...secureDyn], violations: cfg.violation === "protect" ? 0 : violators.length, errDisabled: cfg.violation === "shutdown" && violators.length > 0, violators, free: slots - secureDyn.length };
}
const psConfig = (net, sw, port) => {
    const e = effIf(net, sw, port);
    return e.portSecurity?.enabled && e.mode === "access" ? e.portSecurity : undefined;
};
function psAdmit(net, sw, port, cfg, mac) {
    const k = key(sw, port), cur = net.ops.portSecurity[k] ?? { seen: [], secure: [], violations: 0, errDisabled: false };
    const d = derivePortSecurity(cfg, cur.seen);
    if (d.secure.includes(mac))
        return true;
    if (d.violators.includes(mac))
        return false;
    if (!net.record)
        return d.free > 0;
    const seen = cur.seen.length < exports.NET2_OPS_LIMITS.portSecuritySeen ? [...cur.seen, mac] : cur.seen;
    const n = derivePortSecurity(cfg, seen);
    net.ops.portSecurity[k] = { seen: n.seen, secure: n.secure, violations: n.violations, errDisabled: n.errDisabled };
    return d.free > 0;
}
function settlePortSecurity(net) {
    const out = {};
    for (const sw of sortedIds(net, "switch"))
        for (const port of networkCliEngine_1.SWITCH_PORTS) {
            const cfg = psConfig(net, sw, port);
            if (!cfg)
                continue;
            const k = key(sw, port);
            const prev = net.ops.portSecurity[k];
            let seen = prev?.seen ?? [];
            const shut = effIf(net, sw, port).shutdown;
            if (shut) {
                const d = derivePortSecurity(cfg, seen);
                seen = cfg.sticky ? d.secure.filter(m => !cfg.macs.includes(m)) : [];
            }
            const d = derivePortSecurity(cfg, seen);
            out[k] = { seen: d.seen, secure: d.secure, violations: d.violations, errDisabled: d.errDisabled || (prev?.errDisabled === true && !shut) };
        }
    net.ops.portSecurity = out;
}
function learnMac(net, l, mac) {
    const table = (net.ops.macTables[l.sw] ??= []);
    const i = table.findIndex(e => e.vlan === l.vlan && e.mac === mac);
    if (i >= 0)
        table[i] = { vlan: l.vlan, mac, port: l.port };
    else if (table.length < exports.NET2_OPS_LIMITS.macEntriesPerSwitch)
        table.push({ vlan: l.vlan, mac, port: l.port });
}
function l2Deliver(net, from, mac, accept, mode) {
    const queue = [], visited = new Set(), learned = [];
    let found = null;
    const offer = (ep, trail) => { if (!found && !sameEp(ep, from) && accept(ep))
        found = { ep, trail }; };
    const cross = (dev, port, tag, trail) => { const p = (0, exports.peerOf)(net, dev, port); if (p && linkUp(net, dev, port))
        queue.push({ dev: p.deviceId, port: p.port, tag, trail }); };
    const bridge = (ap, fromHost, fromMgmt, trail) => {
        if (visited.has("ap|" + ap))
            return;
        visited.add("ap|" + ap);
        if (!fromMgmt)
            offer({ dev: ap, iface: "mgmt" }, trail);
        for (const h of Object.keys(net.ops.wifi).sort()) {
            const w = net.ops.wifi[h];
            if (w.status === "associated" && w.ap === ap && h !== fromHost)
                offer({ dev: h, iface: "wlan0" }, trail);
        }
        if (fromHost !== null || fromMgmt)
            cross(ap, "eth0", null, trail);
    };
    const inVlan = (sw, vlan, ingress, trail) => {
        if (visited.has(sw + "|" + vlan))
            return;
        visited.add(sw + "|" + vlan);
        const t2 = ingress === null ? trail : [...trail, { sw, vlan, port: ingress }];
        if (ingress !== null)
            learned.push({ sw, vlan, port: ingress });
        if (swState(net, sw).interfaces["vlan" + vlan] || vlan === 1)
            offer({ dev: sw, iface: "vlan" + vlan }, t2);
        for (const { port: q, e } of switchPorts(net, sw)) {
            if (q === ingress || !linkUp(net, sw, q))
                continue;
            if (e.mode === "trunk") {
                if ((0, net2SwitchCli_1.trunkAllows)(e, vlan))
                    cross(sw, q, vlan === e.nativeVlan ? null : vlan, t2);
            }
            else if (e.accessVlan === vlan)
                cross(sw, q, null, t2);
        }
    };
    const k = kindOf(net, from.dev);
    if (k === "router") {
        const st = rtState(net, from.dev), parent = (0, net2RouterCli_1.parentOf)(from.iface);
        if (!(0, net2RouterCli_1.router2IfUp)(st, from.iface, p => linkUp(net, from.dev, p)))
            return null;
        const sub = from.iface.includes(".") ? st.subinterfaces[from.iface] : undefined;
        cross(from.dev, parent, sub && !sub.native ? sub.vlan ?? null : null, []);
    }
    else if (k === "switch") {
        const m = /^vlan(\d+)$/.exec(from.iface);
        if (!m)
            return null;
        inVlan(from.dev, Number(m[1]), null, []);
    }
    else if (k === "ap")
        bridge(from.dev, null, true, []);
    else if (from.iface === "eth0")
        cross(from.dev, "eth0", null, []);
    else {
        const w = net.ops.wifi[from.dev];
        if (w?.status === "associated" && w.ap)
            bridge(w.ap, from.dev, false, []);
    }
    while (queue.length && !(found && mode === "unicast")) {
        const a = queue.shift();
        const kind = kindOf(net, a.dev);
        if (kind === "switch") {
            const e = effIf(net, a.dev, a.port);
            let vlan;
            if (e.mode === "trunk") {
                vlan = a.tag ?? e.nativeVlan;
                if (!(0, net2SwitchCli_1.trunkAllows)(e, vlan))
                    continue;
            }
            else {
                if (a.tag !== null)
                    continue;
                vlan = e.accessVlan;
                const cfg = psConfig(net, a.dev, a.port);
                if (cfg && !psAdmit(net, a.dev, a.port, cfg, mac))
                    continue;
            }
            if (!net.vlanDb.get(a.dev)?.has(vlan))
                continue;
            inVlan(a.dev, vlan, a.port, a.trail);
        }
        else if (kind === "router") {
            const st = rtState(net, a.dev);
            const subs = Object.keys(st.subinterfaces).filter(n => (0, net2RouterCli_1.parentOf)(n) === a.port && st.subinterfaces[n].vlan !== undefined && st.subinterfaces[n].shutdown !== true);
            if (a.tag === null) {
                const nat = subs.find(n => st.subinterfaces[n].native);
                offer({ dev: a.dev, iface: nat ?? a.port }, a.trail);
            }
            else {
                const s = subs.find(n => !st.subinterfaces[n].native && st.subinterfaces[n].vlan === a.tag);
                if (s)
                    offer({ dev: a.dev, iface: s }, a.trail);
            }
        }
        else if (kind === "ap") {
            if (a.port === "eth0" && a.tag === null)
                bridge(a.dev, null, false, a.trail);
        }
        else if (kind && a.port === "eth0" && a.tag === null)
            offer({ dev: a.dev, iface: "eth0" }, a.trail);
    }
    const hit = found;
    if (net.record && net.learn)
        for (const l of mode === "broadcast" ? learned : hit ? hit.trail : [])
            learnMac(net, l, mac);
    return hit ? hit.ep : null;
}
function arpLearn(net, at, ip, mac) {
    if (!net.record || !(0, net2Model_1.isHostKind)(kindOf(net, at.dev)))
        return;
    const list = (net.ops.arp[at.dev] ??= []);
    const i = list.findIndex(e => e.ip === ip && e.iface === at.iface);
    if (i >= 0)
        list[i] = { iface: at.iface, ip, mac };
    else if (list.length < exports.NET2_OPS_LIMITS.arpEntries)
        list.push({ iface: at.iface, ip, mac });
}
function arpResolve(net, from, ip) {
    const src = l3Of(net, from);
    if (!src)
        return null;
    const owner = l2Deliver(net, from, (0, exports.macOf)(from), ep => l3Of(net, ep)?.ip === ip, "broadcast");
    if (!owner)
        return null;
    if (!l2Deliver(net, owner, (0, exports.macOf)(owner), ep => sameEp(ep, from), "unicast"))
        return null;
    arpLearn(net, from, ip, (0, exports.macOf)(owner));
    arpLearn(net, owner, src.ip, (0, exports.macOf)(from));
    return owner;
}
function routerOwn(net, router, ip) {
    return endpointsOf(net, router).find(ep => l3Of(net, ep)?.ip === ip);
}
function routerEgress(net, router, ip) {
    let best;
    for (const ep of endpointsOf(net, router)) {
        const a = l3Of(net, ep);
        if (!a || !(0, net2Common_1.sameSubnet)(a.ip, ip, a.mask))
            continue;
        const len = (0, net2Common_1.prefixLength)(a.mask);
        if (!best || len > best.len)
            best = { ep, len };
    }
    return best?.ep;
}
function forwardLeg(net, from, dst) {
    const src = l3Of(net, from);
    if (!src)
        return { ok: false, reason: "SOURCE_NO_ADDRESS", routers: [] };
    if (src.ip === dst)
        return { ok: true, target: from, routers: [] };
    if (kindOf(net, from.dev) === "router") {
        const own = routerOwn(net, from.dev, dst);
        if (own)
            return { ok: true, target: own, routers: [] };
        const egress = routerEgress(net, from.dev, dst);
        if (!egress)
            return { ok: false, reason: "NO_ROUTE", routers: [] };
        const t = arpResolve(net, egress, dst);
        return t ? { ok: true, target: t, routers: [] } : { ok: false, reason: "DESTINATION_UNREACHABLE", routers: [] };
    }
    if ((0, net2Common_1.sameSubnet)(src.ip, dst, src.mask)) {
        const t = arpResolve(net, from, dst);
        return t ? { ok: true, target: t, routers: [] } : { ok: false, reason: "DESTINATION_UNREACHABLE", routers: [] };
    }
    const gw = src.gateway;
    if (!gw)
        return { ok: false, reason: "NO_GATEWAY", routers: [] };
    if (!(0, net2Common_1.sameSubnet)(gw, src.ip, src.mask))
        return { ok: false, reason: "GATEWAY_UNREACHABLE", routers: [] };
    const g = arpResolve(net, from, gw);
    if (!g)
        return { ok: false, reason: "GATEWAY_UNREACHABLE", routers: [] };
    if (kindOf(net, g.dev) !== "router")
        return { ok: false, reason: "GATEWAY_NOT_ROUTER", routers: [] };
    const routers = [g.dev];
    const own = routerOwn(net, g.dev, dst);
    if (own)
        return { ok: true, target: own, routers, gateway: gw };
    const egress = routerEgress(net, g.dev, dst);
    if (!egress)
        return { ok: false, reason: "NO_ROUTE", routers, gateway: gw };
    const t = arpResolve(net, egress, dst);
    return t ? { ok: true, target: t, routers, gateway: gw } : { ok: false, reason: "DESTINATION_UNREACHABLE", routers, gateway: gw };
}
function probe(net, from, dst) {
    const f = forwardLeg(net, from, dst);
    if (!f.ok)
        return { ok: false, reason: f.reason, routers: f.routers, replyRouters: [], ...(f.gateway ? { gateway: f.gateway } : {}) };
    const src = l3Of(net, from);
    const back = sameEp(f.target, from) ? { ok: true, target: from, routers: [] } : forwardLeg(net, f.target, src.ip);
    const g = f.gateway ? { gateway: f.gateway } : {};
    if (!back.ok || !sameEp(back.target, from))
        return { ok: false, reason: "REPLY_FAILED", target: f.target, routers: f.routers, replyRouters: [], ...g };
    const base = (0, net2Model_1.isHostKind)(kindOf(net, f.target.dev)) ? 128 : 255;
    return { ok: true, reason: "REACHABLE", target: f.target, routers: f.routers, replyRouters: back.routers, ttl: base - back.routers.length, ...g };
}
function pickSource(net, host, dst) {
    const eps = endpointsOf(net, host).filter(ep => l3Of(net, ep));
    if (dst) {
        const local = eps.find(ep => { const a = l3Of(net, ep); return (0, net2Common_1.sameSubnet)(a.ip, dst, a.mask); });
        if (local)
            return local;
    }
    return eps.find(ep => l3Of(net, ep).gateway) ?? eps[0];
}
function reachDevices(net, a, b) {
    const srcs = endpointsOf(net, a).filter(ep => l3Of(net, ep));
    if (!srcs.length)
        return { reachable: false, reason: "SOURCE_NO_ADDRESS" };
    const dsts = endpointsOf(net, b).map(ep => l3Of(net, ep)?.ip).filter((x) => !!x);
    if (!dsts.length)
        return { reachable: false, reason: "DESTINATION_NO_ADDRESS" };
    let first;
    for (const s of srcs)
        for (const d of dsts) {
            const p = probe(net, s, d);
            if (p.ok && p.target?.dev === b)
                return { reachable: true, reason: "REACHABLE", path: [a, ...p.routers, b] };
            first ??= p.ok ? "WRONG_DESTINATION" : p.reason;
        }
    return { reachable: false, reason: first ?? "UNREACHABLE" };
}
function dnsLookup(net, host, name) {
    const ep = pickSource(net, host);
    const dns = ep ? net.ops.adapters[host + "/" + ep.iface]?.dns : undefined;
    if (!ep || !dns)
        return { ok: false, reason: "NO_DNS_SERVER" };
    const src = pickSource(net, host, dns);
    const p = probe(net, src, dns);
    const svc = p.ok && p.target && kindOf(net, p.target.dev) === "server" ? hostState(net, p.target.dev).services?.dns : undefined;
    if (!svc || !svc.enabled)
        return { ok: false, reason: "DNS_UNREACHABLE", server: dns };
    const rec = svc.records.find(r => r.name === name.toLowerCase());
    return rec ? { ok: true, address: rec.address, server: dns } : { ok: false, reason: "NXDOMAIN", server: dns };
}
function httpGet(net, host, target) {
    let address = target;
    if (!/^\d+\.\d+\.\d+\.\d+$/.test(target)) {
        const r = dnsLookup(net, host, target);
        if (!r.ok)
            return { ok: false, reason: "UNRESOLVED" };
        address = r.address;
    }
    const src = pickSource(net, host, address);
    if (!src)
        return { ok: false, reason: "NO_ADDRESS" };
    const p = probe(net, src, address);
    const svc = p.ok && p.target && kindOf(net, p.target.dev) === "server" ? hostState(net, p.target.dev).services?.http : undefined;
    return svc && svc.enabled ? { ok: true, title: svc.title, body: svc.body, address } : { ok: false, reason: "TIMEOUT" };
}
function trunkPeers(net, sw) {
    const out = [];
    for (const { port: p, peer } of net.cabled.get(sw) ?? []) {
        if (kindOf(net, peer.deviceId) !== "switch" || !linkUp(net, sw, p))
            continue;
        if (effIf(net, sw, p).mode === "trunk" && effIf(net, peer.deviceId, peer.port).mode === "trunk")
            out.push(peer.deviceId);
    }
    return out;
}
const ownVlans = (st) => [1, ...Object.keys(st.vlans).map(Number)].sort((a, b) => a - b);
function computeVtp(net) {
    const out = {};
    for (const id of sortedIds(net, "switch")) {
        const st = swState(net, id), own = { revision: st.vtp.revision, source: null, vlans: ownVlans(st) };
        if (st.vtp.mode !== "client" || !st.vtp.domain) {
            out[id] = own;
            continue;
        }
        const same = (o) => o.vtp.domain === st.vtp.domain && o.vtp.password === st.vtp.password && o.vtp.version === st.vtp.version;
        const seen = new Set([id]), queue = [id];
        let best;
        while (queue.length) {
            const cur = queue.shift();
            for (const n of trunkPeers(net, cur)) {
                if (seen.has(n) || !same(swState(net, n)))
                    continue;
                seen.add(n);
                queue.push(n);
                const o = swState(net, n);
                if (o.vtp.mode === "server" && (!best || o.vtp.revision > swState(net, best).vtp.revision || (o.vtp.revision === swState(net, best).vtp.revision && n < best)))
                    best = n;
            }
        }
        if (best && swState(net, best).vtp.revision >= st.vtp.revision)
            out[id] = { revision: swState(net, best).vtp.revision, source: best, vlans: ownVlans(swState(net, best)) };
        else
            out[id] = own;
    }
    return out;
}
function effectiveVlanNames(net, sw) {
    const src = net.ops.vtp[sw]?.source;
    return clone((src ? swState(net, src) : swState(net, sw)).vlans);
}
function computeWifi(net) {
    const out = {};
    const aps = sortedIds(net, "ap");
    for (const id of net.config.devices.filter(d => (0, net2Model_1.adapterNames)(d).includes("wlan0")).map(d => d.id).sort()) {
        const intent = hostState(net, id).wifi;
        if (!intent) {
            out[id] = { status: "disconnected" };
            continue;
        }
        const ap = aps.find(a => apState(net, a).enabled && apState(net, a).ssid === intent.ssid);
        if (!ap) {
            out[id] = { status: "no-ssid", ssid: intent.ssid };
            continue;
        }
        const st = apState(net, ap);
        out[id] = st.security === "wpa2" && (st.passphrase.length < 8 || intent.passphrase !== st.passphrase) ? { status: "auth-failed", ssid: intent.ssid } : { status: "associated", ssid: intent.ssid, ap };
    }
    return out;
}
function dhcpServiceAt(net, ep) {
    const a = l3Of(net, ep);
    if (!a)
        return undefined;
    const k = kindOf(net, ep.dev);
    if (k === "router") {
        const st = rtState(net, ep.dev);
        const pools = Object.entries(st.dhcp.pools).filter(([, p]) => p.network && p.mask && (0, net2Common_1.sameSubnet)(a.ip, p.network, p.mask) && (0, net2Common_1.networkAddress)(a.ip, p.mask) === p.network)
            .sort(([n1, p1], [n2, p2]) => (0, net2Common_1.prefixLength)(p2.mask) - (0, net2Common_1.prefixLength)(p1.mask) || (n1 < n2 ? -1 : n1 > n2 ? 1 : 0));
        if (!pools.length)
            return undefined;
        const [name, p] = pools[0];
        const net0 = (0, net2Common_1.ipv4ToInt)(p.network), bc = (0, net2Common_1.ipv4ToInt)((0, net2Common_1.broadcastAddress)(p.network, p.mask));
        return { server: ep, serverIp: a.ip, pool: name, first: net0 + 1, last: bc - 1, mask: p.mask, ...(p.defaultRouter ? { gateway: p.defaultRouter } : {}), ...(p.dns ? { dns: p.dns } : {}), excluded: st.dhcp.excluded };
    }
    if (k === "server") {
        const svc = hostState(net, ep.dev).services?.dhcp;
        if (!svc || !svc.enabled || net.ops.adapters[ep.dev + "/" + ep.iface]?.status !== "static" || !(0, net2Common_1.sameSubnet)(svc.pool.start, a.ip, a.mask) || svc.pool.mask !== a.mask)
            return undefined;
        const start = (0, net2Common_1.ipv4ToInt)(svc.pool.start), bc = (0, net2Common_1.ipv4ToInt)((0, net2Common_1.broadcastAddress)(a.ip, a.mask));
        return { server: ep, serverIp: a.ip, pool: "serverPool", first: start, last: Math.min(start + svc.pool.max - 1, bc - 1), mask: svc.pool.mask, ...(svc.pool.defaultRouter ? { gateway: svc.pool.defaultRouter } : {}), ...(svc.pool.dns ? { dns: svc.pool.dns } : {}), excluded: [] };
    }
    return undefined;
}
function staticallyUsed(net) {
    const used = new Set();
    for (const d of net.config.devices) {
        const st = net.devices[d.id];
        if (d.kind === "router")
            for (const a of (0, net2RouterCli_1.routerAddresses)(st))
                used.add(a.ipAddress);
        else if (d.kind === "switch")
            for (const c of Object.values(st.interfaces)) {
                if (c.ipAddress)
                    used.add(c.ipAddress);
            }
        else if (d.kind === "ap") {
            if (st.address)
                used.add(st.address);
        }
        else
            for (const a of Object.values(st.adapters))
                if (a && a.mode === "static" && a.address)
                    used.add(a.address);
    }
    return used;
}
function apipaFor(mac, taken) {
    const h = (0, net2Common_1.fnv1a)("apipa:" + mac);
    let n = ((1 + (h % 254)) << 8) | ((h >>> 8) & 255);
    for (let i = 0; i < 65024; i++) {
        const ip = "169.254." + (n >> 8) + "." + (n & 255);
        if (!taken.has(ip))
            return ip;
        n = n + 1 > (254 << 8) + 255 ? 256 : n + 1;
    }
    return "169.254.1.0";
}
function lowestFree(s, taken) {
    const ranges = s.excluded.map(([a, b]) => [(0, net2Common_1.ipv4ToInt)(a), (0, net2Common_1.ipv4ToInt)(b)]);
    let n = s.first;
    for (let guard = 0; n <= s.last && guard < 4096; guard++) {
        const r = ranges.find(([a, b]) => n >= a && n <= b);
        if (r) {
            n = r[1] + 1;
            continue;
        }
        const ip = (0, net2Common_1.intToIpv4)(n);
        if (!taken(ip))
            return ip;
        n++;
    }
    return undefined;
}
function computeAdapters(net) {
    const prev = net.ops.adapters;
    const adapters = {};
    const clients = [];
    const hosts = net.config.devices.filter(d => (0, net2Model_1.isHostKind)(d.kind)).map(d => d.id).sort();
    for (const id of hosts)
        for (const iface of (0, net2Model_1.adapterNames)(net.dev.get(id))) {
            const cfg = hostState(net, id).adapters[iface] ?? { mode: "static" };
            const k = id + "/" + iface;
            if (cfg.mode === "static") {
                const o = { status: "static" };
                if (cfg.address && cfg.mask) {
                    o.address = cfg.address;
                    o.mask = cfg.mask;
                }
                if (cfg.gateway)
                    o.gateway = cfg.gateway;
                if (cfg.dns)
                    o.dns = cfg.dns;
                adapters[k] = o;
                continue;
            }
            if (!(0, exports.hostConnected)(net, id, iface)) {
                adapters[k] = { status: "disconnected" };
                continue;
            }
            if (cfg.released) {
                adapters[k] = { status: "released" };
                continue;
            }
            adapters[k] = prev[k]?.status === "dhcp" || prev[k]?.status === "apipa" ? { ...prev[k] } : { status: "apipa" };
            clients.push({ id, iface, key: k });
        }
    net.ops.adapters = adapters;
    const services = new Map();
    for (const c of clients) {
        const ep = { dev: c.id, iface: c.iface }, mac = (0, exports.macOf)(ep);
        const hold = {};
        const server = l2Deliver(net, ep, mac, e => (hold.svc = dhcpServiceAt(net, e)) !== undefined, "broadcast");
        if (server && hold.svc && l2Deliver(net, server, (0, exports.macOf)(server), e => sameEp(e, ep), "unicast"))
            services.set(c.key, hold.svc);
    }
    const used = staticallyUsed(net), leased = new Set();
    const bindings = {};
    const fits = (s, ip) => {
        const n = (0, net2Common_1.ipv4ToInt)(ip);
        return n >= s.first && n <= s.last && !used.has(ip) && !leased.has(ip) && !s.excluded.some(([a, b]) => (0, net2Common_1.ipCompare)(ip, a) >= 0 && (0, net2Common_1.ipCompare)(ip, b) <= 0);
    };
    const lease = (c, s, ip) => {
        leased.add(ip);
        const o = { status: "dhcp", address: ip, mask: s.mask };
        if (s.gateway)
            o.gateway = s.gateway;
        if (s.dns)
            o.dns = s.dns;
        o.dhcpServer = s.serverIp;
        adapters[c.key] = o;
        (bindings[s.server.dev] ??= []).push({ address: ip, mac: (0, exports.macOf)({ dev: c.id, iface: c.iface }), client: c.key, pool: s.pool });
    };
    const pending = [];
    for (const c of clients) {
        const s = services.get(c.key), p = prev[c.key];
        if (s && p?.status === "dhcp" && p.address && p.dhcpServer === s.serverIp && p.mask === s.mask && fits(s, p.address))
            lease(c, s, p.address);
        else
            pending.push(c);
    }
    const apipaTaken = new Set();
    for (const c of pending) {
        const s = services.get(c.key);
        let ip;
        if (s)
            ip = lowestFree(s, a => used.has(a) || leased.has(a));
        if (s && ip) {
            lease(c, s, ip);
            continue;
        }
        const addr = apipaFor((0, exports.macOf)({ dev: c.id, iface: c.iface }), apipaTaken);
        apipaTaken.add(addr);
        adapters[c.key] = { status: "apipa", address: addr, mask: "255.255.0.0" };
    }
    for (const k of Object.keys(bindings))
        bindings[k].sort((a, b) => (0, net2Common_1.ipCompare)(a.address, b.address));
    net.ops.adapters = adapters;
    net.ops.dhcpBindings = bindings;
}
function sortRecord(r) { const o = {}; for (const k of Object.keys(r).sort())
    o[k] = r[k]; return o; }
function canonicalOps(ops) {
    const nonEmpty = (r, cmp) => { const o = {}; for (const k of Object.keys(r).sort())
        if (r[k].length)
            o[k] = [...r[k]].sort(cmp); return o; };
    return {
        adapters: sortRecord(ops.adapters), wifi: sortRecord(ops.wifi),
        dhcpBindings: nonEmpty(ops.dhcpBindings, (a, b) => (0, net2Common_1.ipCompare)(a.address, b.address)), vtp: sortRecord(ops.vtp), portSecurity: sortRecord(ops.portSecurity),
        arp: nonEmpty(ops.arp, (a, b) => (a.iface < b.iface ? -1 : a.iface > b.iface ? 1 : (0, net2Common_1.ipCompare)(a.ip, b.ip))),
        macTables: nonEmpty(ops.macTables, (a, b) => a.vlan - b.vlan || (a.mac < b.mac ? -1 : a.mac > b.mac ? 1 : 0))
    };
}
function settleLearned(net) {
    for (const sw of Object.keys(net.ops.macTables)) {
        if (kindOf(net, sw) !== "switch") {
            delete net.ops.macTables[sw];
            continue;
        }
        net.ops.macTables[sw] = net.ops.macTables[sw].filter(e => linkUp(net, sw, e.port));
    }
    for (const h of Object.keys(net.ops.arp)) {
        if (!(0, net2Model_1.isHostKind)(kindOf(net, h))) {
            delete net.ops.arp[h];
            continue;
        }
        net.ops.arp[h] = net.ops.arp[h].filter(e => { const a = l3Of(net, { dev: h, iface: e.iface }); return !!a && (0, net2Common_1.sameSubnet)(a.ip, e.ip, a.mask); });
    }
}
function reconcile(config, devices, prev) {
    const net = makeNet(config, devices, clone(prev), true);
    net.ops.vtp = computeVtp(net);
    refreshVlanDb(net);
    net.ops.wifi = computeWifi(net);
    settlePortSecurity(net);
    for (let round = 0; round < exports.NET2_OPS_LIMITS.reconcileRounds; round++) {
        const before = JSON.stringify([net.ops.adapters, net.ops.dhcpBindings, net.ops.portSecurity]);
        computeAdapters(net);
        settlePortSecurity(net);
        if (JSON.stringify([net.ops.adapters, net.ops.dhcpBindings, net.ops.portSecurity]) === before)
            break;
    }
    settleLearned(net);
    return canonicalOps(net.ops);
}
function withTraffic(config, devices, ops, run) {
    const net = makeNet(config, devices, clone(ops), true);
    net.learn = true;
    const result = run(net);
    return { result, ops: net.ops };
}
function switchContext(net, sw) {
    const v = net.ops.vtp[sw];
    return {
        linkUp: p => linkUp(net, sw, p),
        errDisabled: p => (0, exports.isErrDisabled)(net, sw, p),
        effectiveVlans: { vlans: effectiveVlanNames(net, sw), revision: v ? v.revision : swState(net, sw).vtp.revision, source: v ? v.source : null },
        macTable: (net.ops.macTables[sw] ?? []).map(e => ({ ...e })),
        portSecurity: p => {
            const cfg = psConfig(net, sw, p);
            if (!cfg)
                return undefined;
            const o = net.ops.portSecurity[key(sw, p)] ?? { seen: [], secure: [...cfg.macs], violations: 0, errDisabled: false };
            return { secure: o.secure.map(mac => ({ mac, type: cfg.macs.includes(mac) ? "static" : cfg.sticky ? "sticky" : "dynamic" })), violations: o.violations, errDisabled: o.errDisabled };
        }
    };
}
function routerContext(net, r) {
    return { linkUp: p => linkUp(net, r, p), bindings: (net.ops.dhcpBindings[r] ?? []).map(b => ({ address: b.address, mac: b.mac, pool: b.pool })) };
}
