// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isSviName = exports.NETWORK_CLI_STATE_VERSION = exports.networkCliStateFingerprint = exports.targetCheckCount = exports.isNetworkCliAnswerAnswered = exports.networkCliScoringMode = exports.networkCliQuestionVersion = exports.defaultNetworkCliAnswerKey = exports.defaultNetworkCliConfig = exports.NETWORK_CLI_SCORING_MODES = exports.NETWORK_CLI_TYPE_KEY = void 0;
exports.initialStateOf = initialStateOf;
exports.projectNetworkCliConfigForStudent = projectNetworkCliConfigForStudent;
exports.validateNetworkCliQuestion = validateNetworkCliQuestion;
exports.normalizeNetworkCliAnswer = normalizeNetworkCliAnswer;
exports.bindNetworkCliAnswerToQuestion = bindNetworkCliAnswerToQuestion;
exports.evaluateNetworkCliTarget = evaluateNetworkCliTarget;
exports.scoreNetworkCli = scoreNetworkCli;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const networkCliEngine_1 = require("./networkCliEngine");
Object.defineProperty(exports, "NETWORK_CLI_STATE_VERSION", { enumerable: true, get: function () { return networkCliEngine_1.NETWORK_CLI_STATE_VERSION; } });
Object.defineProperty(exports, "isSviName", { enumerable: true, get: function () { return networkCliEngine_1.isSviName; } });
exports.NETWORK_CLI_TYPE_KEY = "networkCli";
exports.NETWORK_CLI_SCORING_MODES = Object.freeze(["proportional", "allOrNothing"]);
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);
const INTERFACE_TARGET_FIELDS = ["mode", "accessVlan", "nativeVlan", "shutdown", "ipAddress", "subnetMask"];
const defaultNetworkCliConfig = () => ({ device: "switch", initialState: (0, networkCliEngine_1.createDeviceState)() });
exports.defaultNetworkCliConfig = defaultNetworkCliConfig;
const defaultNetworkCliAnswerKey = () => ({ targetState: {}, scoring: "proportional" });
exports.defaultNetworkCliAnswerKey = defaultNetworkCliAnswerKey;
const networkCliQuestionVersion = (node) => (isObj(node) ? (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(exports.NETWORK_CLI_TYPE_KEY, node.questionTypeVersion) : undefined);
exports.networkCliQuestionVersion = networkCliQuestionVersion;
const networkCliScoringMode = (answerKey) => (isObj(answerKey) && answerKey.scoring === "allOrNothing" ? "allOrNothing" : "proportional");
exports.networkCliScoringMode = networkCliScoringMode;
function initialStateOf(cfg) {
    const s = (0, networkCliEngine_1.canonicalizeState)(cfg.initialState);
    const vlans = { ...s.vlans };
    for (const name of Object.keys(s.interfaces)) {
        const v = s.interfaces[name].accessVlan;
        if (v !== undefined && v !== 1 && !vlans[String(v)])
            vlans[String(v)] = {};
    }
    return (0, networkCliEngine_1.canonicalizeState)({ ...s, vlans });
}
const STATE_KEYS = ["v", "device", "hostname", "vlans", "interfaces"];
function pickStateShape(raw) {
    if (!isObj(raw))
        return raw;
    const out = {};
    for (const k of STATE_KEYS)
        if (raw[k] !== undefined)
            out[k] = raw[k];
    if (isObj(out.vlans)) {
        const v = {};
        for (const id of Object.keys(out.vlans)) {
            if (FORBIDDEN.has(id))
                return undefined;
            const e = out.vlans[id];
            v[id] = isObj(e) ? (e.name === undefined ? {} : { name: e.name }) : e;
        }
        out.vlans = v;
    }
    if (isObj(out.interfaces)) {
        const ifs = {};
        for (const n of Object.keys(out.interfaces)) {
            if (FORBIDDEN.has(n))
                return undefined;
            const e = out.interfaces[n];
            if (!isObj(e)) {
                ifs[n] = e;
                continue;
            }
            const c = {};
            for (const f of INTERFACE_TARGET_FIELDS)
                if (e[f] !== undefined)
                    c[f] = e[f];
            ifs[n] = c;
        }
        out.interfaces = ifs;
    }
    return out;
}
function projectNetworkCliConfigForStudent(cfg) {
    if (!isObj(cfg) || cfg.device !== "switch")
        return undefined;
    const st = (0, networkCliEngine_1.normalizeDeviceState)(pickStateShape(cfg.initialState));
    if (!st.ok)
        return undefined;
    return { device: "switch", initialState: initialStateOf({ device: "switch", initialState: st.state }) };
}
const err = (code, message, path) => ({ code, message, severity: "error", path });
const PUBLIC_KEYS = new Set(["device", "initialState"]);
const TARGET_KEYS = new Set(["hostname", "vlans", "interfaces"]);
function validateTargetInterface(rawName, entry, where, out) {
    const name = FORBIDDEN.has(rawName) ? null : (0, networkCliEngine_1.normalizeInterfaceName)(rawName);
    if (!name) {
        out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "واجهة غير موجودة على هذا الجهاز في الحالة المستهدفة: " + rawName, where));
        return undefined;
    }
    if (!isObj(entry)) {
        out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "إعداد الواجهة المستهدف غير صالح: " + rawName, where));
        return undefined;
    }
    const physical = (0, networkCliEngine_1.isPhysicalPort)(name);
    let checks = 0;
    for (const k of Object.keys(entry)) {
        if (!INTERFACE_TARGET_FIELDS.includes(k)) {
            out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "حقل غير معروف في الواجهة المستهدفة " + rawName + ": " + k, where));
            continue;
        }
        const v = entry[k];
        let ok = true;
        if (k === "mode")
            ok = physical && (v === "access" || v === "trunk");
        else if (k === "accessVlan" || k === "nativeVlan")
            ok = physical && typeof v === "number" && (0, networkCliEngine_1.parseVlanId)(String(v), { allowOne: true, allowReserved: false }) !== null;
        else if (k === "shutdown")
            ok = typeof v === "boolean";
        else if (k === "ipAddress")
            ok = !physical && typeof v === "string" && (0, networkCliEngine_1.isIpv4)(v);
        else if (k === "subnetMask")
            ok = !physical && typeof v === "string" && (0, networkCliEngine_1.isSubnetMask)(v);
        if (!ok)
            out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "قيمة غير صالحة في الواجهة المستهدفة " + (0, networkCliEngine_1.displayInterfaceName)(name) + ": " + k, where));
        else
            checks++;
    }
    if (typeof entry.ipAddress === "string" && typeof entry.subnetMask === "string" && (0, networkCliEngine_1.isIpv4)(entry.ipAddress) && (0, networkCliEngine_1.isSubnetMask)(entry.subnetMask) && !(0, networkCliEngine_1.isUsableHostAddress)(entry.ipAddress, entry.subnetMask))
        out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "عنوان IP المستهدف ليس عنوان مضيف صالحًا ضمن قناعه: " + (0, networkCliEngine_1.displayInterfaceName)(name), where));
    return { name, checks };
}
function validateNetworkCliQuestion(node) {
    const out = [];
    if ((0, exports.networkCliQuestionVersion)(node) === undefined)
        out.push(err("NETCLI_VERSION_UNSUPPORTED", "إصدار سؤال محاكي الشبكة غير مدعوم في هذا الإصدار من التطبيق.", "questionTypeVersion"));
    const cfg = node.networkCli;
    if (!isObj(cfg))
        return [...out, err("NETCLI_CONFIG_MISSING", "إعداد محاكي الشبكة مفقود أو غير صالح.", "networkCli")];
    for (const k of Object.keys(cfg))
        if (!PUBLIC_KEYS.has(k))
            out.push(err("NETCLI_CONFIG_UNKNOWN_KEY", "حقل غير معروف في إعداد المحاكي: " + k, "networkCli." + k));
    if (cfg.device !== "switch")
        out.push(err("NETCLI_DEVICE_UNSUPPORTED", "نوع الجهاز غير مدعوم في هذا الإصدار (المدعوم: switch).", "networkCli.device"));
    const st = (0, networkCliEngine_1.normalizeDeviceState)(cfg.initialState);
    if (!st.ok)
        out.push(err("NETCLI_INITIAL_STATE_INVALID", "الحالة الابتدائية للجهاز غير صالحة (" + st.detail + ").", "networkCli.initialState"));
    const key = node.answer;
    if (!isObj(key) || !isObj(key.targetState))
        return [...out, err("NETCLI_TARGET_MISSING", "الحالة المستهدفة (مفتاح التصحيح) مفقودة.", "answer.targetState")];
    const t = key.targetState;
    let checks = 0;
    for (const k of Object.keys(t))
        if (!TARGET_KEYS.has(k))
            out.push(err("NETCLI_TARGET_UNKNOWN_KEY", "حقل غير معروف في الحالة المستهدفة: " + k, "answer.targetState." + k));
    if (t.hostname !== undefined) {
        if (typeof t.hostname === "string" && (0, networkCliEngine_1.isValidHostname)(t.hostname))
            checks++;
        else
            out.push(err("NETCLI_TARGET_HOSTNAME_INVALID", "اسم الجهاز المستهدف غير صالح.", "answer.targetState.hostname"));
    }
    if (t.vlans !== undefined) {
        if (!isObj(t.vlans))
            out.push(err("NETCLI_TARGET_VLAN_INVALID", "قائمة VLAN المستهدفة غير صالحة.", "answer.targetState.vlans"));
        else
            for (const id of Object.keys(t.vlans)) {
                const where = "answer.targetState.vlans." + id;
                if (FORBIDDEN.has(id) || (0, networkCliEngine_1.parseVlanId)(id, { allowOne: false, allowReserved: false }) === null) {
                    out.push(err("NETCLI_TARGET_VLAN_INVALID", "رقم VLAN مستهدف غير صالح (2–4094، بلا المحجوزة): " + id, where));
                    continue;
                }
                const v = t.vlans[id];
                if (!isObj(v) || Object.keys(v).some(x => x !== "name")) {
                    out.push(err("NETCLI_TARGET_VLAN_INVALID", "إدخال VLAN المستهدف غير صالح: " + id, where));
                    continue;
                }
                checks++;
                if (v.name !== undefined) {
                    if (typeof v.name === "string" && (0, networkCliEngine_1.isValidVlanName)(v.name))
                        checks++;
                    else
                        out.push(err("NETCLI_TARGET_VLAN_INVALID", "اسم VLAN المستهدف غير صالح: " + id, where));
                }
            }
    }
    if (t.interfaces !== undefined) {
        if (!isObj(t.interfaces))
            out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "قائمة الواجهات المستهدفة غير صالحة.", "answer.targetState.interfaces"));
        else {
            const seen = new Set();
            for (const raw of Object.keys(t.interfaces)) {
                const r = validateTargetInterface(raw, t.interfaces[raw], "answer.targetState.interfaces." + raw, out);
                if (!r)
                    continue;
                if (seen.has(r.name))
                    out.push(err("NETCLI_TARGET_INTERFACE_INVALID", "الواجهة مكررة في الحالة المستهدفة: " + raw, "answer.targetState.interfaces." + raw));
                seen.add(r.name);
                checks += r.checks;
            }
        }
    }
    if (checks === 0 && !out.some(i => i.code.startsWith("NETCLI_TARGET_") && i.code !== "NETCLI_TARGET_UNKNOWN_KEY"))
        out.push(err("NETCLI_TARGET_EMPTY", "حدّد عنصرًا واحدًا على الأقل في الحالة المستهدفة (اسم الجهاز، VLAN، أو إعداد واجهة).", "answer.targetState"));
    if (key.scoring !== undefined && !exports.NETWORK_CLI_SCORING_MODES.includes(key.scoring))
        out.push(err("NETCLI_SCORING_UNKNOWN", "طريقة احتساب العلامة غير معروفة.", "answer.scoring"));
    return out;
}
function normalizeNetworkCliAnswer(a) {
    if (!isObj(a) || a.kind !== "networkCli" || !Array.isArray(a.commands))
        return { ok: false, code: "NETCLI_ANSWER_INVALID" };
    if (a.commands.length > networkCliEngine_1.NETWORK_CLI_LIMITS.commands)
        return { ok: false, code: "NETCLI_HISTORY_TOO_LARGE" };
    const commands = [];
    for (const c of a.commands) {
        if (typeof c !== "string" || c.length > networkCliEngine_1.NETWORK_CLI_LIMITS.inputChars)
            return { ok: false, code: "NETCLI_ANSWER_INVALID" };
        commands.push(c);
    }
    const st = (0, networkCliEngine_1.normalizeDeviceState)(a.state);
    if (!st.ok)
        return { ok: false, code: "NETCLI_ANSWER_INVALID" };
    return { ok: true, answer: { kind: "networkCli", commands, state: st.state } };
}
function bindNetworkCliAnswerToQuestion(a, question) {
    const base = normalizeNetworkCliAnswer(a);
    if (!base.ok)
        return base;
    if (!isObj(question) || String(question.presentationType ?? question.type ?? "") !== exports.NETWORK_CLI_TYPE_KEY || (0, exports.networkCliQuestionVersion)(question) === undefined)
        return { ok: false, code: "NETCLI_QUESTION_MISMATCH" };
    const cfg = projectNetworkCliConfigForStudent(question.networkCli);
    if (!cfg)
        return { ok: false, code: "NETCLI_QUESTION_INVALID" };
    const replay = (0, networkCliEngine_1.replayCommands)(cfg.initialState, base.answer.commands);
    return { ok: true, answer: { kind: "networkCli", commands: base.answer.commands, state: replay.session.state } };
}
const isNetworkCliAnswerAnswered = (a) => isObj(a) && a.kind === "networkCli" && Array.isArray(a.commands) && a.commands.some(c => typeof c === "string" && c.trim() !== "");
exports.isNetworkCliAnswerAnswered = isNetworkCliAnswerAnswered;
const show = (v) => (v === undefined ? "—" : typeof v === "boolean" ? (v ? "shutdown" : "no shutdown") : String(v));
const FIELD_LABEL = { mode: "وضع المنفذ (access / trunk)", accessVlan: "VLAN الوصول", nativeVlan: "Native VLAN", shutdown: "الحالة الإدارية", ipAddress: "عنوان IPv4", subnetMask: "قناع الشبكة" };
function evaluateNetworkCliTarget(target, state) {
    const c = (0, networkCliEngine_1.canonicalizeState)(state);
    const out = [];
    if (typeof target.hostname === "string")
        out.push({ id: "hostname", label: "اسم الجهاز", expected: target.hostname, actual: c.hostname, ok: c.hostname === target.hostname });
    for (const id of Object.keys(target.vlans ?? {}).filter(k => !FORBIDDEN.has(k)).sort((a, b) => Number(a) - Number(b))) {
        const t = target.vlans[id];
        const exists = id === "1" || !!c.vlans[id];
        out.push({ id: "vlan:" + id + ":exists", label: "VLAN " + id + " موجودة", expected: "موجودة", actual: exists ? "موجودة" : "غير موجودة", ok: exists });
        if (t && typeof t.name === "string") {
            const actual = c.vlans[id]?.name;
            out.push({ id: "vlan:" + id + ":name", label: "اسم VLAN " + id, expected: t.name, actual: show(actual), ok: actual === t.name });
        }
    }
    const byName = new Map();
    for (const raw of Object.keys(target.interfaces ?? {})) {
        const n = FORBIDDEN.has(raw) ? null : (0, networkCliEngine_1.normalizeInterfaceName)(raw);
        const v = target.interfaces[raw];
        if (n && isObj(v) && !byName.has(n))
            byName.set(n, v);
    }
    for (const name of (0, networkCliEngine_1.sortInterfaceNames)([...byName.keys()])) {
        const t = byName.get(name), exists = (0, networkCliEngine_1.interfaceExists)(c, name), e = (0, networkCliEngine_1.effectiveInterfaceConfig)(c, name);
        for (const f of INTERFACE_TARGET_FIELDS) {
            if (t[f] === undefined)
                continue;
            const actual = exists ? e[f] : undefined;
            out.push({ id: "if:" + name + ":" + f, label: (0, networkCliEngine_1.displayInterfaceName)(name) + " — " + FIELD_LABEL[f], expected: show(t[f]), actual: show(actual), ok: actual === t[f] });
        }
    }
    return out;
}
const targetCheckCount = (target) => evaluateNetworkCliTarget(target, (0, networkCliEngine_1.createDeviceState)()).length;
exports.targetCheckCount = targetCheckCount;
function scoreNetworkCli(input) {
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const cfg = projectNetworkCliConfigForStudent(input.config);
    const target = isObj(input.answerKey) && isObj(input.answerKey.targetState) ? input.answerKey.targetState : undefined;
    const total = target ? (0, exports.targetCheckCount)(target) : 0;
    if (!cfg || !target || total === 0)
        return { score: 0, correct: false, manualReview: true, parts: { correct: 0, total } };
    const base = normalizeNetworkCliAnswer(input.response);
    if (!base.ok)
        return { score: 0, correct: false, manualReview: false, parts: { correct: 0, total } };
    const state = (0, networkCliEngine_1.replayCommands)(cfg.initialState, base.answer.commands).session.state;
    const checks = evaluateNetworkCliTarget(target, state);
    const passed = checks.filter(c => c.ok).length;
    const all = passed === checks.length;
    const score = (0, exports.networkCliScoringMode)(input.answerKey) === "allOrNothing" ? (all ? max : 0) : max * passed / checks.length;
    return { score: Math.min(max, Math.max(0, score)), correct: all, manualReview: false, parts: { correct: passed, total: checks.length } };
}
const networkCliStateFingerprint = (state) => (0, networkCliEngine_1.serializeState)(state);
exports.networkCliStateFingerprint = networkCliStateFingerprint;
