// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.topologyDevice = exports.serializeTopologyState = exports.isValidDeviceLabel = exports.isValidLinkId = exports.isValidDeviceId = exports.PC_FIELDS = exports.devicePorts = exports.PC_PORTS = exports.TOPOLOGY_DEVICE_KINDS = exports.TOPOLOGY_LIMITS = exports.TOPOLOGY_STATE_VERSION = exports.TOPOLOGY_CONFIG_VERSION = exports.NETWORK_TOPOLOGY_PLUGIN_VERSION = exports.NETWORK_TOPOLOGY_PLUGIN_KEY = void 0;
exports.isValidPcValue = isValidPcValue;
exports.canonicalPcConfig = canonicalPcConfig;
exports.validateTopologyConfig = validateTopologyConfig;
exports.initialTopologyState = initialTopologyState;
exports.canonicalizeTopologyState = canonicalizeTopologyState;
exports.linkAt = linkAt;
const networkCliEngine_1 = require("./networkCliEngine");
const routerCliEngine_1 = require("./routerCliEngine");
exports.NETWORK_TOPOLOGY_PLUGIN_KEY = "networkTopology";
exports.NETWORK_TOPOLOGY_PLUGIN_VERSION = 1;
exports.TOPOLOGY_CONFIG_VERSION = 1;
exports.TOPOLOGY_STATE_VERSION = 1;
exports.TOPOLOGY_LIMITS = Object.freeze({ devices: 20, links: 40, labelChars: 24, commandsPerDevice: 300, actions: 1000, pcValueChars: 15 });
exports.TOPOLOGY_DEVICE_KINDS = Object.freeze(["router", "switch", "pc"]);
exports.PC_PORTS = Object.freeze(["eth0"]);
const devicePorts = (kind) => (kind === "router" ? routerCliEngine_1.ROUTER_PORTS : kind === "switch" ? networkCliEngine_1.SWITCH_PORTS : exports.PC_PORTS);
exports.devicePorts = devicePorts;
exports.PC_FIELDS = Object.freeze(["address", "mask", "gateway", "dns"]);
const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const DEVICE_ID = /^[a-z][a-z0-9_-]{0,31}$/;
const LINK_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/;
const CONTROL = /[\u0000-\u001f\u007f]/;
const isValidDeviceId = (id) => typeof id === "string" && DEVICE_ID.test(id) && !FORBIDDEN.has(id);
exports.isValidDeviceId = isValidDeviceId;
const isValidLinkId = (id) => typeof id === "string" && LINK_ID.test(id) && !FORBIDDEN.has(id);
exports.isValidLinkId = isValidLinkId;
const isValidDeviceLabel = (label) => typeof label === "string" && !!label.trim() && label.length <= exports.TOPOLOGY_LIMITS.labelChars && !CONTROL.test(label);
exports.isValidDeviceLabel = isValidDeviceLabel;
const isUnit = (n) => typeof n === "number" && Number.isFinite(n) && n >= 0 && n <= 1;
function isValidPcValue(field, value) {
    if (typeof value !== "string" || value.length > exports.TOPOLOGY_LIMITS.pcValueChars)
        return false;
    if (value === "")
        return true;
    return field === "mask" ? (0, networkCliEngine_1.isSubnetMask)(value) : (0, networkCliEngine_1.isIpv4)(value);
}
function canonicalPcConfig(raw) {
    const out = {};
    for (const f of exports.PC_FIELDS) {
        const v = raw[f];
        if (typeof v === "string" && v !== "" && isValidPcValue(f, v))
            out[f] = v;
    }
    return out;
}
function normalizeInitialPc(raw) {
    if (!isObj(raw) || Object.keys(raw).some(k => FORBIDDEN.has(k) || !exports.PC_FIELDS.includes(k)))
        return undefined;
    for (const f of exports.PC_FIELDS)
        if (raw[f] !== undefined && !isValidPcValue(f, raw[f]))
            return undefined;
    const c = canonicalPcConfig(raw);
    if ((c.address === undefined) !== (c.mask === undefined))
        return undefined;
    if (c.address && c.mask && !(0, networkCliEngine_1.isUsableHostAddress)(c.address, c.mask))
        return undefined;
    return c;
}
const CONFIG_KEYS = new Set(["v", "devices", "links"]);
const DEVICE_KEYS = new Set(["id", "kind", "label", "x", "y", "initial"]);
const LINK_KEYS = new Set(["id", "a", "b"]);
const ENDPOINT_KEYS = new Set(["deviceId", "port"]);
function validateTopologyConfig(raw) {
    const out = [];
    const err = (code, message, path) => out.push(path === undefined ? { code, message } : { code, message, path });
    if (!isObj(raw))
        return { ok: false, issues: [{ code: "NETTOPO_CONFIG_INVALID", message: "إعداد الشبكة مفقود أو غير صالح.", path: "config" }] };
    for (const k of Object.keys(raw))
        if (!CONFIG_KEYS.has(k))
            err("NETTOPO_CONFIG_UNKNOWN_KEY", "حقل غير معروف في إعداد الشبكة: " + k, "config." + k);
    if (raw.v !== exports.TOPOLOGY_CONFIG_VERSION)
        err("NETTOPO_CONFIG_VERSION_UNSUPPORTED", "إصدار إعداد الشبكة غير مدعوم.", "config.v");
    if (!Array.isArray(raw.devices) || !Array.isArray(raw.links)) {
        err("NETTOPO_CONFIG_INVALID", "قائمة الأجهزة أو الوصلات غير صالحة.", "config");
        return { ok: false, issues: out };
    }
    if (raw.devices.length === 0)
        err("NETTOPO_NO_DEVICES", "أضف جهازًا واحدًا على الأقل إلى المخطط.", "config.devices");
    if (raw.devices.length > exports.TOPOLOGY_LIMITS.devices) {
        err("NETTOPO_TOO_MANY_DEVICES", "عدد الأجهزة يتجاوز الحد (" + exports.TOPOLOGY_LIMITS.devices + ").", "config.devices");
        return { ok: false, issues: out };
    }
    if (raw.links.length > exports.TOPOLOGY_LIMITS.links) {
        err("NETTOPO_TOO_MANY_LINKS", "عدد الوصلات يتجاوز الحد (" + exports.TOPOLOGY_LIMITS.links + ").", "config.links");
        return { ok: false, issues: out };
    }
    const devices = [];
    const kinds = new Map();
    raw.devices.forEach((d, i) => {
        const where = "config.devices[" + i + "]";
        if (!isObj(d) || Object.keys(d).some(k => !DEVICE_KEYS.has(k))) {
            err("NETTOPO_DEVICE_INVALID", "الجهاز رقم " + (i + 1) + " يحتوي حقولًا غير معروفة أو غير صالح.", where);
            return;
        }
        let ok = true;
        if (!(0, exports.isValidDeviceId)(d.id)) {
            err("NETTOPO_DEVICE_ID_INVALID", "معرّف الجهاز رقم " + (i + 1) + " غير صالح (حروف إنجليزية صغيرة وأرقام، يبدأ بحرف).", where + ".id");
            ok = false;
        }
        else if (kinds.has(d.id)) {
            err("NETTOPO_DEVICE_ID_DUPLICATE", "معرّف جهاز مكرر: " + d.id, where + ".id");
            ok = false;
        }
        if (!exports.TOPOLOGY_DEVICE_KINDS.includes(d.kind)) {
            err("NETTOPO_DEVICE_KIND_UNSUPPORTED", "نوع جهاز غير مدعوم في هذا الإصدار: " + String(d.kind) + " (المدعوم: راوتر، سويتش، حاسوب).", where + ".kind");
            ok = false;
        }
        if (!(0, exports.isValidDeviceLabel)(d.label)) {
            err("NETTOPO_DEVICE_LABEL_INVALID", "اسم العرض للجهاز رقم " + (i + 1) + " مطلوب (حتى " + exports.TOPOLOGY_LIMITS.labelChars + " حرفًا).", where + ".label");
            ok = false;
        }
        if (!isUnit(d.x) || !isUnit(d.y)) {
            err("NETTOPO_DEVICE_POSITION_INVALID", "موضع الجهاز رقم " + (i + 1) + " غير صالح.", where);
            ok = false;
        }
        if (!ok)
            return;
        const kind = d.kind;
        const dev = { id: d.id, kind, label: d.label, x: d.x, y: d.y };
        if (d.initial !== undefined) {
            const init = kind === "pc" ? normalizeInitialPc(d.initial) : kind === "switch" ? (() => { const r = (0, networkCliEngine_1.normalizeDeviceState)(d.initial); return r.ok ? r.state : undefined; })() : (() => { const r = (0, routerCliEngine_1.normalizeRouterState)(d.initial); return r.ok ? r.state : undefined; })();
            if (!init) {
                err("NETTOPO_DEVICE_INITIAL_INVALID", "الحالة الابتدائية للجهاز «" + dev.label + "» غير صالحة.", where + ".initial");
                return;
            }
            dev.initial = init;
        }
        kinds.set(dev.id, kind);
        devices.push(dev);
    });
    const links = [];
    const linkIds = new Set(), usedPorts = new Set();
    raw.links.forEach((l, i) => {
        const where = "config.links[" + i + "]";
        if (!isObj(l) || Object.keys(l).some(k => !LINK_KEYS.has(k)) || !isObj(l.a) || !isObj(l.b) || Object.keys(l.a).some(k => !ENDPOINT_KEYS.has(k)) || Object.keys(l.b).some(k => !ENDPOINT_KEYS.has(k))) {
            err("NETTOPO_LINK_INVALID", "الوصلة رقم " + (i + 1) + " غير صالحة.", where);
            return;
        }
        let ok = true;
        if (!(0, exports.isValidLinkId)(l.id)) {
            err("NETTOPO_LINK_INVALID", "معرّف الوصلة رقم " + (i + 1) + " غير صالح.", where + ".id");
            ok = false;
        }
        else if (linkIds.has(l.id)) {
            err("NETTOPO_LINK_ID_DUPLICATE", "معرّف وصلة مكرر: " + l.id, where + ".id");
            ok = false;
        }
        const ends = [];
        for (const side of ["a", "b"]) {
            const e = l[side];
            const kind = typeof e.deviceId === "string" ? kinds.get(e.deviceId) : undefined;
            if (!kind) {
                err("NETTOPO_LINK_DEVICE_UNKNOWN", "طرف الوصلة رقم " + (i + 1) + " يشير إلى جهاز غير موجود: " + String(e.deviceId), where + "." + side);
                ok = false;
                continue;
            }
            if (typeof e.port !== "string" || !(0, exports.devicePorts)(kind).includes(e.port)) {
                err("NETTOPO_LINK_PORT_INVALID", "المنفذ " + String(e.port) + " غير موجود على الجهاز " + String(e.deviceId) + ".", where + "." + side + ".port");
                ok = false;
                continue;
            }
            ends.push({ deviceId: e.deviceId, port: e.port });
        }
        if (ends.length === 2 && ends[0].deviceId === ends[1].deviceId) {
            err("NETTOPO_LINK_SELF", "لا يمكن وصل جهاز بنفسه (الوصلة رقم " + (i + 1) + ").", where);
            ok = false;
        }
        if (ends.length === 2 && ok)
            for (const e of ends) {
                const k = e.deviceId + ":" + e.port;
                if (usedPorts.has(k)) {
                    err("NETTOPO_PORT_IN_USE", "المنفذ " + e.port + " على " + e.deviceId + " موصول بأكثر من وصلة.", where);
                    ok = false;
                }
            }
        if (!ok || ends.length !== 2)
            return;
        linkIds.add(l.id);
        for (const e of ends)
            usedPorts.add(e.deviceId + ":" + e.port);
        links.push({ id: l.id, a: ends[0], b: ends[1] });
    });
    if (out.length)
        return { ok: false, issues: out };
    return { ok: true, config: { v: exports.TOPOLOGY_CONFIG_VERSION, devices, links }, issues: [] };
}
const sortedIds = (config, kind) => config.devices.filter(d => d.kind === kind).map(d => d.id).sort();
function initialTopologyState(config) {
    const byId = new Map(config.devices.map(d => [d.id, d]));
    const pcs = {}, switches = {}, routers = {};
    for (const id of sortedIds(config, "pc"))
        pcs[id] = canonicalPcConfig(byId.get(id).initial ?? {});
    for (const id of sortedIds(config, "switch")) {
        const init = byId.get(id).initial;
        switches[id] = init ? (0, networkCliEngine_1.canonicalizeState)(init) : (0, networkCliEngine_1.createDeviceState)();
    }
    for (const id of sortedIds(config, "router")) {
        const init = byId.get(id).initial;
        routers[id] = init ? (0, routerCliEngine_1.canonicalizeRouterState)(init) : (0, routerCliEngine_1.createRouterState)();
    }
    return { v: exports.TOPOLOGY_STATE_VERSION, pcs, switches, routers };
}
function canonicalizeTopologyState(state) {
    const pcs = {}, switches = {}, routers = {};
    for (const id of Object.keys(state.pcs).filter(k => !FORBIDDEN.has(k)).sort())
        pcs[id] = canonicalPcConfig(state.pcs[id]);
    for (const id of Object.keys(state.switches).filter(k => !FORBIDDEN.has(k)).sort())
        switches[id] = (0, networkCliEngine_1.canonicalizeState)(state.switches[id]);
    for (const id of Object.keys(state.routers).filter(k => !FORBIDDEN.has(k)).sort())
        routers[id] = (0, routerCliEngine_1.canonicalizeRouterState)(state.routers[id]);
    return { v: exports.TOPOLOGY_STATE_VERSION, pcs, switches, routers };
}
const serializeTopologyState = (state) => JSON.stringify(canonicalizeTopologyState(state));
exports.serializeTopologyState = serializeTopologyState;
const topologyDevice = (config, id) => config.devices.find(d => d.id === id);
exports.topologyDevice = topologyDevice;
function linkAt(config, deviceId, port) {
    for (const l of config.links) {
        if (l.a.deviceId === deviceId && l.a.port === port)
            return { link: l, peer: l.b };
        if (l.b.deviceId === deviceId && l.b.port === port)
            return { link: l, peer: l.a };
    }
    return undefined;
}
