// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isReservedParametricIdV3 = exports.isReservedParametricIdV2 = exports.isReservedParametricId = exports.PARAMETRIC_CONSTANTS_V3 = exports.PARAMETRIC_FUNCTIONS_V3 = exports.PARAMETRIC_FUNCTIONS_V2 = exports.PARAMETRIC_ID_RE = exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS = exports.PARAMETRIC_FUNCTIONS = exports.PARAMETRIC_LIMITS = void 0;
exports.parseExpression = parseExpression;
exports.parseConstraint = parseConstraint;
exports.powInt = powInt;
exports.roundTo = roundTo;
exports.evaluateExpression = evaluateExpression;
exports.evaluateConstraint = evaluateConstraint;
exports.PARAMETRIC_LIMITS = Object.freeze({
    variables: 20, idChars: 32, intAbs: 1_000_000_000, valueAbs: 1e15, expressionChars: 500, tokens: 200, depth: 32, constraints: 20, constraintChars: 300,
    attempts: 100, exponentAbs: 64, roundDigits: 10, functionArgs: 10, templateChars: 4000, placeholders: 100, identityChars: 200, maxAttemptNumber: 1_000_000,
    astNodes: 160, derivedVariables: 20, positions: 10_000_000, decimalPlaces: 6, formatDecimals: 10
});
exports.PARAMETRIC_FUNCTIONS = Object.freeze(["abs", "round", "floor", "ceil", "min", "max"]);
const ARITY = Object.freeze({ abs: [1, 1], round: [1, 2], floor: [1, 1], ceil: [1, 1], min: [2, 10], max: [2, 10] });
exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS = new Set(["__proto__", "constructor", "prototype", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable", "toString", "toLocaleString", "valueOf", "__defineGetter__", "__defineSetter__", "__lookupGetter__", "__lookupSetter__"]);
exports.PARAMETRIC_ID_RE = /^[A-Za-z][A-Za-z0-9_]{0,31}$/;
const isFunctionName = (s) => exports.PARAMETRIC_FUNCTIONS.includes(s);
exports.PARAMETRIC_FUNCTIONS_V2 = Object.freeze([...exports.PARAMETRIC_FUNCTIONS, "sqrt", "pow", "log", "log10", "exp"]);
const ARITY_V2 = Object.freeze({ ...ARITY, sqrt: [1, 1], pow: [2, 2], log: [1, 1], log10: [1, 1], exp: [1, 1] });
const isFunctionNameV2 = (s) => exports.PARAMETRIC_FUNCTIONS_V2.includes(s);
exports.PARAMETRIC_FUNCTIONS_V3 = Object.freeze(["abs", "round", "floor", "ceil", "min", "max", "sqrt", "pow", "log10", "exp", "ln", "sin", "cos", "tan", "asin", "acos", "atan"]);
exports.PARAMETRIC_CONSTANTS_V3 = Object.freeze({ pi: Math.PI, e: Math.E });
const ARITY_ALL = Object.freeze({ ...ARITY_V2, ln: [1, 1], sin: [1, 1], cos: [1, 1], tan: [1, 1], asin: [1, 1], acos: [1, 1], atan: [1, 1] });
const isFunctionNameV3 = (s) => exports.PARAMETRIC_FUNCTIONS_V3.includes(s);
const isConstantV3 = (s) => s === "pi" || s === "e";
class ExprError {
    code;
    constructor(code) { this.code = code; }
}
function tokenize(src) {
    const out = [];
    let i = 0;
    while (i < src.length) {
        const ch = src[i];
        if (ch === " " || ch === "\t") {
            i++;
            continue;
        }
        if (ch >= "0" && ch <= "9") {
            const m = /^([0-9]+)(\.[0-9]+)?/.exec(src.slice(i));
            if (m[1].length > 15 || (m[2] && m[2].length > 16))
                throw new ExprError("EXPR_TOKEN_INVALID");
            out.push({ k: "num", v: Number(m[0]) });
            i += m[0].length;
            continue;
        }
        if ((ch >= "A" && ch <= "Z") || (ch >= "a" && ch <= "z") || ch === "_") {
            const m = /^[A-Za-z_][A-Za-z0-9_]*/.exec(src.slice(i));
            if (m[0].length > exports.PARAMETRIC_LIMITS.idChars)
                throw new ExprError("EXPR_TOKEN_INVALID");
            if (exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS.has(m[0]))
                throw new ExprError("EXPR_FORBIDDEN_IDENTIFIER");
            out.push({ k: "id", v: m[0] });
            i += m[0].length;
            continue;
        }
        if ("+-*/%^(),".includes(ch)) {
            out.push({ k: "op", v: ch });
            i++;
            continue;
        }
        const two = src.slice(i, i + 2);
        if (two === "<=" || two === ">=" || two === "==" || two === "!=") {
            out.push({ k: "cmp", v: two });
            i += 2;
            continue;
        }
        if (ch === "<" || ch === ">") {
            out.push({ k: "cmp", v: ch });
            i++;
            continue;
        }
        throw new ExprError("EXPR_TOKEN_INVALID");
    }
    if (out.length > exports.PARAMETRIC_LIMITS.tokens)
        throw new ExprError("EXPR_TOO_MANY_TOKENS");
    return out;
}
class Parser {
    pos = 0;
    depth = 0;
    nodes = 0;
    language;
    refs = new Set();
    tokens;
    constructor(tokens, language = 1) { this.tokens = tokens; this.language = language; }
    node(n) { if (this.language !== 1 && ++this.nodes > exports.PARAMETRIC_LIMITS.astNodes)
        throw new ExprError("EXPR_TOO_COMPLEX"); return n; }
    isFn(name) { return this.language === 3 ? isFunctionNameV3(name) : this.language === 2 ? isFunctionNameV2(name) : isFunctionName(name); }
    peek() { return this.tokens[this.pos]; }
    isOp(v) { const t = this.peek(); return !!t && t.k === "op" && t.v === v; }
    expectOp(v) { if (!this.isOp(v))
        throw new ExprError("EXPR_SYNTAX"); this.pos++; }
    enter() { if (++this.depth > exports.PARAMETRIC_LIMITS.depth)
        throw new ExprError("EXPR_TOO_DEEP"); }
    atEnd() { return this.pos >= this.tokens.length; }
    peekCmp() { const t = this.peek(); return t && t.k === "cmp" ? t.v : undefined; }
    takeCmp() { const c = this.peekCmp(); if (!c)
        throw new ExprError("EXPR_NOT_A_COMPARISON"); this.pos++; return c; }
    additive() {
        let a = this.multiplicative();
        for (;;) {
            if (this.isOp("+") || this.isOp("-")) {
                const op = this.tokens[this.pos++].v;
                a = this.node({ t: "bin", op, a, b: this.multiplicative() });
            }
            else
                return a;
        }
    }
    multiplicative() {
        let a = this.unary();
        for (;;) {
            if (this.isOp("*") || this.isOp("/") || this.isOp("%")) {
                const op = this.tokens[this.pos++].v;
                a = this.node({ t: "bin", op, a, b: this.unary() });
            }
            else
                return a;
        }
    }
    unary() {
        this.enter();
        try {
            if (this.isOp("-")) {
                this.pos++;
                return this.node({ t: "neg", a: this.unary() });
            }
            return this.power();
        }
        finally {
            this.depth--;
        }
    }
    power() {
        const base = this.primary();
        if (this.isOp("^")) {
            this.pos++;
            const exponent = this.unary();
            return this.language !== 1 ? this.node({ t: "call", fn: "pow", args: [base, exponent] }) : { t: "bin", op: "^", a: base, b: exponent };
        }
        return base;
    }
    primary() {
        const t = this.peek();
        if (!t)
            throw new ExprError("EXPR_SYNTAX");
        if (t.k === "num") {
            this.pos++;
            return this.node({ t: "num", v: t.v });
        }
        if (t.k === "op" && t.v === "(") {
            this.pos++;
            const e = this.additive();
            this.expectOp(")");
            return e;
        }
        if (t.k === "id") {
            this.pos++;
            if (this.language === 3 && t.v === "log")
                throw new ExprError("EXPR_AMBIGUOUS_LOG");
            if (this.isOp("(")) {
                if (!this.isFn(t.v))
                    throw new ExprError("EXPR_UNKNOWN_FUNCTION");
                const fn = t.v;
                this.pos++;
                const args = [];
                if (!this.isOp(")")) {
                    for (;;) {
                        args.push(this.additive());
                        if (args.length > exports.PARAMETRIC_LIMITS.functionArgs)
                            throw new ExprError("EXPR_ARITY");
                        if (this.isOp(",")) {
                            this.pos++;
                            continue;
                        }
                        break;
                    }
                }
                this.expectOp(")");
                const [lo, hi] = ARITY_ALL[fn];
                if (args.length < lo || args.length > hi)
                    throw new ExprError("EXPR_ARITY");
                return this.node({ t: "call", fn, args });
            }
            if (this.isFn(t.v))
                throw new ExprError("EXPR_SYNTAX");
            if (this.language === 3 && isConstantV3(t.v))
                return this.node({ t: "num", v: exports.PARAMETRIC_CONSTANTS_V3[t.v] });
            this.refs.add(t.v);
            return this.node({ t: "var", id: t.v });
        }
        throw new ExprError("EXPR_SYNTAX");
    }
}
const sortedRefs = (p) => [...p.refs].sort();
function prepare(src, maxChars) {
    if (typeof src !== "string" || src.trim() === "")
        throw new ExprError("EXPR_EMPTY");
    if (src.length > maxChars)
        throw new ExprError("EXPR_TOO_LONG");
    return tokenize(src);
}
function parseExpression(src, options = {}) {
    try {
        const p = new Parser(prepare(src, exports.PARAMETRIC_LIMITS.expressionChars), options.language === 3 ? 3 : options.language === 2 ? 2 : 1);
        const ast = p.additive();
        if (p.peekCmp())
            return { ok: false, code: "EXPR_COMPARISON_NOT_ALLOWED" };
        if (!p.atEnd())
            return { ok: false, code: "EXPR_SYNTAX" };
        return { ok: true, ast, refs: sortedRefs(p) };
    }
    catch (e) {
        if (e instanceof ExprError)
            return { ok: false, code: e.code };
        throw e;
    }
}
function parseConstraint(src, options = {}) {
    try {
        const p = new Parser(prepare(src, exports.PARAMETRIC_LIMITS.constraintChars), options.language === 2 ? 2 : 1);
        const left = p.additive();
        const op = p.takeCmp();
        const right = p.additive();
        if (!p.atEnd())
            return { ok: false, code: "EXPR_SYNTAX" };
        return { ok: true, constraint: { left, op, right }, refs: sortedRefs(p) };
    }
    catch (e) {
        if (e instanceof ExprError)
            return { ok: false, code: e.code };
        throw e;
    }
}
const bounded = (v) => {
    if (!Number.isFinite(v))
        throw new ExprError("EVAL_NON_FINITE");
    if (Math.abs(v) > exports.PARAMETRIC_LIMITS.valueAbs)
        throw new ExprError("EVAL_OUT_OF_RANGE");
    return v === 0 ? 0 : v;
};
function powInt(base, e) {
    let r = 1, b = base, n = Math.abs(e);
    while (n > 0) {
        if (n & 1)
            r *= b;
        n >>>= 1;
        if (n > 0)
            b *= b;
    }
    return e < 0 ? 1 / r : r;
}
const normalize12 = (v) => (Number.isFinite(v) ? Number(v.toPrecision(12)) : v);
function powV2(a, b) {
    if (Math.abs(b) > exports.PARAMETRIC_LIMITS.exponentAbs)
        throw new ExprError("EVAL_EXPONENT_INVALID");
    if (a === 0 && b < 0)
        throw new ExprError("EVAL_DIVIDE_BY_ZERO");
    if (Number.isInteger(b))
        return powInt(a, b);
    if (a < 0)
        throw new ExprError("EVAL_DOMAIN");
    if (a === 0)
        return 0;
    return normalize12(Math.pow(a, b));
}
function roundTo(x, digits) {
    const f = powInt(10, digits), y = bounded(Math.abs(x) * f);
    const r = Math.round(Number(y.toPrecision(15))) / f;
    return x < 0 ? -r : r;
}
function evalNode(n, values) {
    switch (n.t) {
        case "num": return bounded(n.v);
        case "var": {
            if (!values.has(n.id))
                throw new ExprError("EVAL_UNKNOWN_VARIABLE");
            const v = values.get(n.id);
            if (typeof v !== "number")
                throw new ExprError("EVAL_NON_FINITE");
            return bounded(v);
        }
        case "neg": return bounded(-evalNode(n.a, values));
        case "bin": {
            const a = evalNode(n.a, values), b = evalNode(n.b, values);
            switch (n.op) {
                case "+": return bounded(a + b);
                case "-": return bounded(a - b);
                case "*": return bounded(a * b);
                case "/":
                    if (b === 0)
                        throw new ExprError("EVAL_DIVIDE_BY_ZERO");
                    return bounded(a / b);
                case "%":
                    if (b === 0)
                        throw new ExprError("EVAL_DIVIDE_BY_ZERO");
                    return bounded(a % b);
                case "^":
                    if (!Number.isInteger(b) || Math.abs(b) > exports.PARAMETRIC_LIMITS.exponentAbs)
                        throw new ExprError("EVAL_EXPONENT_INVALID");
                    if (a === 0 && b < 0)
                        throw new ExprError("EVAL_DIVIDE_BY_ZERO");
                    return bounded(powInt(a, b));
            }
            throw new ExprError("EVAL_NON_FINITE");
        }
        case "call": {
            const args = n.args.map(x => evalNode(x, values));
            switch (n.fn) {
                case "abs": return bounded(Math.abs(args[0]));
                case "floor": return bounded(Math.floor(args[0]));
                case "ceil": return bounded(Math.ceil(args[0]));
                case "min": return bounded(Math.min(...args));
                case "max": return bounded(Math.max(...args));
                case "round": {
                    const d = args.length > 1 ? args[1] : 0;
                    if (!Number.isInteger(d) || d < 0 || d > exports.PARAMETRIC_LIMITS.roundDigits)
                        throw new ExprError("EVAL_ROUND_DIGITS_INVALID");
                    return bounded(roundTo(args[0], d));
                }
                case "sqrt":
                    if (args[0] < 0)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(Math.sqrt(args[0]));
                case "pow": return bounded(powV2(args[0], args[1]));
                case "log":
                    if (args[0] <= 0)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(normalize12(Math.log(args[0])));
                case "log10":
                    if (args[0] <= 0)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(normalize12(Math.log10(args[0])));
                case "exp": return bounded(normalize12(Math.exp(args[0])));
                case "ln":
                    if (args[0] <= 0)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(normalize12(Math.log(args[0])));
                case "sin": return bounded(normalize12(Math.sin(args[0])));
                case "cos": return bounded(normalize12(Math.cos(args[0])));
                case "tan": return bounded(normalize12(Math.tan(args[0])));
                case "asin":
                    if (args[0] < -1 || args[0] > 1)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(normalize12(Math.asin(args[0])));
                case "acos":
                    if (args[0] < -1 || args[0] > 1)
                        throw new ExprError("EVAL_DOMAIN");
                    return bounded(normalize12(Math.acos(args[0])));
                case "atan": return bounded(normalize12(Math.atan(args[0])));
            }
        }
    }
    throw new ExprError("EVAL_NON_FINITE");
}
function evaluateExpression(ast, values) {
    try {
        return { ok: true, value: evalNode(ast, values) };
    }
    catch (e) {
        if (e instanceof ExprError)
            return { ok: false, code: e.code };
        throw e;
    }
}
function evaluateConstraint(c, values) {
    const l = evaluateExpression(c.left, values);
    if (!l.ok)
        return l;
    const r = evaluateExpression(c.right, values);
    if (!r.ok)
        return r;
    const a = l.value, b = r.value;
    const holds = c.op === "<" ? a < b : c.op === "<=" ? a <= b : c.op === ">" ? a > b : c.op === ">=" ? a >= b : c.op === "==" ? a === b : a !== b;
    return { ok: true, holds };
}
const isReservedParametricId = (id) => isFunctionName(id) || exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS.has(id);
exports.isReservedParametricId = isReservedParametricId;
const isReservedParametricIdV2 = (id) => isFunctionNameV2(id) || exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS.has(id);
exports.isReservedParametricIdV2 = isReservedParametricIdV2;
const isReservedParametricIdV3 = (id) => isFunctionNameV3(id) || isConstantV3(id) || id === "log" || exports.PARAMETRIC_FORBIDDEN_IDENTIFIERS.has(id);
exports.isReservedParametricIdV3 = isReservedParametricIdV3;
