// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fmtPhysics = exports.peakHeight = exports.impactSpeed = exports.velocityAt = exports.heightAt = exports.FREE_FALL_UNITS = exports.FREE_FALL_LIMITS = exports.FREE_FALL_CONFIG_VERSION = exports.FREE_FALL_PLUGIN_VERSION = exports.FREE_FALL_PLUGIN_KEY = void 0;
exports.impactTime = impactTime;
exports.bodyAt = bodyAt;
exports.sampleTrajectory = sampleTrajectory;
exports.validateFreeFallModel = validateFreeFallModel;
exports.validateFreeFallConfig = validateFreeFallConfig;
const trustedSimVocabulary_1 = require("./trustedSimVocabulary");
exports.FREE_FALL_PLUGIN_KEY = "physicsFreeFall";
exports.FREE_FALL_PLUGIN_VERSION = 1;
exports.FREE_FALL_CONFIG_VERSION = 1;
exports.FREE_FALL_LIMITS = Object.freeze({
    heightMax: 10000, velocityAbsMax: 1000, gravityMin: 0.1, gravityMax: 100, maxTimeMax: 600,
    measurements: 12, points: 12, labelChars: 80, valueAbsMax: 1e6, samplesMax: 2001
});
exports.FREE_FALL_UNITS = Object.freeze(["s", "m", "m/s"]);
const L = exports.FREE_FALL_LIMITS;
const ROOT_KEYS = ["v", "model", "view", "tasks"];
const MODEL_KEYS = ["initialHeight", "initialVelocity", "gravity"];
const VIEW_KEYS = ["maxTime", "showVelocityGraph"];
const exactKeys = (o, keys) => Object.keys(o).length === keys.length && keys.every(k => Object.prototype.hasOwnProperty.call(o, k));
const num = (v, min, max) => typeof v === "number" && Number.isFinite(v) && v >= min && v <= max;
const isLabel = (v) => typeof v === "string" && v.trim().length > 0 && v.length <= L.labelChars && !(0, trustedSimVocabulary_1.hasControlCharacter)(v);
const heightAt = (m, t) => m.initialHeight + m.initialVelocity * t - 0.5 * m.gravity * t * t;
exports.heightAt = heightAt;
const velocityAt = (m, t) => m.initialVelocity - m.gravity * t;
exports.velocityAt = velocityAt;
function impactTime(m) {
    const root = Math.sqrt(m.initialVelocity * m.initialVelocity + 2 * m.gravity * m.initialHeight);
    return m.initialVelocity > 0 ? (m.initialVelocity + root) / m.gravity : (2 * m.initialHeight) / (root - m.initialVelocity || 1);
}
const impactSpeed = (m) => Math.sqrt(m.initialVelocity * m.initialVelocity + 2 * m.gravity * m.initialHeight);
exports.impactSpeed = impactSpeed;
const peakHeight = (m) => (m.initialVelocity > 0 ? m.initialHeight + (m.initialVelocity * m.initialVelocity) / (2 * m.gravity) : m.initialHeight);
exports.peakHeight = peakHeight;
function bodyAt(m, t) {
    const ti = impactTime(m);
    if (!(t < ti))
        return { t, y: 0, v: (0, exports.velocityAt)(m, ti), landed: true };
    const time = t > 0 ? t : 0;
    return { t: time, y: (0, exports.heightAt)(m, time), v: (0, exports.velocityAt)(m, time), landed: false };
}
function sampleTrajectory(m, maxTime, count) {
    const n = Math.max(2, Math.min(L.samplesMax, Number.isFinite(count) ? Math.floor(count) : 2));
    const end = Math.min(Number.isFinite(maxTime) && maxTime > 0 ? maxTime : 0, impactTime(m));
    const out = [];
    for (let i = 0; i < n; i++) {
        const t = (i * end) / (n - 1);
        out.push({ t, y: Math.max(0, (0, exports.heightAt)(m, t)), v: (0, exports.velocityAt)(m, t) });
    }
    return out;
}
function validateFreeFallModel(raw) {
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw) || !exactKeys(raw, MODEL_KEYS))
        return undefined;
    const { initialHeight: h, initialVelocity: v, gravity: g } = raw;
    if (!num(h, 0, L.heightMax) || !num(v, -L.velocityAbsMax, L.velocityAbsMax) || !num(g, L.gravityMin, L.gravityMax))
        return undefined;
    if (h === 0 && v <= 0)
        return undefined;
    return { initialHeight: h, initialVelocity: v, gravity: g };
}
function validateFreeFallConfig(raw) {
    const issues = [];
    const add = (code, message, path) => { issues.push({ code, message, path }); };
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw))
        return { ok: false, issues: [{ code: "FREEFALL_CONFIG_INVALID", message: "إعداد محاكاة السقوط الحر مفقود أو غير صالح.", path: "smartSim.config" }] };
    for (const k of Object.keys(raw))
        if (!ROOT_KEYS.includes(k))
            add("FREEFALL_CONFIG_UNKNOWN_KEY", "حقل غير مسموح في إعداد السقوط الحر: " + k, "smartSim.config." + k);
    if (raw.v !== exports.FREE_FALL_CONFIG_VERSION)
        add("FREEFALL_CONFIG_VERSION_UNSUPPORTED", "إصدار إعداد السقوط الحر غير مدعوم.", "smartSim.config.v");
    const model = validateFreeFallModel(raw.model);
    if (!model)
        add("FREEFALL_MODEL_INVALID", "النموذج الفيزيائي غير صالح: الارتفاع الابتدائي 0–" + L.heightMax + " م، السرعة الابتدائية ±" + L.velocityAbsMax + " م/ث، الجاذبية " + L.gravityMin + "–" + L.gravityMax + " م/ث² (قيمة موجبة)، ويجب أن يبدأ الجسم فوق الأرض أو يُقذف إلى الأعلى.", "smartSim.config.model");
    let view;
    const rv = raw.view;
    if (!(0, trustedSimVocabulary_1.isPlainObject)(rv) || !exactKeys(rv, VIEW_KEYS) || !num(rv.maxTime, Number.MIN_VALUE, L.maxTimeMax) || typeof rv.showVelocityGraph !== "boolean")
        add("FREEFALL_VIEW_INVALID", "إعداد العرض غير صالح: مدة التجربة عدد موجب حتى " + L.maxTimeMax + " ث.", "smartSim.config.view");
    else {
        view = { maxTime: rv.maxTime, showVelocityGraph: rv.showVelocityGraph };
        if (model && view.maxTime < impactTime(model))
            add("FREEFALL_VIEW_TOO_SHORT", "مدة التجربة أقصر من زمن وصول الجسم إلى الأرض (" + (0, exports.fmtPhysics)(impactTime(model)) + " ث).", "smartSim.config.view.maxTime");
    }
    const tasks = validateTasks(raw.tasks, add);
    if (issues.length || !model || !view || !tasks)
        return { ok: false, issues };
    return { ok: true, config: { v: exports.FREE_FALL_CONFIG_VERSION, model, view, tasks } };
}
function validateTasks(raw, add) {
    const where = "smartSim.config.tasks";
    if (!(0, trustedSimVocabulary_1.isPlainObject)(raw) || !exactKeys(raw, ["measurements", "points"]) || !Array.isArray(raw.measurements) || !Array.isArray(raw.points)) {
        add("FREEFALL_TASK_INVALID", "قائمة المهام غير صالحة.", where);
        return undefined;
    }
    if (raw.measurements.length > L.measurements || raw.points.length > L.points) {
        add("FREEFALL_TASKS_TOO_MANY", "عدد المهام يتجاوز الحد (" + L.measurements + " قياسًا و" + L.points + " نقطة).", where);
        return undefined;
    }
    if (raw.measurements.length + raw.points.length === 0) {
        add("FREEFALL_TASKS_EMPTY", "أضف مهمة قياس أو نقطة واحدة على الأقل.", where);
        return undefined;
    }
    let ok = true;
    const seen = new Set();
    const ident = (id, path) => {
        if (!(0, trustedSimVocabulary_1.isSemanticId)(id)) {
            add("FREEFALL_TASK_INVALID", "معرّف المهمة غير صالح.", path);
            ok = false;
            return false;
        }
        if (seen.has(id)) {
            add("FREEFALL_TASK_ID_DUPLICATE", "معرّف مهمة مكرر: " + id, path);
            ok = false;
            return false;
        }
        seen.add(id);
        return true;
    };
    const measurements = [];
    raw.measurements.forEach((m, i) => {
        const path = where + ".measurements[" + i + "]";
        if (!(0, trustedSimVocabulary_1.isPlainObject)(m) || !exactKeys(m, ["id", "label", "unit"]) || !isLabel(m.label) || typeof m.unit !== "string" || !exports.FREE_FALL_UNITS.includes(m.unit)) {
            add("FREEFALL_TASK_INVALID", "مهمة القياس رقم " + (i + 1) + " غير صالحة (المعرّف، الوصف حتى " + L.labelChars + " حرفًا، الوحدة s أو m أو m/s).", path);
            ok = false;
            return;
        }
        if (ident(m.id, path))
            measurements.push({ id: m.id, label: m.label, unit: m.unit });
    });
    const points = [];
    raw.points.forEach((p, i) => {
        const path = where + ".points[" + i + "]";
        if (!(0, trustedSimVocabulary_1.isPlainObject)(p) || !exactKeys(p, ["id", "label"]) || !isLabel(p.label)) {
            add("FREEFALL_TASK_INVALID", "مهمة النقطة رقم " + (i + 1) + " غير صالحة.", path);
            ok = false;
            return;
        }
        if (ident(p.id, path))
            points.push({ id: p.id, label: p.label });
    });
    return ok ? { measurements, points } : undefined;
}
const fmtPhysics = (n) => (Number.isFinite(n) ? String(Number(n.toPrecision(6))) : "—");
exports.fmtPhysics = fmtPhysics;
