// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.physicsLabPluginV1 = exports.PHYSICS_LAB_DESCRIPTOR_V1 = exports.labRuleView = exports.evaluateLabCheck = exports.expectedLabValue = exports.replayLab = exports.initialLabState = exports.normalizeLabAction = exports.LAB_CHECK_KINDS = exports.LAB_MAX_ACTIONS = exports.LAB_LABEL = void 0;
exports.validateLabCheck = validateLabCheck;
const physicsLabModel_1 = require("./physicsLabModel");
const labCore_1 = require("./physics/labCore");
const measurementTasks_1 = require("./physics/measurementTasks");
exports.LAB_LABEL = "مختبر الفيزياء المتقدم (البندول، النابض، الطاقة، الدوائر)";
exports.LAB_MAX_ACTIONS = 500;
exports.LAB_CHECK_KINDS = Object.freeze(["lab.referenceValue"]);
const VMAX = physicsLabModel_1.LAB_LIMITS.valueAbsMax;
const CODES = { invalid: "LAB_ACTION_INVALID", tooMany: "LAB_ACTIONS_TOO_MANY" };
const boundsOf = (c) => {
    const xIsTime = physicsLabModel_1.LAB_PRIMARY_AXES[c.experiment].xIsTime;
    return { measurementIds: c.tasks.measurements.map(m => m.id), pointIds: c.tasks.points.map(p => p.id), valueAbsMax: VMAX, pointX: { min: xIsTime ? 0 : -VMAX, max: xIsTime ? c.view.maxTime : VMAX } };
};
const normalizeLabAction = (raw, config) => (0, measurementTasks_1.normalizeTaskAction)(raw, boundsOf(config), CODES.invalid);
exports.normalizeLabAction = normalizeLabAction;
const initialLabState = () => (0, measurementTasks_1.initialTaskState)();
exports.initialLabState = initialLabState;
const replayLab = (config, rawActions) => (0, measurementTasks_1.replayTaskActions)(rawActions, boundsOf(config), exports.LAB_MAX_ACTIONS, CODES);
exports.replayLab = replayLab;
const TOLERANCE_MAX = 1e7;
const expectedLabValue = (check, config) => (0, labCore_1.labQuantities)({ kind: config.experiment, params: config.params }, config.view.maxTime)[check.quantity] ?? null;
exports.expectedLabValue = expectedLabValue;
function validateLabCheck(raw, config) {
    const fail = (message) => ({ ok: false, issues: [{ code: "LAB_CHECK_INVALID", message }] });
    if (raw.kind !== "lab.referenceValue")
        return fail("نوع فحص غير معروف.");
    if (!(0, measurementTasks_1.exactKeys)(raw, ["id", "label", "weight", "kind", "measurementId", "quantity", "tolerance"]))
        return fail("معاملات الفحص «" + String(raw.label) + "» غير مطابقة لنوعه.");
    if (typeof raw.tolerance !== "number" || !Number.isFinite(raw.tolerance) || raw.tolerance <= 0 || raw.tolerance > TOLERANCE_MAX)
        return fail("السماحية في الفحص «" + String(raw.label) + "» يجب أن تكون عددًا موجبًا.");
    const m = typeof raw.measurementId === "string" ? config.tasks.measurements.find(x => x.id === raw.measurementId) : undefined;
    if (!m)
        return fail("الفحص «" + String(raw.label) + "» يشير إلى قياس غير معرّف في المهام.");
    const q = labCore_1.LAB_QUANTITY_SPEC[config.experiment].find(s => s.id === raw.quantity);
    if (!q)
        return fail("الكمية المرجعية في الفحص «" + String(raw.label) + "» غير معروفة لهذه التجربة.");
    if (q.unit !== m.unit)
        return fail("وحدة القياس «" + m.label + "» لا تناسب الكمية «" + q.label + "» (" + q.unit + ").");
    const check = { id: raw.id, label: raw.label, weight: raw.weight, kind: "lab.referenceValue", measurementId: m.id, quantity: q.id, tolerance: raw.tolerance };
    const expected = (0, exports.expectedLabValue)(check, config);
    if (expected === null || !Number.isFinite(expected))
        return fail("الكمية «" + q.label + "» غير معرّفة في هذه التجربة بقيمها الحالية (مثلًا لا تكتمل اهتزازة خلال مدة التجربة أو التخميد حرج/فوق حرج).");
    return { ok: true, check };
}
const evaluateLabCheck = (check, state, config) => (0, measurementTasks_1.evaluateReferenceValue)((0, exports.expectedLabValue)(check, config), state, check.measurementId, check.tolerance, labCore_1.fmtLab);
exports.evaluateLabCheck = evaluateLabCheck;
const labRuleView = (state, config) => (0, measurementTasks_1.taskRuleView)(state, config.tasks.measurements.map(m => m.id), config.tasks.points.map(p => p.id));
exports.labRuleView = labRuleView;
exports.PHYSICS_LAB_DESCRIPTOR_V1 = {
    descriptorVersion: 1, key: physicsLabModel_1.LAB_PLUGIN_KEY, version: physicsLabModel_1.LAB_PLUGIN_VERSION, label: exports.LAB_LABEL, domain: "physics",
    sceneKinds: ["2d"], rendererFamilies: ["svg2d", "graph2d", "form"],
    capabilities: ["scene.2d", "simulation.play", "simulation.pause", "simulation.scrub", "graph.2d", "point.place", "value.set"],
    actionKinds: [...measurementTasks_1.TASK_ACTION_KINDS], checkKinds: [...exports.LAB_CHECK_KINDS], genericRules: ["numericNear@1", "pointNear@1"], assetKinds: [],
    tools: ["play", "pause", "scrub", "placePoint", "form"], accessibility: ["keyboardAlternative", "semanticLabels", "toolLabels", "textTranscript"],
    supports: { autosave: true, restore: true, reset: true, partialCredit: true, offline: true, twoDimensional: true, threeDimensional: false }
};
exports.physicsLabPluginV1 = Object.freeze({
    key: physicsLabModel_1.LAB_PLUGIN_KEY,
    version: physicsLabModel_1.LAB_PLUGIN_VERSION,
    label: exports.LAB_LABEL,
    maxActions: exports.LAB_MAX_ACTIONS,
    descriptor: exports.PHYSICS_LAB_DESCRIPTOR_V1,
    checkKinds: exports.LAB_CHECK_KINDS,
    validateConfig: (raw) => (0, physicsLabModel_1.validateLabConfig)(raw),
    createRuntime: measurementTasks_1.createTaskRuntime,
    normalizeAction: exports.normalizeLabAction,
    applyAction: (rt, a) => (0, measurementTasks_1.applyTaskAction)(rt, a),
    canonicalState: (rt) => (0, measurementTasks_1.canonicalTaskState)(rt),
    serializeState: (s) => JSON.stringify(s),
    validateCheck: validateLabCheck,
    evaluateCheck: exports.evaluateLabCheck,
    ruleView: exports.labRuleView
});
