// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LEGACY_TYPE_ALIASES = exports.GRADING_MODE_LABELS = exports.CATEGORY_ORDER = exports.CATEGORY_LABELS = void 0;
exports.resolveQuestionTypeKeyOrAlias = resolveQuestionTypeKeyOrAlias;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
exports.CATEGORY_LABELS = Object.freeze({ choice: "اختيار", response: "إجابات", structured: "منظّم", interactive: "تفاعلي", composite: "مركّب" });
exports.CATEGORY_ORDER = Object.freeze(["choice", "response", "structured", "interactive", "composite"]);
exports.GRADING_MODE_LABELS = Object.freeze({ auto: "تصحيح تلقائي", manual: "تصحيح يدوي", hybrid: "تصحيح هجين", composed: "تصحيح مركّب" });
exports.LEGACY_TYPE_ALIASES = Object.freeze({
    mcq: "multipleChoice", multiplechoice: "multipleChoice",
    tf: "trueFalse", truefalse: "trueFalse",
    multitruefalse: "multiTrueFalse", multitf: "multiTrueFalse",
    open: "shortAnswer", short: "shortAnswer", shortanswer: "shortAnswer", essay: "shortAnswer",
    fillblank: "fillBlank", fill: "fillBlank",
    wordbank: "wordBank",
    matching: "matching", match: "matching",
    ordering: "ordering", order: "ordering",
    tablefill: "tableFill", table: "tableFill",
    clifill: "cliFill", cli: "cliFill",
    compound: "compound"
});
function resolveQuestionTypeKeyOrAlias(raw) {
    const direct = (0, questionTypeCatalog_1.resolveQuestionTypeKey)(raw);
    if (direct)
        return direct;
    if (typeof raw !== "string")
        return undefined;
    const alias = exports.LEGACY_TYPE_ALIASES[raw.trim().toLowerCase()];
    return alias && (0, questionTypeCatalog_1.isKnownQuestionType)(alias) ? alias : undefined;
}
