// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeUnit = exports.NUMERIC_EPSILON = exports.MULTIPLE_SELECT_SCORING_LABELS = exports.MULTIPLE_SELECT_SCORING = void 0;
exports.scoreMultipleSelect = scoreMultipleSelect;
exports.parseNumericInput = parseNumericInput;
exports.scoreNumericResponse = scoreNumericResponse;
exports.scoreMatrix = scoreMatrix;
exports.scoreCategorization = scoreCategorization;
exports.MULTIPLE_SELECT_SCORING = Object.freeze(["allOrNothing", "partialNoPenalty", "partialWithPenalty"]);
exports.MULTIPLE_SELECT_SCORING_LABELS = Object.freeze({ allOrNothing: "كل شيء أو لا شيء", partialNoPenalty: "علامة جزئية بدون خصم", partialWithPenalty: "علامة جزئية مع خصم للاختيارات الخاطئة" });
exports.NUMERIC_EPSILON = 1e-9;
const clamp = (n, max) => Math.min(Math.max(0, n), Math.max(0, max));
const idList = (v) => (Array.isArray(v) ? v.filter((x) => typeof x === "string" && x !== "") : []);
function scoreMultipleSelect(input) {
    const valid = new Set(idList(input.optionIds));
    const correct = new Set(idList(input.correctOptionIds).filter(id => valid.has(id)));
    const selected = [...new Set(idList(input.selectedOptionIds).filter(id => valid.has(id)))];
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    if (!selected.length)
        return { score: 0, correct: false, answered: false, selected };
    const hits = selected.filter(id => correct.has(id)).length, misses = selected.length - hits, total = correct.size;
    let ratio = 0;
    if (input.scoring === "allOrNothing")
        ratio = hits === total && misses === 0 ? 1 : 0;
    else if (input.scoring === "partialNoPenalty")
        ratio = total ? hits / total : 0;
    else if (input.scoring === "partialWithPenalty")
        ratio = total ? Math.max(0, (hits - misses) / total) : 0;
    const score = clamp(ratio * max, max);
    return { score, correct: total > 0 && hits === total && misses === 0, answered: true, selected };
}
const ARABIC_INDIC = "٠١٢٣٤٥٦٧٨٩", EXTENDED_ARABIC_INDIC = "۰۱۲۳۴۵۶۷۸۹";
const NUMBER_PATTERN = /^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/;
function parseNumericInput(raw) {
    if (typeof raw === "number")
        return Number.isFinite(raw) ? raw : null;
    if (typeof raw !== "string")
        return null;
    let s = raw.trim();
    if (!s)
        return null;
    s = s.replace(/[٠-٩]/g, ch => String(ARABIC_INDIC.indexOf(ch))).replace(/[۰-۹]/g, ch => String(EXTENDED_ARABIC_INDIC.indexOf(ch)));
    s = s.replace(/[٬]/g, "").replace(/[٫،,]/g, ".").replace(/[−–]/g, "-").replace(/\s+/g, "");
    if (!NUMBER_PATTERN.test(s))
        return null;
    const n = Number(s);
    return Number.isFinite(n) ? n : null;
}
const normalizeUnit = (raw) => (typeof raw === "string" ? raw.normalize("NFKC").toLowerCase().replace(/\s+/g, "") : "");
exports.normalizeUnit = normalizeUnit;
const finite = (v) => typeof v === "number" && Number.isFinite(v);
function scoreNumericResponse(input) {
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const r = input.response && typeof input.response === "object" ? input.response : null;
    const rawValue = r && r.kind === "numeric" ? r.value : undefined;
    if (typeof rawValue !== "string" || !rawValue.trim())
        return { score: 0, correct: false, answered: false, reason: "unanswered" };
    const v = parseNumericInput(rawValue);
    if (v === null)
        return { score: 0, correct: false, answered: true, reason: "not-a-number" };
    const a = input.answer || {};
    if (input.unitRequired) {
        const expectedUnit = (0, exports.normalizeUnit)(a.unit);
        if (!expectedUnit || (0, exports.normalizeUnit)(r?.unit) !== expectedUnit)
            return { score: 0, correct: false, answered: true, reason: "unit" };
    }
    let ok = false;
    if (a.mode === "tolerance" && finite(a.expected) && finite(a.tolerance) && a.tolerance >= 0) {
        const eps = exports.NUMERIC_EPSILON * Math.max(1, Math.abs(a.expected), Math.abs(a.tolerance));
        ok = Math.abs(v - a.expected) <= a.tolerance + eps;
    }
    else if (a.mode === "range" && finite(a.min) && finite(a.max) && a.min <= a.max) {
        const eps = exports.NUMERIC_EPSILON * Math.max(1, Math.abs(a.min), Math.abs(a.max));
        ok = v >= a.min - eps && v <= a.max + eps;
    }
    else
        return { score: 0, correct: false, answered: true, reason: "invalid-key" };
    return ok ? { score: max, correct: true, answered: true, reason: "correct" } : { score: 0, correct: false, answered: true, reason: "outside" };
}
const validIds = (list) => (Array.isArray(list) ? list.map(x => (x && typeof x === "object" ? x.id : undefined)).filter((id) => typeof id === "string" && id !== "") : []);
const stringMap = (v) => { const out = {}; if (v && typeof v === "object" && !Array.isArray(v))
    for (const [k, val] of Object.entries(v))
        if (typeof val === "string")
            out[k] = val; return out; };
function scoreMatrix(input) {
    const rows = validIds(input.rows), cols = new Set(validIds(input.columns)), key = stringMap(input.correctColumnByRow), values = stringMap(input.values);
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const answered = rows.some(r => (values[r] ?? "") !== "");
    let correctRows = 0;
    for (const r of rows)
        if (cols.has(key[r]) && values[r] === key[r])
            correctRows++;
    const totalRows = rows.length;
    const score = totalRows ? clamp((correctRows / totalRows) * max, max) : 0;
    return { score, correct: totalRows > 0 && correctRows === totalRows, answered, correctRows, totalRows };
}
function scoreCategorization(input) {
    const items = validIds(input.items), cats = new Set(validIds(input.categories)), key = stringMap(input.correctCategoryByItem), values = stringMap(input.values);
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0;
    const answered = items.some(i => (values[i] ?? "") !== "");
    let correctItems = 0;
    for (const i of items)
        if (cats.has(key[i]) && values[i] === key[i])
            correctItems++;
    const totalItems = items.length;
    const score = totalItems ? clamp((correctItems / totalItems) * max, max) : 0;
    return { score, correct: totalItems > 0 && correctItems === totalItems, answered, correctItems, totalItems };
}
