// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hasRegisteredTypeDefaults = exports.registerTypeDefaults = void 0;
exports.applyRegisteredTypeDefaults = applyRegisteredTypeDefaults;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const defaults = (0, questionTypeCatalog_1.createVersionedRegistry)("type defaults");
const registerTypeDefaults = (key, version, fn) => defaults.register(key, version, fn);
exports.registerTypeDefaults = registerTypeDefaults;
const hasRegisteredTypeDefaults = (key, version) => typeof key === "string" && Number.isInteger(version) && defaults.has(key, version);
exports.hasRegisteredTypeDefaults = hasRegisteredTypeDefaults;
function applyRegisteredTypeDefaults(key, version, ensure, newId) {
    if (typeof key !== "string" || !Number.isInteger(version))
        return false;
    const hit = defaults.resolve(key, version);
    if (!hit || hit.version !== version)
        return false;
    hit.impl(ensure, newId);
    return true;
}
(0, exports.registerTypeDefaults)("multipleSelect", 1, (ensure, newId) => {
    ensure("options", [{ id: newId("opt"), text: "" }, { id: newId("opt"), text: "" }]);
    ensure("answer", { correctOptionIds: [], scoring: "allOrNothing" });
});
(0, exports.registerTypeDefaults)("numericResponse", 1, ensure => {
    ensure("numeric", { unitRequired: false });
    ensure("answer", { mode: "tolerance", expected: 0, tolerance: 0 });
});
(0, exports.registerTypeDefaults)("matrix", 1, (ensure, newId) => {
    ensure("matrix", { rows: [{ id: newId("row"), label: "" }], columns: [{ id: newId("col"), label: "" }, { id: newId("col"), label: "" }] });
    ensure("answer", { correctColumnByRow: {} });
});
(0, exports.registerTypeDefaults)("simulation", 1, () => { });
const CODING_DEFAULT_CONFIG = () => ({ allowedLanguages: ["python"], defaultLanguage: "python", starterCode: {}, taskMode: "program", inputMode: "stdin", outputMode: "stdout", limits: { sourceBytes: 65536, outputBytes: 65536, timeMs: 2000, memoryMb: 256 }, publicTests: [] });
(0, exports.registerTypeDefaults)("coding", 1, ensure => {
    ensure("coding", CODING_DEFAULT_CONFIG());
    ensure("answer", { hiddenTests: [], comparator: "trimTrailingWhitespace", referenceSolutions: {} });
});
(0, exports.registerTypeDefaults)("coding", 2, ensure => {
    ensure("coding", CODING_DEFAULT_CONFIG());
    ensure("answer", { hiddenTests: [], comparator: "trimTrailingWhitespace", referenceSolutions: {}, compileErrorPolicy: "manualReview" });
});
(0, exports.registerTypeDefaults)("networkCli", 1, ensure => {
    ensure("networkCli", { device: "switch", initialState: { v: 1, device: "switch", hostname: "Switch", vlans: {}, interfaces: {} } });
    ensure("answer", { targetState: {}, scoring: "proportional" });
});
(0, exports.registerTypeDefaults)("categorization", 1, (ensure, newId) => {
    ensure("categorization", { categories: [{ id: newId("cat"), label: "" }, { id: newId("cat"), label: "" }], items: [{ id: newId("item"), label: "" }] });
    ensure("answer", { correctCategoryByItem: {} });
});
