// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.questionTypeLabel = exports.currentQuestionTypeVersion = exports.compoundPartTypeKeys = exports.listQuestionTypes = exports.isKnownQuestionType = exports.questionTypeDefinition = exports.questionTypeIdentityKey = exports.QUESTION_TYPE_CATALOG = exports.LEGACY_QUESTION_TYPE_KEYS = void 0;
exports.registerQuestionType = registerQuestionType;
exports.supportsQuestionTypeVersion = supportsQuestionTypeVersion;
exports.effectiveQuestionTypeVersion = effectiveQuestionTypeVersion;
exports.createVersionedRegistry = createVersionedRegistry;
exports.resolveQuestionTypeKey = resolveQuestionTypeKey;
const FLAG = { a: "autoGrading", m: "manualGrading", h: "hybridGrading", p: "partialCredit", c: "compoundPart", i: "interactive", r: "requiresImage", o: "offline" };
const caps = (flags) => {
    const c = { autoGrading: false, manualGrading: false, hybridGrading: false, partialCredit: false, compoundPart: false, interactive: false, requiresImage: false, offline: false };
    for (const ch of flags)
        c[FLAG[ch]] = true;
    return Object.freeze(c);
};
const def = (d) => Object.freeze({ ...d, responseKinds: Object.freeze([...d.responseKinds]) });
const row = (key, label, category, gradingMode, flags, responseKinds, legacy = false) => def({ key, version: 1, label, category, gradingMode, capabilities: caps(flags), responseKinds, legacy });
exports.LEGACY_QUESTION_TYPE_KEYS = Object.freeze(["multipleChoice", "trueFalse", "multiTrueFalse", "shortAnswer", "fillBlank", "wordBank", "matching", "ordering", "tableFill", "cliFill", "compound"]);
const PRODUCTION_ROWS = [
    ["multipleChoice", "اختيار من متعدد", "choice", "auto", "aco", ["choice"], true],
    ["trueFalse", "صح أو خطأ", "choice", "auto", "aco", ["choice"], true],
    ["multiTrueFalse", "صح/خطأ متعدد", "choice", "auto", "acop", ["fields"], true],
    ["shortAnswer", "إجابة قصيرة / مفتوحة", "response", "hybrid", "amhco", ["text"], true],
    ["fillBlank", "إكمال فراغات", "response", "auto", "acop", ["sequence", "fields"], true],
    ["wordBank", "مخزن كلمات", "response", "auto", "acop", ["sequence", "fields"], true],
    ["matching", "مطابقة", "structured", "auto", "acop", ["fields"], true],
    ["ordering", "ترتيب", "structured", "auto", "acop", ["sequence"], true],
    ["tableFill", "إكمال جدول", "structured", "auto", "acop", ["fields", "table"], true],
    ["cliFill", "أوامر CLI", "response", "auto", "acop", ["fields"], true],
    ["compound", "سؤال مركّب", "composite", "composed", "amhpo", ["compound"], true],
    ["multipleSelect", "اختيار متعدد الإجابات", "choice", "auto", "acop", ["multiChoice"], false],
    ["numericResponse", "إجابة رقمية", "response", "auto", "aco", ["numeric"], false],
    ["matrix", "مصفوفة / شبكة اختيارات", "structured", "auto", "acop", ["fields"], false],
    ["categorization", "تصنيف العناصر", "structured", "auto", "acop", ["fields"], false],
    ["simulation", "محاكاة تفاعلية", "interactive", "manual", "mio", ["simulation"], false],
    ["coding", "برمجة / كتابة كود", "interactive", "hybrid", "mhpio", ["code"], false]
];
exports.QUESTION_TYPE_CATALOG = Object.freeze(PRODUCTION_ROWS.map(r => row(r[0], r[1], r[2], r[3], r[4], [...r[5]], r[6])));
const questionTypeIdentityKey = (key, version) => key + "@" + version;
exports.questionTypeIdentityKey = questionTypeIdentityKey;
const KEY_PATTERN = /^[A-Za-z][A-Za-z0-9]{1,63}$/;
const registry = new Map(exports.QUESTION_TYPE_CATALOG.map(d => [d.key, d]));
const productionKeys = new Set(exports.QUESTION_TYPE_CATALOG.map(d => d.key));
function registerQuestionType(definition) {
    if (!definition || typeof definition !== "object")
        throw new Error("question type definition required");
    const key = definition.key;
    if (typeof key !== "string" || !KEY_PATTERN.test(key))
        throw new Error("invalid question type key");
    if (registry.has(key))
        throw new Error("question type already registered: " + key);
    if (!Number.isInteger(definition.version) || definition.version < 1)
        throw new Error("invalid question type version");
    if (!["choice", "response", "structured", "interactive", "composite"].includes(definition.category))
        throw new Error("invalid question type category");
    if (!["auto", "manual", "hybrid", "composed"].includes(definition.gradingMode))
        throw new Error("invalid grading mode");
    registry.set(key, def({ ...definition, legacy: false }));
    return () => { if (!productionKeys.has(key))
        registry.delete(key); };
}
const questionTypeDefinition = (key) => (typeof key === "string" ? registry.get(key) : undefined);
exports.questionTypeDefinition = questionTypeDefinition;
const isKnownQuestionType = (key) => typeof key === "string" && registry.has(key);
exports.isKnownQuestionType = isKnownQuestionType;
const listQuestionTypes = () => [...registry.values()];
exports.listQuestionTypes = listQuestionTypes;
const compoundPartTypeKeys = () => (0, exports.listQuestionTypes)().filter(d => d.capabilities.compoundPart).map(d => d.key);
exports.compoundPartTypeKeys = compoundPartTypeKeys;
const currentQuestionTypeVersion = (key) => (0, exports.questionTypeDefinition)(key)?.version ?? 0;
exports.currentQuestionTypeVersion = currentQuestionTypeVersion;
function supportsQuestionTypeVersion(key, version) {
    const d = (0, exports.questionTypeDefinition)(key);
    if (!d)
        return false;
    if (version === undefined)
        return true;
    return Number.isInteger(version) && version >= 1 && version <= d.version;
}
function effectiveQuestionTypeVersion(key, storedVersion) {
    const d = (0, exports.questionTypeDefinition)(key);
    if (!d)
        return undefined;
    if (storedVersion === undefined)
        return 1;
    if (typeof storedVersion !== "number" || !Number.isInteger(storedVersion) || storedVersion < 1 || storedVersion > d.version)
        return undefined;
    return storedVersion;
}
function createVersionedRegistry(what, options = {}) {
    const entries = new Map();
    return {
        register(key, version, impl) {
            if (typeof key !== "string" || !KEY_PATTERN.test(key) || !Number.isInteger(version) || version < 1 || impl == null)
                throw new Error("invalid " + what + " registration: " + key + "@" + version);
            const id = (0, exports.questionTypeIdentityKey)(key, version);
            if (entries.has(id))
                throw new Error(what + " already registered: " + id);
            entries.set(id, impl);
            return () => { if (entries.get(id) === impl)
                entries.delete(id); };
        },
        resolve(rawKey, storedVersion) {
            const key = resolveQuestionTypeKey(rawKey) ?? (typeof rawKey === "string" && !options.requireKnownType ? rawKey.trim() : undefined);
            if (!key)
                return undefined;
            const version = (0, exports.isKnownQuestionType)(key) ? effectiveQuestionTypeVersion(key, storedVersion) : (storedVersion === undefined || storedVersion === 1 ? 1 : undefined);
            if (version === undefined)
                return undefined;
            const impl = entries.get((0, exports.questionTypeIdentityKey)(key, version));
            return impl === undefined ? undefined : { key, version, impl };
        },
        has(key, version) { return entries.has((0, exports.questionTypeIdentityKey)(key, version)); }
    };
}
function resolveQuestionTypeKey(raw) {
    if (typeof raw !== "string")
        return undefined;
    const s = raw.trim();
    if (!s)
        return undefined;
    if (registry.has(s))
        return s;
    const lower = s.toLowerCase();
    for (const k of registry.keys())
        if (k.toLowerCase() === lower)
            return k;
    return undefined;
}
const questionTypeLabel = (key) => (0, exports.questionTypeDefinition)(resolveQuestionTypeKey(key))?.label;
exports.questionTypeLabel = questionTypeLabel;
