// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SCENE3D_SELECTION_FAIL_CLOSED = exports.isScene3DSelectionAnswerAnswered = exports.scene3DSelectionQuestionVersion = exports.defaultScene3DSelectionAnswerKey = exports.SCENE3D_SELECTION_SCORING = exports.SCENE3D_SELECTION_MODES = exports.SCENE3D_SELECTION_LIMITS = exports.SCENE3D_SELECTION_CONFIG_VERSION = exports.SCENE3D_SELECTION_TYPE_KEY = void 0;
exports.validateScene3DSelectionConfig = validateScene3DSelectionConfig;
exports.validateScene3DSelectionAnswerKey = validateScene3DSelectionAnswerKey;
exports.validateScene3DSelectionQuestion = validateScene3DSelectionQuestion;
exports.projectScene3DSelectionConfigForStudent = projectScene3DSelectionConfigForStudent;
exports.normalizeScene3DSelectionAnswer = normalizeScene3DSelectionAnswer;
exports.bindScene3DSelectionAnswerToQuestion = bindScene3DSelectionAnswerToQuestion;
exports.scoreScene3DSelection = scoreScene3DSelection;
exports.evaluateScene3DSelection = evaluateScene3DSelection;
const questionTypeCatalog_1 = require("./questionTypeCatalog");
const proseGuard_1 = require("./richContent/proseGuard");
const sceneSpec_1 = require("./interactive3d/sceneSpec");
exports.SCENE3D_SELECTION_TYPE_KEY = "scene3DSelection";
exports.SCENE3D_SELECTION_CONFIG_VERSION = 1;
exports.SCENE3D_SELECTION_LIMITS = Object.freeze({ labelChars: 160, minTargets: 2, responseTargets: 128 });
exports.SCENE3D_SELECTION_MODES = Object.freeze(["single", "multiple"]);
exports.SCENE3D_SELECTION_SCORING = Object.freeze(["allOrNothing", "partial"]);
const err = (code, message, path) => ({ code, message, severity: "error", ...(path ? { path } : {}) });
const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);
const isPlain = (v) => { if (!v || typeof v !== "object" || Array.isArray(v))
    return false; const p = Object.getPrototypeOf(v); return p === Object.prototype || p === null; };
const onlyKeys = (o, allowed) => Object.keys(o).every(k => allowed.includes(k) && !FORBIDDEN.has(k));
const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
const ID = /^[A-Za-z][A-Za-z0-9_-]{0,31}$/;
const TARGET = /^(object|face|edge|vertex):[A-Za-z][A-Za-z0-9_-]{0,31}$/;
const BIDI = /[\u202A-\u202E\u2066-\u2069]/, INVISIBLE = /[\u00AD\u034F\u061C\u180E\u200B\u200E\u200F\u2060\uFEFF]/;
const defaultScene3DSelectionAnswerKey = () => ({ scoring: "allOrNothing", correct: [] });
exports.defaultScene3DSelectionAnswerKey = defaultScene3DSelectionAnswerKey;
const scene3DSelectionQuestionVersion = (node) => isPlain(node) ? (0, questionTypeCatalog_1.effectiveQuestionTypeVersion)(exports.SCENE3D_SELECTION_TYPE_KEY, node.questionTypeVersion) : undefined;
exports.scene3DSelectionQuestionVersion = scene3DSelectionQuestionVersion;
function validateScene3DSelectionConfig(raw) {
    if (!isPlain(raw))
        return { ok: false, issues: [err("SCENE3D_SELECTION_CONFIG_MISSING", "إعداد سؤال الاختيار من نموذج 3D مفقود أو غير صالح.", "scene3DSelection")] };
    const issues = [];
    if (!onlyKeys(raw, ["v", "scene", "target", "mode", "maxSelections", "label"]))
        issues.push(err("SCENE3D_SELECTION_UNKNOWN_KEY", "إعداد سؤال 3D يحتوي حقولًا غير معروفة.", "scene3DSelection"));
    if (raw.v !== 1)
        issues.push(err("SCENE3D_SELECTION_VERSION", "إصدار سؤال 3D غير مدعوم.", "scene3DSelection.v"));
    const scene = (0, sceneSpec_1.validateInteractive3DSceneSpec)(raw.scene, "scene3DSelection.scene");
    if (!scene.ok)
        issues.push(...scene.issues.slice(0, 10).map(i => err("SCENE3D_SELECTION_SCENE_INVALID", i.message + " [" + i.code + "]", i.path)));
    const target = raw.target, mode = raw.mode;
    if (typeof target !== "string" || !sceneSpec_1.SCENE3D_TARGET_KINDS.includes(target))
        issues.push(err("SCENE3D_SELECTION_TARGET_INVALID", "حدّد ما يختاره الطالب: مجسم/جزء أو وجه أو حافة أو رأس.", "scene3DSelection.target"));
    if (typeof mode !== "string" || !exports.SCENE3D_SELECTION_MODES.includes(mode))
        issues.push(err("SCENE3D_SELECTION_MODE_INVALID", "طريقة الاختيار غير معروفة.", "scene3DSelection.mode"));
    let label;
    if (own(raw, "label")) {
        const l = raw.label;
        if (typeof l !== "string" || !l.trim() || l.trim().length > exports.SCENE3D_SELECTION_LIMITS.labelChars || proseGuard_1.CONTROL.test(l) || proseGuard_1.RAW_HTML.test(l) || BIDI.test(l) || INVISIBLE.test(l))
            issues.push(err("SCENE3D_SELECTION_LABEL_INVALID", "تعليمة الاختيار نص عادي غير فارغ حتى 160 حرفًا.", "scene3DSelection.label"));
        else
            label = l.trim();
    }
    let targets = [];
    if (scene.ok && typeof target === "string" && sceneSpec_1.SCENE3D_TARGET_KINDS.includes(target)) {
        if (!scene.value.interaction.select)
            issues.push(err("SCENE3D_SELECTION_SELECT_DISABLED", "المشهد لا يسمح بالاختيار؛ فعّل select في إعداد التفاعل.", "scene3DSelection.scene.interaction.select"));
        targets = (0, sceneSpec_1.scene3DTargets)(scene.value, target);
        if (targets.length < exports.SCENE3D_SELECTION_LIMITS.minTargets)
            issues.push(err("SCENE3D_SELECTION_TARGETS_TOO_FEW", "يحتاج السؤال عنصرين على الأقل من نوع «" + sceneSpec_1.SCENE3D_TARGET_KIND_LABELS[target] + "».", "scene3DSelection.target"));
    }
    const max = raw.maxSelections;
    if (typeof max !== "number" || !Number.isInteger(max) || max < 1 || (targets.length > 0 && max > targets.length) || (mode === "single" && max !== 1))
        issues.push(err("SCENE3D_SELECTION_MAX_INVALID", "الحد الأقصى للاختيارات غير صالح.", "scene3DSelection.maxSelections"));
    if (issues.length || !scene.ok)
        return { ok: false, issues };
    return { ok: true, config: { v: 1, scene: scene.value, target: target, mode: mode, maxSelections: max, ...(label ? { label } : {}) }, targets, issues: [] };
}
function checkKey(raw, cfg) {
    if (!isPlain(raw))
        return { ok: false, issues: [err("SCENE3D_SELECTION_KEY_INVALID", "مفتاح تصحيح سؤال 3D مفقود أو غير صالح.", "answer")] };
    const issues = [];
    if (!onlyKeys(raw, ["scoring", "correct"]))
        issues.push(err("SCENE3D_SELECTION_KEY_INVALID", "مفتاح التصحيح يحتوي حقولًا غير معروفة.", "answer"));
    const scoring = raw.scoring;
    if (typeof scoring !== "string" || !exports.SCENE3D_SELECTION_SCORING.includes(scoring))
        issues.push(err("SCENE3D_SELECTION_SCORING_UNKNOWN", "طريقة الاحتساب غير معروفة.", "answer.scoring"));
    const correct = raw.correct;
    if (!Array.isArray(correct) || correct.some(x => typeof x !== "string")) {
        issues.push(err("SCENE3D_SELECTION_KEY_INVALID", "الاختيارات الصحيحة غير صالحة.", "answer.correct"));
        return { ok: false, issues };
    }
    if (!cfg)
        return issues.length ? { ok: false, issues } : { ok: true, key: { scoring: scoring, correct: [...correct] }, issues: [] };
    if (cfg.config.mode === "single" && scoring === "partial")
        issues.push(err("SCENE3D_SELECTION_SCORING_UNKNOWN", "الاختيار الواحد يُصحّح بالكل أو لا شيء.", "answer.scoring"));
    const order = cfg.targets.map(sceneSpec_1.scene3DTargetKey), keys = correct;
    if (!keys.length)
        issues.push(err("SCENE3D_SELECTION_KEY_EMPTY", "حدّد الإجابة الصحيحة على النموذج.", "answer.correct"));
    if (new Set(keys).size !== keys.length)
        issues.push(err("SCENE3D_SELECTION_KEY_DUPLICATE", "الإجابة الصحيحة مكررة.", "answer.correct"));
    const unknown = keys.filter(k => !order.includes(k));
    if (unknown.length)
        issues.push(err("SCENE3D_SELECTION_KEY_UNKNOWN_TARGET", "مفتاح التصحيح يذكر هدفًا غير موجود: «" + unknown[0].slice(0, 48) + "».", "answer.correct"));
    if (cfg.config.mode === "single" && keys.length > 1)
        issues.push(err("SCENE3D_SELECTION_KEY_SINGLE", "الاختيار الواحد له إجابة صحيحة واحدة.", "answer.correct"));
    if (keys.length > cfg.config.maxSelections)
        issues.push(err("SCENE3D_SELECTION_KEY_UNREACHABLE", "عدد الإجابات الصحيحة أكبر من الحد المتاح للطالب.", "answer.correct"));
    return issues.length ? { ok: false, issues } : { ok: true, key: { scoring: scoring, correct: order.filter(k => keys.includes(k)) }, issues: [] };
}
function validateScene3DSelectionAnswerKey(raw, rawConfig) {
    const cfg = validateScene3DSelectionConfig(rawConfig);
    if (!cfg.ok)
        return { ok: false, issues: [err("SCENE3D_SELECTION_KEY_CONFIG_INVALID", "لا يمكن فحص المفتاح لأن إعداد سؤال 3D غير صالح.", "scene3DSelection")] };
    return checkKey(raw, cfg);
}
function validateScene3DSelectionQuestion(node) {
    const out = [];
    if ((0, exports.scene3DSelectionQuestionVersion)(node) === undefined)
        out.push(err("SCENE3D_SELECTION_VERSION_UNSUPPORTED", "إصدار سؤال 3D غير مدعوم.", "questionTypeVersion"));
    const cfg = validateScene3DSelectionConfig(node.scene3DSelection);
    if (!cfg.ok)
        out.push(...cfg.issues);
    const key = checkKey(node.answer, cfg.ok ? cfg : null);
    if (!key.ok)
        out.push(...key.issues);
    return out;
}
function projectScene3DSelectionConfigForStudent(raw) {
    const r = validateScene3DSelectionConfig(raw);
    if (!r.ok)
        return null;
    const scene = (0, sceneSpec_1.projectInteractive3DSceneForStudent)(r.config.scene);
    return scene ? { ...r.config, scene } : null;
}
function readResponse(response, cfg) {
    if (!isPlain(response) || response.kind !== "scene3DSelection" || !Array.isArray(response.targets))
        return { ok: false, code: "SCENE3D_SELECTION_ANSWER_INVALID" };
    if (response.sceneId !== cfg.config.scene.id)
        return { ok: false, code: "SCENE3D_SELECTION_SCENE_MISMATCH" };
    const given = response.targets;
    if (given.length > Math.min(cfg.config.maxSelections, exports.SCENE3D_SELECTION_LIMITS.responseTargets))
        return { ok: false, code: "SCENE3D_SELECTION_TOO_MANY" };
    if (given.some(k => typeof k !== "string"))
        return { ok: false, code: "SCENE3D_SELECTION_ANSWER_INVALID" };
    const order = cfg.targets.map(sceneSpec_1.scene3DTargetKey);
    if (given.some(k => !order.includes(k)))
        return { ok: false, code: "SCENE3D_SELECTION_TARGET_UNKNOWN" };
    if (new Set(given).size !== given.length)
        return { ok: false, code: "SCENE3D_SELECTION_DUPLICATE" };
    return { ok: true, targets: order.filter(k => given.includes(k)) };
}
function normalizeScene3DSelectionAnswer(a) {
    if (!isPlain(a) || a.kind !== "scene3DSelection" || typeof a.sceneId !== "string" || !ID.test(a.sceneId) || FORBIDDEN.has(a.sceneId) || !Array.isArray(a.targets))
        return { ok: false, code: "SCENE3D_SELECTION_ANSWER_INVALID" };
    if (a.targets.length > exports.SCENE3D_SELECTION_LIMITS.responseTargets)
        return { ok: false, code: "SCENE3D_SELECTION_TOO_MANY" };
    if (a.targets.some(k => typeof k !== "string" || !TARGET.test(k)))
        return { ok: false, code: "SCENE3D_SELECTION_ANSWER_INVALID" };
    if (new Set(a.targets).size !== a.targets.length)
        return { ok: false, code: "SCENE3D_SELECTION_DUPLICATE" };
    return { ok: true, answer: { kind: "scene3DSelection", sceneId: a.sceneId, targets: [...a.targets] } };
}
function bindScene3DSelectionAnswerToQuestion(a, question) {
    const shape = normalizeScene3DSelectionAnswer(a);
    if (!shape.ok)
        return shape;
    const cfg = isPlain(question) ? validateScene3DSelectionConfig(question.scene3DSelection) : null;
    if (!cfg || !cfg.ok)
        return shape;
    const r = readResponse(shape.answer, cfg);
    return r.ok ? { ok: true, answer: { kind: "scene3DSelection", sceneId: cfg.config.scene.id, targets: r.targets } } : r;
}
const isScene3DSelectionAnswerAnswered = (a) => isPlain(a) && a.kind === "scene3DSelection" && Array.isArray(a.targets) && a.targets.length > 0;
exports.isScene3DSelectionAnswerAnswered = isScene3DSelectionAnswerAnswered;
exports.SCENE3D_SELECTION_FAIL_CLOSED = Object.freeze({ score: 0, correct: false, manualReview: true, parts: Object.freeze({ correct: 0, total: 0 }) });
function authorityOf(rawConfig, rawKey) {
    const cfg = validateScene3DSelectionConfig(rawConfig);
    if (!cfg.ok)
        return null;
    const key = checkKey(rawKey, cfg);
    return key.ok ? { config: cfg.config, targets: cfg.targets, key: key.key } : null;
}
function scoreScene3DSelection(input) {
    const max = Number.isFinite(input.maxMarks) ? Math.max(0, input.maxMarks) : 0, auth = authorityOf(input.config, input.answerKey);
    if (!auth)
        return { ...exports.SCENE3D_SELECTION_FAIL_CLOSED, parts: { ...exports.SCENE3D_SELECTION_FAIL_CLOSED.parts } };
    const total = auth.key.correct.length, r = readResponse(input.response, auth);
    if (!r.ok)
        return { score: 0, correct: false, manualReview: false, parts: { correct: 0, total } };
    const hits = r.targets.filter(k => auth.key.correct.includes(k)).length, union = new Set([...r.targets, ...auth.key.correct]).size;
    const exact = hits === total && r.targets.length === total;
    const score = auth.key.scoring === "allOrNothing" ? (exact ? max : 0) : max * hits / Math.max(1, union);
    return { score: Math.min(max, Math.max(0, score)), correct: exact, manualReview: false, parts: { correct: hits, total } };
}
function evaluateScene3DSelection(rawConfig, rawKey, rawResponse) {
    const auth = authorityOf(rawConfig, rawKey);
    if (!auth) {
        const cfg = validateScene3DSelectionConfig(rawConfig);
        return { ok: false, issues: cfg.ok ? validateScene3DSelectionAnswerKey(rawKey, rawConfig).issues : cfg.issues };
    }
    const r = readResponse(rawResponse, auth), chosen = new Set(r.ok ? r.targets : []);
    const results = auth.targets.map(t => { const key = (0, sceneSpec_1.scene3DTargetKey)(t), selected = chosen.has(key), expected = auth.key.correct.includes(key); return { key, label: t.label, detail: t.detail ?? "", selected, expected, mark: selected && expected ? "correct" : selected ? "incorrect" : expected ? "missed" : null }; });
    const hits = results.filter(x => x.mark === "correct").length;
    return { ok: true, correct: hits, total: auth.key.correct.length, exact: hits === auth.key.correct.length && chosen.size === hits, results };
}
