// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isHtmlPath = exports.isInsideDist = exports.SMARTSIM_DIST_PREFIX = exports.SMARTSIM_PATH_MAX = exports.SMARTSIM_DESCRIPTION_MAX = exports.SMARTSIM_TITLE_MAX = exports.SMARTSIM_PACKAGE_HASH_PATTERN = exports.SMARTSIM_PACKAGE_ID_PATTERN = exports.SMARTSIM_SUPPORTED_RESPONSE_SCHEMA_VERSIONS = exports.SMARTSIM_SUPPORTED_RUNTIME_VERSIONS = exports.SIMULATION_RUNTIME_VERSION = exports.SMARTSIM_MANIFEST_SCHEMA_VERSION = void 0;
exports.isSafePackagePath = isSafePackagePath;
exports.validateSmartSimManifest = validateSmartSimManifest;
exports.validateSimulationReference = validateSimulationReference;
exports.simulationReferenceOf = simulationReferenceOf;
exports.SMARTSIM_MANIFEST_SCHEMA_VERSION = 1;
exports.SIMULATION_RUNTIME_VERSION = 1;
exports.SMARTSIM_SUPPORTED_RUNTIME_VERSIONS = Object.freeze([1]);
exports.SMARTSIM_SUPPORTED_RESPONSE_SCHEMA_VERSIONS = Object.freeze([1]);
exports.SMARTSIM_PACKAGE_ID_PATTERN = /^[a-z][a-z0-9-]{1,63}$/;
exports.SMARTSIM_PACKAGE_HASH_PATTERN = /^sha256:[0-9a-f]{64}$/;
exports.SMARTSIM_TITLE_MAX = 120;
exports.SMARTSIM_DESCRIPTION_MAX = 1000;
exports.SMARTSIM_PATH_MAX = 255;
exports.SMARTSIM_DIST_PREFIX = "dist/";
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const issue = (code, message, path) => ({ code, message, severity: "error", path });
const SCHEME = /^[a-zA-Z][a-zA-Z0-9+.-]*:/;
const DRIVE = /^[a-zA-Z]:/;
function hasControlChar(s) { for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c < 0x20 || c === 0x7f)
        return true;
} return false; }
function isSafePackagePath(p) {
    if (typeof p !== "string" || p.length === 0 || p.length > exports.SMARTSIM_PATH_MAX)
        return false;
    if (hasControlChar(p) || p.includes("\\") || p.startsWith("/") || p.startsWith("//") || DRIVE.test(p) || SCHEME.test(p))
        return false;
    const segments = p.split("/");
    for (const s of segments)
        if (s === "" || s === "." || s === "..")
            return false;
    return true;
}
const isInsideDist = (p) => p.startsWith(exports.SMARTSIM_DIST_PREFIX) && p.length > exports.SMARTSIM_DIST_PREFIX.length;
exports.isInsideDist = isInsideDist;
const isHtmlPath = (p) => /\.html?$/i.test(p);
exports.isHtmlPath = isHtmlPath;
function validateSmartSimManifest(raw) {
    const issues = [];
    if (!isObj(raw))
        return { ok: false, issues: [issue("MANIFEST_INVALID", "manifest.json يجب أن يكون كائن JSON.")] };
    if (raw.schemaVersion !== exports.SMARTSIM_MANIFEST_SCHEMA_VERSION)
        issues.push(issue("MANIFEST_SCHEMA_VERSION", "schemaVersion غير مدعوم: " + String(raw.schemaVersion) + " (المدعوم: 1).", "schemaVersion"));
    if (typeof raw.packageId !== "string" || !exports.SMARTSIM_PACKAGE_ID_PATTERN.test(raw.packageId))
        issues.push(issue("MANIFEST_PACKAGE_ID", "packageId يجب أن يكون معرّفًا ثابتًا بأحرف لاتينية صغيرة وأرقام وشرطات (2–64 حرفًا، يبدأ بحرف).", "packageId"));
    if (!Number.isInteger(raw.packageVersion) || raw.packageVersion < 1)
        issues.push(issue("MANIFEST_PACKAGE_VERSION", "packageVersion يجب أن يكون عددًا صحيحًا موجبًا (1، 2، 3…).", "packageVersion"));
    if (typeof raw.title !== "string" || !raw.title.trim() || raw.title.length > exports.SMARTSIM_TITLE_MAX)
        issues.push(issue("MANIFEST_TITLE", "title مطلوب (حتى " + exports.SMARTSIM_TITLE_MAX + " حرفًا).", "title"));
    if (raw.description !== undefined && (typeof raw.description !== "string" || raw.description.length > exports.SMARTSIM_DESCRIPTION_MAX))
        issues.push(issue("MANIFEST_DESCRIPTION", "description يجب أن يكون نصًا (حتى " + exports.SMARTSIM_DESCRIPTION_MAX + " حرف).", "description"));
    if (!isSafePackagePath(raw.entry) || !(0, exports.isInsideDist)(raw.entry))
        issues.push(issue("ENTRY_UNSAFE", "entry يجب أن يكون مسارًا نسبيًا آمنًا داخل dist/ (مثل dist/index.html).", "entry"));
    if (raw.runtime !== "web")
        issues.push(issue("MANIFEST_RUNTIME", "runtime يجب أن يكون \"web\".", "runtime"));
    if (!Number.isInteger(raw.runtimeVersion) || !exports.SMARTSIM_SUPPORTED_RUNTIME_VERSIONS.includes(raw.runtimeVersion))
        issues.push(issue("RUNTIME_UNSUPPORTED", "runtimeVersion غير مدعوم: " + String(raw.runtimeVersion) + " (المدعوم: " + exports.SMARTSIM_SUPPORTED_RUNTIME_VERSIONS.join(", ") + ").", "runtimeVersion"));
    if (!Number.isInteger(raw.responseSchemaVersion) || !exports.SMARTSIM_SUPPORTED_RESPONSE_SCHEMA_VERSIONS.includes(raw.responseSchemaVersion))
        issues.push(issue("RESPONSE_SCHEMA_UNSUPPORTED", "responseSchemaVersion غير مدعوم: " + String(raw.responseSchemaVersion) + ".", "responseSchemaVersion"));
    if (!isObj(raw.capabilities))
        issues.push(issue("MANIFEST_CAPABILITIES", "capabilities يجب أن يكون كائنًا (autosave / restore / reset / partialCredit / offline).", "capabilities"));
    else
        for (const [k, v] of Object.entries(raw.capabilities))
            if (typeof v !== "boolean")
                issues.push(issue("MANIFEST_CAPABILITIES", "capabilities." + k + " يجب أن يكون true/false.", "capabilities." + k));
    if (issues.length)
        return { ok: false, issues };
    const caps = raw.capabilities;
    const manifest = {
        schemaVersion: 1, packageId: raw.packageId, packageVersion: raw.packageVersion, title: raw.title.trim(),
        entry: raw.entry, runtime: "web", runtimeVersion: raw.runtimeVersion, responseSchemaVersion: raw.responseSchemaVersion,
        capabilities: { autosave: caps.autosave === true, restore: caps.restore === true, reset: caps.reset === true, partialCredit: caps.partialCredit === true, offline: caps.offline === true }
    };
    if (typeof raw.description === "string" && raw.description.trim())
        manifest.description = raw.description.trim();
    return { ok: true, manifest, issues };
}
function validateSimulationReference(cfg) {
    if (!isObj(cfg))
        return [issue("SIM_PACKAGE_MISSING", "لم يتم اختيار حزمة محاكاة لهذا السؤال. اختر محاكيًا من المكتبة أو ارفع حزمة .smartsim.", "simulation")];
    const out = [];
    if (typeof cfg.packageId !== "string" || !exports.SMARTSIM_PACKAGE_ID_PATTERN.test(cfg.packageId))
        out.push(issue("SIM_PACKAGE_ID_INVALID", "معرّف حزمة المحاكاة غير صالح.", "simulation.packageId"));
    if (!Number.isInteger(cfg.packageVersion) || cfg.packageVersion < 1)
        out.push(issue("SIM_PACKAGE_VERSION_INVALID", "إصدار حزمة المحاكاة يجب أن يكون رقمًا صحيحًا محددًا (لا \"latest\").", "simulation.packageVersion"));
    if (typeof cfg.packageHash !== "string" || !exports.SMARTSIM_PACKAGE_HASH_PATTERN.test(cfg.packageHash))
        out.push(issue("SIM_PACKAGE_HASH_INVALID", "بصمة حزمة المحاكاة (sha256) مفقودة أو غير صالحة؛ يجب تثبيت الحزمة بالضبط.", "simulation.packageHash"));
    if (!Number.isInteger(cfg.runtimeVersion) || !exports.SMARTSIM_SUPPORTED_RUNTIME_VERSIONS.includes(cfg.runtimeVersion))
        out.push(issue("SIM_RUNTIME_UNSUPPORTED", "إصدار بيئة تشغيل المحاكاة غير مدعوم.", "simulation.runtimeVersion"));
    if (cfg.entry !== undefined && (!isSafePackagePath(cfg.entry) || !(0, exports.isHtmlPath)(cfg.entry)))
        out.push(issue("SIM_ENTRY_UNSAFE", "مسار ملف الدخول للمحاكاة غير آمن.", "simulation.entry"));
    if (cfg.title !== undefined && (typeof cfg.title !== "string" || cfg.title.length > exports.SMARTSIM_TITLE_MAX))
        out.push(issue("SIM_TITLE_INVALID", "عنوان المحاكاة غير صالح.", "simulation.title"));
    if (cfg.scenario !== undefined && !isObj(cfg.scenario))
        out.push(issue("SIM_SCENARIO_INVALID", "سيناريو المحاكاة يجب أن يكون كائن JSON.", "simulation.scenario"));
    if (cfg.publicConfig !== undefined && !isObj(cfg.publicConfig))
        out.push(issue("SIM_PUBLIC_CONFIG_INVALID", "الإعدادات العامة للمحاكاة يجب أن تكون كائن JSON.", "simulation.publicConfig"));
    return out;
}
function simulationReferenceOf(pkg) {
    const ref = { packageId: pkg.packageId, packageVersion: pkg.packageVersion, packageHash: pkg.packageHash, runtimeVersion: pkg.runtimeVersion };
    if (typeof pkg.entry === "string" && pkg.entry)
        ref.entry = pkg.entry;
    if (typeof pkg.title === "string" && pkg.title)
        ref.title = pkg.title;
    return ref;
}
