// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isForbiddenKey = exports.listSmartSimPluginDescriptors = exports.listSmartSimPlugins = exports.smartSimPluginId = exports.SMART_SIM_LIMITS = void 0;
exports.registerSmartSimPlugin = registerSmartSimPlugin;
exports.resolveSmartSimPlugin = resolveSmartSimPlugin;
exports.resolveSmartSimDescriptor = resolveSmartSimDescriptor;
exports.checkBoundedJson = checkBoundedJson;
const trustedSimDescriptor_1 = require("./trustedSimDescriptor");
exports.SMART_SIM_LIMITS = Object.freeze({ actions: 1000, answerBytes: 262144, depth: 8, checks: 100, checkLabelChars: 120, maxWeight: 1000, keysPerObject: 64 });
const KEY_PATTERN = /^[a-z][A-Za-z0-9]{1,47}$/;
const FORBIDDEN_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const smartSimPluginId = (key, version) => key + "@" + version;
exports.smartSimPluginId = smartSimPluginId;
const plugins = new Map();
const descriptors = new Map();
const FUNCTIONS = ["validateConfig", "createRuntime", "normalizeAction", "applyAction", "canonicalState", "serializeState", "validateCheck", "evaluateCheck"];
function registerSmartSimPlugin(plugin) {
    if (!plugin || typeof plugin !== "object")
        throw new Error("smartSim plugin required");
    const { key, version } = plugin;
    if (typeof key !== "string" || !KEY_PATTERN.test(key) || FORBIDDEN_KEYS.has(key))
        throw new Error("invalid smartSim plugin key: " + String(key));
    if (typeof version !== "number" || !Number.isInteger(version) || version < 1)
        throw new Error("invalid smartSim plugin version for " + key);
    for (const f of FUNCTIONS)
        if (typeof plugin[f] !== "function")
            throw new Error("smartSim plugin " + key + "@" + version + ": " + f + " must be a function");
    for (const f of ["validateActions", "reviewDetails", "ruleView"])
        if (plugin[f] !== undefined && typeof plugin[f] !== "function")
            throw new Error("smartSim plugin " + key + "@" + version + ": " + f + " must be a function");
    if (typeof plugin.label !== "string" || !plugin.label.trim())
        throw new Error("smartSim plugin " + key + "@" + version + ": label required");
    if (!Number.isInteger(plugin.maxActions) || plugin.maxActions < 1 || plugin.maxActions > exports.SMART_SIM_LIMITS.actions)
        throw new Error("smartSim plugin " + key + "@" + version + ": maxActions must be 1.." + exports.SMART_SIM_LIMITS.actions);
    if (!Array.isArray(plugin.checkKinds) || plugin.checkKinds.length === 0 || plugin.checkKinds.some(k => typeof k !== "string" || !k))
        throw new Error("smartSim plugin " + key + "@" + version + ": checkKinds required");
    const checked = (0, trustedSimDescriptor_1.validateSmartSimDescriptor)(plugin.descriptor);
    if (!checked.ok)
        throw new Error("smartSim plugin " + key + "@" + version + ": invalid descriptor (" + checked.issues.map(i => i.code).join(", ") + ")");
    const d = checked.descriptor;
    if (d.key !== key || d.version !== version || d.label !== plugin.label)
        throw new Error("smartSim plugin " + key + "@" + version + ": descriptor identity / label does not match the plugin");
    if (d.checkKinds.length !== plugin.checkKinds.length || d.checkKinds.some(k => !plugin.checkKinds.includes(k)))
        throw new Error("smartSim plugin " + key + "@" + version + ": descriptor checkKinds do not match the plugin");
    if (d.genericRules.length && typeof plugin.ruleView !== "function")
        throw new Error("smartSim plugin " + key + "@" + version + ": generic rules require a ruleView");
    const id = (0, exports.smartSimPluginId)(key, version);
    if (plugins.has(id))
        throw new Error("smartSim plugin already registered: " + id);
    plugins.set(id, plugin);
    descriptors.set(id, d);
    return () => { if (plugins.get(id) === plugin) {
        plugins.delete(id);
        descriptors.delete(id);
    } };
}
function resolveSmartSimPlugin(key, version) {
    if (typeof key !== "string" || typeof version !== "number" || !Number.isInteger(version))
        return undefined;
    return plugins.get((0, exports.smartSimPluginId)(key, version));
}
const listSmartSimPlugins = () => [...plugins.values()].map(p => ({ key: p.key, version: p.version, label: p.label }));
exports.listSmartSimPlugins = listSmartSimPlugins;
function resolveSmartSimDescriptor(key, version) {
    if (typeof key !== "string" || typeof version !== "number" || !Number.isInteger(version))
        return undefined;
    return descriptors.get((0, exports.smartSimPluginId)(key, version));
}
const listSmartSimPluginDescriptors = () => [...descriptors.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([, d]) => (0, trustedSimDescriptor_1.descriptorData)(d));
exports.listSmartSimPluginDescriptors = listSmartSimPluginDescriptors;
function checkBoundedJson(value) {
    let failure;
    const walk = (v, depth) => {
        if (failure)
            return;
        if (depth > exports.SMART_SIM_LIMITS.depth) {
            failure = "SMARTSIM_JSON_TOO_DEEP";
            return;
        }
        if (v === null || typeof v === "string" || typeof v === "boolean")
            return;
        if (typeof v === "number") {
            if (!Number.isFinite(v))
                failure = "SMARTSIM_JSON_INVALID";
            return;
        }
        if (Array.isArray(v)) {
            for (const x of v)
                walk(x, depth + 1);
            return;
        }
        if (typeof v !== "object" || Object.getPrototypeOf(v) !== Object.prototype && Object.getPrototypeOf(v) !== null) {
            failure = "SMARTSIM_JSON_INVALID";
            return;
        }
        const keys = Object.keys(v);
        if (keys.length > exports.SMART_SIM_LIMITS.keysPerObject) {
            failure = "SMARTSIM_JSON_INVALID";
            return;
        }
        for (const k of keys) {
            if (FORBIDDEN_KEYS.has(k)) {
                failure = "SMARTSIM_JSON_INVALID";
                return;
            }
            walk(v[k], depth + 1);
        }
    };
    walk(value, 0);
    if (failure)
        return failure;
    let text;
    try {
        text = JSON.stringify(value);
    }
    catch {
        return "SMARTSIM_JSON_INVALID";
    }
    return typeof text !== "string" || utf8Length(text) > exports.SMART_SIM_LIMITS.answerBytes ? "SMARTSIM_ANSWER_TOO_LARGE" : undefined;
}
function utf8Length(text) {
    let n = 0;
    for (let i = 0; i < text.length; i++) {
        const c = text.charCodeAt(i);
        if (c < 0x80)
            n += 1;
        else if (c < 0x800)
            n += 2;
        else if (c >= 0xd800 && c <= 0xdbff && i + 1 < text.length) {
            n += 4;
            i++;
        }
        else
            n += 3;
    }
    return n;
}
const isForbiddenKey = (k) => FORBIDDEN_KEYS.has(k);
exports.isForbiddenKey = isForbiddenKey;
