import { describe, it, expect, beforeAll } from "vitest";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { publishAndAssign, takeExam } from "../certification-20g/lifecycle.js";
import { ledgerOf, attemptInvariants } from "../certification-20g/ledger.js";
import { scanProjection } from "../certification-20g/scan.js";
import { A } from "../certification-20g/kit.js";
import { parseStructuredExamJson } from "../../../src/structuredExamImport";
import { toSavedStructuredExam } from "../../../src/examBuilderState";
import { evaluateExamFinalization } from "../../../src/examFinalization";
import { validateMeshModelSpec } from "../../../src/meshModels/meshModelSpec";
import { MESH_LIBRARY } from "../../../src/meshModels/meshAssetCatalog";
import { writeGlb, testAssemblyModel } from "../../../src/meshModels/glbWriter";
import { evaluateMeshPartSelection, meshNeutralPartLabel, validateMeshPartSelectionQuestion } from "../../../src/meshPartSelectionQuestion";
import { MESH_MODELS_ACCEPTANCE_PATH, MODELS_21DB3 } from "../../../scripts/mesh-models-21db3-exam.mjs";

// Phase 21D-B.3 — the REALISTIC 3D MESH MODELS ACCEPTANCE EXAM (docs/fixtures/mesh-models-21db3/…json, generated by
// scripts/generate-mesh-models-21db3-fixture.mjs): an Arabic exam with three heart questions (single choice, a two-part partial-credit
// selection, an identification question with hidden labels), three brain questions (single, an all-or-nothing three-part selection, an
// identification question with hidden labels) and an ordinary multiple-choice question in the same exam — 28 marks, six models over the two
// reviewed BodyParts3D library assets. Driven through the REAL platform: import / canonical save / export / re-import, finalization,
// save → load → governance (including the mesh-asset availability gate) → publish → assignment, sanitized delivery (models exact, hidden
// labels replaced, no key), autosave / restore, idempotent submit, hand-derived ledgers (PERFECT / PARTIAL / BLANK / ATTACKER) and teacher
// review. A second part certifies the governance gate for teacher-UPLOADED models (bytes present, hash re-verified, labelled parts exist).
const require_ = createRequire(import.meta.url);
const { createPlatform, TEACHER } = require_("../certification-20g/platform.js");
const { examOfficialStats } = require_("../../src/lib/exam-structure.js");
const { gradeExam } = require_("../../src/lib/assignment-grading.js");
const { sanitizeExamForStudent } = require_("../../src/lib/student-exam-sanitize.js");
const { canonicalizeExamContent } = require_("../../src/lib/exam-canonical.js");
const { normalizeDraftAnswers } = require_("../../src/lib/draft-answers.js");
const store = require_("../../src/lib/mesh-assets/store.js");
const { inspectGlbAsset } = require_("../../src/lib/shared-finalization/meshModels/glbAsset.js");
const { createMemoryContainer } = require_("../fixtures/memory-container.js");
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const load = () => JSON.parse(fs.readFileSync(path.join(repo, MESH_MODELS_ACCEPTANCE_PATH), "utf8"));
const qs = e => e.sections.flatMap(s => s.questions);
const configsOf = e => Object.fromEntries(qs(e).filter(q => q.meshPartSelection).map(q => [q.examQuestionId, q.meshPartSelection]));
const STUDENTS = { "mm-perfect": "طالب مثالي", "mm-partial": "طالب جزئي", "mm-blank": "طالب لم يجب", "mm-attacker": "طالب مهاجم" };

const sel = (modelId, ...parts) => ({ kind: "meshPartSelection", modelId, parts });
const PERFECT = {
  h1: sel("heartChambers", "leftVentricle"), h2: sel("heartVessels", "aorta", "pulmonaryTrunk"), h3: sel("heartValves", "mitralValve"),
  b1: sel("brainBalance", "cerebellum"), b2: sel("brainStem", "midbrain", "pons", "medullaOblongata"), b3: sel("brainLobes", "occipitalLobe"),
  c1: A.choice(0)
};
// h1 the right ventricle · h2 only the aorta of {aorta, pulmonary trunk} (partial: 4 × 1/2 = 2) · b2 two of the three brainstem parts
// (all-or-nothing: 0) · b3 the parietal lobe · c1 a wrong option. The order a student clicks in never matters (h2/b2 stored in model order).
const PARTIAL = { ...PERFECT, h1: sel("heartChambers", "rightVentricle"), h2: sel("heartVessels", "aorta"), b2: sel("brainStem", "pons", "midbrain"), b3: sel("brainLobes", "parietalLobe"), c1: A.choice(3) };
const LEDGER = {
  PERFECT: { h1: [4, 0], h2: [4, 0], h3: [4, 0], b1: [4, 0], b2: [6, 0], b3: [4, 0], c1: [2, 0] },
  PARTIAL: { h1: [0, 0], h2: [2, 0], h3: [4, 0], b1: [4, 0], b2: [0, 0], b3: [0, 0], c1: [0, 0] }
};
const TOTAL = { PERFECT: 28, PARTIAL: 10 };
// ATTACKER — every mesh answer is forged: a self-graded answer carrying a score / camera / pixels, more parts than allowed, another
// question's model, a duplicate, a part the question never labelled, a prototype key, a mesh answer on the multiple-choice question and on a
// question that does not exist. The ingest binder refuses every one (nothing stored, nothing graded): the attacker earns 0.
const ATTACKER = {
  h1: { ...sel("heartChambers", "leftVentricle"), score: 4, correct: true, camera: { azimuth: 1 }, x: 120, y: 80 },
  h2: sel("heartVessels", "aorta", "pulmonaryTrunk", "superiorVenaCava"),
  h3: sel("heartChambers", "mitralValve"),
  b1: sel("brainBalance", "cerebellum", "cerebellum"),
  b2: sel("brainStem", "midbrain", "pons", "thalamus"),
  b3: sel("brainLobes", "__proto__"),
  c1: sel("brainLobes", "frontalLobe"),
  zz: sel("heartChambers", "leftVentricle")
};
const ATTACKER_REFUSED = [
  ["b1", "MESH_SELECTION_DUPLICATE"], ["b2", "MESH_SELECTION_PART_UNKNOWN"], ["b3", "MESH_SELECTION_ANSWER_INVALID"], ["c1", "MESH_SELECTION_QUESTION_MISMATCH"],
  ["h1", "MESH_SELECTION_ANSWER_INVALID"], ["h2", "MESH_SELECTION_TOO_MANY"], ["h3", "MESH_SELECTION_MODEL_MISMATCH"], ["zz", "MESH_SELECTION_QUESTION_MISMATCH"]
];

describe("21DB3 authoring: the fixture is a real, finalizable exam over the reviewed anatomical library", () => {
  it("schemaVersion 2, three sections (28 marks), six meshPartSelection questions + one multiple choice, every model valid against the catalog", () => {
    const e = load();
    expect([e.schemaVersion, e.examId, e.sections.map(s => s.id)]).toEqual([2, "EXAMBANK-21DB3-MESH-MODELS", ["sec-heart", "sec-brain", "sec-mixed"]]);
    const s = examOfficialStats(e);
    expect([s.totalMarks, ...s.sections.map(x => x.totalMarks)]).toEqual([28, 12, 14, 2]);
    expect(qs(e).map(q => q.presentationType)).toEqual([...Array(6).fill("meshPartSelection"), "multipleChoice"]);
    for (const q of qs(e).filter(x => x.meshPartSelection)) {
      expect(validateMeshPartSelectionQuestion(q), q.examQuestionId).toEqual([]);
      const m = validateMeshModelSpec(q.meshPartSelection.model);
      expect(m.ok && m.library && m.library.id, q.examQuestionId).toBe(q.meshPartSelection.model.asset.id);
    }
    expect(new Set(qs(e).filter(x => x.meshPartSelection).map(q => q.meshPartSelection.model.asset.id))).toEqual(new Set(["human-heart-bp3d", "human-brain-bp3d"]));
    expect(evaluateExamFinalization(e).blockers.map(b => b.message)).toEqual([]);
  });
  it("the exam JSON references the models by library id + version + SHA-256 only: no binary, no data URI, no URL, small", () => {
    const raw = fs.readFileSync(path.join(repo, MESH_MODELS_ACCEPTANCE_PATH), "utf8");
    expect(raw.length).toBeLessThan(32 * 1024);
    expect(raw).not.toMatch(/data:|base64|https?:\/\/|\.glb|"uri"|"url"|"src"/i);
    for (const m of Object.values(MODELS_21DB3)) {
      const lib = MESH_LIBRARY.find(a => a.id === m.asset.id);
      expect([m.asset.version, m.asset.sha256]).toEqual([lib.version, lib.sha256]);
    }
  });
  it("import / export is EXACT: import → canonical save → export → import keeps every model, config and key byte-for-byte", () => {
    const e = load();
    const imp = parseStructuredExamJson(JSON.stringify(e), "ExamBank_21DB3_Mesh_Models_Acceptance.json");
    expect([imp.canOpen, imp.parseErrors, imp.validationErrors.filter(i => i.severity === "error")]).toEqual([true, [], []]);
    expect(qs(imp.exam)).toEqual(qs(e));
    const saved = toSavedStructuredExam(imp.exam);
    expect(configsOf(saved)).toEqual(configsOf(e));
    const again = parseStructuredExamJson(JSON.stringify(saved), "re-export.json");
    expect(configsOf(again.exam)).toEqual(configsOf(e));
    expect(qs(again.exam).map(q => q.answer)).toEqual(qs(e).map(q => q.answer));
    expect(configsOf(canonicalizeExamContent(e))).toEqual(configsOf(e));
  });
  it("a \"first N answered\" section counts a mesh answer as answered (an empty selection never takes a slot)", () => {
    const e = load();
    e.sections = [{ ...e.sections[0], gradingPolicy: "firstNAnswered", requiredAnswers: 2 }];
    const g = (answers) => gradeExam(e, answers);
    // h1 wrong + h2 blank (empty selection) + h3 right → h1 and h3 are the two counted units: 0 + 4 of 8
    const r = g({ h1: sel("heartChambers", "rightVentricle"), h2: sel("heartVessels"), h3: sel("heartValves", "mitralValve") });
    expect([r.score, r.totalMarks, r.questions.filter(q => q.countedMaxMarks > 0).map(q => q.questionId)]).toEqual([4, 8, ["h1", "h3"]]);
    // all three right → only the first two answered count
    expect(g(PERFECT).score).toBe(8);
    expect(g({}).score).toBe(0);
  });
  it("finalization refuses a model that points outside the reviewed library or carries an executable / unknown field", () => {
    const tamper = mutate => { const e = load(); mutate(e.sections[0].questions[0].meshPartSelection.model); return evaluateExamFinalization(e).blockers.length; };
    expect(tamper(m => { m.asset.sha256 = "f".repeat(64); })).toBeGreaterThan(0);
    expect(tamper(m => { m.asset = { source: "url", url: "https://evil.example/heart.glb" }; })).toBeGreaterThan(0);
    expect(tamper(m => { m.renderer = { script: "alert(1)" }; })).toBeGreaterThan(0);
    expect(tamper(m => { m.parts.push({ id: "thalamus", label: "المهاد" }); })).toBeGreaterThan(0);
  });
  it("the student projection keeps the models, replaces hidden labels with neutral names, and leaks no key", () => {
    const e = load();
    const p = sanitizeExamForStudent(e);
    const cfg = configsOf(p), orig = configsOf(e);
    for (const id of ["h1", "h2", "b1", "b2"]) expect(cfg[id], id).toEqual(orig[id]);
    for (const id of ["h3", "b3"]) {
      expect(cfg[id].model.parts, id).toEqual(orig[id].model.parts.map((x, i) => ({ id: x.id, label: meshNeutralPartLabel(i) })));
      const json = JSON.stringify(cfg[id]);
      for (const x of orig[id].model.parts) expect(json, id).not.toContain(x.label);
    }
    expect(scanProjection(p, { secrets: ["allOrNothing", "\"partial\""] })).toEqual([]);
    expect(JSON.stringify(p)).not.toMatch(/"correct"|"scoring"/);
  });
});

describe("21DB3 full platform lifecycle", () => {
  let p, aid, published;
  const runs = {};
  beforeAll(async () => {
    p = createPlatform({ students: STUDENTS });
    published = await publishAndAssign(p, load());
    aid = published.aid;
    runs.PERFECT = await takeExam(p, aid, "mm-perfect", PERFECT, { chunks: 3 });
    runs.PARTIAL = await takeExam(p, aid, "mm-partial", PARTIAL);
  }, 120000);

  it("save → load → governance (mesh gate passes: library assets only) → publish → assignment keep every model byte-for-byte", () => {
    const e = load();
    expect(published.pub.ok).toBe(true);
    expect(configsOf(published.loaded)).toEqual(configsOf(e));
    expect(configsOf(p.assignmentOf(aid).examSnapshot)).toEqual(configsOf(e));
    expect(qs(p.assignmentOf(aid).examSnapshot).map(q => q.answer)).toEqual(qs(e).map(q => q.answer));
  });
  it("delivery: the student receives every model (hidden labels neutral), pre-start hides the body, nothing private leaks", () => {
    const e = load();
    for (const [name, r] of Object.entries(runs)) {
      expect(r.preStart.status, name).toBe(200);
      expect(JSON.stringify(r.preStart.jsonBody), name).not.toContain("human-heart-bp3d");
      const delivered = configsOf(r.delivery.jsonBody.assignment.exam);
      expect(delivered.h1, name).toEqual(configsOf(e).h1);
      expect(delivered.h3.model.parts.map(x => x.label), name).toEqual(["الجزء ١", "الجزء ٢", "الجزء ٣", "الجزء ٤"]);
      expect(scanProjection(r.delivery.jsonBody, { secrets: ["allOrNothing"] }), name).toEqual([]);
      expect(JSON.stringify(r.delivery.jsonBody), name).not.toMatch(/"correct"|"scoring"/);
    }
  });
  it("autosave / restore of the part selections is exact (canonical model order); submit is idempotent; ledgers = hand-derived", () => {
    for (const [name, r] of Object.entries(runs)) {
      for (const x of r.restores) expect(x.restored, name).toEqual(x.expected.answers);
      expect(r.restores.at(-1).restored.h2, name).toEqual(r.answers.h2.parts.length === 2 ? sel("heartVessels", "aorta", "pulmonaryTrunk") : sel("heartVessels", "aorta"));
      expect([r.submit.status, r.duplicateSubmit.status], name).toEqual([200, 409]);
      expect(ledgerOf(r.attempt).questions, name).toEqual(LEDGER[name]);
      expect([r.attempt.score, r.attempt.totalMarks, r.attempt.finalized], name).toEqual([TOTAL[name], 28, true]);
      expect(attemptInvariants(r.attempt, 28), name).toEqual([]);
    }
    expect(runs.PARTIAL.attempt.answers.b2).toEqual(sel("brainStem", "midbrain", "pons"));
  });
  it("a blank submission scores 0 and is final: an unanswered model question is an ordinary unanswered question (never a review)", async () => {
    const s = p.student("mm-blank");
    await s.start(aid);
    expect((await s.submit(aid, {})).status).toBe(200);
    expect(ledgerOf(s.attempt(aid)).questions).toEqual(Object.fromEntries(Object.keys(LEDGER.PERFECT).map(id => [id, [0, 0]])));
    expect([s.attempt(aid).score, s.attempt(aid).manualReviewMarks, s.attempt(aid).finalized]).toEqual([0, 0, true]);
  });
  it("ATTACKER: every forged mesh answer is refused at ingest with its classified code; nothing forged is stored or graded", async () => {
    const snapshot = p.assignmentOf(aid).examSnapshot;
    const n = normalizeDraftAnswers(ATTACKER, snapshot);
    expect(n.rejected.map(r => [r.id, r.code]).sort()).toEqual([...ATTACKER_REFUSED].sort());
    expect(n.answers).toEqual({});
    const s = p.student("mm-attacker");
    expect((await s.start(aid)).status).toBe(200);
    expect((await s.draft(aid, ATTACKER)).status).toBe(200);
    expect((await s.state(aid)).jsonBody.state.draftAnswers).toEqual({});
    expect((await s.submit(aid, ATTACKER)).status).toBe(200);
    const att = s.attempt(aid);
    expect(att.answers).toEqual({});
    expect([att.score, att.manualReviewMarks, att.finalized]).toEqual([0, 0, true]);
    expect(attemptInvariants(att, 28)).toEqual([]);
    expect(JSON.stringify(att)).not.toMatch(/"x":120|"camera"|"score":4,"correct":true/);
  });
  it("grading is decided by the server only and is repeatable: regrading the stored answers gives the same marks", () => {
    const snapshot = p.assignmentOf(aid).examSnapshot;
    for (const [name, r] of Object.entries(runs)) {
      const again = gradeExam(snapshot, r.attempt.answers);
      expect([again.score, gradeExam(snapshot, r.attempt.answers).score], name).toEqual([TOTAL[name], TOTAL[name]]);
    }
  });
  it("FAIL CLOSED on the published snapshot: a mesh question whose model or key can no longer be classified goes to teacher review — never an automatic mark, never a silent zero", () => {
    const snapshot = structuredClone(p.assignmentOf(aid).examSnapshot);
    const q = id => qs(snapshot).find(x => x.examQuestionId === id);
    q("h2").meshPartSelection.model.asset.version = 2;   // a library version this application does not know
    q("b2").answer.scoring = "mostly";                    // a key that cannot be classified
    const r = gradeExam(snapshot, runs.PERFECT.attempt.answers);
    const row = id => r.questions.find(x => x.questionId === id);
    expect([row("h2").manualReview, row("h2").score, row("b2").manualReview, row("b2").score]).toEqual([true, 0, true, 0]);
    expect(["h1", "h3", "b1", "b3", "c1"].map(id => row(id).manualReview)).toEqual([false, false, false, false, false]);
    expect([r.score, r.manualReviewMarks, r.finalized]).toEqual([28 - 4 - 6, 4 + 6, false]);
  });
  it("teacher review: the question carries its REAL model (true labels even when hidden from the student), the key and the stored answer", async () => {
    const rv = await p.teacher.reviewGet(aid, "mm-partial");
    expect(rv.status).toBe(200);
    const byId = Object.fromEntries(rv.jsonBody.questions.map(q => [q.questionId, q]));
    for (const [id, [auto]] of Object.entries(LEDGER.PARTIAL)) expect(byId[id].autoGrade.score, id).toBe(auto);
    const e = load(), h2 = byId.h2, h3 = byId.h3;
    expect([h2.type, h2.meshPartSelection, h2.expectedAnswer, h2.studentAnswer]).toEqual(["meshPartSelection", configsOf(e).h2, { scoring: "partial", correct: ["aorta", "pulmonaryTrunk"] }, sel("heartVessels", "aorta")]);
    expect(h3.meshPartSelection.model.parts.map(x => x.label)).toEqual(configsOf(e).h3.model.parts.map(x => x.label));
    const ev = evaluateMeshPartSelection(h2.meshPartSelection, h2.expectedAnswer, h2.studentAnswer);
    expect(ev.ok && [ev.correct, ev.total, ev.exact, ev.results.filter(x => x.mark).map(x => [x.id, x.mark])]).toEqual([1, 2, false, [["aorta", "correct"], ["pulmonaryTrunk", "missed"]]]);
    const saved = await p.teacher.saveReview(aid, "mm-partial", {}, 1, "مراجعة أسئلة النماذج ثلاثية الأبعاد");
    expect([saved.status, saved.jsonBody.result.score, saved.jsonBody.result.finalized]).toEqual([200, 10, true]);
  });
});

describe("21DB3 governance gate for teacher-uploaded models", () => {
  const glb = Buffer.from(writeGlb(testAssemblyModel()));
  const sha = crypto.createHash("sha256").update(glb).digest("hex");
  const report = inspectGlbAsset(new Uint8Array(glb.buffer, glb.byteOffset, glb.length));
  const uploadModel = (over = {}) => ({
    version: 1, id: "assembly", title: "تركيبة اختبار مرفوعة", description: "نموذج رفعه المعلم وتحقق منه الخادم.",
    asset: { source: "upload", sha256: sha, byteLength: glb.length }, parts: [{ id: "ball", label: "الكرة" }, { id: "rod", label: "القضيب" }, { id: "frontBlock", label: "المكعب الأمامي" }],
    controls: { rotate: true, zoom: true, hideParts: true }, ...over
  });
  const uploadExam = (model = uploadModel()) => ({
    schemaVersion: 2, examId: "EXAMBANK-21DB3-UPLOAD", title: "نموذج مرفوع", status: "draft", metadata: {},
    sections: [{ id: "s1", title: "أ", gradingPolicy: "all", questions: [{ examQuestionId: "u1", presentationType: "meshPartSelection", questionTypeVersion: 1, text: "اختر الكرة.", marks: 3, meshPartSelection: { v: 1, model, mode: "single", maxSelections: 1 }, answer: { scoring: "allOrNothing", correct: ["ball"] } }] }]
  });
  const persist = container => store.persistAsset(container, { buffer: glb, summary: report.summary, ownerHash: store.ownerHashOf(TEACHER), fileName: "assembly.glb" });

  it("the availability check: missing asset, length mismatch, unlabelled part and corrupted bytes are reported; a stored valid asset passes; library assets are not looked up", async () => {
    expect(report.ok).toBe(true);
    const { container } = createMemoryContainer();
    expect((await store.examMeshAssetAvailabilityIssues(container, uploadExam())).map(i => i.code)).toEqual(["MESH_ASSET_UNAVAILABLE"]);
    await persist(container);
    expect(await store.examMeshAssetAvailabilityIssues(container, uploadExam())).toEqual([]);
    expect(await store.examMeshAssetAvailabilityIssues(container, uploadExam(uploadModel({ asset: { source: "upload", sha256: sha, byteLength: glb.length - 1 } })))).toHaveLength(1);
    expect(await store.examMeshAssetAvailabilityIssues(container, uploadExam(uploadModel({ parts: [{ id: "ball", label: "الكرة" }, { id: "wheel", label: "عجلة" }] })))).toHaveLength(1);
    expect(await store.examMeshAssetAvailabilityIssues(createMemoryContainer().container, load())).toEqual([]);
  });
  it("corrupted bytes at rest (same name, other content) block publication", async () => {
    const mem = createMemoryContainer();
    await persist(mem.container);
    const blob = mem.container.getBlockBlobClient(store.BLOBS_PREFIX + sha + ".glb");
    const tampered = Buffer.from(glb); tampered[tampered.length - 1] ^= 0xff;
    await blob.upload(tampered, tampered.length);
    expect((await store.examMeshAssetAvailabilityIssues(mem.container, uploadExam())).map(i => i.code)).toEqual(["MESH_ASSET_UNAVAILABLE"]);
  });
  it("platform: submit-review is refused (422 MESH_ASSET_UNAVAILABLE) while the upload is missing; once stored, the exam publishes, delivers and grades", async () => {
    const missing = createPlatform({ students: { "up-s": "طالب" } });
    const saved = await missing.teacher.saveExam(uploadExam());
    expect(saved.status).toBe(200);
    const pub = await missing.teacher.publish((await missing.teacher.loadExam(saved.jsonBody.blobName)).jsonBody.exam);
    expect(pub.ok).toBe(false);
    const refusal = pub.steps.at(-1);
    expect([refusal.status, refusal.jsonBody.code]).toEqual([422, "MESH_ASSET_UNAVAILABLE"]);

    const ready = createPlatform({ students: { "up-s": "طالب" } });
    await persist(ready.mem.container);
    const { aid } = await publishAndAssign(ready, uploadExam());
    const run = await takeExam(ready, aid, "up-s", { u1: sel("assembly", "ball") });
    expect(configsOf(run.delivery.jsonBody.assignment.exam).u1.model.asset).toEqual({ source: "upload", sha256: sha, byteLength: glb.length });
    expect([run.attempt.score, run.attempt.totalMarks, run.attempt.finalized]).toEqual([3, 3, true]);
  }, 60000);
});
