// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.meshModelPlainText = exports.meshModelMissingParts = exports.isSha256Hex = exports.isMeshModelId = exports.DEFAULT_MESH_CAMERA = exports.MESH_MODEL_LIMITS = exports.MESH_MODEL_VERSION = void 0;
exports.meshAssetUrl = meshAssetUrl;
exports.validateMeshModelSpec = validateMeshModelSpec;
const proseGuard_1 = require("../richContent/proseGuard");
const glbAsset_1 = require("./glbAsset");
const meshAssetCatalog_1 = require("./meshAssetCatalog");
exports.MESH_MODEL_VERSION = 1;
exports.MESH_MODEL_LIMITS = Object.freeze({
    titleChars: 160, descriptionChars: 600, labelChars: 60, partDescriptionChars: 300, partsMin: 1, partsMax: glbAsset_1.MESH_ASSET_LIMITS.maxParts,
    azimuthAbs: Math.PI, pitchAbs: 1.45, zoomMin: 0.6, zoomMax: 3
});
exports.DEFAULT_MESH_CAMERA = Object.freeze({ azimuth: 0, elevation: 0.2, zoom: 1 });
const ID = /^[A-Za-z][A-Za-z0-9_-]{0,47}$/;
const HEX64 = /^[0-9a-f]{64}$/;
const RESERVED = ["__proto__", "constructor", "prototype"];
const isPlain = (v) => {
    if (!v || typeof v !== "object" || Array.isArray(v))
        return false;
    const p = Object.getPrototypeOf(v);
    return p === Object.prototype || p === null;
};
const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
const isMeshModelId = (v) => typeof v === "string" && ID.test(v) && !RESERVED.includes(v);
exports.isMeshModelId = isMeshModelId;
const isSha256Hex = (v) => typeof v === "string" && HEX64.test(v);
exports.isSha256Hex = isSha256Hex;
function meshAssetUrl(ref) {
    if (!(0, exports.isSha256Hex)(ref.sha256))
        return null;
    return ref.source === "library" ? "/mesh-assets/" + ref.sha256 + ".glb" : "/api/mesh-assets/runtime/" + ref.sha256;
}
function validate(raw, library) {
    const issues = [];
    const fail = (code, path, message) => { if (issues.length < 20)
        issues.push({ code, path, message }); };
    const object = (o, path, keys, optional = []) => {
        if (!isPlain(o)) {
            fail("MESH_MODEL_OBJECT_INVALID", path, "مطلوب كائن بيانات عادي.");
            return null;
        }
        for (const k of Object.keys(o))
            if (!keys.includes(k))
                fail("MESH_MODEL_UNKNOWN_KEY", path + "." + k, "حقل غير مسموح في النموذج ثلاثي الأبعاد: " + k.slice(0, 32));
        for (const k of keys)
            if (!optional.includes(k) && !own(o, k))
                fail("MESH_MODEL_MISSING_KEY", path + "." + k, "حقل مطلوب مفقود: " + k);
        return o;
    };
    const text = (v, path, max) => {
        if (typeof v !== "string" || !v.trim() || v.length > max || proseGuard_1.CONTROL.test(v) || proseGuard_1.RAW_HTML.test(v) || proseGuard_1.UNSAFE_BIDI.test(v) || proseGuard_1.UNSAFE_INVISIBLE.test(v)) {
            fail("MESH_MODEL_TEXT_INVALID", path, "النص فارغ أو أطول من " + max + " محرفًا أو يتضمن علامات غير مسموحة.");
            return null;
        }
        return v;
    };
    const bool = (v, path) => (typeof v === "boolean" ? v : (fail("MESH_MODEL_FLAG_INVALID", path, "القيمة يجب أن تكون صحيحًا أو خطأً."), null));
    const number = (v, path, lo, hi) => {
        if (typeof v !== "number" || !Number.isFinite(v) || v < lo || v > hi) {
            fail("MESH_MODEL_NUMBER_INVALID", path, "قيمة عددية خارج الحدود المسموحة (" + lo.toFixed(2) + " … " + hi.toFixed(2) + ").");
            return null;
        }
        return v === 0 ? 0 : v;
    };
    const top = object(raw, "model", ["version", "id", "title", "description", "asset", "parts", "controls", "camera"], ["camera"]);
    if (!top)
        return { ok: false, issues };
    if (top.version !== exports.MESH_MODEL_VERSION)
        fail("MESH_MODEL_VERSION_INVALID", "model.version", "إصدار نموذج ثلاثي الأبعاد غير مدعوم.");
    const id = (0, exports.isMeshModelId)(top.id) ? top.id : (fail("MESH_MODEL_ID_INVALID", "model.id", "معرّف النموذج غير صالح (حرف لاتيني أولًا، حتى 48 محرفًا)."), null);
    const title = text(top.title, "model.title", exports.MESH_MODEL_LIMITS.titleChars);
    const description = text(top.description, "model.description", exports.MESH_MODEL_LIMITS.descriptionChars);
    let asset = null, entry = null;
    if (isPlain(top.asset) && top.asset.source === "library") {
        const a = object(top.asset, "model.asset", ["source", "id", "version", "sha256"]);
        if (a) {
            const aid = (0, exports.isMeshModelId)(a.id) ? a.id : (fail("MESH_MODEL_ASSET_INVALID", "model.asset.id", "معرّف أصل المكتبة غير صالح."), null);
            const ver = typeof a.version === "number" && Number.isInteger(a.version) && a.version >= 1 && a.version <= 1000 ? a.version : (fail("MESH_MODEL_ASSET_INVALID", "model.asset.version", "إصدار أصل المكتبة غير صالح."), null);
            const sha = (0, exports.isSha256Hex)(a.sha256) ? a.sha256 : (fail("MESH_MODEL_ASSET_INVALID", "model.asset.sha256", "بصمة SHA-256 غير صالحة (64 محرفًا ست عشريًا صغيرًا)."), null);
            if (aid && ver && sha) {
                const found = (0, meshAssetCatalog_1.meshLibraryAsset)(library, aid, ver);
                if (!found)
                    fail("MESH_MODEL_ASSET_UNKNOWN", "model.asset", "النموذج غير موجود في مكتبة النماذج المعتمدة: " + aid + " v" + ver);
                else if (found.sha256 !== sha)
                    fail("MESH_MODEL_ASSET_HASH_MISMATCH", "model.asset.sha256", "بصمة الملف لا تطابق النسخة المعتمدة من المكتبة.");
                else {
                    entry = found;
                    asset = { source: "library", id: aid, version: ver, sha256: sha };
                }
            }
        }
    }
    else if (isPlain(top.asset) && top.asset.source === "upload") {
        const a = object(top.asset, "model.asset", ["source", "sha256", "byteLength"]);
        if (a) {
            const sha = (0, exports.isSha256Hex)(a.sha256) ? a.sha256 : (fail("MESH_MODEL_ASSET_INVALID", "model.asset.sha256", "بصمة SHA-256 غير صالحة (64 محرفًا ست عشريًا صغيرًا)."), null);
            const len = typeof a.byteLength === "number" && Number.isInteger(a.byteLength) && a.byteLength >= 20 && a.byteLength <= glbAsset_1.MESH_ASSET_LIMITS.maxBytes ? a.byteLength : (fail("MESH_MODEL_ASSET_INVALID", "model.asset.byteLength", "حجم ملف النموذج غير صالح."), null);
            if (sha && len)
                asset = { source: "upload", sha256: sha, byteLength: len };
        }
    }
    else
        fail("MESH_MODEL_ASSET_INVALID", "model.asset", "مصدر النموذج يجب أن يكون مكتبة النماذج المعتمدة أو ملفًا رفعه المعلم وتحقق منه الخادم.");
    const parts = [];
    if (!Array.isArray(top.parts) || top.parts.length < exports.MESH_MODEL_LIMITS.partsMin || top.parts.length > exports.MESH_MODEL_LIMITS.partsMax) {
        fail("MESH_MODEL_PARTS_COUNT", "model.parts", "يضم النموذج من " + exports.MESH_MODEL_LIMITS.partsMin + " إلى " + exports.MESH_MODEL_LIMITS.partsMax + " جزءًا مسمّى.");
    }
    else {
        const seen = new Set();
        top.parts.forEach((p, i) => {
            const at = "model.parts[" + i + "]", o = object(p, at, ["id", "label", "description"], ["description"]);
            if (!o)
                return;
            const pid = (0, glbAsset_1.isMeshPartId)(o.id) ? o.id : (fail("MESH_MODEL_PART_ID_INVALID", at + ".id", "معرّف الجزء غير صالح."), null);
            if (pid && seen.has(pid))
                fail("MESH_MODEL_PART_DUPLICATE", at + ".id", "جزء مكرر: " + pid);
            if (pid)
                seen.add(pid);
            if (pid && entry && !entry.parts.some(x => x.id === pid))
                fail("MESH_MODEL_PART_UNKNOWN", at + ".id", "الجزء «" + pid + "» غير موجود في ملف النموذج.");
            const label = text(o.label, at + ".label", exports.MESH_MODEL_LIMITS.labelChars);
            const desc = own(o, "description") ? text(o.description, at + ".description", exports.MESH_MODEL_LIMITS.partDescriptionChars) : undefined;
            if (pid && label && desc !== null)
                parts.push({ id: pid, label, ...(desc ? { description: desc } : {}) });
        });
    }
    const cr = object(top.controls, "model.controls", ["rotate", "zoom", "hideParts"]);
    let controls = null;
    if (cr) {
        const rotate = bool(cr.rotate, "model.controls.rotate"), zoom = bool(cr.zoom, "model.controls.zoom"), hideParts = bool(cr.hideParts, "model.controls.hideParts");
        if (rotate !== null && zoom !== null && hideParts !== null)
            controls = { rotate, zoom, hideParts };
    }
    let camera;
    if (own(top, "camera")) {
        const c = object(top.camera, "model.camera", ["azimuth", "elevation", "zoom"]);
        if (c) {
            const azimuth = number(c.azimuth, "model.camera.azimuth", -exports.MESH_MODEL_LIMITS.azimuthAbs, exports.MESH_MODEL_LIMITS.azimuthAbs);
            const elevation = number(c.elevation, "model.camera.elevation", -exports.MESH_MODEL_LIMITS.pitchAbs, exports.MESH_MODEL_LIMITS.pitchAbs);
            const zoom = number(c.zoom, "model.camera.zoom", exports.MESH_MODEL_LIMITS.zoomMin, exports.MESH_MODEL_LIMITS.zoomMax);
            if (azimuth !== null && elevation !== null && zoom !== null)
                camera = { azimuth, elevation, zoom };
        }
    }
    if (issues.length || !id || !title || !description || !asset || !controls || !parts.length)
        return { ok: false, issues: issues.length ? issues : [{ code: "MESH_MODEL_INVALID", path: "model", message: "النموذج ثلاثي الأبعاد غير صالح." }] };
    return { ok: true, value: { version: exports.MESH_MODEL_VERSION, id, title, description, asset, parts, controls, ...(camera ? { camera } : {}) }, library: entry, issues: [] };
}
function validateMeshModelSpec(raw, options = {}) {
    try {
        return validate(raw, options.library ?? meshAssetCatalog_1.MESH_LIBRARY);
    }
    catch {
        return { ok: false, issues: [{ code: "MESH_MODEL_INVALID", path: "model", message: "تعذر التحقق من النموذج ثلاثي الأبعاد." }] };
    }
}
const meshModelMissingParts = (spec, assetPartIds) => spec.parts.map(p => p.id).filter(id => !assetPartIds.includes(id));
exports.meshModelMissingParts = meshModelMissingParts;
const meshModelPlainText = (s) => [s.title, s.description, ...s.parts.map(p => p.label + (p.description ? ": " + p.description : ""))].join("\n");
exports.meshModelPlainText = meshModelPlainText;
