// GENERATED by scripts/build-shared-finalization.mjs from src/*.ts — DO NOT EDIT (drift-guarded by api/tests/shared-finalization-drift-14a.test.js).
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MATH_FEATURES = void 0;
exports.MATH_FEATURES = Object.freeze([
    { id: "fractions", group: "basic", example: "\\frac{a}{b}" },
    { id: "roots", group: "basic", example: "\\sqrt[3]{x}" },
    { id: "scripts", group: "basic", example: "x_{1}^{2}" },
    { id: "greek", group: "basic", example: "\\alpha + \\beta = \\gamma" },
    { id: "relations", group: "basic", example: "a \\le b \\ne c" },
    { id: "text", group: "basic", example: "\\text{السرعة} = \\frac{d}{t}" },
    { id: "fences", group: "basic", example: "\\left( a + b \\right)^{2}" },
    { id: "derivatives", group: "calculus", example: "\\frac{dy}{dx}" },
    { id: "secondDerivatives", group: "calculus", example: "\\frac{d^{2}y}{dx^{2}}" },
    { id: "partialDerivatives", group: "calculus", example: "\\frac{\\partial f}{\\partial x}" },
    { id: "integrals", group: "calculus", example: "\\int_{0}^{1} x^{2} \\, dx" },
    { id: "multipleIntegrals", group: "calculus", example: "\\iint_{D} f(x,y) \\, dA" },
    { id: "largeOperators", group: "calculus", example: "\\sum_{i=1}^{n} i^{2}" },
    { id: "limits", group: "calculus", example: "\\lim_{x \\to 0} \\frac{\\sin x}{x}" },
    { id: "matrices", group: "linearAlgebra", example: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}" },
    { id: "determinants", group: "linearAlgebra", example: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc" },
    { id: "cases", group: "linearAlgebra", example: "f(x) = \\begin{cases} x^{2} & x \\ge 0 \\\\ -x & x < 0 \\end{cases}" },
    { id: "aligned", group: "linearAlgebra", example: "\\begin{aligned} V &= IR \\\\ P &= VI \\end{aligned}" },
    { id: "complex", group: "complex", example: "z = a + bi, \\quad \\overline{z} = a - bi" },
    { id: "complexParts", group: "complex", example: "\\Re(z) = a, \\quad \\Im(z) = b, \\quad \\arg(z) = \\theta" },
    { id: "numberSets", group: "complex", example: "x \\in \\mathbb{R}, \\quad z \\in \\mathbb{C}" },
    { id: "scientificNotation", group: "science", example: "6.02 \\times 10^{23}" },
    { id: "units", group: "science", example: "9.8 \\, \\mathrm{m}\\,\\mathrm{s}^{-2}" },
    { id: "chemistry", group: "science", example: "\\mathrm{SO}_4^{2-}" },
    { id: "chemicalEquations", group: "science", example: "2\\mathrm{H}_2 + \\mathrm{O}_2 \\rightarrow 2\\mathrm{H}_2\\mathrm{O}" },
    { id: "equilibrium", group: "science", example: "\\mathrm{N}_2 + 3\\mathrm{H}_2 \\rightleftharpoons 2\\mathrm{NH}_3" },
    { id: "ohmsLaw", group: "science", example: "V = IR, \\quad R = \\frac{V}{I}" },
    { id: "electricity", group: "science", example: "X_C = \\frac{1}{2\\pi f C}" },
    { id: "vectors", group: "geometry", example: "\\vec{F} = m\\vec{a}" },
    { id: "geometry", group: "geometry", example: "\\angle ABC = 90^{\\circ}, \\quad AB \\perp CD" }
].map(f => Object.freeze(f)));
