
import {useEffect,useMemo,useState} from "react";
import {IconClose,IconCheck} from "./icons";
type A={attemptNumber:number;submittedAt:string;score:number;totalMarks:number;percentage:number;manualReviewMarks:number;finalized:boolean};
type Q={questionId:string;questionNumber:number;text:string;marks:number;studentAnswer:any;expectedAnswer:any;autoGrade:{score?:number;manualReview?:boolean}|null;manualScore:number|null;teacherComment:string};
type Data={assignment:{assignmentId:string;title:string;totalMarks:number};student:{studentId:string;studentName:string;studentCode:string};attempt:A&{teacherFeedback:string};attempts:A[];questions:Q[]};
type Props={token:string;assignmentId:string;studentId:string;initialAttempt:number;onClose:()=>void;onSaved:()=>void};
function pretty(v:any):string{if(v===null||v===undefined)return "—";if(typeof v==="string")return v||"—";if(typeof v==="boolean")return v?"✓":"✗";if(Array.isArray(v))return v.map(pretty).join(" | ");if(typeof v==="object"){if(v.kind==="choice")return "الخيار رقم "+(Number(v.index)+1);if(v.kind==="text")return String(v.value||"—");if(Array.isArray(v.values))return v.values.map(pretty).join(" | ");const p=[v.correctText,v.correctAnswer,v.correctOptionValue,v.correctOptionLabel,v.text,v.values].filter(x=>x!==undefined);return p.length?p.map(pretty).join(" | "):JSON.stringify(v)}return String(v)}
const fmt=(v:string)=>v?new Date(v).toLocaleString("ar"):"—";
export default function AssignmentReview({token,assignmentId,studentId,initialAttempt,onClose,onSaved}:Props){
 const [attemptNumber,setAttemptNumber]=useState(initialAttempt),[data,setData]=useState<Data|null>(null),[scores,setScores]=useState<Record<string,string>>({}),[comments,setComments]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function api<T>(url:string,options:RequestInit={}):Promise<T>{const h=new Headers(options.headers||{});h.set("Content-Type","application/json");h.set("x-builder-token",token);h.set("Authorization","Bearer "+token);const r=await fetch(url,{...options,headers:h}),j=await r.json() as T&{error?:string};if(!r.ok)throw new Error(j.error||"حدث خطأ.");return j}
 async function load(n=attemptNumber){setLoading(true);setError("");try{const r=await api<Data&{ok:true}>("/api/assignment-review?assignmentId="+encodeURIComponent(assignmentId)+"&studentId="+encodeURIComponent(studentId)+"&attemptNumber="+n);setData(r);const s:Record<string,string>={},c:Record<string,string>={};for(const q of r.questions){s[q.questionId]=q.manualScore===null||q.manualScore===undefined?"":String(q.manualScore);c[q.questionId]=q.teacherComment||""}setScores(s);setComments(c);setFeedback(r.attempt.teacherFeedback||"");setAttemptNumber(n)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التصحيح.")}finally{setLoading(false)}}
 useEffect(()=>{void load(initialAttempt)},[assignmentId,studentId,initialAttempt]);
 const provisional=useMemo(()=>{if(!data)return null;let total=0;for(const q of data.questions){const v=scores[q.questionId];total+=v!==""?Math.min(q.marks,Math.max(0,Number(v)||0)):Number(q.autoGrade?.score||0)}return Number(total.toFixed(2))},[data,scores]);
 async function save(){if(!data)return;setSaving(true);setError("");try{const overrides:Record<string,{score:number;comment:string}>={};for(const q of data.questions){const raw=scores[q.questionId];if(raw!=="")overrides[q.questionId]={score:Math.min(q.marks,Math.max(0,Number(raw)||0)),comment:comments[q.questionId]||""}}const r=await api<{result:{score:number;totalMarks:number;percentage:number;manualReviewMarks:number;finalized:boolean}}>("/api/assignment-review",{method:"POST",body:JSON.stringify({action:"saveReview",assignmentId,studentId,attemptNumber,overrides,teacherFeedback:feedback})});setNotice(r.result.finalized?"✓ تم اعتماد العلامة النهائية: "+r.result.score+"/"+r.result.totalMarks+" ("+r.result.percentage+"%)":"✓ تم الحفظ، وما زالت "+r.result.manualReviewMarks+" علامة بحاجة للمراجعة.");await load(attemptNumber);onSaved()}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ التصحيح.")}finally{setSaving(false)}}
 if(loading)return <div className="review-overlay" dir="rtl"><div className="review-modal"><div className="platform-loading">⏳ جارٍ تحميل ورقة الطالب...</div></div></div>;
 return <div className="review-overlay" dir="rtl"><div className="review-modal"><div className="review-top"><div><span className="platform-eyebrow">Manual Review · Phase 2.0D</span><h2>{data?.assignment.title}</h2><p>{data?.student.studentName} · {data?.student.studentCode}</p></div><button onClick={onClose}><IconClose size={14}/>إغلاق</button></div>{error&&<div className="platform-error">{error}</div>}{notice&&<div className="platform-notice">{notice}</div>}{data&&<><div className="review-summary"><div><span>المحاولة</span><strong>{attemptNumber}</strong></div><div><span>التسليم</span><strong>{fmt(data.attempt.submittedAt)}</strong></div><div><span>العلامة الحالية</span><strong>{data.attempt.score}/{data.attempt.totalMarks}</strong></div><div><span>بعد التعديل</span><strong>{provisional}/{data.attempt.totalMarks}</strong></div><div><span>الحالة</span><strong>{data.attempt.finalized?"نهائي":"يحتاج مراجعة"}</strong></div></div><div className="review-attempt-tabs">{data.attempts.map(a=><button className={a.attemptNumber===attemptNumber?"active":""} key={a.attemptNumber} onClick={()=>void load(a.attemptNumber)}>محاولة {a.attemptNumber} · {a.score}/{a.totalMarks}</button>)}</div><div className="review-question-list">{data.questions.map(q=><article className={"review-question "+(q.autoGrade?.manualReview?"needs-review":"")} key={q.questionId}><div className="review-qhead"><div><span>السؤال {q.questionNumber}</span><strong>{q.marks} علامة</strong>{q.autoGrade?.manualReview&&<em>يحتاج تصحيحًا يدويًا</em>}</div><div className="review-auto">آلي: {Number(q.autoGrade?.score||0)}/{q.marks}</div></div><p className="review-qtext">{q.text}</p><div className="review-answer-grid"><div><span>إجابة الطالب</span><pre>{pretty(q.studentAnswer)}</pre></div><div><span>الإجابة المعتمدة</span><pre>{pretty(q.expectedAnswer)}</pre></div></div><div className="review-grade-row"><label>علامة المعلم<input type="number" min="0" max={q.marks} step="0.5" value={scores[q.questionId]??""} placeholder={String(q.autoGrade?.score??0)} onChange={e=>setScores(x=>({...x,[q.questionId]:e.target.value}))}/><small>من {q.marks}</small></label><label className="review-comment">ملاحظة للطالب<input value={comments[q.questionId]??""} onChange={e=>setComments(x=>({...x,[q.questionId]:e.target.value}))} placeholder="اختياري"/></label><button onClick={()=>setScores(x=>({...x,[q.questionId]:String(q.autoGrade?.score??0)}))}>استخدم العلامة الآلية</button></div></article>)}</div><label className="review-general-feedback"><span>ملاحظة عامة للطالب</span><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="مثال: أداء جيد، راجع موضوع Subnet Mask..."/></label><div className="review-footer"><button onClick={onClose}><IconClose size={14}/>إلغاء</button><button className="platform-primary" onClick={save} disabled={saving}>{saving?"⏳ جارٍ الحفظ...":<><IconCheck size={14}/>حفظ واعتماد التصحيح</>}</button></div></>}</div></div>
}
