
import {useEffect,useMemo,useState} from "react";
type Classroom={classId:string;name:string;grade:string;active:boolean};
type Item={assignmentId:string;classId:string;className:string;title:string;instructions:string;status:"draft"|"published"|"archived";openAt:string;dueAt:string;sourceExamId:string;sourceExamTitle:string;questionCount:number;totalMarks:number;maxAttempts:number;createdAt:string;updatedAt:string};
type Exam={examId?:string;title?:string;totalMarks?:number;questions?:unknown[]};
type StudentResult={studentId:string;studentName:string;studentCode:string;attemptsUsed:number;allowedAttempts:number;latestResult:{score:number;totalMarks:number;percentage:number;submittedAt:string;finalized:boolean;manualReviewMarks:number}|null};
type Props={token:string;classes:Classroom[];currentExam:unknown|null};
const localDate=(hours:number)=>{const d=new Date(Date.now()+hours*3600000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)},fmt=(v:string)=>v?new Date(v).toLocaleString("ar"):"بدون موعد";
export default function AssignmentsPanel({token,classes,currentExam}:Props){
 const exam=currentExam&&typeof currentExam==="object"?currentExam as Exam:null;
 const [items,setItems]=useState<Item[]>([]),[classId,setClassId]=useState(""),[title,setTitle]=useState(""),[instructions,setInstructions]=useState("أجب عن جميع الأسئلة واقرأ التعليمات جيدًا قبل البدء."),[openAt,setOpenAt]=useState(localDate(0)),[dueAt,setDueAt]=useState(localDate(72)),[maxAttempts,setMaxAttempts]=useState(1),[publish,setPublish]=useState(true),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[resultsFor,setResultsFor]=useState<Item|null>(null),[results,setResults]=useState<StudentResult[]>([]);
 const active=useMemo(()=>classes.filter(x=>x.active),[classes]);useEffect(()=>{if(!classId&&active[0])setClassId(active[0].classId)},[active,classId]);useEffect(()=>{if(exam?.title&&!title.trim())setTitle(exam.title)},[exam?.title]);
 async function api<T>(url:string,options:RequestInit={}):Promise<T>{const h=new Headers(options.headers||{});h.set("Content-Type","application/json");h.set("x-builder-token",token);h.set("Authorization","Bearer "+token);const r=await fetch(url,{...options,headers:h}),j=await r.json() as T&{error?:string};if(!r.ok)throw new Error(j.error||"حدث خطأ.");return j}
 async function load(){setLoading(true);try{const r=await api<{assignments:Item[]}>("/api/assignments");setItems(r.assignments||[])}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الواجبات.")}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function create(){if(busy||!classId||!title.trim()||!exam||!Array.isArray(exam.questions)||!exam.questions.length)return;setBusy(true);setError("");try{const r=await api<{assignment:Item}>("/api/assignments",{method:"POST",body:JSON.stringify({action:"create",classId,title:title.trim(),instructions:instructions.trim(),openAt:openAt?new Date(openAt).toISOString():"",dueAt:dueAt?new Date(dueAt).toISOString():"",maxAttempts,publish,examSnapshot:currentExam})});setItems(x=>[r.assignment,...x]);setNotice(publish?"✓ تم إنشاء الواجب ونشره.":"✓ تم حفظ الواجب كمسودة.")}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الواجب.")}finally{setBusy(false)}}
 async function action(item:Item,body:any){setBusy(true);try{const r=await api<{assignment:Item}>("/api/assignments",{method:"POST",body:JSON.stringify({assignmentId:item.assignmentId,...body})});setItems(x=>x.map(y=>y.assignmentId===item.assignmentId?r.assignment:y));if(resultsFor?.assignmentId===item.assignmentId)setResultsFor(r.assignment)}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية.")}finally{setBusy(false)}}
 async function remove(item:Item){if(!window.confirm("حذف الواجب «"+item.title+"»؟"))return;setBusy(true);try{await api("/api/assignments",{method:"POST",body:JSON.stringify({action:"delete",assignmentId:item.assignmentId})});setItems(x=>x.filter(y=>y.assignmentId!==item.assignmentId));if(resultsFor?.assignmentId===item.assignmentId){setResultsFor(null);setResults([])}}catch(e){setError(e instanceof Error?e.message:"تعذر حذف الواجب.")}finally{setBusy(false)}}
 async function loadResults(item:Item){setBusy(true);setError("");try{const r=await api<{students:StudentResult[]}>("/api/assignment-results?assignmentId="+encodeURIComponent(item.assignmentId));setResultsFor(item);setResults(r.students||[])}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل النتائج.")}finally{setBusy(false)}}
 async function retry(student:StudentResult){if(!resultsFor)return;setBusy(true);try{const r=await api<{allowedAttempts:number}>("/api/assignment-results",{method:"POST",body:JSON.stringify({action:"allowRetry",assignmentId:resultsFor.assignmentId,studentId:student.studentId})});setResults(x=>x.map(s=>s.studentId===student.studentId?{...s,allowedAttempts:r.allowedAttempts}:s));setNotice("✓ تم السماح بمحاولة إضافية للطالب "+student.studentName)}catch(e){setError(e instanceof Error?e.message:"تعذر السماح بالمحاولة.")}finally{setBusy(false)}}
 const visible=classId?items.filter(x=>x.classId===classId):items;
 return <section className="assignments-panel platform-card"><div className="assignments-heading"><div><span className="platform-eyebrow">Assignments · Phase 2.0C</span><h3>الواجبات والنتائج</h3><p>الطالب يحل داخل الموقع، والنظام يصحح ويسجل العلامة والمحاولات.</p></div><button onClick={load} disabled={loading}>↻ تحديث</button></div>{error&&<div className="platform-error assignment-inline-message">{error}</div>}{notice&&<div className="platform-notice assignment-inline-message">{notice}</div>}
  <div className="assignment-source-card"><div><span>الامتحان الحالي</span><strong>{exam?.title||"لا يوجد امتحان مفتوح"}</strong><small>{Array.isArray(exam?.questions)?exam?.questions?.length+" سؤال":"افتح امتحانًا من باني الامتحان أولًا"}</small></div><div className="assignment-source-marks">{exam?.totalMarks?exam.totalMarks+" علامة":"—"}</div></div>
  <div className="assignment-create-grid"><label>الصف<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">اختر الصف</option>{active.map(c=><option key={c.classId} value={c.classId}>{c.name}{c.grade?" · "+c.grade:""}</option>)}</select></label><label>عنوان الواجب<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="assignment-wide-field">تعليمات<textarea value={instructions} onChange={e=>setInstructions(e.target.value)}/></label><label>يفتح في<input type="datetime-local" value={openAt} onChange={e=>setOpenAt(e.target.value)}/></label><label>آخر موعد<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>عدد المحاولات<select value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}</option>)}</select></label><label className="assignment-publish-toggle"><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/><span>نشر مباشرة</span></label><button className="platform-primary assignment-create-button" onClick={create} disabled={busy||!classId||!title.trim()||!exam||!Array.isArray(exam.questions)||!exam.questions.length}>{busy?"⏳ جارٍ الحفظ...":"📤 إنشاء الواجب"}</button></div>
  <div className="assignment-list">{visible.map(item=><article className="assignment-row" key={item.assignmentId}><div className="assignment-row-main"><div className="assignment-title-line"><strong>{item.title}</strong><span className={"assignment-status "+item.status}>{item.status==="published"?"منشور":item.status==="archived"?"مؤرشف":"مسودة"}</span></div><span>{item.questionCount} سؤال · {item.totalMarks} علامة · {item.maxAttempts||1} محاولة</span><small>التسليم: {fmt(item.dueAt)}</small></div><div className="assignment-row-actions"><button onClick={()=>loadResults(item)} disabled={busy}>📊 النتائج</button>{item.status!=="published"&&<button onClick={()=>action(item,{action:"setStatus",status:"published"})} disabled={busy}>نشر</button>}{item.status==="published"&&<button onClick={()=>action(item,{action:"setStatus",status:"draft"})} disabled={busy}>إيقاف النشر</button>}<select className="assignment-attempt-select" value={item.maxAttempts||1} onChange={e=>action(item,{action:"setMaxAttempts",maxAttempts:Number(e.target.value)})} disabled={busy}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} محاولات</option>)}</select><button className="assignment-delete-button" onClick={()=>remove(item)} disabled={busy}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className="platform-empty">لا توجد واجبات لهذا الصف بعد.</div>}</div>
  {resultsFor&&<section className="assignment-results-panel"><div className="assignments-heading"><div><span className="platform-eyebrow">Results</span><h3>نتائج: {resultsFor.title}</h3></div><button onClick={()=>{setResultsFor(null);setResults([])}}>إغلاق</button></div><div className="students-table-wrap"><table className="students-table"><thead><tr><th>الطالب</th><th>المحاولات</th><th>آخر علامة</th><th>التاريخ</th><th>إجراء</th></tr></thead><tbody>{results.map(s=><tr key={s.studentId}><td><strong>{s.studentName}</strong><small className="result-code">{s.studentCode}</small></td><td>{s.attemptsUsed} / {s.allowedAttempts}</td><td>{s.latestResult?<strong>{s.latestResult.score}/{s.latestResult.totalMarks} ({s.latestResult.percentage}%)</strong>:"لم يسلّم"}</td><td>{s.latestResult?fmt(s.latestResult.submittedAt):"—"}</td><td><button onClick={()=>retry(s)} disabled={busy||s.attemptsUsed===0}>+ محاولة إضافية</button></td></tr>)}</tbody></table></div></section>}
 </section>
}
