
import {lazy,Suspense,useCallback,useEffect,useId,useMemo,useRef,useState} from "react";
import {lazyWithRetry} from "./lazyWithRetry";
import {endReasonLabel as sharedEndReasonLabel} from "./assignments/attemptPolicy";
import useFocusTrap from "./ui/useFocusTrap";
import useBodyScrollLock from "./ui/useBodyScrollLock";
import {useConfirm} from "./ui/useConfirm";
import {IconClose,IconCheck} from "./icons";
import {QuestionTextBlock} from "./questionContent";
import {gradingClass,resolveGradingStatus,type GradingStatus} from "./gradingStatus";
import {extractRequestId} from "./lib/requestTrace";
// Phase 17A — a code answer is shown as TEXT through the shared read-only viewer (language badge, line numbers, bounded scroll,
// copy); the teacher-side key is summarised factually. Manual marks below stay the official grading authority.
import {CodeSourceView,CodeKeySummary} from "./coding/CodeSourceView";
import CodeStimulusView from "./questionTypes/CodeStimulusView";   // 19F: the question's read-only code stimulus, as the student saw it
// Phase 18C — a network CLI answer is shown as its canonical device state + the per-check comparison + the transcript as TEXT; the
// private target is summarised factually. Manual marks below stay the official grading authority.
import {NetworkCliAnswerView,NetworkCliKeySummary} from "./networkCli/NetworkCliReviewView";
// Phase 19A — an inline cloze answer is shown as the passage with each response inline + per-blank ✓ / ✗ against the private key
// (teacher only) + earned parts; an invalid published config / key is an explicit manual-review state. Manual marks stay the authority.
import {InlineClozeAnswerView,InlineClozeKeySummary} from "./inlineCloze/InlineClozeReviewView";
// Phase 19D — a visual answer is shown on the question image: hotspot = private targets (✓ matched / ✗ missed) + the student's points;
// labelDiagram = per zone the student's label vs the correct label. Teacher only; manual marks stay the official override.
import {HotspotAnswerView,HotspotKeySummary,LabelDiagramAnswerView,LabelDiagramKeySummary} from "./visual/VisualReviewView";
// Phase 19B — the EXACT official parametric instance of the attempt, regenerated by the server with the grading authority.
import {ParametricAnswerView} from "./parametric/ParametricReviewView";
// Phase 17E-D — the teacher coding EVIDENCE panel (server projection `codingEvidence`) with retry (same revision) / force regrade
// (new revision, confirmation first) — identifiers only; the manual teacher mark below remains the override that always wins.
import CodingAutoGradeBlock,{type EvidenceActionResult} from "./coding/CodingAutoGradeBlock";
import {actionErrorMessage,normalizeEvidence} from "./coding/codingTeacherEvidence";
// Phase 19E — an openResponse answer is graded with the published RUBRIC in a lazy panel (student text beside the criteria; one level —
// or allowed bounded custom points — per criterion). The save sends the rubric selections only; the SERVER computes the official score.
import type {RubricAwardsInput} from "./openResponse/RubricGradingPanel";
// The parent decides synchronously (same shared engine as the server): which stored selections still bind (stale ones are never
// hydrated), whether a selection is complete (save gate) and the provisional score — never through child effects.
import {openResponseReviewModel,scoreOpenResponseRubric} from "./openResponseQuestion";
const RubricGradingPanel=lazy(lazyWithRetry(()=>import("./openResponse/RubricGradingPanel"),"teacher-rubric-grading"));
// Phase 19G — the scenario CONTEXT (title, instructions, shared sources) a linked question was answered in: the server emits the same strict
// projection the student saw, once per scenario; shown above the response so the teacher grades in context. Lazy (own chunk).
const ScenarioContextView=lazy(lazyWithRetry(()=>import("./scenario/ScenarioView").then(m=>({default:m.ScenarioContextView})),"teacher-scenario-context"));
type ReviewScenario={id:string;sectionId:string;version:1;title?:string;instructions?:string;sources:never[];questionIds:string[]};
const isRubricQ=(q:{type?:string})=>q.type==="openResponse";
const rubricNode=(q:{marks:number;openResponse?:unknown;questionTypeVersion?:unknown;expectedAnswer:unknown})=>({presentationType:"openResponse",questionTypeVersion:q.questionTypeVersion??undefined,marks:q.marks,openResponse:q.openResponse,answer:q.expectedAnswer});
const rubricScoreOf=(q:{marks:number;openResponse?:unknown;questionTypeVersion?:unknown;expectedAnswer:unknown},aw:RubricAwardsInput|undefined)=>{const r=scoreOpenResponseRubric(rubricNode(q),aw||{});return r.ok?r.score:null};
function storedAwards(review:unknown):RubricAwardsInput{const out:RubricAwardsInput={};const a=review&&typeof review==="object"?(review as {awards?:unknown}).awards:null;if(a&&typeof a==="object")for(const [id,v] of Object.entries(a as Record<string,{levelId?:unknown;points?:unknown}>))if(v&&typeof v.levelId==="string")out[id]={levelId:v.levelId};else if(v&&typeof v.points==="number")out[id]={points:v.points};return out}
type A={attemptNumber:number;submittedAt:string;score:number;totalMarks:number;percentage:number;manualReviewMarks:number;finalized:boolean;gradingStatus?:GradingStatus;startedAt?:string;endedAt?:string;endReason?:string;timedOut?:boolean};
// Server-authoritative gradingStatus via the SHARED resolver (never from score/percentage). No local copy.
const gsOf=(a:{gradingStatus?:GradingStatus;manualReviewMarks:number;finalized:boolean}):GradingStatus=>resolveGradingStatus(a);
// Phase 7A: the shared Arabic end-reason labels (incl. «غادر صفحة الامتحان» for a strict integrity exit).
const endReasonLabel=sharedEndReasonLabel;
type Q={questionId:string;questionNumber:number;text:string;marks:number;type?:string;scenarioId?:string;networkCli?:unknown;inlineCloze?:unknown;hotspot?:unknown;labelDiagram?:unknown;openResponse?:unknown;questionTypeVersion?:unknown;rubricReview?:unknown;codeTemplateReview?:{ok:boolean;language?:string;source?:string;code?:string};codeStimulus?:unknown;image?:unknown;parametricInstance?:unknown;studentAnswer:any;expectedAnswer:any;autoGrade:{score?:number;manualReview?:boolean}|null;manualScore:number|null;teacherComment:string;codingEvidence?:unknown};
type Data={scenarios?:ReviewScenario[];assignment:{assignmentId:string;title:string;totalMarks:number};student:{studentId:string;studentName:string;studentCode:string};attempt:A&{teacherFeedback:string};attempts:A[];questions:Q[]};
type Props={token:string;assignmentId:string;studentId:string;initialAttempt:number;onClose:()=>void;onSaved:()=>void};
function pretty(v:any):string{if(v===null||v===undefined)return "—";if(typeof v==="string")return v||"—";if(typeof v==="boolean")return v?"✓":"✗";if(Array.isArray(v))return v.map(pretty).join(" | ");if(typeof v==="object"){if(v.kind==="choice")return "الخيار رقم "+(Number(v.index)+1);if(v.kind==="text")return String(v.value||"—");if(Array.isArray(v.values))return v.values.map(pretty).join(" | ");const p=[v.correctText,v.correctAnswer,v.correctOptionValue,v.correctOptionLabel,v.text,v.values].filter(x=>x!==undefined);return p.length?p.map(pretty).join(" | "):JSON.stringify(v)}return String(v)}
const fmt=(v:string)=>v?new Date(v).toLocaleString("ar"):"—";
// Phase 17E-D — the automatic score of a coding question as the EVIDENCE says (null while there is none: a technical failure or
// an open first grading is never offered as a "0" to copy into the teacher mark).
const codingAutomaticScore=(q:Q):number|null|undefined=>q.codingEvidence===undefined||q.codingEvidence===null?undefined:(normalizeEvidence(q.codingEvidence)?.automaticScore??null);
export default function AssignmentReview({token,assignmentId,studentId,initialAttempt,onClose,onSaved}:Props){
 const [attemptNumber,setAttemptNumber]=useState(initialAttempt),[data,setData]=useState<Data|null>(null),[scores,setScores]=useState<Record<string,string>>({}),[comments,setComments]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState(""),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[rubric,setRubric]=useState<Record<string,RubricAwardsInput>>({});
 // Phase 17E-D — read tickets + view context. Every review read takes a ticket; only the NEWEST read may be applied, so a slow
 // read of another attempt / student / an older revision can never overwrite what the teacher is looking at. The context key is
 // the (assignment, student, attempt) the teacher asked for LAST; an action response that arrives after it changed (or after the
 // review was closed) updates nothing and triggers no reload.
 const readSeq=useRef(0),mountedRef=useRef(true),contextRef=useRef(""),savingRef=useRef(false),actionRef=useRef(false),dataRef=useRef<Data|null>(null);
 useEffect(()=>{mountedRef.current=true;return ()=>{mountedRef.current=false}},[]);
 const headers=()=>{const h=new Headers();h.set("Content-Type","application/json");h.set("x-builder-token",token);h.set("Authorization","Bearer "+token);return h};
 async function api<T>(url:string,options:RequestInit={}):Promise<T>{const r=await fetch(url,{...options,headers:headers()}),j=await r.json() as T&{error?:string};if(!r.ok)throw new Error(j.error||"حدث خطأ.");return j}
 async function load(n=attemptNumber){
  const seq=++readSeq.current,ctx=assignmentId+"|"+studentId+"|"+n;contextRef.current=ctx;
  // A different student / assignment is a different review: its previous data is never shown while the new one loads.
  if(dataRef.current&&(dataRef.current.assignment.assignmentId!==assignmentId||dataRef.current.student.studentId!==studentId))dataRef.current=null;
  if(!dataRef.current)setLoading(true);else setRefreshing(true);
  setError("");
  try{
   const r=await api<Data&{ok:true}>("/api/assignment-review?assignmentId="+encodeURIComponent(assignmentId)+"&studentId="+encodeURIComponent(studentId)+"&attemptNumber="+n);
   if(!mountedRef.current||seq!==readSeq.current)return;                       // a newer read (or a close) superseded this one
   dataRef.current=r;setData(r);const s:Record<string,string>={},c:Record<string,string>={};for(const q of r.questions){s[q.questionId]=q.manualScore===null||q.manualScore===undefined?"":String(q.manualScore);c[q.questionId]=q.teacherComment||""}const rb:Record<string,RubricAwardsInput>={};for(const q of r.questions)if(isRubricQ(q)){const m=openResponseReviewModel(rubricNode(q),q.rubricReview);rb[q.questionId]=m.ok&&!m.stale?storedAwards(q.rubricReview):{}}setRubric(rb);setScores(s);setComments(c);setFeedback(r.attempt.teacherFeedback||"");setAttemptNumber(n)
  }catch(e){if(!mountedRef.current||seq!==readSeq.current)return;setError(e instanceof Error?e.message:"تعذر تحميل التصحيح.")}
  finally{if(mountedRef.current&&seq===readSeq.current){setLoading(false);setRefreshing(false)}}
 }
 useEffect(()=>{void load(initialAttempt)},[assignmentId,studentId,initialAttempt]);
 // Phase 17E-D — retry / force regrade: identifiers only, ONE in flight, followed by an authoritative reload of the SAME context.
 async function regrade(questionId:string,action:"retry"|"force",n:number):Promise<EvidenceActionResult>{
  if(actionRef.current)return {stale:true};
  actionRef.current=true;
  const ctx=contextRef.current;
  let res:Response|null=null,body:{code?:unknown}|null=null;
  try{res=await fetch("/api/coding/regrade",{method:"POST",headers:headers(),body:JSON.stringify({action,assignmentId,studentId,attemptNumber:n,questionId})});try{body=await res.json()}catch{body=null}}catch{res=null}
  finally{actionRef.current=false}
  if(!mountedRef.current||contextRef.current!==ctx)return {stale:true};
  if(!res)return {ok:false,message:actionErrorMessage(0,"")};
  if(res.ok){void load(n);return {ok:true}}
  if(res.status===404||res.status===409)void load(n);
  return {ok:false,message:actionErrorMessage(res.status,typeof body?.code==="string"?body.code:"",extractRequestId(res))};
 }
 const {confirm,confirmDialog,confirmPending}=useConfirm();
 // UX-8a — legacy overlay made a real modal in place (no Dialog migration): the shared useFocusTrap owns focus
 // containment, Escape and focus return to the opener; useBodyScrollLock owns the body scroll lock. The panel
 // element is the SAME node across the loading and loaded states so the trap never holds a detached root, and
 // onClose is read through a ref so a parent re-render never re-arms the trap (which would move focus).
 // Phase 17E-D — while the force-regrade confirmation (a stacked Dialog) is open, this trap is released: Escape / Tab belong to
 // the confirmation, and its own focus return lands back on the action inside this review.
 const panelRef=useRef<HTMLDivElement>(null),onCloseRef=useRef(onClose);
 useEffect(()=>{onCloseRef.current=onClose});
 const escape=useCallback(()=>onCloseRef.current(),[]);
 useFocusTrap(panelRef,!confirmPending,escape);
 useBodyScrollLock(true);
 const titleId="review-title-"+useId().replace(/[^a-zA-Z0-9_-]/g,"");
 const provisional=useMemo(()=>{if(!data)return null;let total=0;for(const q of data.questions){const v=scores[q.questionId];if(isRubricQ(q)){const sc=rubricScoreOf(q,rubric[q.questionId]);total+=sc!==null?sc:Number(q.manualScore??q.autoGrade?.score??0);continue}total+=v!==""?Math.min(q.marks,Math.max(0,Number(v)||0)):Number(q.autoGrade?.score||0)}return Number(total.toFixed(2))},[data,scores,rubric]);
 async function save(){
  if(!data||savingRef.current)return;                                          // synchronous guard: one save in flight
  savingRef.current=true;setSaving(true);setError("");
  const ctx=contextRef.current,n=attemptNumber;
  try{const overrides:Record<string,{score:number;comment:string}|{rubricAwards:RubricAwardsInput;comment:string}>={};for(const q of data.questions){if(isRubricQ(q)){const aw=rubric[q.questionId]||{},comment=comments[q.questionId]||"";if(Object.keys(aw).length){if(rubricScoreOf(q,aw)===null)throw new Error("أكمل اختيار مستوى صالح لكل معيار في السؤال "+q.questionNumber+" قبل الحفظ.");overrides[q.questionId]={rubricAwards:aw,comment}}else if(comment.trim()&&comment!==(q.teacherComment||""))throw new Error("اختر مستويات سلم التقييم للسؤال "+q.questionNumber+" قبل إضافة ملاحظة عليه.");continue}const raw=scores[q.questionId];if(raw!=="")overrides[q.questionId]={score:Math.min(q.marks,Math.max(0,Number(raw)||0)),comment:comments[q.questionId]||""}}const r=await api<{result:{score:number;totalMarks:number;percentage:number;manualReviewMarks:number;finalized:boolean}}>("/api/assignment-review",{method:"POST",body:JSON.stringify({action:"saveReview",assignmentId,studentId,attemptNumber:n,overrides,teacherFeedback:feedback})});
   if(!mountedRef.current)return;
   if(contextRef.current===ctx){setNotice(r.result.finalized?"✓ تم اعتماد العلامة النهائية: "+r.result.score+"/"+r.result.totalMarks+" ("+r.result.percentage+"%)":"✓ تم الحفظ، وما زالت "+r.result.manualReviewMarks+" علامة بحاجة للمراجعة.");await load(n)}
   onSaved()}
  catch(e){if(mountedRef.current&&contextRef.current===ctx)setError(e instanceof Error?e.message:"تعذر حفظ التصحيح.")}
  finally{savingRef.current=false;if(mountedRef.current)setSaving(false)}
 }
 return <div className="review-overlay" dir="rtl"><div ref={panelRef} className="review-modal" role="dialog" aria-modal="true" aria-labelledby={loading?undefined:titleId} aria-label={loading?"مراجعة ورقة الطالب":undefined}>{loading?<><div className="review-top"><div><span className="platform-eyebrow">Manual Review · Phase 2.0D</span><p role="status" className="platform-loading">جارٍ تحميل ورقة الطالب...</p></div><button type="button" onClick={onClose}><IconClose size={14}/>إغلاق</button></div></>:<><div className="review-top"><div><span className="platform-eyebrow">Manual Review · Phase 2.0D</span><h2 id={titleId}>{data?.assignment.title||"مراجعة ورقة الطالب"}</h2><p>{data?.student.studentName} · {data?.student.studentCode}</p></div><button type="button" onClick={onClose}><IconClose size={14}/>إغلاق</button></div>{error&&<div className="platform-error">{error}</div>}{notice&&<div className="platform-notice">{notice}</div>}{data&&<><div className="review-summary"><div><span>المحاولة</span><strong>{attemptNumber}</strong></div><div><span>بدأ</span><strong>{fmt(data.attempt.startedAt||"")}</strong></div><div><span>انتهى</span><strong>{fmt(data.attempt.endedAt||data.attempt.submittedAt)}</strong></div><div><span>سبب الانتهاء</span><strong>{endReasonLabel(data.attempt.endReason)}</strong></div><div><span>التسليم</span><strong>{fmt(data.attempt.submittedAt)}</strong></div><div><span>العلامة الحالية</span><strong>{data.attempt.score}/{data.attempt.totalMarks}</strong></div><div><span>بعد التعديل</span><strong>{provisional}/{data.attempt.totalMarks}</strong></div><div><span>الحالة</span><strong className={"review-grade-status iex-grade-"+gradingClass(gsOf(data.attempt))}>{gsOf(data.attempt)==="final"?"نهائي":"يحتاج مراجعة"}</strong></div>{gsOf(data.attempt)==="pendingReview"&&<div><span>متبقٍ للمراجعة</span><strong>{data.attempt.manualReviewMarks} علامة</strong></div>}</div><div className="review-attempt-tabs">{data.attempts.map(a=>{const gs=gsOf(a);return <button className={(a.attemptNumber===attemptNumber?"active":"")+" iex-grade-"+gradingClass(gs)} key={a.attemptNumber} onClick={()=>void load(a.attemptNumber)}>محاولة {a.attemptNumber} · {a.score}/{a.totalMarks} · {gs==="final"?"نهائي":"مراجعة"}</button>})}</div>{refreshing&&<p className="platform-loading review-refreshing">جارٍ تحديث البيانات...</p>}<div className="review-question-list">{data.questions.map(q=>{const auto=codingAutomaticScore(q);return <article className={"review-question "+(q.autoGrade?.manualReview?"needs-review":"")} key={q.questionId}><div className="review-qhead"><div><span>السؤال {q.questionNumber}</span><strong>{q.marks} علامة</strong>{q.scenarioId&&<em className="review-scenario-tag">ضمن سيناريو</em>}{q.autoGrade?.manualReview&&<em>يحتاج تصحيحًا يدويًا</em>}</div><div className="review-auto">آلي: {auto===undefined?Number(q.autoGrade?.score||0):auto===null?"—":auto}/{q.marks}</div></div><div className="review-qtext"><QuestionTextBlock text={q.text}/></div>{q.scenarioId&&(()=>{const sc=(data.scenarios||[]).find(x=>x.id===q.scenarioId);return sc?<Suspense fallback={<p role="status" className="platform-loading">جارٍ تحميل سياق السيناريو...</p>}><ScenarioContextView scenario={sc} open heading="h4" testId="review-scenario" className="iex-scenario review-scenario-context"/></Suspense>:null})()}<CodeStimulusView stimulus={q.codeStimulus} testId="review-code-stimulus"/><div className="review-answer-grid">{q.studentAnswer?.kind==="code"&&typeof q.studentAnswer.source==="string"?<><div><span>إجابة الطالب</span><CodeSourceView source={q.studentAnswer.source} language={String(q.studentAnswer.language||"")}/></div><div><span>الإجابة المعتمدة</span><CodeKeySummary answerKey={q.expectedAnswer}/></div></>:q.studentAnswer?.kind==="codeTemplate"?<><div><span>إجابة الطالب (البرنامج كما أعاد الخادم بناءه من القالب المقفل)</span>{q.codeTemplateReview?.ok&&typeof q.codeTemplateReview.source==="string"?<CodeSourceView source={q.codeTemplateReview.source} language={String(q.codeTemplateReview.language||"")}/>:<p role="note" data-testid="code-template-review-invalid">تعذّر إعادة بناء البرنامج من القالب المنشور وإجابات الفراغات؛ لا تُعرض شيفرة مُخمَّنة.</p>}</div><div><span>الإجابة المعتمدة</span><CodeKeySummary answerKey={q.expectedAnswer}/></div></>:q.type==="parametricNumeric"?<><div><span>الحالة المولّدة لهذه المحاولة</span><ParametricAnswerView instance={q.parametricInstance} answer={q.studentAnswer}/></div><div><span>تعبير الإجابة</span><bdi dir="ltr">{typeof q.expectedAnswer?.expression==="string"?q.expectedAnswer.expression:"—"}</bdi></div></>:isRubricQ(q)?<Suspense fallback={<p role="status" className="platform-loading">جارٍ تحميل سلم التقييم...</p>}><RubricGradingPanel question={q} awards={rubric[q.questionId]||{}} onChange={a=>setRubric(x=>({...x,[q.questionId]:a}))}/></Suspense>:q.type==="hotspot"?<><div><span>إجابة الطالب</span><HotspotAnswerView answer={q.studentAnswer} answerKey={q.expectedAnswer} config={q.hotspot} image={q.image}/></div><div><span>الإجابة المعتمدة</span><HotspotKeySummary answerKey={q.expectedAnswer}/></div></>:q.type==="labelDiagram"?<><div><span>إجابة الطالب</span><LabelDiagramAnswerView answer={q.studentAnswer} answerKey={q.expectedAnswer} config={q.labelDiagram} image={q.image}/></div><div><span>الإجابة المعتمدة</span><LabelDiagramKeySummary answerKey={q.expectedAnswer}/></div></>:q.type==="inlineCloze"?<><div><span>إجابة الطالب</span><InlineClozeAnswerView answer={q.studentAnswer} answerKey={q.expectedAnswer} config={q.inlineCloze}/></div><div><span>الإجابة المعتمدة</span><InlineClozeKeySummary answerKey={q.expectedAnswer} config={q.inlineCloze}/></div></>:q.type==="networkCli"?<><div><span>إجابة الطالب</span><NetworkCliAnswerView answer={q.studentAnswer} answerKey={q.expectedAnswer} config={q.networkCli}/></div><div><span>الإجابة المعتمدة</span><NetworkCliKeySummary answerKey={q.expectedAnswer}/></div></>:<><div><span>إجابة الطالب</span><pre>{pretty(q.studentAnswer)}</pre></div><div><span>الإجابة المعتمدة</span>{q.type==="coding"?<CodeKeySummary answerKey={q.expectedAnswer}/>:<pre>{pretty(q.expectedAnswer)}</pre>}</div></>}{q.codingEvidence!==undefined&&q.codingEvidence!==null&&<CodingAutoGradeBlock key={attemptNumber+":"+q.questionId} evidence={q.codingEvidence} questionNumber={q.questionNumber} studentName={data.student.studentName} attemptNumber={attemptNumber} confirm={confirm} refreshing={refreshing} onRefresh={()=>void load(attemptNumber)} onAction={a=>regrade(q.questionId,a,attemptNumber)}/>}</div><div className="review-grade-row">{isRubricQ(q)?<p data-testid="rubric-score-row">الدرجة من سلم التقييم: <bdi dir="ltr">{rubricScoreOf(q,rubric[q.questionId])??q.manualScore??"—"} / {q.marks}</bdi> <small>(يحتسبها الخادم عند الحفظ)</small></p>:<label>علامة المعلم<input type="number" min="0" max={q.marks} step="0.5" value={scores[q.questionId]??""} placeholder={auto===undefined?String(q.autoGrade?.score??0):auto===null?"":String(auto)} onChange={e=>setScores(x=>({...x,[q.questionId]:e.target.value}))}/><small>من {q.marks}</small></label>}<label className="review-comment">ملاحظة للطالب<input value={comments[q.questionId]??""} onChange={e=>setComments(x=>({...x,[q.questionId]:e.target.value}))} placeholder="اختياري"/></label>{!isRubricQ(q)&&<button onClick={()=>setScores(x=>({...x,[q.questionId]:String(auto===undefined?q.autoGrade?.score??0:auto)}))} disabled={auto===null} title={auto===null?"لا توجد علامة آلية مكتملة بعد":undefined}>استخدم العلامة الآلية</button>}</div></article>})}</div><label className="review-general-feedback"><span>ملاحظة عامة للطالب</span><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="مثال: أداء جيد، راجع موضوع Subnet Mask..."/></label><div className="review-footer"><button onClick={onClose}><IconClose size={14}/>إلغاء</button><button className="platform-primary" onClick={save} disabled={saving}>{saving?"⏳ جارٍ الحفظ...":<><IconCheck size={14}/>حفظ واعتماد التصحيح</>}</button></div></>}</>}{confirmDialog}</div></div>
}
