import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  PARAMETRIC_FUNCTIONS, PARAMETRIC_FUNCTIONS_V2, PARAMETRIC_LIMITS, evaluateConstraint, evaluateExpression, formatParametricValue, generateInstance, generateInstanceV2,
  officialSeedText, parseConstraint, parseExpression, previewSeedText, renderTemplate, parseTemplate, validateDerivedVariables, validateGenerationIdentity,
  validateParametricFormat, validateVariablesV2
} from "./parametricEngine";

// Phase 19C — engine v2 (generatorVersion 2 + expression language 2), ADDITIVE to the frozen v1 engine of Phase 19B:
// explicit integer / decimal variables generated by index on a scaled-integer grid (no step accumulation, ≤ 6 decimals), safe
// functions sqrt / pow / log / log10 / exp with `^` ≡ pow, derived variables evaluated in a validated dependency (topological)
// order, constraints over base + derived values, a presentation-only format layer (plain / fixed / percentage) and explicit
// complexity budgets. Every pinned instance below was produced by an INDEPENDENT reference implementation of the v2 specification.
// New-capability suite (fail-first on 751003f: no v2 API).
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const V2 = { language: 2 as const };
const env = (o: Record<string, number>) => new Map(Object.entries(o));
const ev2 = (src: string, values: Record<string, number> = {}) => {
  const p = parseExpression(src, V2);
  if (!p.ok) return { parse: p.code };
  const r = evaluateExpression(p.ast, env(values));
  return r.ok ? { value: r.value } : { eval: r.code };
};
const vars = (raw: unknown) => { const r = validateVariablesV2(raw); if (!r.ok) throw new Error(JSON.stringify(r.issues)); return r.variables; };
const derived = (raw: unknown, base: string[]) => { const r = validateDerivedVariables(raw, new Set(base)); if (!r.ok) throw new Error(JSON.stringify(r.issues)); return r.derived; };
const cons = (list: string[]) => list.map(c => { const p = parseConstraint(c, V2); if (!p.ok) throw new Error(c + " " + p.code); return p.constraint; });
const ID = (over: Record<string, unknown> = {}) => validateGenerationIdentity({ assignmentId: "asg-19c", studentId: "stu-1", attemptNumber: 1, questionKey: "q1", ...over })!;
const PHYS = () => vars([{ id: "d", kind: "decimal", min: 10, max: 50, step: 0.5 }, { id: "t", kind: "decimal", min: 2, max: 8, step: 0.25 }]);
const codes = (r: { ok: boolean; issues?: { code: string }[] }) => (r.ok ? [] : (r.issues ?? []).map(i => i.code));

describe("19C engine — language 2: safe functions, ^ ≡ pow, domains, complexity", () => {
  it("adds sqrt, pow, log, log10, exp to the v1 vocabulary; v1 is unchanged (sqrt is still unknown in language 1)", () => {
    expect([...PARAMETRIC_FUNCTIONS_V2]).toEqual(["abs", "round", "floor", "ceil", "min", "max", "sqrt", "pow", "log", "log10", "exp"]);
    expect([...PARAMETRIC_FUNCTIONS]).toEqual(["abs", "round", "floor", "ceil", "min", "max"]);
    expect(parseExpression("sqrt(4)")).toMatchObject({ ok: false, code: "EXPR_UNKNOWN_FUNCTION" });
    expect(parseExpression("sqrt(4)", { language: 1 })).toMatchObject({ ok: false, code: "EXPR_UNKNOWN_FUNCTION" });
    expect(ev2("sqrt(16) + pow(2, 10) + log10(1000) + log(exp(2))")).toEqual({ value: 4 + 1024 + 3 + 2 });
    expect(ev2("sqrt(2)")).toEqual({ value: Math.SQRT2 });
  });
  it("`^` and pow are the SAME exponentiation in language 2 (integer exponents exact; a positive base allows a fractional exponent)", () => {
    for (const [a, b] of [["2 ^ 10", "pow(2, 10)"], ["2 ^ -2", "pow(2, -2)"], ["9 ^ 0.5", "pow(9, 0.5)"], ["-2 ^ 2", "-pow(2, 2)"], ["2 ^ 3 ^ 2", "pow(2, pow(3, 2))"]]) expect(ev2(a), a).toEqual(ev2(b));
    expect(ev2("9 ^ 0.5")).toEqual({ value: 3 });
    expect(ev2("2 ^ 0.5")).toEqual({ value: 1.41421356237 });                                          // transcendental results normalized to 12 significant digits
    expect(ev2("2 ^ (32 - p) - 2", { p: 26 })).toEqual({ value: 62 });
  });
  it("domain errors, overflow and non-finite results fail closed (never NaN / Infinity)", () => {
    expect(ev2("sqrt(-1)")).toEqual({ eval: "EVAL_DOMAIN" });
    expect(ev2("log(0)")).toEqual({ eval: "EVAL_DOMAIN" });
    expect(ev2("log(-2)")).toEqual({ eval: "EVAL_DOMAIN" });
    expect(ev2("log10(0)")).toEqual({ eval: "EVAL_DOMAIN" });
    expect(ev2("(-8) ^ 0.5")).toEqual({ eval: "EVAL_DOMAIN" });
    expect(ev2("pow(0, -1)")).toEqual({ eval: "EVAL_DIVIDE_BY_ZERO" });
    expect(ev2("exp(1000)")).toMatchObject({ eval: expect.stringMatching(/EVAL_OUT_OF_RANGE|EVAL_NON_FINITE/) });
    expect(ev2("exp(40)")).toEqual({ eval: "EVAL_OUT_OF_RANGE" });
    expect(ev2("pow(10, 16)")).toEqual({ eval: "EVAL_OUT_OF_RANGE" });
    expect(ev2("pow(2, 65)")).toEqual({ eval: "EVAL_EXPONENT_INVALID" });
    expect(ev2("sqrt(1, 2)")).toEqual({ parse: "EXPR_ARITY" });
    expect(ev2("pow(2)")).toEqual({ parse: "EXPR_ARITY" });
  });
  it("the language-2 whitelist is closed: unknown / host functions, member access and prototype names are refused", () => {
    for (const src of ["cbrt(8)", "Math.sqrt(4)", "sin(1)", "eval(1)", "constructor(1)", "a.b", "log2(8)", "random()", "hypot(3, 4)"]) expect(parseExpression(src, V2).ok, src).toBe(false);
  });
  it("explicit AST-node budget (EXPR_TOO_COMPLEX) on top of the length / token / depth limits", () => {
    expect(PARAMETRIC_LIMITS.astNodes).toBe(160);
    const wide = Array.from({ length: 90 }, () => "a").join("+");                                        // 179 tokens, 179 nodes
    expect(parseExpression(wide, V2)).toMatchObject({ ok: false, code: "EXPR_TOO_COMPLEX" });
    expect(parseExpression(Array.from({ length: 70 }, () => "a").join("+"), V2).ok).toBe(true);
  });
  it("language-2 constraints may use the new functions; still exactly one comparison", () => {
    const c = parseConstraint("sqrt(a) < b", V2);
    expect(c.ok && evaluateConstraint(c.constraint, env({ a: 16, b: 5 }))).toEqual({ ok: true, holds: true });
    expect(parseConstraint("a < b && b < c", V2).ok).toBe(false);
    expect(parseConstraint("sqrt(a) < b").ok).toBe(false);                                                // language 1 default
  });
});

describe("19C engine — explicit integer / decimal variables on a scaled grid", () => {
  it("kinds are explicit; integer step defaults to 1; a decimal needs a positive step; authored values keep ≤ 6 decimals", () => {
    expect(validateVariablesV2([{ id: "a", kind: "integer", min: 2, max: 10 }])).toEqual({ ok: true, variables: [{ id: "a", kind: "integer", min: 2, max: 10, step: 1 }] });
    expect(validateVariablesV2([{ id: "r", kind: "decimal", min: 1.5, max: 9.5, step: 0.5, format: { kind: "fixed", decimals: 1 } }])).toEqual({ ok: true, variables: [{ id: "r", kind: "decimal", min: 1.5, max: 9.5, step: 0.5, format: { kind: "fixed", decimals: 1 } }] });
    const c = (raw: unknown) => codes(validateVariablesV2(raw));
    expect(c([{ id: "a", kind: "int", min: 1, max: 2 }])).toEqual(["PARAM_VAR_KIND_UNSUPPORTED"]);            // the v1 spelling is not a v2 kind
    expect(c([{ id: "a", min: 1, max: 2 }])).toEqual(["PARAM_VAR_INVALID"]);                                // kind is never inferred
    expect(c([{ id: "a", kind: "integer", min: 1.5, max: 2 }])).toEqual(["PARAM_VAR_BOUNDS_INVALID"]);
    for (const step of [0, -0.5, Number.NaN, Number.POSITIVE_INFINITY, "0.5"]) expect(c([{ id: "r", kind: "decimal", min: 0, max: 1, step }]), String(step)).toEqual(["PARAM_VAR_STEP_INVALID"]);
    expect(c([{ id: "r", kind: "decimal", min: 0, max: 1 }])).toEqual(["PARAM_VAR_STEP_INVALID"]);
    expect(c([{ id: "r", kind: "decimal", min: 0, max: 1, step: 0.3 }])).toEqual(["PARAM_VAR_STEP_MISALIGNED"]);
    expect(c([{ id: "r", kind: "decimal", min: 0, max: 1, step: 1 / 3 }])).toEqual(["PARAM_VAR_PRECISION"]);
    expect(c([{ id: "r", kind: "decimal", min: 0.1234567, max: 1, step: 0.1 }])).toEqual(["PARAM_VAR_PRECISION"]);
    expect(c([{ id: "r", kind: "decimal", min: 2, max: 1, step: 0.5 }])).toEqual(["PARAM_VAR_RANGE_IMPOSSIBLE"]);
    expect(c([{ id: "r", kind: "decimal", min: 0, max: 100, step: 0.000001 }])).toEqual(["PARAM_VAR_TOO_MANY_POSITIONS"]);
    expect(c([{ id: "r", kind: "decimal", min: 0, max: 1, step: 0.5, format: { kind: "ip" } }])).toEqual(["PARAM_FORMAT_INVALID"]);
    expect(c([{ id: "a", kind: "integer", min: 1, max: 2, extra: 1 }])).toEqual(["PARAM_VAR_INVALID"]);
    expect(c([JSON.parse('{"id":"a","kind":"integer","min":1,"max":2,"__proto__":{}}')])).toEqual(["PARAM_VAR_INVALID"]);
  });
  it("decimal values are EXACT grid points — never 0.30000000000000004 — inside the declared range, both ends reachable", () => {
    const x = vars([{ id: "x", kind: "decimal", min: 0.1, max: 0.9, step: 0.1 }]);
    const seen = new Set<number>();
    for (let s = 1; s <= 400; s++) {
      const g = generateInstanceV2({ variables: x, derived: [], constraints: [] }, previewSeedText(2, "t1", s));
      if (!g.ok) throw new Error("gen");
      const v = g.values.x;
      expect(v >= 0.1 && v <= 0.9).toBe(true);
      expect(String(v)).toMatch(/^0\.[1-9]$/);
      seen.add(v);
    }
    expect([...seen].sort()).toEqual([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]);
  });
  it("EXACT pinned v2 instances (independent reference): decimals, same identity replays, another attempt differs", () => {
    const g = (seed: string) => generateInstanceV2({ variables: PHYS(), derived: derived([{ id: "speed", expression: "d / t" }], ["d", "t"]), constraints: [] }, seed);
    expect(g(officialSeedText(2, ID()))).toEqual({ ok: true, values: { d: 32, t: 3.75 }, derived: { speed: 8.533333333333333 }, attempt: 1 });
    expect(g(officialSeedText(2, ID()))).toEqual(g(officialSeedText(2, ID())));
    expect(g(officialSeedText(2, ID({ attemptNumber: 2 })))).toEqual({ ok: true, values: { d: 41.5, t: 2 }, derived: { speed: 20.75 }, attempt: 1 });
    expect(g(previewSeedText(2, "q1", 1))).toEqual({ ok: true, values: { d: 44, t: 2.5 }, derived: { speed: 17.6 }, attempt: 1 });
    const tenths = vars([{ id: "x", kind: "decimal", min: 0.1, max: 0.9, step: 0.1 }, { id: "y", kind: "decimal", min: 0.1, max: 0.9, step: 0.1 }]);
    expect(generateInstanceV2({ variables: tenths, derived: [], constraints: [] }, previewSeedText(2, "t1", 1))).toEqual({ ok: true, values: { x: 0.9, y: 0.4 }, derived: {}, attempt: 1 });
    expect(generateInstanceV2({ variables: vars([{ id: "p", kind: "integer", min: 24, max: 30 }]), derived: [], constraints: [] }, officialSeedText(2, ID({ questionKey: "n1" })))).toEqual({ ok: true, values: { p: 30 }, derived: {}, attempt: 1 });
  });
  it("the v1 generator is untouched and refuses v2 input; v2 generation never uses the v1 entry point", () => {
    expect(generateInstance({ generatorVersion: 2, variables: [], constraints: [] }, "x")).toEqual({ ok: false, code: "GEN_UNSUPPORTED_VERSION" });
  });
});

describe("19C engine — derived variables (dependency graph, topological order)", () => {
  it("single and chained dependencies; declaration order may differ from dependency order (deterministic topological evaluation)", () => {
    const d = validateDerivedVariables([{ id: "sq", expression: "s * s" }, { id: "s", expression: "a + b" }], new Set(["a", "b"]));
    expect(d.ok && d.order).toEqual(["s", "sq"]);
    const base = vars([{ id: "a", kind: "integer", min: 1, max: 9 }, { id: "b", kind: "integer", min: 1, max: 9 }]);
    const g = generateInstanceV2({ variables: base, derived: d.ok ? d.derived : [], constraints: cons(["sq > 50"]) }, officialSeedText(2, ID({ questionKey: "c1" })));
    expect(g).toEqual({ ok: true, values: { a: 8, b: 3 }, derived: { s: 11, sq: 121 }, attempt: 1 });
  });
  it("refuses cycles, self references, unknown references, duplicates, collisions with base names, invalid expressions and too many derived values", () => {
    const c = (raw: unknown, base = ["a", "b"]) => codes(validateDerivedVariables(raw, new Set(base)));
    expect(c([{ id: "x", expression: "y + 1" }, { id: "y", expression: "x + 1" }])).toEqual(["PARAM_DERIVED_CYCLE"]);
    expect(c([{ id: "x", expression: "y" }, { id: "y", expression: "z" }, { id: "z", expression: "x * a" }])).toEqual(["PARAM_DERIVED_CYCLE"]);
    expect(c([{ id: "x", expression: "x + 1" }])).toEqual(["PARAM_DERIVED_SELF_REFERENCE"]);
    expect(c([{ id: "x", expression: "q * 2" }])).toEqual(["PARAM_DERIVED_UNKNOWN_REFERENCE"]);
    expect(c([{ id: "x", expression: "a" }, { id: "x", expression: "b" }])).toEqual(["PARAM_DERIVED_ID_DUPLICATE"]);
    expect(c([{ id: "a", expression: "b * 2" }])).toEqual(["PARAM_DERIVED_COLLISION"]);
    expect(c([{ id: "x", expression: "sqrt(" }])).toEqual(["PARAM_DERIVED_EXPRESSION_INVALID"]);
    expect(c([{ id: "x", expression: "Math.sqrt(a)" }])).toEqual(["PARAM_DERIVED_EXPRESSION_INVALID"]);
    expect(c([{ id: "abs", expression: "a" }])).toEqual(["PARAM_DERIVED_ID_INVALID"]);
    expect(c([{ id: "x", expression: "a", note: 1 }])).toEqual(["PARAM_DERIVED_INVALID"]);
    expect(c(Array.from({ length: PARAMETRIC_LIMITS.derivedVariables + 1 }, (_, i) => ({ id: "d" + i, expression: "a" })))).toEqual(["PARAM_DERIVED_TOO_MANY"]);
    expect(c("a * b")).toEqual(["PARAM_DERIVED_INVALID"]);
    expect(validateDerivedVariables([], new Set(["a"]))).toEqual({ ok: true, derived: [], order: [] });
  });
  it("a derived value that cannot be evaluated for a candidate (sqrt of a negative) rejects that candidate; never NaN", () => {
    const base = vars([{ id: "x", kind: "integer", min: -5, max: 5 }]);
    const d = derived([{ id: "r", expression: "sqrt(x)" }], ["x"]);
    for (let s = 1; s <= 30; s++) {
      const g = generateInstanceV2({ variables: base, derived: d, constraints: [] }, previewSeedText(2, "s", s));
      if (g.ok) { expect(g.values.x).toBeGreaterThanOrEqual(0); expect(Number.isFinite(g.derived.r)).toBe(true); }
    }
    const never = generateInstanceV2({ variables: vars([{ id: "x", kind: "integer", min: -5, max: -1 }]), derived: d, constraints: [] }, previewSeedText(2, "s", 1));
    expect(never).toEqual({ ok: false, code: "GEN_CONSTRAINTS_UNSATISFIED" });
  });
});

describe("19C engine — constraints over base + derived values, bounded retries", () => {
  it("pinned: the first candidate violates a != b and is rejected; the second is accepted", () => {
    const base = vars([{ id: "a", kind: "integer", min: 2, max: 10 }, { id: "b", kind: "integer", min: 3, max: 12 }]);
    const d = derived([{ id: "area", expression: "a * b" }], ["a", "b"]);
    expect(generateInstanceV2({ variables: base, derived: d, constraints: cons(["a != b"]) }, officialSeedText(2, ID({ questionKey: "r1" })))).toEqual({ ok: true, values: { a: 8, b: 10 }, derived: { area: 80 }, attempt: 2 });
    expect(generateInstanceV2({ variables: vars([{ id: "x", kind: "integer", min: 1, max: 100 }]), derived: derived([{ id: "r", expression: "sqrt(x)" }], ["x"]), constraints: cons(["sqrt(x) < 5"]) }, officialSeedText(2, ID({ questionKey: "s1" })))).toEqual({ ok: true, values: { x: 12 }, derived: { r: 3.4641016151377544 }, attempt: 1 });
  });
  it("the bound is EXACTLY 100 candidates (independent reference): a first match at candidate 94 succeeds, one at candidate 110 fails", () => {
    const base = vars([{ id: "x", kind: "integer", min: 1, max: 20 }]);
    expect(generateInstanceV2({ variables: base, derived: [], constraints: cons(["x == 7"]) }, previewSeedText(2, "bound", 31))).toEqual({ ok: true, values: { x: 7 }, derived: {}, attempt: 94 });
    expect(generateInstanceV2({ variables: base, derived: [], constraints: cons(["x == 7"]) }, previewSeedText(2, "bound", 35))).toEqual({ ok: false, code: "GEN_CONSTRAINTS_UNSATISFIED" });
  });
  it("impossible constraints fail closed after EXACTLY the hard retry bound (100 candidates) — never an unbounded loop", () => {
    expect(PARAMETRIC_LIMITS.attempts).toBe(100);
    const base = vars([{ id: "a", kind: "integer", min: 1, max: 5 }]);
    expect(generateInstanceV2({ variables: base, derived: [], constraints: cons(["a > 5"]) }, officialSeedText(2, ID()))).toEqual({ ok: false, code: "GEN_CONSTRAINTS_UNSATISFIED" });
    const src = fs.readFileSync(path.join(repo, "src/parametricEngine.ts"), "utf8");
    expect(src).not.toMatch(/while\s*\(\s*true\s*\)|for\s*\(\s*;\s*;\s*\)\s*\{[^}]*generate/);
  });
});

describe("19C engine — presentation formats (display only, never grading)", () => {
  it("plain, fixed and percentage with bounded precision; round half away from zero; no negative zero", () => {
    expect(formatParametricValue(8.533333333333333, { kind: "plain" })).toBe("8.53333333333");
    expect(formatParametricValue(8.533333333333333, { kind: "fixed", decimals: 2 })).toBe("8.53");
    expect(formatParametricValue(3.75, { kind: "fixed", decimals: 1 })).toBe("3.8");
    expect(formatParametricValue(-3.75, { kind: "fixed", decimals: 1 })).toBe("-3.8");
    expect(formatParametricValue(1.005, { kind: "fixed", decimals: 2 })).toBe("1.01");
    expect(formatParametricValue(-0.0001, { kind: "fixed", decimals: 2 })).toBe("0.00");
    expect(formatParametricValue(42, { kind: "fixed", decimals: 0 })).toBe("42");
    expect(formatParametricValue(0.18518518518518517, { kind: "percentage", decimals: 1 })).toBe("18.5%");
    expect(formatParametricValue(0.8, { kind: "percentage", decimals: 0 })).toBe("80%");
    expect(formatParametricValue(12, undefined)).toBe("12");
  });
  it("format validation is strict: known kinds only, integer decimals 0..10, exact keys", () => {
    expect(PARAMETRIC_LIMITS.formatDecimals).toBe(10);
    expect(validateParametricFormat({ kind: "fixed", decimals: 2 })).toEqual({ kind: "fixed", decimals: 2 });
    expect(validateParametricFormat({ kind: "plain" })).toEqual({ kind: "plain" });
    for (const bad of [{ kind: "fixed" }, { kind: "fixed", decimals: 11 }, { kind: "fixed", decimals: 1.5 }, { kind: "percentage", decimals: -1 }, { kind: "plain", decimals: 2 }, { kind: "ipv4" }, { kind: "scientific", decimals: 2 }, null, "fixed"])
      expect(validateParametricFormat(bad), JSON.stringify(bad)).toBeNull();
  });
  it("the template renders formatted values; formats change only the text", () => {
    const t = parseTemplate("t = {{t}} ث، السرعة ≈ {{speed}}", new Set(["t", "speed"]));
    expect(t.ok && renderTemplate(t.parts, { t: 3.75, speed: 8.533333333333333 }, { t: { kind: "fixed", decimals: 1 }, speed: { kind: "fixed", decimals: 2 } })).toBe("t = 3.8 ث، السرعة ≈ 8.53");
    expect(t.ok && renderTemplate(t.parts, { t: 3.75, speed: 8.533333333333333 })).toBe("t = 3.75 ث، السرعة ≈ 8.53333333333");
  });
});
