
import {useEffect,useState} from "react";
type Props={token:string;displayName:string;onLogout:()=>void};
type Summary={assignmentId:string;title:string;instructions:string;openAt:string;dueAt:string;sourceExamTitle:string;questionCount:number;totalMarks:number;availability:"scheduled"|"open"|"closed";createdAt:string};
type Question={examQuestionId:string;text:string;marks:number;options?:Array<{text?:string;value?:string;label?:string}>;fields?:Array<{id?:string;label?:string}>;wordBank?:string[];image?:{exists?:boolean;visible?:boolean;assets?:Array<{dataUrl?:string}>}};
type Detail={assignmentId:string;title:string;instructions:string;openAt:string;dueAt:string;questionCount:number;totalMarks:number;exam:{title?:string;questions?:Question[]}};
type Dashboard={student:{userId:string;code:string;displayName:string;classId:string};classroom:{classId:string;name:string;grade:string;schoolYear:string}|null;assignments:Summary[];stats:{assigned:number;completed:number;average:number|null}};
const fmt=(v:string)=>v?new Date(v).toLocaleString("ar"):"بدون موعد";
const label=(v:Summary["availability"])=>v==="scheduled"?"قريبًا":v==="closed"?"انتهى الموعد":"متاح الآن";
export default function StudentPortal({token,displayName,onLogout}:Props){
 const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancel=false;(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/student-dashboard",{headers:{"x-student-token":token,Authorization:"Bearer "+token}}),j=await r.json() as {error?:string;student?:Dashboard["student"];classroom?:Dashboard["classroom"];assignments?:Summary[];stats?:Dashboard["stats"]};if(r.status===401){onLogout();return}if(!r.ok||!j.student||!j.stats)throw new Error(j.error||"تعذر تحميل صفحة الطالب.");if(!cancel)setData({student:j.student,classroom:j.classroom||null,assignments:j.assignments||[],stats:j.stats})}catch(e){if(!cancel)setError(e instanceof Error?e.message:"تعذر تحميل الصفحة.")}finally{if(!cancel)setLoading(false)}})();return()=>{cancel=true}},[token,onLogout]);
 async function open(item:Summary){if(item.availability==="scheduled")return;setBusy(true);setError("");try{const r=await fetch("/api/student-assignment/"+encodeURIComponent(item.assignmentId),{headers:{"x-student-token":token,Authorization:"Bearer "+token}}),j=await r.json() as {error?:string;assignment?:Detail};if(r.status===401){onLogout();return}if(!r.ok||!j.assignment)throw new Error(j.error||"تعذر فتح الواجب.");setDetail(j.assignment);window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(e instanceof Error?e.message:"تعذر فتح الواجب.")}finally{setBusy(false)}}
 if(detail){const qs=detail.exam.questions||[];return <main className="student-portal" dir="rtl"><header className="student-topbar"><div className="student-brand"><span className="student-logo">EB</span><div><h1>{detail.title}</h1><p>ExamBank 2.0 · واجب الطالب</p></div></div><div className="student-assignment-top-actions"><button className="student-logout" onClick={()=>setDetail(null)}>العودة للمهام</button><button className="student-logout" onClick={onLogout}>تسجيل الخروج</button></div></header><section className="student-shell">{error&&<div className="platform-error">{error}</div>}<section className="student-assignment-header"><div><span className="platform-eyebrow">Assignment</span><h2>{detail.title}</h2><p>{detail.instructions}</p></div><div className="student-assignment-summary"><strong>{detail.questionCount}</strong><span>سؤال</span><strong>{detail.totalMarks}</strong><span>علامة</span></div></section><div className="phase-c-notice"><strong>✓ الواجب وصل إلى حسابك</strong><span>حاليًا تستطيع معاينة الأسئلة. في Phase 2.0C سنفعّل الإجابة، الحفظ التلقائي، التسليم والتصحيح.</span></div><section className="student-question-list">{qs.map((q,i)=><article className="student-question-card" key={q.examQuestionId||String(i)}><div className="student-question-heading"><strong>السؤال {i+1}</strong><span>{q.marks||0} علامة</span></div><div className="student-question-text">{q.text}</div>{q.wordBank&&q.wordBank.length>0&&<div className="student-word-bank">{q.wordBank.map((w,n)=><span key={w+"-"+n}>{w}</span>)}</div>}{q.options&&q.options.length>0&&<ol className="student-question-options">{q.options.map((o,n)=><li key={n}>{o.text||o.label||o.value||""}</li>)}</ol>}{q.fields&&q.fields.length>0&&<div className="student-field-list">{q.fields.map((f,n)=><div key={f.id||String(n)}><span>{f.label||"إجابة"}</span><div className="student-answer-line"/></div>)}</div>}{q.image?.exists&&q.image.visible&&q.image.assets?.map((a,n)=>a.dataUrl?<img className="student-question-image" key={n} src={a.dataUrl} alt={"صورة السؤال "+(i+1)}/>:null)}</article>)}</section></section></main>}
 return <main className="student-portal" dir="rtl"><header className="student-topbar"><div className="student-brand"><span className="student-logo">EB</span><div><h1>ExamBank 2.0</h1><p>بوابة الطالب للتدريب والواجبات</p></div></div><button className="student-logout" onClick={onLogout}>تسجيل الخروج</button></header><section className="student-shell">{loading&&<div className="platform-loading">⏳ جارٍ تحميل حسابك...</div>}{busy&&<div className="platform-loading">⏳ جارٍ فتح الواجب...</div>}{error&&<div className="platform-error">{error}</div>}{!loading&&data&&<><section className="student-welcome-card"><div><span className="platform-eyebrow">Student Portal</span><h2>مرحبًا {data.student.displayName||displayName}</h2><p>{data.classroom?data.classroom.name+(data.classroom.grade?" · "+data.classroom.grade:""):"لم يتم ربط حسابك بصف بعد."}</p></div><div className="student-code-chip">الكود: <strong>{data.student.code}</strong></div></section><section className="student-stat-grid"><article><strong>{data.stats.assigned}</strong><span>مهام</span></article><article><strong>{data.stats.completed}</strong><span>مكتملة</span></article><article><strong>{data.stats.average===null?"—":data.stats.average+"%"}</strong><span>المعدل</span></article></section><section className="student-main-grid"><article className="student-panel"><div className="student-panel-heading"><div><span className="platform-eyebrow">Assignments</span><h3>المهام والواجبات</h3></div><span className="phase-chip">Phase 2.0B</span></div><div className="student-assignment-list">{data.assignments.map(item=><article className={"student-assignment-card "+item.availability} key={item.assignmentId}><div className="student-assignment-card-main"><div className="student-assignment-card-title"><strong>{item.title}</strong><span>{label(item.availability)}</span></div><p>{item.instructions}</p><small>{item.questionCount} سؤال · {item.totalMarks} علامة</small><small>الفتح: {fmt(item.openAt)}</small><small>التسليم: {fmt(item.dueAt)}</small></div><button onClick={()=>open(item)} disabled={busy||item.availability==="scheduled"}>{item.availability==="scheduled"?"لم يفتح بعد":item.availability==="closed"?"عرض الواجب":"فتح الواجب"}</button></article>)}{!data.assignments.length&&<div className="student-empty-state"><span>📝</span><strong>لا توجد مهام منشورة الآن</strong><p>عندما يرسل المعلم واجبًا إلى صفك سيظهر هنا تلقائيًا.</p></div>}</div></article><article className="student-panel student-next-panel"><span className="platform-eyebrow">Coming Next</span><h3>Phase 2.0C</h3><ul><li>كتابة الإجابات داخل الموقع</li><li>حفظ تلقائي أثناء الحل</li><li>تسليم الواجب</li><li>تصحيح تلقائي ونتيجة</li></ul></article></section></>}</section></main>
}
