
import {useEffect,useState} from "react";
import StudentExamPage from "./StudentExamPage";
import {IconLogout,IconAssignments} from "./icons";
type Props={token:string;displayName:string;onLogout:()=>void};
type Summary={assignmentId:string;title:string;instructions:string;openAt:string;dueAt:string;effectiveDueAt?:string;questionCount:number;totalMarks:number;availability:"scheduled"|"open"|"closed";attemptsUsed:number;allowedAttempts:number;canAttempt:boolean;latestScore:number|null;latestPercentage:number|null;createdAt:string};
type Detail={assignmentId:string;title:string;instructions:string;openAt:string;dueAt:string;effectiveDueAt?:string;maxAttempts:number;questionCount:number;totalMarks:number;exam:{title?:string;metadata?:{school?:string;subject?:string;grade?:string;className?:string;generalInstructions?:string};questions?:any[]}};
type Dashboard={student:{userId:string;code:string;displayName:string;classId:string};classroom:{classId:string;name:string;grade:string;schoolYear:string}|null;assignments:Summary[];stats:{assigned:number;completed:number;average:number|null}};
const fmt=(v:string)=>v?new Date(v).toLocaleString("ar"):"بدون موعد";
const label=(v:Summary["availability"])=>v==="scheduled"?"قريبًا":v==="closed"?"انتهى الموعد":"متاح الآن";
export default function StudentPortal({token,displayName,onLogout}:Props){
 const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/student-dashboard",{headers:{"x-student-token":token,Authorization:"Bearer "+token}}),j=await r.json() as any;if(r.status===401){onLogout();return}if(!r.ok||!j.student||!j.stats)throw new Error(j.error||"تعذر تحميل صفحة الطالب.");setData({student:j.student,classroom:j.classroom||null,assignments:j.assignments||[],stats:j.stats})}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الصفحة.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token]);
 async function open(item:Summary){if(item.availability==="scheduled")return;setBusy(true);setError("");try{const r=await fetch("/api/student-assignment/"+encodeURIComponent(item.assignmentId),{headers:{"x-student-token":token,Authorization:"Bearer "+token}}),j=await r.json() as any;if(r.status===401){onLogout();return}if(!r.ok||!j.assignment)throw new Error(j.error||"تعذر فتح الواجب.");setDetail(j.assignment);window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(e instanceof Error?e.message:"تعذر فتح الواجب.")}finally{setBusy(false)}}
 if(detail&&data)return <StudentExamPage token={token} assignment={detail} studentName={data.student.displayName||displayName} className={data.classroom?data.classroom.name+(data.classroom.grade?" · "+data.classroom.grade:""):""} onLogout={onLogout} onBack={()=>{setDetail(null);void load()}}/>;
 return <main className="student-portal" dir="rtl"><header className="student-topbar"><div className="student-brand"><span className="student-logo">EB</span><div><h1>ExamBank 2.0</h1><p>بوابة الطالب للتدريب والواجبات</p></div></div><button className="student-logout" onClick={onLogout}><IconLogout size={16}/>تسجيل الخروج</button></header><section className="student-shell">{loading&&<div className="platform-loading">⏳ جارٍ تحميل حسابك...</div>}{busy&&<div className="platform-loading">⏳ جارٍ فتح الواجب...</div>}{error&&<div className="platform-error">{error}</div>}{!loading&&data&&<><section className="student-welcome-card"><div><span className="platform-eyebrow">Student Portal</span><h2>مرحبًا {data.student.displayName||displayName}</h2><p>{data.classroom?data.classroom.name+(data.classroom.grade?" · "+data.classroom.grade:""):"لم يتم ربط حسابك بصف بعد."}</p></div><div className="student-code-chip">الكود: <strong>{data.student.code}</strong></div></section><section className="student-stat-grid"><article><strong>{data.stats.assigned}</strong><span>مهام</span></article><article><strong>{data.stats.completed}</strong><span>مكتملة</span></article><article><strong>{data.stats.average===null?"—":data.stats.average+"%"}</strong><span>المعدل</span></article></section><section className="student-main-grid"><article className="student-panel"><div className="student-panel-heading"><div><span className="platform-eyebrow">Assignments</span><h3>المهام والواجبات</h3></div></div><div className="student-assignment-list">{data.assignments.map(item=><article className={"student-assignment-card "+item.availability} key={item.assignmentId}><div className="student-assignment-card-main"><div className="student-assignment-card-title"><strong>{item.title}</strong><span>{label(item.availability)}</span></div><p>{item.instructions}</p><small>{item.questionCount} سؤال · {item.totalMarks} علامة</small><small>التسليم: {fmt(item.effectiveDueAt||item.dueAt)} · المحاولات: {item.attemptsUsed}/{item.allowedAttempts}</small>{item.latestScore!==null&&<strong className="student-latest-score">آخر علامة: {item.latestScore}/{item.totalMarks} ({item.latestPercentage}%)</strong>}</div><button onClick={()=>open(item)} disabled={busy||item.availability==="scheduled"}>{item.availability==="scheduled"?"لم يفتح بعد":item.latestScore!==null?(item.canAttempt?"النتيجة / محاولة جديدة":"عرض النتيجة"):item.availability==="closed"?"عرض الواجب":"ابدأ الحل"}</button></article>)}{!data.assignments.length&&<div className="student-empty-state"><IconAssignments size={30}/><strong>لا توجد مهام منشورة الآن</strong><p>عندما يرسل المعلم واجبًا إلى صفك سيظهر هنا تلقائيًا.</p></div>}</div></article><article className="student-panel student-next-panel"><span className="platform-eyebrow">ExamBank 2.0</span><h3>نظام الواجب التفاعلي</h3><ul><li>حل مباشر داخل الموقع</li><li>حفظ تلقائي للإجابات</li><li>تسليم وتصحيح آلي</li><li>تسجيل العلامة والمحاولات</li></ul></article></section></>}</section></main>
}
