const { app } = require("@azure/functions");
const fs = require("fs");
const path = require("path");
const { requireBuilderAuth } = require("../lib/builder-auth");

// The exam library is read-only global system data, so it ships bundled with the app (versioned in
// the repo under api/src/data/exam-library, generated by scripts/build-791381-library.cjs) and is
// read straight off disk - same pattern as config/topics.json. No Azure Blob, no upload step: git
// -> deploy -> library available. If the library later becomes editable from a SuperAdmin panel,
// this single reader can be swapped to Blob without touching any caller.
const DATA_CANDIDATES = [
  path.join(process.cwd(), "src", "data", "exam-library"),
  path.join(__dirname, "..", "data", "exam-library")
];

const VALID_ID = /^[A-Za-z0-9_-]+$/;

function dataDir() {
  for (const candidate of DATA_CANDIDATES) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return DATA_CANDIDATES[DATA_CANDIDATES.length - 1];
}

function readJsonOrNull(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch {
    return null;
  }
}

app.http("examLibrary", {
  methods: ["GET"],
  authLevel: "anonymous",
  route: "exam-library/{id?}",
  handler: async request => {
    try {
      const auth = requireBuilderAuth(request);
      if (!auth.ok) return auth.response;

      const dir = dataDir();
      const id = String(request.params?.id || "").trim();

      if (!id) {
        // Small metadata-only catalog (no examSnapshot); the frontend decides how to present each
        // item's publishable flag. Full item JSON is fetched separately only when one is selected.
        const catalog = readJsonOrNull(path.join(dir, "catalog.json"));
        return { status: 200, jsonBody: { ok: true, catalog: Array.isArray(catalog) ? catalog : [] } };
      }

      if (!VALID_ID.test(id)) {
        return { status: 400, jsonBody: { ok: false, error: "معرّف غير صالح." } };
      }

      const item = readJsonOrNull(path.join(dir, "items", id + ".json"));
      if (!item) {
        return { status: 404, jsonBody: { ok: false, error: "العنصر غير موجود في المكتبة." } };
      }
      return { status: 200, jsonBody: { ok: true, item } };
    } catch {
      return { status: 500, jsonBody: { ok: false, error: "تعذر تحميل مكتبة الامتحانات حاليًا." } };
    }
  }
});
